### ISSUE TITLE
1.5 group by 带别名时报错（SQL Server）

### ISSUE THREAD

**Issue by dahai2016** [MyCATApache/Mycat-Server#1041]
使用mycat连接SQL Server，执行分组sql（带别名）报错
SELECT a.workflowid, COUNT(1) FROM workflow_base a GROUP BY a.workflowid

而GROUP BY后不带别名则可以正确解析
SELECT a.workflowid, COUNT(1) FROM workflow_base a GROUP BY workflowid

报错：
`java.lang.ClassCastException: com.alibaba.druid.sql.ast.expr.SQLPropertyExpr cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.expr.MySqlSelectGroupByExpr
	at org.opencloudb.parser.druid.impl.DruidSelectParser.buildGroupByCols(DruidSelectParser.java:559)
	at org.opencloudb.parser.druid.impl.DruidSelectParser.parseAggGroupCommon(DruidSelectParser.java:178)
	at org.opencloudb.parser.druid.impl.DruidSelectSqlServerParser.parseOrderAggGroupSqlServer(DruidSelectSqlServerParser.java:81)
	at org.opencloudb.parser.druid.impl.DruidSelectSqlServerParser.sqlserverParse(DruidSelectSqlServerParser.java:72)
	at org.opencloudb.parser.druid.impl.DruidSelectSqlServerParser.statementParse(DruidSelectSqlServerParser.java:39)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:63)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:64)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
	at org.opencloudb.route.RouteService.route(RouteService.java:133)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:227)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Unknown Source)`

**Comment by magicdoom** [comment]
druid解析时候丢了dbtype    目前已经提交pr给druid  等待合并

**Comment by magicdoom** [comment]
druid官方已经合并  等druid 1.0.25发布  再更新mycat
