### ISSUE TITLE
Mycat字段类型处理错误

### ISSUE THREAD

**Issue by skeght** [MyCATApache/Mycat-Server#1042]
io.mycat.sqlengine.mpp.ColMeta 里面的字段类型处理有误 比如COL_TYPE_LONG是4字节的 实际处理时是按8字节的long处理的。
步骤：1.useOffHeapForMerge=1 使用堆外合并；
2.select distinct id_goods,id_customer from orders; orders表是分片表（id_goods,id_customer均为4字节int），会被解析成两个分片的groupby查询来合并，合并时处理COL_TYPE_LONG类型字段时按8字节处理报错。

**Comment by skeght** [comment]
[WARN ][BusinessExecutor7] caught exception  java.lang.IllegalArgumentException: offset (0) + length (8) exceed the capacity of the array: 1
	at io.mycat.memory.unsafe.utils.BytesTools.explainWrongLengthOrOffset(BytesTools.java:400)
	at io.mycat.memory.unsafe.utils.BytesTools.toLong(BytesTools.java:374)
	at io.mycat.memory.unsafe.utils.BytesTools.toLong(BytesTools.java:347)
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.getGroupKey(UnsafeRowGrouper.java:475)
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.addRow(UnsafeRowGrouper.java:559)
	at io.mycat.sqlengine.mpp.DataNodeMergeManager.run(DataNodeMergeManager.java:372)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:624)

**Comment by magicdoom** [comment]
章大侠已经fix  请验证
