### ISSUE TITLE
跨库join无法使用

### ISSUE THREAD

**Issue by Kagamine** [MyCATApache/Mycat-Server#1082]
```sql
SELECT `x`.`Begin`, `x`.`BriberiesCount`, `x`.`End`, `x`.`Id`, `x`.`Price`, `x`.`Ratio`, `x`.`Title`, `y`.`Merchant`
FROM `Activities` AS `x`
INNER JOIN `AspNetUsers` AS `y` ON `x`.`MerchantId` = `y`.`Id`
ORDER BY `x`.`Begin` DESC
```

Activities在四台节点上以MOD方式分片，AspNetUsers只在dn1上，执行上述语句时，只返回了第一台存储的Activities。

**Comment by Kagamine** [comment]
```
INFO   | jvm 1    | 2016/09/02 12:56:39 | class ./catlet file io/mycat/catlets/ShareJoin.class
INFO   | jvm 1    | 2016/09/02 12:56:39 | jar ./catlet file io/mycat/catlets/ShareJoin.jar
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,695 [INFO ][$_NIOREACTOR-2-RW] table `AspNetUsers` Alias:`y` Hints:[]  (io.mycat.catlets.JoinParser:JoinParser.java:92) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,695 [INFO ][$_NIOREACTOR-2-RW] SQL: SELECT `x`.`Begin`, `x`.`BriberiesCount`, `x`.`End`, `x`.`Id`, `x`.`Price`, `x`.`Ratio`, `x`.`Title`, `y`.`Merchant`
INFO   | jvm 1    | 2016/09/02 12:56:39 | FROM `Activities` AS `x`
INFO   | jvm 1    | 2016/09/02 12:56:39 | JOIN `AspNetUsers` AS `y` ON `x`.`MerchantId` = `y`.`Id`
INFO   | jvm 1    | 2016/09/02 12:56:39 | ORDER BY `x`.`Begin` DESC  (io.mycat.catlets.JoinParser:JoinParser.java:70) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,696 [INFO ][$_NIOREACTOR-2-RW] Catlet exec:wechat_dn0,wechat_dn1,wechat_dn2,wechat_dn3, sql:select `Begin` , `BriberiesCount` , `End` , `Id` , `Price` , `Ratio` , `Title`, `MerchantId` from `Activities` order by `Begin`  DESC  (io.mycat.catlets.ShareJoin:ShareJoin.java:148) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,698 [WARN ][$_NIOREACTOR-2-RW] caught err: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at java.util.ArrayList.get(ArrayList.java:411)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.util.ResultSetUtil.getColumnValAsString(ResultSetUtil.java:82)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.catlets.ShareDBJoinHandler.onRowData(ShareJoin.java:319)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.sqlengine.SQLJob.rowResponse(SQLJob.java:154)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:204)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:135)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:263)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2016/09/02 12:56:39 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/02 12:56:39 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:107) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,698 [INFO ][$_NIOREACTOR-2-RW] close connection,reason:program err:java.lang.IndexOutOfBoundsException: Index: 8, Size: 8 ,MySQLConnection [id=242, lastTime=1472792199689, user=root, schema=wechat, old shema=wechat, borrowed=true, fromSlaveDB=false, threadId=216, charset=utf8, txIsolation=3, autocommit=true, attachment=wechat_dn1{select `Begin` , `BriberiesCount` , `End` , `Id` , `Price` , `Ratio` , `Title`, `MerchantId` from `Activities` order by `Begin`  DESC}, respHandler=SQLJob [ id=2,dataNodeOrDatabase=wechat_dn1,sql=select `Begin` , `BriberiesCount` , `End` , `Id` , `Price` , `Ratio` , `Title`, `MerchantId` from `Activities` order by `Begin`  DESC,  jobHandler=io.mycat.catlets.ShareDBJoinHandler@2d597309], host=139.129.210.116, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.net.AbstractConnection:AbstractConnection.java:508) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,699 [INFO ][$_NIOREACTOR-1-RW] all job finished  for front connection: ServerConnection [id=459, schema=wechat, host=222.93.91.168, user=root,txIsolation=3, autocommit=true, schema=wechat]  (io.mycat.sqlengine.EngineCtx:EngineCtx.java:172) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,700 [INFO ][$_NIOREACTOR-1-RW] write  eof ,packgId:11  (io.mycat.sqlengine.EngineCtx:EngineCtx.java:160) 
INFO   | jvm 1    | 2016/09/02 12:56:39 | 2016-09-02 12:56:39,700 [INFO ][$_NIOREACTOR-1-RW] 发送数据OK  (io.mycat.catlets.ShareJoin$1:ShareJoin.java:157) 
INFO   | jvm 1    | 2016/09/02 12:56:40 | 2016-09-02 12:56:40,043 [WARN ][$_NIOREACTOR-2-RW]  find no Route:SELECT * FROM `wechat`.`activities` LIMIT 0  (io.mycat.route.parser.druid.impl.DruidSelectParser:DruidSelectParser.java:436) 
INFO   | jvm 1    | 2016/09/02 12:56:40 | 2016-09-02 12:56:40,043 [WARN ][$_NIOREACTOR-2-RW] ServerConnection [id=459, schema=wechat, host=222.93.91.168, user=root,txIsolation=3, autocommit=true, schema=wechat]SELECT * FROM `wechat`.`activities` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `wechat`.`activities` LIMIT 0 java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `wechat`.`activities` LIMIT 0
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:437)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:77)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.route.RouteService.route(RouteService.java:133)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:260)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:209)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:462)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:444)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2016/09/02 12:56:40 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/02 12:56:40 |  (io.mycat.server.ServerConnection:ServerConnection.java:268) 
```

**Comment by DuGuangWei** [comment]
这个你找到问题的解决方案了吗？
