### ISSUE TITLE
使用mysql-connector-java的6.0.3版驱动，查询报CLIENT_PLUGIN_AUTH is required错，连接字符串配置 useSSL=false 无效

### ISSUE THREAD

**Issue by sunnyfun888** [MyCATApache/Mycat-Server#1092]
应用相关错误日志摘要：

```
Caused by: com.mysql.cj.core.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_51]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_51]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_51]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_51]
    at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.mysqla.io.MysqlaProtocol.rejectConnection(MysqlaProtocol.java:286) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:208) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1330) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:154) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1783) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1653) ~[mysql-connector-java-6.0.3.jar:6.0.3]
    ... 52 common frames omitted
```

此错误一般由于使用ssl方式连接mysql，但没配置证书造成，一般可在连接字符串配置useSSL=false，以关闭ssl方式绕过，但此参数在mycat上配置无效，而使用该驱动直连mysql时是有效的。
其他可能有类似情况的参数：verifyServerCertificate=false

**Comment by ZzzCrazyPig** [comment]
@sunnyfun888  用的mycat是什么版本

**Comment by manondidi** [comment]
官网最新的1.6.7 还有这个问题
