### ISSUE TITLE
INSERT INTO 报错java.lang.IndexOutOfBoundsException: Index: 2, Size: 2? 

### ISSUE THREAD

**Issue by allankin** [MyCATApache/Mycat-Server#1131]
mycat  version: 1.4-release
表：
CREATE TABLE `customer` (
  `NAME` varchar(30) DEFAULT NULL,
  `ID` int(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

插入：
INSERT INTO  customer (NAME, ID) VALUES ('tom', 2) 
报错：
09/27 07:40:36.596   WARN [$_NIOREACTOR-0-RW] (ServerConnection.java:209) -ServerConnection [id=2, schema=TESTDB, host=192.168.1.101, user=test,txIsolation=3, autocommit=true, schema=TESTDB]INSERT INTO  customer (NAME, ID) VALUES ('tom', 2) err:java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:984)
        at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:877)
        at org.opencloudb.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:755)
        at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:75)
        at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:61)
        at org.opencloudb.route.RouteService.route(RouteService.java:118)
        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:201)
        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:120)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
你配置错误  根据分片规则计算出的dataNode  你没有配那么多

**Comment by allankin** [comment]
后来找到了，节点少配一个，tks
