### ISSUE TITLE
1.6使用subTables属性select count时报空指针异常

### ISSUE THREAD

**Issue by yintaiyuan** [MyCATApache/Mycat-Server#1144]
mycat1.6 使用subTables属性实现单库分表，使用oracle进行存储，当进行select count操作时，mycat控制台会报空指针异常：

2016-10-11 14:29:57.517  WARN [BusinessExecutor4] (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:660)) - caught exception 
java.lang.NullPointerException
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.aggregateRow(UnsafeRowGrouper.java:589) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.addRow(UnsafeRowGrouper.java:556) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.sqlengine.mpp.DataNodeMergeManager.run(DataNodeMergeManager.java:373) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_13]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_13]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_13]

配置如下（使用自然月进行分片）：
	<tableRule name="sharding-by-month">
		<rule>
			<columns>create_time</columns>
			<algorithm>partbymonth</algorithm>
		</rule>
	</tableRule>
	<function name="partbymonth"
		class="io.mycat.route.function.PartitionByMonth">
		<property name="dateFormat">yyyy-MM-dd</property>
		<property name="sBeginDate">2016-07-01</property>
	</function>

	<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">		
		<table name="SYS_LOG" needAddLimit="false" primaryKey="ID" dataNode="dn1" subTables="SYS_LOG_201607,SYS_LOG_201608,SYS_LOG_201609,SYS_LOG" 
			   rule="sharding-by-month">
		</table>
	</schema>
	<dataNode name="dn1" dataHost="dataHost01" database="test"/>
	<dataHost name="dataHost01" maxCon="1000" minCon="1" balance="0"
			  writeType="0" dbType="oracle" dbDriver="jdbc">
		<heartbeat>select 1 from dual</heartbeat>
		<connectionInitSql>alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'</connectionInitSql>
		<writeHost host="hostS1" url="jdbc:oracle:thin:@192.168.1.1:1521:NYY1" user="test"
				   password="test" />
	</dataHost>

其他查询操作正常，请问各位大侠该如何解决？谢谢

**Comment by yintaiyuan** [comment]
而且发现每次连接数据库时，debug都会显示发送了这样一条语句，
 1 -> dn1{SELECT @@character_set_database, @@collation_database}
但是却执行不了
execute  sql err : errno:936 ORA-00936: 缺失表达式
不知有没有影响。。。

**Comment by magicdoom** [comment]
你mysqljdbc 驱动版本多少    试试5.1.35

**Comment by yintaiyuan** [comment]
@magicdoom 你好，我底层连得是oracle，这跟驱动有关系吗？那oracle应该用哪个驱动呢？谢谢

**Comment by magicdoom** [comment]
你连mycat用的mysql的 jdbc驱动

**Comment by yintaiyuan** [comment]
@magicdoom 试过5.1.35也一样的错误。。。我用navicat连也一样。。。

**Comment by goushijie** [comment]
@yintaiyuan ，我们也需要这样用，解决了吗
