### ISSUE TITLE
1.6在win7下运行startup_nowrap.bat异常

### ISSUE THREAD

**Issue by enet2006** [MyCATApache/Mycat-Server#1152]
Failed to parse byte string: -187904819B
        at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAs(JavaUtils.java:22
3)
        at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAsBytes(JavaUtils.ja
va:234)
        at io.mycat.memory.unsafe.utils.MycatPropertyConf.byteStringAsBytes(Myca
tPropertyConf.java:92)
        at io.mycat.memory.unsafe.utils.MycatPropertyConf.getSizeAsBytes(MycatPr
opertyConf.java:50)
        at io.mycat.memory.unsafe.memory.mm.MemoryManager.<init>(MemoryManager.j
ava:30)
        at io.mycat.memory.unsafe.memory.mm.ResultMergeMemoryManager.<init>(Resu
ltMergeMemoryManager.java:15)
        at io.mycat.memory.MyCatMemory.<init>(MyCatMemory.java:125)
        at io.mycat.MycatServer.startup(MycatServer.java:327)
        at io.mycat.MycatStartup.main(MycatStartup.java:57)
 (io.mycat.MycatStartup:MycatStartup.java:62)

**Comment by magicdoom** [comment]
吧server.xml的配置贴一下   你是不是自己改了配置

**Comment by enet2006** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mycat:server SYSTEM "server.dtd">
<mycat:server xmlns:mycat="http://io.mycat/">
	<system>
	<property name="useSqlStat">0</property>  
	<property name="useGlobleTableCheck">0</property>  

		<property name="sequnceHandlerType">2</property>
       
         
	
	
		
		<property name="processorBufferPoolType">0</property>
		
		
		
		
		
		
		
		
		<property name="handleDistributedTransactions">0</property>
		
			
		<property name="useOffHeapForMerge">1</property>

		
		<property name="memoryPageSize">1m</property>

		
		<property name="spillsFileBufferSize">1k</property>

		<property name="useStreamOutput">0</property>

		
		<property name="systemReserveMemorySize">384m</property>
	</system>
	
	
	
	
	<user name="root">
		<property name="password">digdeep</property>
		<property name="schemas">TESTDB</property>
		
		
		
	</user>

	<user name="user">
		<property name="password">user</property>
		<property name="schemas">TESTDB</property>
		<property name="readOnly">true</property>
	</user>

</mycat:server>

**Comment by ZzzCrazyPig** [comment]
看下日志输出 `totalNetWorkBufferSize`为多少，同时打开startup_nowrap.bat看一下jvm参数`MaxDirectMemorySize`配了多少
```
[INFO ][main] totalNetWorkBufferSize = ?MB
```

**Comment by magicdoom** [comment]
jvm参数设置大点
