### ISSUE TITLE
select id as id from user:  [Err] 1064 - can't find table define in schema ID schema:TESTDB

### ISSUE THREAD

**Issue by chenyb888** [MyCATApache/Mycat-Server#1172]
java version "1.7.0_65"
mycat version
BuildTime  2016-10-12 09:00:27
GitVersion   cacf0e792dc36682dcac849abd8cdef7b82f7c5d
MavenVersion 1.6-RELEASE

**Comment by ZzzCrazyPig** [comment]
这个错误信息不准确，它的意思应该是：你没有定义`user`这个表(`schema.xml`文件里面`TESTDB`库没有这个表)

**Comment by chenyb888** [comment]
跟了一下，应该是 io/mycat/route/parser/druid/DruidParserFactory.java #124    stmt.accept(schemaStatVisitor); 这个方法有点问题，schemaStatVisitor.aliasMap 解析出来 =2，把id也认成表名了
    private static List<String> parseTables(SQLStatement stmt, SchemaStatVisitor schemaStatVisitor)
    {
        List<String> tables = new ArrayList<>();
        stmt.accept(schemaStatVisitor);

**Comment by magicdoom** [comment]
你需要给出更详细的信息 才好排查问题   比如什么sql解析的有问题

**Comment by gaojingsong** [comment]
2016-12-06 18:55:18,531 [INFO ][$_NIOREACTOR-1-RW] close connection,reason:quit cmd ,ServerConnection [id=5, schema=TESTDB, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB]  (io.mycat.net.AbstractConnection:AbstractConnection.java:508) 
2016-12-06 18:55:27,625 [WARN ][$_NIOREACTOR-0-RW] can't find table define in schema ID schema:TESTDB  (io.mycat.route.util.RouterUtil:RouterUtil.java:1001) 
2016-12-06 18:55:27,687 [WARN ][$_NIOREACTOR-0-RW] ServerConnection [id=4, schema=TESTDB, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB]SELECT id as id FROM `t_gaojs` err:java.sql.SQLNonTransientException: can't find table define in schema ID schema:TESTDB java.sql.SQLNonTransientException: can't find table define in schema ID schema:TESTDB
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1002)
	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:412)
	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287)
	at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67)
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84)
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
	at io.mycat.route.RouteService.route(RouteService.java:133)
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:276)
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
	at java.lang.Thread.run(Thread.java:722)
 (io.mycat.server.ServerConnection:ServerConnection.java:281) 

 错误的SQL语句：
SELECT id as id FROM `t_gaojs`;

OK的SQL语句：
SELECT id  FROM `t_gaojs`;


Debug结果发现：
TableConfig tableConfig = schema.getTables().get(tableName.toUpperCase());
			if(tableConfig == null) {
}此处返回【ID 和table 作为表名字集合报错】

**Comment by magicdoom** [comment]
最近1.6.5 已经fix这种情况
