### ISSUE TITLE
Mycat-server-1.5.1-RELEASE-20160929233042-linux_全局ID本地文件自增报-Too many open files

### ISSUE THREAD

**Issue by 59090939** [MyCATApache/Mycat-Server#1191]
11/03 15:58:24.588  ERROR [Thread-1] (IncrSequencePropHandler.java:116) -/usr/local/mycat/conf/sequence_conf.properties (Too many open files)
11/03 15:58:24.592  ERROR [Thread-1] (IncrSequencePropHandler.java:74) -/usr/local/mycat/conf/sequence_conf.properties (Too many open files)
11/03 15:58:24.592  ERROR [Thread-1] (MyCATSequnceProcessor.java:88) -MyCATSequenceProcessor.executeSeq(SesionSQLPair)
java.lang.RuntimeException: fetch Param Values error.
        at org.opencloudb.sequence.handler.IncrSequenceHandler.nextId(IncrSequenceHandler.java:60)
        at org.opencloudb.parser.druid.DruidSequenceHandler.getExecuteSql(DruidSequenceHandler.java:58)
        at org.opencloudb.route.MyCATSequnceProcessor.executeSeq(MyCATSequnceProcessor.java:84)
        at org.opencloudb.route.MyCATSequnceProcessor.access$200(MyCATSequnceProcessor.java:18)
        at org.opencloudb.route.MyCATSequnceProcessor$ExecuteThread.run(MyCATSequnceProcessor.java:104)
修改了open files数目，
ulimit -n 204800

**Comment by ZzzCrazyPig** [comment]
应该是BUG。生产上不建议使用本地文件自增

**Comment by 59090939** [comment]
你生产上面用的是那种方式。不过已经解决，不是BUG。

**Comment by ZzzCrazyPig** [comment]
噢？你的解决方式就是修改open files？持续跑着也不会再报错了？生产上如果要自增，用数据库方式自增，如果业务层可以提供，那用业务层的自增

**Comment by 59090939** [comment]
是的。修改open files.

**Comment by ZzzCrazyPig** [comment]
恩，建议还是用其他方式的自增方案，因为你的解决办法治标不治本，也许压力一大，这个值依然不够

**Comment by magicdoom** [comment]
文件方式的序列只用测试用      没有意义   后续会废弃掉

**Comment by 59090939** [comment]
那请问一下，现在自增方的话用的是那一种方案啊。。。

**Comment by magicdoom** [comment]
db  去看权威指南

**Comment by 59090939** [comment]
在看，只是想听听南兄的看法。。我觉的数据库方式，也不是太好。

**Comment by magicdoom** [comment]
db 或者1.6的zk方式都是比较好的

**Comment by 59090939** [comment]
1.5支不支持zk方式？？
