### ISSUE TITLE
Mycat查询多个AVG列抛java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ZzzCrazyPig** [MyCATApache/Mycat-Server#1194]
mycat版本1.5和1.6 旧内存管理模式下查询多个AVG列抛`java.lang.IndexOutOfBoundsException`

BUG重现:

```sql
mysql> select avg(id),avg(id) from product;
ERROR 1105 (HY000): java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
```

mycat后台异常堆栈:

```bash
caught exception  java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at io.mycat.sqlengine.mpp.RowDataPacketGrouper.mergAvg(RowDataPacketGrouper.java:240)
	at io.mycat.sqlengine.mpp.RowDataPacketGrouper.getResult(RowDataPacketGrouper.java:68)
	at io.mycat.sqlengine.mpp.DataMergeService.getResults(DataMergeService.java:272)
	at io.mycat.sqlengine.mpp.DataMergeService.run(DataMergeService.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

定位到`RowDataPacketGrouper`类的`mergAvg`方法，发现处理逻辑有问题:

在处理avg结果的for循环里面删除了数组元素，导致下一个avg的处理抛数组下表越界的Exception。

**Comment by magicdoom** [comment]
你可以尝试修复下
