### ISSUE TITLE
v1.3.2 数据少的时候查询排序结果正常，当数据量多时则异常：(DataMergeService.java:274) -data Merge error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by yoyoch1** [MyCATApache/Mycat-Server#120]
现象：
（1）把时间范围条件缩得很短时，数据量少时可以查出来结果，时段很长数据量多时就报如下错误，数据量应该也不是很大，分片1有47行汇总数据，分片2有469行汇总数据，分片3~12汇总数据没有。
（2）SQL格式：
      select sum(...) As s,date_format(....) As dt,name
      from T1
      inner join T2 on ......
      inner join T3 on....
      where .....
      group by   dt
      order by   dt      
      去掉order by   dt      后正常查出结果
（3）异常log：
01/27 18:42:42.383  DEBUG [$_NIOREACTOR-0-RW] (ServerQueryHandler.java:64) -ServerConnection [id=2, schema=test01, host=192.168.1.18, user=root,txIsolation=3, autocommit=false, schema=test01]rollback
01/27 18:42:42.383  DEBUG [$_NIOREACTOR-0-RW] (NonBlockingSession.java:191) -no session bound connections found ,no need send rollback cmd 
01/27 18:42:42.384   WARN [BusinessExecutor0] (DataMergeService.java:274) -data Merge error:
java.lang.NullPointerException
	at org.opencloudb.mpp.DataMergeService.handleRowData(DataMergeService.java:236)
	at org.opencloudb.mpp.DataMergeService.access$200(DataMergeService.java:48)
	at org.opencloudb.mpp.DataMergeService$2.run(DataMergeService.java:260)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
01/27 18:42:42.384   WARN [BusinessExecutor4] (DataMergeService.java:274) -data Merge error:
java.lang.NullPointerException
	at org.opencloudb.mpp.DataMergeService.handleRowData(DataMergeService.java:236)
	at org.opencloudb.mpp.DataMergeService.access$200(DataMergeService.java:48)
	at org.opencloudb.mpp.DataMergeService$2.run(DataMergeService.java:260)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

。。。。

}, respHandler=org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler@270f009c, host=localhost, port=3307, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
01/27 18:59:35.182  DEBUG [$_NIOREACTOR-3-RW] (PhysicalDatasource.java:386) -release channel MySQLConnection [id=3, lastTime=1422356375078, schema=db02, borrowed=true, fromSlaveDB=false, threadId=116, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=localhost, port=3310, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
01/27 18:59:35.185   WARN [BusinessExecutor3] (MultiNodeQueryHandler.java:401) -caught exception 
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 515
	at java.util.Vector.get(Unknown Source)
	at org.opencloudb.mpp.tmp.RowDataSorter.getSortedResult(RowDataSorter.java:78)
	at org.opencloudb.mpp.DataMergeService.getResults(DataMergeService.java:125)
	at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler.outputMergeResult(MultiNodeQueryHandler.java:284)
	at org.opencloudb.mpp.DataMergeService$1.run(DataMergeService.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
01/27 18:59:35.186  DEBUG [BusinessExecutor3] (MultiNodeHandler.java:193) -error all end ,clear session resource 
01/27 18:59:35.186  DEBUG [BusinessExecutor3] (DataMergeService.java:312) -clear data 
01/27 18:59:35.186  DEBUG [BusinessExecutor3] (DataMergeService.java:312) -clear data

**Comment by apachemycat** [comment]
看看最新版本是否解决了这个Bug

**Comment by mycatmerger** [comment]
请检查是否分片的表结构不一致

**Comment by magicdoom** [comment]
跨库join默认不支持
