### ISSUE TITLE
ERROR 3009 (HY000): java.lang.NullPointerException

### ISSUE THREAD

**Issue by wengad82** [MyCATApache/Mycat-Server#1268]
在schema和server中新增了配置，一个新的schema，关联了一个新的dataNode，但是datanode使用一个老的datahosts。修改后，reload @@config 成功，但是执行show tables是 报错
mysql> show tables;
ERROR 3009 (HY000): java.lang.NullPointerException
这时候必须重启mycat服务才能生效，这个是这么用的吗？ 还是有BUG?

日志文件信息如下：
2016-12-07 12:04:17.440  WARN [$_NIOREACTOR-3-RW] (io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:135)) - ServerConnection [id=3, schema=CRMDB_DBA2, host=127.0.0.1, user=fstar_dba2,txIsolation=3, autocommit=true, schema=CRMDB_DBA2]show tables, route={
   1 -> crm_dn1_dba23{show tables}
}
java.lang.NullPointerException
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:182) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:132) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:288) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.response.ShowTables.response(ShowTables.java:57) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.handler.ShowHandler.handle(ShowHandler.java:48) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:76) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]

**Comment by HashZhang** [comment]
不是这么改的，需要执行reload @@config_all

**Comment by HashZhang** [comment]
不是这么改的，需要执行reload @@config_all

**Comment by HashZhang** [comment]
不是这么改的，需要执行reload @@config_all
