### ISSUE TITLE
v1.3.2-druidparser解析，但报另外一个解析的org.opencloudb.parser.SQLParserDelegate.parse异常

### ISSUE THREAD

**Issue by yoyoch1** [MyCATApache/Mycat-Server#127]
1.解析器：druidparser
2.SQL：insert into test01(name,descs) values('sdf','sdf'),values('sdfdf','sdfdsgfdf'）
3.备注：id使用db自增序列
5.异常信息：
01/29 16:48:40.105  DEBUG [$_NIOREACTOR-3-RW] (ServerQueryHandler.java:64) -ServerConnection [id=1, schema=iems, host=192.168.1.208, user=root,txIsolation=3, autocommit=true, schema=tt]insert into test01(name,descs)
values('sdf','sdf'),values('sdfdf','sdfdsgfdf')
01/29 16:48:40.107  ERROR [Thread-1] (MyCATSequnceProcessor.java:84) -MyCATSequenceProcessor.executeSeq(SesionSQLPair)
java.sql.SQLSyntaxErrorException: com.foundationdb.sql.StandardException: VALUES is empty
	at org.opencloudb.parser.SQLParserDelegate.parse(SQLParserDelegate.java:70)
	at org.opencloudb.route.MyCATSequnceProcessor.executeSeq(MyCATSequnceProcessor.java:74)
	at org.opencloudb.route.MyCATSequnceProcessor.access$200(MyCATSequnceProcessor.java:22)
	at org.opencloudb.route.MyCATSequnceProcessor$ExecuteThread.run(MyCATSequnceProcessor.java:101)
Caused by: com.foundationdb.sql.StandardException: VALUES is empty
	at com.foundationdb.sql.parser.SQLGrammar.rowValueConstructorElement(SQLGrammar.java:8583)
	at com.foundationdb.sql.parser.SQLGrammar.rowValueConstructor(SQLGrammar.java:8521)
	at com.foundationdb.sql.parser.SQLGrammar.tableValueConstructorList(SQLGrammar.java:9824)
	at com.foundationdb.sql.parser.SQLGrammar.tableValueConstructor(SQLGrammar.java:9805)
	at com.foundationdb.sql.parser.SQLGrammar.simpleTable(SQLGrammar.java:4598)
	at com.foundationdb.sql.parser.SQLGrammar.nonJoinQueryPrimary(SQLGrammar.java:4573)
	at com.foundationdb.sql.parser.SQLGrammar.nonJoinQueryTerm(SQLGrammar.java:4462)
	at com.foundationdb.sql.parser.SQLGrammar.queryExpression(SQLGrammar.java:4367)
	at com.foundationdb.sql.parser.SQLGrammar.insertColumnsAndSource(SQLGrammar.java:8384)
	at com.foundationdb.sql.parser.SQLGrammar.insertStatement(SQLGrammar.java:2449)
	at com.foundationdb.sql.parser.SQLGrammar.preparableSQLDataStatement(SQLGrammar.java:2208)
	at com.foundationdb.sql.parser.SQLGrammar.StatementPart(SQLGrammar.java:1948)
	at com.foundationdb.sql.parser.SQLGrammar.Statement(SQLGrammar.java:1846)
	at com.foundationdb.sql.parser.SQLGrammar.parseStatement(SQLGrammar.java:1832)
	at com.foundationdb.sql.parser.SQLParser.parseStatement(SQLParser.java:104)
	at org.opencloudb.parser.SQLParserDelegate.parse(SQLParserDelegate.java:68)
	... 3 more

**Comment by apachemycat** [comment]
从日志来看，你用的foundationdb解析器，这个解析器不支持insert into test01(name,descs) values('sdf','sdf'),values('sdfdf','sdfdsgfdf'）这种多values的，只有Druid解析器支持，参考Mycat In Action文档看看怎么设置。

**Comment by yoyoch1** [comment]
server.xml中配置的就是 druidparser解析器。怎么调到那个at com.foundationdb.sql.parser呢。到运行了几天了，一直用druidparser。

**Comment by yoyoch1** [comment]
一直都是<property name="defaultSqlParser">druidparser</property>，没配置错吧。

**Comment by linzhiqiang0514** [comment]
.SQL：insert into test01(name,descs) values('sdf','sdf'),values('sdfdf','sdfdsgfdf'）
应该是
.SQL：insert into test01(name,descs) values('sdf','sdf'),('sdfdf','sdfdsgfdf'）
这样才对吧？

**Comment by yoyoch1** [comment]
两样都不支持，看下面异常日志。看来明天再下个版本下来看看。
01/29 16:42:13.743  DEBUG [$_NIOREACTOR-3-RW] (ServerQueryHandler.java:64) -ServerConnection [id=1, schema=iems, host=192.168.1.208, user=root,txIsolation=3, autocommit=true, schema=tt]insert into test01(name,descs)
values('sdf','sdf'),('sdfdf','sdfdsgfdf')
01/29 16:42:13.744  ERROR [Thread-1] (MyCATSequnceProcessor.java:84) -MyCATSequenceProcessor.executeSeq(SesionSQLPair)
java.sql.SQLSyntaxErrorException: com.foundationdb.sql.StandardException: Row value size is different
	at org.opencloudb.parser.SQLParserDelegate.parse(SQLParserDelegate.java:70)
	at org.opencloudb.route.MyCATSequnceProcessor.executeSeq(MyCATSequnceProcessor.java:74)
	at org.opencloudb.route.MyCATSequnceProcessor.access$200(MyCATSequnceProcessor.java:22)
	at org.opencloudb.route.MyCATSequnceProcessor$ExecuteThread.run(MyCATSequnceProcessor.java:101)
Caused by: com.foundationdb.sql.StandardException: Row value size is different
	at com.foundationdb.sql.parser.SQLGrammar.rowValueConstructor(SQLGrammar.java:8538)
	at com.foundationdb.sql.parser.SQLGrammar.tableValueConstructorList(SQLGrammar.java:9824)
	at com.foundationdb.sql.parser.SQLGrammar.tableValueConstructor(SQLGrammar.java:9805)
	at com.foundationdb.sql.parser.SQLGrammar.simpleTable(SQLGrammar.java:4598)
	at com.foundationdb.sql.parser.SQLGrammar.nonJoinQueryPrimary(SQLGrammar.java:4573)
	at com.foundationdb.sql.parser.SQLGrammar.nonJoinQueryTerm(SQLGrammar.java:4462)
	at com.foundationdb.sql.parser.SQLGrammar.queryExpression(SQLGrammar.java:4367)
	at com.foundationdb.sql.parser.SQLGrammar.insertColumnsAndSource(SQLGrammar.java:8384)
	at com.foundationdb.sql.parser.SQLGrammar.insertStatement(SQLGrammar.java:2449)
	at com.foundationdb.sql.parser.SQLGrammar.preparableSQLDataStatement(SQLGrammar.java:2208)
	at com.foundationdb.sql.parser.SQLGrammar.StatementPart(SQLGrammar.java:1948)
	at com.foundationdb.sql.parser.SQLGrammar.Statement(SQLGrammar.java:1846)
	at com.foundationdb.sql.parser.SQLGrammar.parseStatement(SQLGrammar.java:1832)
	at com.foundationdb.sql.parser.SQLParser.parseStatement(SQLParser.java:104)
	at org.opencloudb.parser.SQLParserDelegate.parse(SQLParserDelegate.java:68)
	... 3 more

**Comment by linzhiqiang0514** [comment]
目前最新的1.4-dev已经移除fdb相关的代码，请重新测试看看。

**Comment by yoyoch1** [comment]
那还用配置使用那个解析器不？

**Comment by mycatmerger** [comment]
1.4序列已经完全改成druid解析，推荐使用1.4版
