### ISSUE TITLE
sequnce db方式很不稳定，我昨天测试的正常，下班后把测试机关了今天再启动，sequnce db就无法正常工作

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#129]
问题描述：
第一天往mycat_sequence表中配置了相关表的sequence信息，同时把那三个function也都在数据库创建完成，sequence_db_conf.properties也做了配置。启动的时候，往数据库插入数据，提示：
java.lang.RuntimeException: can't fetch sequnce in db,sequnce :SAM_GLUCOSE
	at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:101)
	at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:71)
	at org.opencloudb.parser.ExtNodeToString4SEQ.nextSequenceNode(ExtNodeToString4SEQ.java:61)
	at com.foundationdb.sql.unparser.NodeToString.toString(NodeToString.java:267)
	at com.foundationdb.sql.unparser.NodeToString.maybeParens(NodeToString.java:1471)
	at com.foundationdb.sql.unparser.NodeToString.resultColumn(NodeToString.java:737)
	at com.foundationdb.sql.unparser.NodeToString.toString(NodeToString.java:95)
	at com.foundationdb.sql.unparser.NodeToString.nodeList(NodeToString.java:1465)
	at com.foundationdb.sql.unparser.NodeToString.nodeList(NodeToString.java:1453)
	at com.foundationdb.sql.unparser.NodeToString.resultColumnList(NodeToString.java:726)
	at com.foundationdb.sql.unparser.NodeToString.toString(NodeToString.java:93)
	at com.foundationdb.sql.unparser.NodeToString.rowResultSetNode(NodeToString.java:707)
	at com.foundationdb.sql.unparser.NodeToString.toString(NodeToString.java:125)
	at com.foundationdb.sql.unparser.NodeToString.insertNode(NodeToString.java:605)
	at com.foundationdb.sql.unparser.NodeToString.toString(NodeToString.java:85)
	at org.opencloudb.route.MyCATSequnceProcessor.executeSeq(MyCATSequnceProcessor.java:76)
	at org.opencloudb.route.MyCATSequnceProcessor.access$2(MyCATSequnceProcessor.java:66)
	at org.opencloudb.route.MyCATSequnceProcessor$ExecuteThread.run(MyCATSequnceProcessor.java:101)

我在org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB 方法中加断点debug后，自己恢复正常了，在2015-01-29一整天测试都正常。
29号下班时我把测试机关了。30号我上班后把测试机打开，启动mycat服务都正常，执行查询操作也都正常，但是插入数据的时候 sequence又报：
java.lang.RuntimeException: can't fetch sequnce in db,sequnce :SAM_GLUCOSE 同样的问题了。
这次加debug断点调试也不行了。好不稳定啊！求解？

**Comment by apachemycat** [comment]
从过程来看，一开始就没有配置正确。请参考Mycat In Action ,若配置正确，则可以 命令行select 序列号的的值。

**Comment by linzhiqiang0514** [comment]
请测试确认问题是否已经解决。
