### ISSUE TITLE
Mycat1.6版本 reload 配置后报错

### ISSUE THREAD

**Issue by Duntian** [MyCATApache/Mycat-Server#1296]
修改schema和server.xml后，通过reload的方式加载
能够正常验证用户名密码，获取到相关database权限，但是在打开库查看表时，报错。

然后重启mycat后，恢复正常。

在日志里看到以下错误
SHOW FULL TABLES WHERE Table_type != 'VIEW', route={
INFO   | jvm 1    | 2016/12/14 14:10:15 |    1 -> config{SHOW FULL TABLES WHERE Table_type != 'VIEW'}
INFO   | jvm 1    | 2016/12/14 14:10:15 | } java.lang.NullPointerException
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:182)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:132)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:288)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.response.ShowFullTables.response(ShowFullTables.java:58)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.handler.ShowHandler.handle(ShowHandler.java:51)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:76)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2016/12/14 14:10:15 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/12/14 14:10:15 |  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:135)

**Comment by magicdoom** [comment]
这个是用某个gui工具连mycat？？

**Comment by zhuam** [comment]
reload @@config_all   or  @@config  ， 另外确认一下是否 reload 成功了

**Comment by fireflyhoo** [comment]
应该是用了 navicat

**Comment by wowkingah** [comment]
https://github.com/MyCATApache/Mycat-Server/issues/1273
