### ISSUE TITLE
这个问题偶尔出现，很头疼啊。

### ISSUE THREAD

**Issue by githublaohu** [MyCATApache/Mycat-Server#1300]
查询语句是
select * from vp_user_var where user_app_id = 800000002 limit 16;

2016-12-16 19:05:03.107 ERROR [$_NIOREACTOR-1-RW] (io.mycat.statistic.HeartbeatRecorder.set(HeartbeatRecorder.java:84)) - record HeartbeatRecorder error 
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_111]
	at io.mycat.statistic.HeartbeatRecorder.calculate(HeartbeatRecorder.java:119) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.statistic.HeartbeatRecorder.set(HeartbeatRecorder.java:82) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.heartbeat.MySQLDetector.onResult(MySQLDetector.java:206) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.heartbeat.MySQLDetector.onResult(MySQLDetector.java:42) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.sqlengine.OneRawSQLQueryResultHandler.finished(OneRawSQLQueryResultHandler.java:81) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.sqlengine.SQLJob.doFinished(SQLJob.java:106) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.sqlengine.SQLJob.rowEofResponse(SQLJob.java:165) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowEofPacket(MySQLConnectionHandler.java:224) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:132) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:263) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6.5-DEV.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by magicdoom** [comment]
主要是HeartbeatRecorder里的linklist是非线程安全的   把这个list替换成线程安全的就可以了，希望有志愿者来修改

**Comment by brotherbin** [comment]
我这也碰到过这个问题，我来改下

**Comment by magicdoom** [comment]
ok  欢迎
