### ISSUE TITLE
插入英文字符"?"时出现错误

### ISSUE THREAD

**Issue by laula001** [MyCATApache/Mycat-Server#1307]
使用mycat1.6 realease版本，插入数据时带有英文问号‘?’，mycat解析语句会将英文问号替换为 ‘时间戳’，从而插入失败，报SQL语法错误

`java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:74) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:133) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:141) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:386) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:99) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2132) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2022) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:193) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:199) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:70) ~[Mycat-server-1.6-RELEASE.jar:?]
	... 16 more`

**Comment by ZzzCrazyPig** [comment]
这是用什么语言接入mycat的？用了预处理sql？mycat1.6是 GitHub上最新的源码编译出来么？这个问题好像前段时间有改动过了

**Comment by magicdoom** [comment]
用1.6.5编译的已经fix

**Comment by laula001** [comment]
@ZzzCrazyPig @magicdoom 感谢回复，不是最新源码编译的，下的编译好的包，开发用的jpa，不过直接insert语句也不行，目前暂时用程序过滤了特殊字符，再测试一下1.6.5版本是否可行吧

**Comment by laula001** [comment]
@ZzzCrazyPig @magicdoom 目前1.6.5还是开发版，不敢用在生产环境上，1.6release版本应该在根本上解决该问题呢？
