### ISSUE TITLE
通过pdo 执行sql 字段类型为 smallint 报 ArrayIndexOutOfBoundsException 异常

### ISSUE THREAD

**Issue by isoleo** [MyCATApache/Mycat-Server#1308]
mycat 1.6.5
php 5.4.3  预处理关闭 false
sql 随便一个就行比如 select * from table 
表字段类型要有一个是 smallint not null 
通过pdo 执行，就会抛如下的错误 。
我从早上一直找到现在。 。。。。

2016-12-22 15:50:43.586  WARN [$_NIOREACTOR-5-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
java.lang.ArrayIndexOutOfBoundsException: 1
	at io.mycat.util.ByteUtil.getShort(ByteUtil.java:158) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.mysql.BinaryRowDataPacket.convert(BinaryRowDataPacket.java:161) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.mysql.BinaryRowDataPacket.read(BinaryRowDataPacket.java:95) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:452) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:204) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:135) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:263) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6.5-DEV.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2016-12-22 15:50:43.586  INFO [$_NIOREACTOR-5-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:508)) - close connection,reason:program err:java.lang.ArrayIndexOutOfBoundsException: 1 ,MySQLConnection [id=45, lastTime=1482393043580, user=ruby_user, schema=c2c_goods, old shema=c2c_goods, borrowed=true, fromSlaveDB=false, threadId=1200546, charset=utf8, txIsolation=3, autocommit=true, attachment=dn45{SELECT goods_id,sub_category_id,style_id,times_num,season_num,file_format,fize_resolution,dpi,pic_size,pci_sex,role_age,info.goods_info,info.preview,glist.goods_name,glist.stock_num,glist.create_time,glist.goods_name,glist.goods_info as ggoods_info,glist.file_size as file_size,glist.price as price,glist.seller_id as seller_id,info.preview as gpreview FROM c2c_goods_drawing info straight_join 
                            c2c_goods_list glist 
                            ON glist.id = info.goods_id 
                             WHERE goods_id = 40}, respHandler=SingleNodeHandler [node=dn45{SELECT goods_id,sub_category_id,style_id,times_num,season_num,file_format,fize_resolution,dpi,pic_size,pci_sex,role_age,info.goods_info,info.preview,glist.goods_name,glist.stock_num,glist.create_time,glist.goods_name,glist.goods_info as ggoods_info,glist.file_size as file_size,glist.price as price,glist.seller_id as seller_id,info.preview as gpreview FROM c2c_goods_drawing info straight_join 
                            c2c_goods_list glist 
                            ON glist.id = info.goods_id 
                             WHERE goods_id = 40}, packetId=25], host=10.171.219.217, port=3309, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]

**Comment by ZzzCrazyPig** [comment]
server.xml的`<system>`配置给一下 @isoleo
