### ISSUE TITLE
MYCAT 全局sequence 查询语句，默认druid sql解析器报错

### ISSUE THREAD

**Issue by jiangchengshi** [MyCATApache/Mycat-Server#1314]
INSERT INTO C_CART
(cartId, customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
VALUES
(next value for MYCATSEQ_CART, ?, ?, ?, ?, ?, ?, ?, ?, ?)

在 控制台 运行， 报错信息(部分)：
caught err: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' FOR MYCATSEQ_CART',expect UPDATE, actual IDENTIFIER MYCATSEQ_CART
at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:179)
at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:237)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:183)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:25)
at io.mycat.server.ServerConnection.execute(ServerConnection.java:214)
at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)

 我已反馈给 druid 大神 @wenshao， 麻烦你们也关注下，推动下这个问题， 是否能更改下语法规则？
https://github.com/alibaba/druid/issues/1559

**Comment by union-gcyjh** [comment]
好的

________________________________
lepao626@outlook.com

发件人： 简单<mailto:notifications@github.com>
发送时间： 2016-12-28 13:39
收件人： MyCATApache/Mycat-Server<mailto:Mycat-Server@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [MyCATApache/Mycat-Server] MYCAT 全局sequence 查询语句，默认druid sql解析器报错 (#1314)

INSERT INTO C_CART
(cartId, customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
VALUES
(next value for MYCATSEQ_CART, ?, ?, ?, ?, ?, ?, ?, ?, ?)

在 控制台 运行， 报错信息(部分)：
caught err: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' FOR MYCATSEQ_CART',expect UPDATE, actual IDENTIFIER MYCATSEQ_CART
at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:179)
at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:237)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:183)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:25)
at io.mycat.server.ServerConnection.execute(ServerConnection.java:214)
at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)

@wenshao<https://github.com/wenshao> 我已反馈给 druid 维护大神， 麻烦你们也关注下，推动下这个问题， 是否能更改下语法规则？
alibaba/druid#1559<https://github.com/alibaba/druid/issues/1559>

**Comment by HashZhang** [comment]
你可以这么写就插入了：
`INSERT INTO C_CART
(customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
VALUES
( ?, ?, ?, ?, ?, ?, ?, ?, ?)`
你不用自己写next value for MYCATSEQ_CART，这个是MyCat帮你改写的

**Comment by jiangchengshi** [comment]
文档...  
测试通过，谢谢！@HashZhang

**Comment by exhui** [comment]
你可以这么写就插入了：
INSERT INTO C_CART (customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?)
你不用自己写next value for MYCATSEQ_CART，这个是MyCat帮你改写的

如果不用写next value，那应该在哪里配置吗？没找到相应的文档

**Comment by jiangchengshi** [comment]
Mycat文档里面有详细说明： 全局Sequence

字段设置为自增，然后按照文档配置下，就可以了。

**Comment by fyzjhh** [comment]
看了下具体实现, mycat当中 next value for MYCATSEQ_xxx 是通过正则匹配 替换为 具体值 , 改写sql实现的;


这个问题是因为sql中如果有next value for MYCATSEQ_xxx , 如果checkSQLschema为true则会在没有进行替换之前就进行 druid 解析sql , druid解析不支持这个语法, 所以就报错了. 

所以一般的就是 不写主键字段, 或者设置 checkSQLschema 为false

**Comment by liubo-tech** [comment]
> 看了下具体实现, mycat当中 next value for MYCATSEQ_xxx 是通过正则匹配 替换为 具体值 , 改写sql实现的;
> 
> 这个问题是因为sql中如果有next value for MYCATSEQ_xxx , 如果checkSQLschema为true则会在没有进行替换之前就进行 druid 解析sql , druid解析不支持这个语法, 所以就报错了.
> 
> 所以一般的就是 不写主键字段, 或者设置 checkSQLschema 为false

checkSQLschema 为false  好用
