### ISSUE TITLE
mycat1.6执行update报错

### ISSUE THREAD

**Issue by dengly** [MyCATApache/Mycat-Server#1319]
我在hibernate上有个sql发给mycat，mycat执行报错了。sql是
```
update
        doorbell
    set
        deletec=1
    where
        id in (
            '0089819a077d4a0d90b8c4a6c54938cb'
        )
```

错误信息是

```
14:51:48.998 [daoBoxServer11-DoorbellDao-Ice.ThreadPool.Server-10] WARN  daoBoxServer11-DoorbellDao -dispatch exception:
identity: DoorbellDao
facet: 
operation: deleteDoorbellByIds
remote host: 10.0.0.111 remote port: 34184
org.springframework.orm.hibernate5.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1105]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
        at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:248)
        at org.springframework.orm.hibernate5.HibernateTemplate.doExecute(HibernateTemplate.java:362)
        at org.springframework.orm.hibernate5.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:326)
        at org.springframework.orm.hibernate5.HibernateTemplate.bulkUpdate(HibernateTemplate.java:1131)
        at com.zzwtec.community.dao.BaseDaoI.deleteObjectByIds(BaseDaoI.java:166)
        at com.zzwtec.community.dao.BaseDaoI$$FastClassBySpringCGLIB$$3d16b66f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.zzwtec.community.dao.BaseDaoI$$EnhancerBySpringCGLIB$$68a148ba.deleteObjectByIds(<generated>)
        at com.zzwtec.community.dao.DoorbellDaoI.deleteDoorbellByIds(DoorbellDaoI.java:62)
        at com.zzwtec.community.dao._DoorbellDaoDisp.___deleteDoorbellByIds(_DoorbellDaoDisp.java:261)
        at com.zzwtec.community.dao._DoorbellDaoDisp.__dispatch(_DoorbellDaoDisp.java:425)
        at Ice.ObjectImpl.ice_dispatch(ObjectImpl.java:294)
        at Ice.ObjectImpl.ice_dispatch(ObjectImpl.java:319)
        at Ice.ObjectImpl$$FastClassBySpringCGLIB$$257bfd82.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.zzwtec.community.dao.DoorbellDaoI$$EnhancerBySpringCGLIB$$60a802da.ice_dispatch(<generated>)
        at com.zzwtec.community.ice.interceptor.PerfDispatchInterceptor.dispatch(PerfDispatchInterceptor.java:63)
        at Ice.DispatchInterceptor.__dispatch(DispatchInterceptor.java:44)
        at IceInternal.Incoming.invoke(Incoming.java:221)
        at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
        at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
        at Ice.ConnectionI.message(ConnectionI.java:1056)
        at IceInternal.ThreadPool.run(ThreadPool.java:395)
        at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
        at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:91)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:60)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:429)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1348)
        at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:102)
        at org.springframework.orm.hibernate5.HibernateTemplate$38.doInHibernate(HibernateTemplate.java:1143)
        at org.springframework.orm.hibernate5.HibernateTemplate$38.doInHibernate(HibernateTemplate.java:1131)
        at org.springframework.orm.hibernate5.HibernateTemplate.doExecute(HibernateTemplate.java:359)
        ... 50 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.sql.ast.expr.SQLInListExpr@8f42eca7' at line 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
        ... 59 more
```

**Comment by brotherbin** [comment]
这个日志提示是语法错误，Mycat是支持这类语句的，看是不是哪里写错了，或者把Mycat的日志贴出来

**Comment by dengly** [comment]
这是mycat的日志
2016-12-29 14:51:48.938  WARN [$_NIOREACTOR-1-RW] (io.mycat.backend.mysql.nio.handler.MultiNodeHandler.errorResponse(MultiNodeHandler.java:135)) - error response from MySQLConnection [id=18387, lastTime=1482994308922, user=root, schema=community_base, old shema=community_base, borrowed=true, fromSlaveDB=false, threadId=2623449, charset=utf8, txIsolation=3, autocommit=false, attachment=communityBase2{update doorbell set deletec=1,_mycat_op_time=1482994308936 where com.alibaba.druid.sql.ast.expr.SQLInListExpr@8f42eca7}, respHandler=io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@18fbd471, host=10.0.0.112, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=true] err You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.sql.ast.expr.SQLInListExpr@8f42eca7' at line 1 code:1064

**Comment by dengly** [comment]
这个com.alibaba.druid.sql.ast.expr.SQLInListExpr@8f42eca7 应该是java对象的地址 可能是在SQL拼接时出了问题

**Comment by brotherbin** [comment]
检查下应用端

**Comment by dengly** [comment]
应用端直连mysql是正常的 但是通过mycat就不行

**Comment by brotherbin** [comment]
你通过命令行把这个sql发到Mycat上试下，看是哪个环节的问题

**Comment by dengly** [comment]
以下是命令行执行的结果
```
mysql> update doorbell set deletec=1 where id in ('0089819a077d4a0d90b8c4a6c54938cb');
ERROR 1105 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.sql.ast.expr.SQLInListExpr@8f42eca7' at line 1
```

**Comment by magicdoom** [comment]
应该是个bug  本来直接tostring    现在打印出对象的地址了

2016-12-30 14:29 GMT+08:00 邓燎燕 <notifications@github.com>:

**Comment by ZzzCrazyPig** [comment]
@dengly 我用最新的mycat1.6源码debug，没重现你的异常，请你最好提供以下信息，方便我们重现:

- mycat的具体版本号
- doorbell这个表的配置(schema.xml配置)，用了什么分片算法？字段`id`是主键？

**Comment by dengly** [comment]
@ZzzCrazyPig 

mycat的版本是Mycat-server-1.6-RELEASE-20161028204710-linux

schema.xml配置如下，没有使用分片，字段id是主键，类型是varchar(32)
```
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
    <schema name="community_base" checkSQLschema="false" sqlMaxLimit="100">
        <table name="doorbell" primaryKey="id" type="global" dataNode="communityBase1,communityBase2" />
    </schema>
    <dataNode name="communityBase1" dataHost="dataHostTest111" database="community_base" />
    <dataNode name="communityBase2" dataHost="dataHostTest112" database="community_base" />
    <dataHost name="dataHostTest111" maxCon="100" minCon="10" balance="2" writeType="0" dbType="mysql" dbDriver="native" switchType="1" slaveThreshold="100" >
        <heartbeat>select user()</heartbeat>
        <writeHost host="10.0.0.111" url="10.0.0.111:3306" user="root" password="123456">
    	    <!-- can have multi read hosts -->
            <readHost host="10.0.0.112" url="10.0.0.112:3306" user="root" password="123456" />
        </writeHost>
    </dataHost>
    <dataHost name="dataHostTest112" maxCon="100" minCon="10" balance="2" writeType="0" dbType="mysql" dbDriver="native" switchType="1" slaveThreshold="100" >
        <heartbeat>select user()</heartbeat>
        <writeHost host="10.0.0.112" url="10.0.0.112:3306" user="root" password="123456">
            <!-- can have multi read hosts -->
            <readHost host="10.0.0.111" url="10.0.0.111:3306" user="root" password="123456" />
        </writeHost>
    </dataHost>
</mycat:schema>
```
