### ISSUE TITLE
load data local异常

### ISSUE THREAD

**Issue by chenlong12** [MyCATApache/Mycat-Server#1328]
**历史数据有3千多万条，目前只能导入200多万条数据就会报一下的错误，各种参数调整均无效果。直接导入mysql没有问题。求大神赐教，用的是1.6版本**

2017-01-10 13:40:03.279  WARN [$_NIOREACTOR-2-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
java.lang.NullPointerException
	at io.mycat.net.AbstractConnection.writeToBuffer(AbstractConnection.java:475) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.write(AbstractConnection.java:417) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.backend.mysql.LoadDataUtil.requestFileDataResponse(LoadDataUtil.java:62) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.requestDataResponse(MultiNodeQueryHandler.java:734) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRequestPacket(MySQLConnectionHandler.java:179) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:101) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:263) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
2017-01-10 13:40:03.301  INFO [$_NIOREACTOR-2-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:508)) - close connection,reason:program err:java.lang.NullPointerException ,MySQLConnection [id=29, lastTime=1484026795819, user=root, schema=mycat_zzjr_server2, old shema=mycat_zzjr_server2, borrowed=true, fromSlaveDB=false, threadId=350, charset=utf8, txIsolation=3, autocommit=true, attachment=dn7{LOAD DATA LOCAL INFILE '/tmp/wallet_profit.txt' INTO TABLE wallet_profit COLUMNS TERMINATED BY '	' LINES TERMINATED BY '
' (`id`, `member_id`, `profit_date`, `prod_id`, `wallet_amount`, `day_wallet_profit`, `base_profit`, `coupon_profit`, `annual_rate`, `coupon_rate`, `gmt_create`, `gmt_modify`)}, respHandler=io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@4b4ebc5b, host=172.17.3.14, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@1e3020fd, writeQueue=0, modifiedSQLExecuted=true]
2017-01-10 13:40:13.130  WARN [$_NIOREACTOR-2-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:

**Comment by 5253zz** [comment]
我也出现这个问题，你现在搞定没

**Comment by jason8888888** [comment]
我也遇到这个问题,之后解决了吗
