### ISSUE TITLE
使用阿里云SLB进行mycat负载均衡时不停 register err

### ISSUE THREAD

**Issue by jokimina** [MyCATApache/Mycat-Server#1357]
### 前端：使用的阿里云SLB暴露

```
2017-01-24 13:15:59.118 ERROR [$_NIOREACTOR-21-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.nio.channels.ClosedChannelException        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[?:1.7.0_121]        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[?:1.7.0_121]        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444) ~[Mycat-server-1.6-RELEASE.jar:?]        at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
2017-01-24 13:15:59.773 ERROR [$_NIOREACTOR-22-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.nio.channels.ClosedChannelException
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[?:1.7.0_121]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[?:1.7.0_121]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]

```

**根据群内兄弟提示可能是SLB的心跳包导致. 希望能得到确认**

**Comment by songwie** [comment]
https://github.com/MyCATApache/Mycat-Server/issues/1345
参考这个问题

**Comment by xiaosilao** [comment]
最终怎么解决的,遇到同样的问题

2017-08-30 10:27:31.815 ERROR [$_NIOREACTOR-22-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[?:1.7.0_80]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[?:1.7.0_80]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
