### ISSUE TITLE
插入报错

### ISSUE THREAD

**Issue by learninton** [MyCATApache/Mycat-Server#1364]
jvm 1    | 2017-02-07 17:02:04,207 [INFO ][$_NIOREACTOR-5-RW] ServerConnection [id=9, schema=telecom_wx, host=127.0.0.1, user=mohoo,txIsolation=3, autocommit=true, schema=telecom_wx]'mohoo' login success  (io.mycat.net.handler.FrontendAuthenticator:FrontendAuthenticator.java:194)
jvm 1    | 2017-02-07 17:02:04,213 [WARN ][$_NIOREACTOR-5-RW] ServerConnection [id=9, schema=telecom_wx, host=127.0.0.1, user=mohoo,txIsolation=3, autocommit=false, schema=telecom_wx]INSERT INTO `dx_weixin_bind` (`itemid`,`openid`,`deviceno`,`bpnum`,`crmid`,`scene`,`channel`,`createtime`,`untime`,`status`,`bindtime`,`from`) VALUES ('B8F05EB0-D870-E149-748E-EA36ABDBA6A0','oKXUCj3BUDeqfvKDCAFuWmg7BZLE','17090025290','00000','10','0','0','1486458124','1486458124','100','2017-02-07 17:02:04','0') err:java.lang.IllegalArgumentException: columnValue:B8F05EB0-D870-E149-748E-EA36ABDBA6A0 Please eliminate any quote and non number within it. java.lang.IllegalArgumentException: columnValue:B8F05EB0-D870-E149-748E-EA36ABDBA6A0 Please eliminate any quote and non number within it.
jvm 1    | 	at io.mycat.route.function.PartitionByLong.calculate(PartitionByLong.java:64)
jvm 1    | 	at io.mycat.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:1278)
jvm 1    | 	at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1075)
jvm 1    | 	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:947)
jvm 1    | 	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:109)
jvm 1    | 	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
jvm 1    | 	at io.mycat.route.RouteService.route(RouteService.java:133)
jvm 1    | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273)
jvm 1    | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
jvm 1    | 	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136)
jvm 1    | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
jvm 1    | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
jvm 1    | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
jvm 1    | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
jvm 1    | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
jvm 1    | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
jvm 1    | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
jvm 1    | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
jvm 1    | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
jvm 1    | 	at java.lang.Thread.run(Thread.java:745)
jvm 1    | Caused by: java.lang.NumberFormatException: For input string: "B8F05EB0-D870-E149-748E-EA36ABDBA6A0"
jvm 1    | 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
jvm 1    | 	at java.lang.Long.parseLong(Long.java:589)
jvm 1    | 	at java.lang.Long.parseLong(Long.java:631)
jvm 1    | 	at io.mycat.route.function.PartitionByLong.calculate(PartitionByLong.java:61)
jvm 1    | 	... 19 more
jvm 1    |  (io.mycat.server.ServerConnection:ServerConnection.java:281)

**Comment by learninton** [comment]
mysql 数据库 中表 类型为varchar 40,

**Comment by learninton** [comment]
分片方式：PartitionByLong

**Comment by ZzzCrazyPig** [comment]
PartitionByLong 分片字段类型应该为数字类型吧，你上面的分片字段用了非数字类型，肯定会抛异常

**Comment by learninton** [comment]
好的明白了，谢谢你。

**Comment by learninton** [comment]
固定分片 hash 算法

本条规则类似于十进制的求模运算，区别在于是二进制的操作,是取 id 的二进制低 10 位， 即 id 二进制 &1111111111。

此算法的优点在于如果按照 10 进制取模运算，在连续插入 1-10 时候 1-10 会被分到 1-10 个分片，增 大了插入的事务控制难度，而此算法根据二进制则可能会分到连续的分片， 减少插入事务事务控制难度。

**Comment by learninton** [comment]
这个事根据二进制进行分片啊，怎么是数字呢？
