### ISSUE TITLE
1.6  表关联和配置问题

### ISSUE THREAD

**Issue by wengad82** [MyCATApache/Mycat-Server#1371]
INFO   | jvm 1    | 2017/02/10 17:18:06 | 2017-02-10 17:18:06,519 [WARN ][$_NIOREACTOR-0-RW] ServerConnection [id=155, schema=CRDB, host=115.172.170.94, user=ftar,txIsolation=3, autocommit=true, schema=CRDB]select *
INFO   | jvm 1    | 2017/02/10 17:18:06 |   from t_func_ctr t1
INFO   | jvm 1    | 2017/02/10 17:18:06 |   left join t_app_func t2
INFO   | jvm 1    | 2017/02/10 17:18:06 |     on t1.func_code = t2.func_code
INFO   | jvm 1    | 2017/02/10 17:18:06 |  LIMIT 0, 1000 err:java.sql.SQLNonTransientException: can't find table define in schema T_FUNC_CTR schema:CRDB java.sql.SQLNonTransientException: can't find table define in schema T_FUNC_CTR schema:CRDB
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:970)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:412)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.route.RouteService.route(RouteService.java:133)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273)
INFO   | jvm 1    | 2017/02/10 17:18:06 | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)

**Comment by wengad82** [comment]
t_func_ctr 
t_app_func 

	<schema name="CMDB" checkSQLschema="false" sqlMaxLimit="10000" dataNode="cm_dn1">
		<table name="absc_t_app_func" dataNode="cm_dn1" />
配置是以上那样的，其中t_func_ctr没配置，导致两表关联后出错。
需要再配置上：
		<table name="absc_t_func_ctr" dataNode="cm_dn1"   />

**Comment by jiangxingang** [comment]
是啊，也遇到这问题，全局表联普通表时。需要这个配置，但有时又不用。很怪！
