### ISSUE TITLE
Mycat长时间运行后，出现假死

### ISSUE THREAD

**Issue by fuzzywy** [MyCATApache/Mycat-Server#1373]
Mycat长时间运行后出现假死，可以看到Linux进程，但是控制台无法连接
日志里频繁出现
INFO   | jvm 1    | 2017/02/12 19:22:14 | 2017-02-12 19:22:14,432 [ERROR][$_NIOREACTOR-2-RW] register err java.lang.NullPointerException
INFO   | jvm 1    | 2017/02/12 19:22:14 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2017/02/12 19:22:18 | 2017-02-12 19:22:18,251 [ERROR][$_NIOREACTOR-3-RW] register err java.lang.NullPointerException
INFO   | jvm 1    | 2017/02/12 19:22:18 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2017/02/12 19:22:22 | 2017-02-12 19:22:22,395 [ERROR][$_NIOREACTOR-4-RW] register err java.lang.NullPointerException
INFO   | jvm 1    | 2017/02/12 19:22:22 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2017/02/12 19:22:24 | 2017-02-12 19:22:24,473 [ERROR][$_NIOREACTOR-5-RW] register err java.lang.NullPointerException
INFO   | jvm 1    | 2017/02/12 19:22:24 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 

控制台无法连接
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
============================================
系统通过keepAlived实现网络层的LB。
出问题的节点是100.93.253.205，keepAlived认为出问题的节点仍然存活。
一天的流量大概在100G左右。

![capture](https://cloud.githubusercontent.com/assets/8663680/22869127/948d6f30-f1d7-11e6-8d19-8d28dc912c59.PNG)

心跳检测的TCP包同样会导致Mycat出现regist error

**Comment by huangyiminghappy** [comment]
什么版本？

**Comment by fuzzywy** [comment]
版本 1.6-RELEASE

**Comment by magicdoom** [comment]
1.6.5 fix le

2017-02-14 16:47 GMT+08:00 wangyang <notifications@github.com>:

**Comment by fuzzywy** [comment]
谢谢，close了

**Comment by k19421** [comment]
要解决这个问题大概要修改哪里的代码？
我们现在测试的时候也遇到类似的问题
并发超过600就报这个错

**Comment by pavelxq** [comment]
怎么解决的，求教

**Comment by Haitianisgood** [comment]
我的方案使用“权威指南”方案：
haproxy+Mycat+Mysql

环境：
```
java 1.8
haproxy 1.7.9和1.8.12都试过
Mycat 1.6
Mysql 5.7
```
每天都出现
```
2018-07-27 12:09:44.280 ERROR [$_NIOREACTOR-3-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.lang.NullPointerException
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:297) ~[?:1.8.0_172]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.BackendAIOConnection.register(BackendAIOConnection.java:47) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
haproxy配置：
```
listen allmycat_service
        bind 172.16.0.10:8096
        mode tcp
        option tcplog
        option httpchk OPTIONS * HTTP/1.1\r\nHost:\ www
        balance roundrobin
        server mycat_10 172.16.0.10:8066 check port 48700 inter 5s rise 2 fall 3
        server mycat_11 172.16.0.11:8066 check port 48700 inter 5s rise 2 fall 3
        timeout server 20000
```
我修改过mycat_status脚本，不是使用mycat命令去检测mycat状态，而是看mycat进程，但这方法依旧解决不了。从此分析下来，这个并不是检测心跳导致的。并且经过一段时间观察，发现通过haproxy请求数mysql频率越大，mycat假死的频率也会增高。

我尝试过的方案：
1. 应用直接连接Mycat，是没有问题的，不会报此错误
2. 只要通过haproxy balance ，肯定就有问题了，问题可能就会出在balance执行过程中
3. 看到另外一个issuse：https://github.com/MyCATApache/Mycat-Server/issues/1616，我在尝试使用Mycat 1.6.5方案，前面依旧使用haproxy方案。目前还在观察中。。。

**Comment by Haitianisgood** [comment]
我的方案使用“权威指南”方案：
haproxy+Mycat+Mysql

环境：
```
java 1.8
haproxy 1.7.9和1.8.12都试过
Mycat 1.6
Mysql 5.7
```
每天都出现
```
2018-07-27 12:09:44.280 ERROR [$_NIOREACTOR-3-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.lang.NullPointerException
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:297) ~[?:1.8.0_172]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.BackendAIOConnection.register(BackendAIOConnection.java:47) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
haproxy配置：
```
listen allmycat_service
        bind 172.16.0.10:8096
        mode tcp
        option tcplog
        option httpchk OPTIONS * HTTP/1.1\r\nHost:\ www
        balance roundrobin
        server mycat_10 172.16.0.10:8066 check port 48700 inter 5s rise 2 fall 3
        server mycat_11 172.16.0.11:8066 check port 48700 inter 5s rise 2 fall 3
        server mycat_12 172.16.0.12:8066 check port 48700 inter 5s rise 2 fall 3
        timeout server 20000
```
我修改过mycat_status脚本，不是使用mycat命令去检测mycat状态，而是看mycat进程，但这方法依旧解决不了。从此分析下来，这个并不是检测心跳导致的。并且经过一段时间观察，发现通过haproxy请求数mysql频率越大，mycat假死的频率也会增高。

我尝试过的方案：
1. 应用直接连接Mycat，是没有问题的，不会报此错误
2. 只要通过haproxy balance ，肯定就有问题了，问题可能就会出在balance执行过程中
3. 看到另外一个issuse：https://github.com/MyCATApache/Mycat-Server/issues/1616，我在尝试使用Mycat 1.6.5方案，前面依旧使用haproxy方案。目前还在观察中。。。
