### ISSUE TITLE
mycat1.5主备自动切换失败

### ISSUE THREAD

**Issue by lic721** [MyCATApache/Mycat-Server#1381]
我用的是mycat1.5, 数据库是sqlserver, 双主一从. 
一个主hostM7的服务器关掉后, 没有自动切换到另一个主hostM7_1.
**schema的配置如下:**
\<dataHost name="localhost7" maxCon="2000" minCon="10" balance="3"
		writeType="0" dbType="sqlserver" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
		\<heartbeat>select 1\</heartbeat>
		\
		\<writeHost host="hostM7" url="jdbc:sqlserver://192.168.253.245:XX" user="XX" password="XX">
			\
			\<readHost host="hostS7" url="jdbc:sqlserver://XXX..." user="XX" password="XX"/>
		\</writeHost>
		\<writeHost host="hostM7_1" url="jdbc:sqlserver://XX..." user="XX" password="XX">
		\</writeHost>
	\</dataHost>

**mycat.log如下:**
02/20 17:52:47.390  ERROR [Timer0] (JDBCHeartbeat.java:112) -JDBCHeartBeat error

com.microsoft.sqlserver.jdbc.SQLServerException: 通过端口 1433 连接到主机 192.168.253.245 的 TCP/IP 连接失败。错误:“Connection refused: connect。请验证连接属性。确保 SQL Server 的实例正在主机上运行，且在此端口接受 TCP/IP 连接，还要确保防火墙没有阻止到此端口的 TCP 连接。”。

	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)

	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:241)

	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2243)

	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:491)

	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1309)

	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:991)

	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:827)

	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1012)

	at java.sql.DriverManager.getConnection(DriverManager.java:571)

	at java.sql.DriverManager.getConnection(DriverManager.java:215)

	at org.opencloudb.jdbc.JDBCDatasource.getConnection(JDBCDatasource.java:80)

	at org.opencloudb.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:98)

	at org.opencloudb.backend.PhysicalDatasource.doHeartbeat(PhysicalDatasource.java:312)

	at org.opencloudb.backend.PhysicalDBPool.doHeartbeat(PhysicalDBPool.java:336)

	at org.opencloudb.MycatServer$6$1.run(MycatServer.java:529)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:745)

9066管理端口进行查看, hostM7_1从来没用过, 按理来说会有操作日志表的插入的:
mysql> show @@datasource;
+-----------+----------+-----------+-----------------+------+-----+--------+------+------+---------+
| DATANODE  | NAME     | TYPE      | HOST            | PORT | W/R | ACTIVE | IDLE | SIZE | EXECUTE |
+-----------+----------+-----------+-----------------+------+-----+--------+------+------+---------+
| dataNode7 | hostM7   | sqlserver | 192.168.253.245 | 1433 | W   |      0 |   10 | 2000 |      33 |
| dataNode7 | hostM7_1 | sqlserver | XXXXXXXXX  | 1433 | W   |      0 |    0 | 2000 |       0 |
| dataNode7 | hostS7   | sqlserver | XXXXXXXXX    | 1433 | R   |      0 |    3 | 2000 |       3 |
+-----------+----------+-----------+-----------------+------+-----+--------+------+------+---------+

**Comment by lic721** [comment]
群里面询问了, mycat1.5不支持sqlserver的主备自动切换
