### ISSUE TITLE
group by date_format(inputdate, '%y-%m-%d') 报错

### ISSUE THREAD

**Issue by sohudo** [MyCATApache/Mycat-Server#139]
默认的SQL解析器和druidparser都报错
select date_format(inputdate, '%y-%m-%d') as inputdate, sum(requestid) as requestid, sum(factprice) as factprice from biaoben group by date_format(inputdate, '%y-%m-%d')
这个语句执行报错
02-05 17:23:32.343   WARN [BusinessExecutor9] (MultiNodeQueryHandler.java:401) -caught exception 
java.lang.NullPointerException
	at org.opencloudb.mpp.DataMergeService.toColumnIndex(DataMergeService.java:304)
	at org.opencloudb.mpp.DataMergeService.onRowMetaData(DataMergeService.java:148)

**Comment by sohudo** [comment]
mysql> select date_format(inputdate, '%y-%m-%d') as inputdate, sum(requestid) as requestid, sum(factprice) as factprice from biaoben group by inputdate order by inputdate;
Empty set (0.00 sec)
再加个排序就变成空记录了

**Comment by sohudo** [comment]
分组，排序都解决了
