### ISSUE TITLE
使用mysql C api中的预处理相关函数mysql_stmt_execute时mycat报错，连接丢失。

### ISSUE THREAD

**Issue by wanghao2445** [MyCATApache/Mycat-Server#1402]
mycat报错信息如下：
WARN [$_NIOREACTOR-0-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
java.lang.ArrayIndexOutOfBoundsException: 14
        at io.mycat.backend.mysql.MySQLMessage.read(MySQLMessage.java:79) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.mysql.ExecutePacket.read(ExecutePacket.java:117) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:128) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:386) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:99) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by ZzzCrazyPig** [comment]
语句的sql和测试数据能给出来？

**Comment by wanghao2445** [comment]
最近在验证公司技术平台对接mycat的可行性的过程中发现此问题，我们在与mysql数据库对接的API中运用了大量的mysql的预处理相关的API，直连mysql的时候是没有问题的。
sql语句就是简单的select，update语句，测试表也是用的mycat的默认全局表company
例如：select * from company where id=1; update company  set name = 'ssss' where id = 1; 这种sql~
目前发现是只要执行到mysql_stmt_execute()函数处，就会出现我之前贴出的错误信息，紧接着就断开连接，烦请大神指点一二。。。

**Comment by ZzzCrazyPig** [comment]
mycat是哪里下的 版本多少？ 1.6-RELEASE? 可以考虑换一下最新的1.6.5?

**Comment by wanghao2445** [comment]
升级到1.65版本，已经没有之前的问题了，多谢！
