### ISSUE TITLE
charsetName is null

### ISSUE THREAD

**Issue by jokxia** [MyCATApache/Mycat-Server#1403]
2017-03-17 10:40:18.372 ERROR [BusinessExecutor3] (io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:343)) - sql execute error, charsetName
java.lang.NullPointerException: charsetName
        at java.lang.String.<init>(String.java:424) ~[?:1.8.0_77]
        at io.mycat.util.StringUtil.decode(StringUtil.java:95) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.util.StringUtil.decode(StringUtil.java:89) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:445) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.backend.jdbc.JDBCConnection.ouputResultSet(JDBCConnection.java:678) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:317) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.backend.jdbc.JDBCConnection.access$000(JDBCConnection.java:32) ~[Mycat-server-1.6.5-BETA.jar:?]
        at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:769) ~[Mycat-server-1.6.5-BETA.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]

**Comment by jokxia** [comment]
不太明白，charsetName，来自哪里，但是handle里面还是要判断是否为空，或者添加默认charSet
