### ISSUE TITLE
mycat 1.6批量提交入库大于1000条报错

### ISSUE THREAD

**Issue by lchh0917** [MyCATApache/Mycat-Server#1425]
版主你好！
我这里目前有客户端采集应用程序连接mycat批量提交入库，后端数据库版本mysql 5.6.29，通过jdbc连接串jdbc:mysql://ip:port/db?rewriteBatchedStatements=true开启批量提交开关，目前测试发现批量值设为500时能正常入库，改为1000时则直接报错，详细日志如下：
**500批量值入库日志：**
2017-03-31 13:43:29,050 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+501】
2017-03-31 13:43:29,097 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+501】
2017-03-31 13:43:30,891 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:43:30,891 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+501】
2017-03-31 13:43:30,922 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+501】
2017-03-31 13:43:43,433 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【过车记录LDcp_N入库，本次读取数据数量为：501】
2017-03-31 13:43:51,951 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:43:51,966 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+501】
2017-03-31 13:43:51,998 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+501】
2017-03-31 13:43:54,010 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:43:54,010 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【过车记录LDcp_N入库，本次成功入库数据数量为：501】
2017-03-31 13:44:09,922 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:44:09,922 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+501】
2017-03-31 13:44:09,953 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+501】
2017-03-31 13:44:19,064 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【过车记录LDcp_N入库，本次读取数据数量为：501】
2017-03-31 13:44:21,154 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:44:21,154 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+501】
2017-03-31 13:44:21,185 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+501】
2017-03-31 13:44:21,606 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行501条
2017-03-31 13:44:21,606 [Thread-1] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【过车记录LDcp_N入库，本次成功入库数据数量为：501】

**1000批量值入库情况：**
2017-03-31 13:35:50,175 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 批量执行1001条
2017-03-31 13:35:50,175 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG成功数量为：+1001】
2017-03-31 13:35:50,238 [Thread-2] INFO  com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG提取数量为：+1001】
2017-03-31 13:35:50,674 [Thread-2] ERROR com.alibaba.druid.pool.DruidDataSource - discard connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:461)
	at com.mysql.jdbc.PreparedStatement.clearBatch(PreparedStatement.java:1143)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1471)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2596)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2474)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559)
	at com.ls.comapi.utils.database.dbpool.DataSourceDCDS.updateBatch(DataSourceDCDS.java:98)
	at com.ls.dataIOT.dcp.dm.quartz.timing.DataLog.execute(DataLog.java:171)
	at com.ls.dataIOT.dcp.dm.quartz.timing.WriteVehicle$2.run(WriteVehicle.java:281)
	at java.lang.Thread.run(Unknown Source)
2017-03-31 13:35:50,674 [Thread-2] ERROR com.ls.comapi.utils.base.tools.LogUtils - 【推送日志LDcp_LOG入库DCDS报错，数据写入本地】
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:461)
	at com.mysql.jdbc.PreparedStatement.clearBatch(PreparedStatement.java:1143)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1471)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2596)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2474)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559)
	at com.ls.comapi.utils.database.dbpool.DataSourceDCDS.updateBatch(DataSourceDCDS.java:98)
	at com.ls.dataIOT.dcp.dm.quartz.timing.DataLog.execute(DataLog.java:171)
	at com.ls.dataIOT.dcp.dm.quartz.timing.WriteVehicle$2.run(WriteVehicle.java:281)
	at java.lang.Thread.run(Unknown Source)

**Comment by lchh0917** [comment]
up!

**Comment by ZzzCrazyPig** [comment]
mycat后台报错日志呢？

**Comment by wrysmile** [comment]
请问现在还有这个问题吗，我现在需要批量插入60000条数据
