### ISSUE TITLE
mysql图形客户端连接mycat(1.6-release),报错Packet size over the limit.

### ISSUE THREAD

**Issue by nimei1248** [MyCATApache/Mycat-Server#1431]
**版主您好！**

最近使用mysql图形客户端连接mycat，一直报错Packet size over the limit，下面是我测试的2款工具：
**1.navicat 11.0.17 (64-bit) - preminum:**
![mycat1](https://cloud.githubusercontent.com/assets/23753020/24824620/b5a00500-1bdc-11e7-815e-5c4d990e7888.jpg)
直接报错，查询不出结果

**2.SQLyog 9.6.3 and 12.08(64 bit)**
需要点击确定2次错误提示，但可以查询出结果，每条语句查询都要点击2次:
第一次：
![mycat2](https://cloud.githubusercontent.com/assets/23753020/24824653/5a877ea4-1bdd-11e7-813e-cf9f992e072b.jpg)

第二次：
![mycat3](https://cloud.githubusercontent.com/assets/23753020/24824661/972aba4c-1bdd-11e7-89f5-45f8baffab0a.jpg)

第二次点击确定后可以看到结果：
![mycat4](https://cloud.githubusercontent.com/assets/23753020/24824671/c2b41866-1bdd-11e7-8b5c-f030fa3fa1ec.jpg)

根据错误提示show status;语句，直接在mycat服务器上使用mysql命令行客户端：
mysql>show status;
mysql>
没有任何返回信息

mycat 报错日志如下：
2017-04-08 09:27:01.151 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.net.FrontendConnection.query(FrontendConnection.java:288)) - ServerConnection [id=3, schema=ucenter, host=192.168.1.20, user=test,txIsolation=3, autocommit=true, schema=ucenter] show status
2017-04-08 09:27:01.151 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:57)) - ServerConnection [id=3, schema=ucenter, host=192.168.1.20, user=test,txIsolation=3, autocommit=true, schema=ucenter]show status
2017-04-08 09:27:01.210 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:110)) - ServerConnection [id=3, schema=ucenter, host=192.168.1.20, user=test,txIsolation=3, autocommit=true, schema=ucenter]show status, route={
   1 -> dn3{show status}
} rrs
2017-04-08 09:27:01.239 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:166)) - rrs.getRunOnSlave() null
2017-04-08 09:27:01.239 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:168)) - node.getRunOnSlave() null
2017-04-08 09:27:01.246 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:177)) - node.getRunOnSlave() null
2017-04-08 09:27:01.246 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:179)) - node.getRunOnSlave() null
2017-04-08 09:27:01.259 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:96)) - rrs.getRunOnSlave() null
2017-04-08 09:27:01.260 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:127)) - rrs.getRunOnSlave() null
2017-04-08 09:27:01.274 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.datasource.PhysicalDBPool.getRWBanlanceCon(PhysicalDBPool.java:456)) - select read source host1_M1 for dataHost:host1_inst1
2017-04-08 09:27:01.294 DEBUG [$_NIOREACTOR-11-RW] (io.mycat.backend.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:448)) - con need syn ,total syn cmd 1 commands schema change:true con:MySQLConnection [id=28, lastTime=1491614821289, user=mycat_user, schema=user_a03, old shema=user_a01, borrowed=true, fromSlaveDB=false, threadId=64, charset=utf8, txIsolation=3, autocommit=true, attachment=dn3{show status}, respHandler=SingleNodeHandler [node=dn3{show status}, packetId=0], host=192.168.1.10, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2017-04-08 09:27:02.560  WARN [$_NIOREACTOR-29-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
**java.lang.IllegalArgumentException: Packet size over the limit.**
        at io.mycat.net.AbstractConnection.ensureFreeSpaceOfReadBuffer(AbstractConnection.java:381) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:366) ~**[Mycat-server-1.6-RELEASE.jar:?]**
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
2017-04-08 09:27:02.572  INFO [$_NIOREACTOR-29-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:508)) - close connection,**reason:program err:java.lang.IllegalArgumentException: Packet size over the limit**. ,MySQLConnection [id=28, lastTime=1491614821295, user=mycat_user, schema=user_a03, old shema=user_a03, borrowed=true, fromSlaveDB=false, threadId=64, charset=utf8, txIsolation=3, autocommit=true, attachment=dn3{show status}, respHandler=SingleNodeHandler [node=dn3{show status}, packetId=0], host=192.168.1.10, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@7d9b2ae1, writeQueue=0, modifiedSQLExecuted=false]
**2017-04-08 09:27:02.582  WARN [$_NIOREACTOR-29-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.backConnectionErr(SingleNodeHandler.java:249)) - execute  sql err : errno:1023 program err:java.lang.IllegalArgumentException: Packet size over the limit. con:**MySQLConnection [id=28, lastTime=1491614821295, user=mycat_user, schema=user_a03, old shema=user_a03, borrowed=true, fromSlaveDB=false, threadId=64, charset=utf8, txIsolation=3, autocommit=true, attachment=dn3{show status}, respHandler=SingleNodeHandler [node=dn3{show status}, packetId=1], host=192.168.1.10, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@7d9b2ae1, writeQueue=0, modifiedSQLExecuted=false] frontend host:192.168.1.20/59870/test

**观察在mysql GUI上面执行sql语句，查看mycat错误跟上面信息是一致的**

**后面尝试：**
1.增大mycat配置文件server.xml参数并重启mycat，错误依旧如此：
指定 Mysql 协议可以携带的数据最大长度  默认 16M
property name="maxPacketSize">64</property

2.根据mycat官方提供参考方法:
![mycat5](https://cloud.githubusercontent.com/assets/23753020/24824851/85cf48c2-1be1-11e7-95d7-6e6c894b6d60.jpg)
调整mycat后端mysql(percona 5.7.17-11 64-bit)配置文件my.cnf参数并重启mysql，错误依旧:
max_allowed_packet = 64M

mycat-1.6-release版本的lib目录下只有一个跟mysql相关的jar包：
mysql-binlog-connector-java-0.4.1.jar

尝试将1.6.5版本中的jar包复制到1.6-release的lib目录下并重启mycat，报错依旧：
mysql-binlog-connector-java-0.6.0.jar
mysql-connector-java-5.1.35.jar

3.尝试在网上搜集一些方法：
![mycat6](https://cloud.githubusercontent.com/assets/23753020/24824957/6f5327b0-1be3-11e7-9226-056f01adbf81.jpg)

![mycat7](https://cloud.githubusercontent.com/assets/23753020/24824958/774bd368-1be3-11e7-819e-f448bc789b5b.jpg)

![mycat8](https://cloud.githubusercontent.com/assets/23753020/24824962/7b4b7dce-1be3-11e7-99cb-95bf82d4b0ac.jpg)

尝试将此参数改成10M/15M(16M以下)并重启mycat，问题依旧：
property name="maxPacketSize">64</property

4.测试1.6.5版本，问题依然没有解决

5.直接在mycat后端mysql上执行show status;是正常的
mysql>show status \G
*************************** 1. row ***************************
Variable_name: Aborted_clients
        Value: 32
*************************** 2. row ***************************
Variable_name: Aborted_connects
        Value: 28
...............................................................................

我的环境信息：
1.OS：
cat /etc/redhat-release 
CentOS release 6.8 (Final)

uname -rm
2.6.32-642.4.2.el6.x86_64 x86_64

2.mycat
Mycat-server-1.6-RELEASE

3.mysql(percona-5.7.17-11)
mysql>select version()\G
*************************** 1. row ***************************
version(): 5.7.17-11-log
1 row in set (0.00 sec)

4.mysql GUI
1).navicat 11.0.17 (64-bit) - preminum
2).SQLyog 9.6.3 and 12.08(64 bit)

**Comment by nimei1248** [comment]
**连接后端mysql使用的驱动为native：**
<dataHost name="host1_inst1" maxCon="20" minCon="5" balance="1" writeType="0"
|   |   | dbType="mysql" dbDriver="native" switchType="-1" slaveThreshold="100">

**Comment by ZzzCrazyPig** [comment]
你好，`maxPacketSize` 这个参数是按字节来算的，16M 应该配置 `16 * 1024 * 1024` 计算后的结果，看了你想配置64M，你的配置应该是错误的

**Comment by ZzzCrazyPig** [comment]
我的建议是，mycat端的server.xml的`maxPacketSize`参数按默认即可，然后配置后端mysql数据库的`max_allow_packet`跟mycat保持一致，即16M

**Comment by ZzzCrazyPig** [comment]
根据我的理解，只要mysql的`max_allow_packet`不要大于mycat端的`maxPacketSize`即可

**Comment by nimei1248** [comment]
@ZzzCrazyPig 
感谢你的解答

今天下午根据你提供的方法，测试如下：
**[第1次:  mycat = mysql]**
mycat:
property name="maxPacketSize">16</property

mysql:
max_allowed_packet = 16M

mysql图形客户端navicat、sqlyog报错依旧：
java.lang.IllegalArgumentException: Packet size over the limit.

**[第2次: mycat > mysql]**
mycat:
property name="maxPacketSize">16</property

mysql:
max_allowed_packet = 14M

mysql图形客户端navicat、sqlyog报错依旧：
java.lang.IllegalArgumentException: Packet size over the limit.

**[第3次: 调整mycat的参数小于16M,mycat > mysql]**
根据下图说明，调整mycat的参数小于16M
![image](https://cloud.githubusercontent.com/assets/23753020/24855627/3442be14-1db0-11e7-8b4b-c49620796e91.png)

mycat:
property name="maxPacketSize">15</property

mysql:
max_allowed_packet = 14M

mysql图形客户端navicat、sqlyog报错依旧：
java.lang.IllegalArgumentException: Packet size over the limit.

**[第4次 注释掉mycat参数,保持其默认的16M,mycat > mysql]**
mycat:
!--property name="maxPacketSize">16</property----
![mycat9](https://cloud.githubusercontent.com/assets/23753020/24855985/374fe2ca-1db1-11e7-86f2-87efb252887b.jpg)

mysql:
max_allowed_packet = 14M

mysql图形客户端navicat，可以正常查询了：
![mycat10](https://cloud.githubusercontent.com/assets/23753020/24856351/733561ce-1db2-11e7-9337-b48aa9fe9573.jpg)

可是，mycat log中报错如下：
2017-04-10 17:49:26.170  WARN [$_NIOREACTOR-15-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:281)) - ServerConnection [id=80, schema=fox, host=10.5.9.22, user=test,txIsolation=3, autocommit=true, schema=fox]SELECT * FROM `fox_a01`.`t_announce` LIMIT 0 **err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `fox_a01`.`t_announce` LIMIT 0**
**java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `fox_a01`.`t_announce` LIMIT 0**
        at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:437) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.RouteService.route(RouteService.java:133) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:222) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]



使用mysql图形客户端SQLyog，无法查询到结果，报错如下：
![mycat11](https://cloud.githubusercontent.com/assets/23753020/24856581/3cda11a0-1db3-11e7-9481-c5448b63bb18.jpg)

2017-04-10 17:59:41.378  WARN [$_NIOREACTOR-9-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - **caught err:
java.nio.BufferOverflowException**
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363) ~[?:1.8.0_25]
        at java.nio.ByteBuffer.put(ByteBuffer.java:859) ~[?:1.8.0_25]
        at io.mycat.util.CompressUtil.compressMysqlPacket(CompressUtil.java:107) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.util.CompressUtil.compressMysqlPacket(CompressUtil.java:62) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.writeNotSend(AbstractConnection.java:424) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.writeToBuffer(AbstractConnection.java:482) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:440) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:204) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:135) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:259) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**[第5次: 保持mycat参数默认，mycat < mysql]**
mycat:
!--property name="maxPacketSize">16</property----
![mycat9](https://cloud.githubusercontent.com/assets/23753020/24855985/374fe2ca-1db1-11e7-86f2-87efb252887b.jpg)

mysql:
max_allowed_packet = 32M

结果同第4次测试

[总结]
如果将mycat参数property name="maxPacketSize">16</property显示开启，则mysql gui navicat不能正常显示结果；保持默认情况，mysql gui navicat可以正常查询显示结果，但mycat日志有报错：
java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `fox_a01`.`t_announce` LIMIT 0

mysql gui SQLyog不能正常查询显示数据，mycat日志报错：
caught err:java.nio.BufferOverflowException

**Comment by ZzzCrazyPig** [comment]
首先，你还是没理解我的意思，`maxPacketSize`是配置字节的，你总是配置16干嘛，16个字节肯定太小啊，要配置`16 * 1024 * 1024`的计算结果。如果这还不懂，那当我没说过。建议你看权威指南再测试吧，第二个错误还是因为配置问题

**Comment by nimei2018** [comment]
抱歉，昨天我一直以为单位是M
今天我再验证下，谢谢

**Comment by nimei1248** [comment]
@ZzzCrazyPig 

今天上午我进行了测试，将mycat的参数：
property name="maxPacketSize">16777216</property 改成字节navicat就可以工作了,非常感谢！
之前一直以为单位是M

虽然navicat执行不会报错，但mycat后台日志，报错如下：
java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `user_a01`.`t2` LIMIT 0
也就是上面说的第2个问题

这个问题目前测试结果是：
**当使用navicat执行的select语句中包含主键字段，就会报错如上；mysql命令行客户端不会**

**下面是测试过程：**
**mysql命令行客户端：**
mysql> desc t2\G
*************************** 1. row ***************************
  Field: id
   Type: int(11)
   Null: NO
    Key: PRI
Default: NULL
  Extra: 
*************************** 2. row ***************************
  Field: name
   Type: varchar(4)
   Null: NO
    Key: 
Default: NULL
  Extra: 
2 rows in set (0.02 sec)

mysql> select id,name from t2\G
*************************** 1. row ***************************
  id: 1
name: a
*************************** 2. row ***************************
  id: 2
name: b
*************************** 3. row ***************************
  id: 3
name: c
3 rows in set (0.00 sec)

**mycat日志：**
2017-04-11 11:46:43.689 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.net.FrontendConnection.query(FrontendConnection.java:288)) - ServerConnection [id=14, schema=ucenter, host=10.66.72.174, user=test,txIsolation=3, autocommit=true, schema=ucenter] select id,name from t2
2017-04-11 11:46:43.689 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:57)) - ServerConnection [id=14, schema=ucenter, host=10.66.72.174, user=test,txIsolation=3, autocommit=true, schema=ucenter]select id,name from t2
2017-04-11 11:46:43.689 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.cache.impl.EnchachePool.get(EnchachePool.java:71)) - SQLRouteCache hit cache ,key:ucenterselect id,name from t2
2017-04-11 11:46:43.689 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:110)) - ServerConnection [id=14, schema=ucenter, host=10.66.72.174, user=test,txIsolation=3, autocommit=true, schema=ucenter]s**elect id,name from t2, route={
   1 -> dn1{SELECT id, name
FROM t2
LIMIT 10000}
} rrs** 
2017-04-11 11:46:43.689 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:166)) - rrs.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:168)) - node.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:177)) - node.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:177)) - node.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:179)) - node.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:96)) - rrs.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:96)) - rrs.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:127)) - rrs.getRunOnSlave() null
2017-04-11 11:46:43.690 DEBUG [$_NIOREACTOR-5-RW] (io.mycat.backend.datasource.PhysicalDBPool.getRWBanlanceCon(PhysicalDBPool.java:456)) - select read source host1_M1 for dataHost:host1_inst1
FROM t2
LIMIT 10000}, respHandler=SingleNodeHandler [node=dn1{SELECT id, name
FROM t2
LIMIT 10000}, packetId=7], host=10.66.72.176, port=4311, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
=false]



**mysql gui navicat测试：
1.全部字段，包含主键**
![mycat12](https://cloud.githubusercontent.com/assets/23753020/24892142/49edaace-1e48-11e7-83a8-a02923345bc1.jpg)

**mycat日志：**
2017-04-11 11:47:36.596 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:57)) - ServerConnection [id=13, schema=ucenter, host=10.5.9.22, user=test,txIsolation=3, autocommit=true, schema=ucenter]SELECT * FROM `user_a01`.`t2` LIMIT 0
2017-04-11 11:47:36.597 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.cache.impl.EnchachePool.get(EnchachePool.java:77)) - SQLRouteCache  miss cache ,key:ucenterSELECT * FROM `user_a01`.`t2` LIMIT 0
2017-04-11 11:47:36.597  WARN [$_NIOREACTOR-3-RW] **(io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:436)) -  find no Route:SELECT * FROM `user_a01`.`t2` LIMIT 0**
2017-04-11 11:47:36.597  WARN [$_NIOREACTOR-3-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:281)) - ServerConnection [id=13, schema=ucenter, host=10.5.9.22, user=test,txIsolation=3, autocommit=true, schema=ucenter]SELECT * FROM `user_a01`.`t2` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `user_a01`.`t2` LIMIT 0
**java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `user_a01`.`t2` LIMIT 0**
        at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:437) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.route.RouteService.route(RouteService.java:133) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:222) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**2.不包含主键字段**
![mycat13](https://cloud.githubusercontent.com/assets/23753020/24892227/f3ee9420-1e48-11e7-84c9-35cec20f4b1d.jpg)

**mycat日志：**
2017-04-11 11:50:17.266 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.cache.impl.EnchachePool.get(EnchachePool.java:77)) - SQLRouteCache  miss cache ,key:ucenterselect name from t2
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.cache.impl.EnchachePool.putIfAbsent(EnchachePool.java:60)) - SQLRouteCache add cache ,key:ucenterselect name from t2 value:**select name from t2, route={
   1 -> dn1{SELECT name
FROM t2
LIMIT 10000}
}**
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:110)) - ServerConnection [id=13, schema=ucenter, host=10.5.9.22, user=test,txIsolation=3, autocommit=true, schema=ucenter]select name from t2, route={
   1 -> dn1{SELECT name
FROM t2
LIMIT 10000}
} rrs 
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:166)) - rrs.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:168)) - node.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:177)) - node.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:179)) - node.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:96)) - rrs.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:127)) - rrs.getRunOnSlave() null
2017-04-11 11:50:17.267 DEBUG [$_NIOREACTOR-3-RW] (io.mycat.backend.datasource.PhysicalDBPool.getRWBanlanceCon(PhysicalDBPool.java:456)) - select read source host1_M1 for dataHost:host1_inst1
FROM t2
LIMIT 10000}, respHandler=SingleNodeHandler [node=dn1{SELECT name
FROM t2
LIMIT 10000}, packetId=6], host=10.66.72.176, port=4311, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
