### ISSUE TITLE
mycat 只是做读写分离 不做分库分表 要怎么配置呢

### ISSUE THREAD

**Issue by ArmorHerO** [MyCATApache/Mycat-Server#1433]
如题额 望大神指教

**Comment by huangyiminghappy** [comment]
<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn7">
         
  </schema>
 <dataNode name="dn7" dataHost="localhost3" database="testdb" />

	<dataHost name="localhost3" maxCon="1000" minCon="10" balance="0"
	writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
	<heartbeat>select user()</heartbeat>
	
	<writeHost host="hostM1" url="10.40.6.187:3306" user="root" password="123456">
		
   		<readHost host="hostS1" url="10.40.6.228:3306" user="root" password="123456" weight="1" />
   	</writeHost>
	 
   </dataHost>

即可

**Comment by ArmorHerO** [comment]
@huangyiminghappy  不需要些dns什么的配置么 直接注释掉就好？可否给我一套完整的配置文件参考，非常感谢

**Comment by yanjunli** [comment]
<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
<dataNode name="dn1" dataHost="localhost3" database="db1" />

重点是 在schema 上 加上 dataNode  属性.

**Comment by ausky** [comment]
@huangyiminghappy balance 为0不是表示不开启读写分离么？ 
我的配置 是： 
<dataHost name="localhost1" maxCon="1000" minCon="10" balance="3"
              writeType="0" dbType="mysql" dbDriver="native" switchType="1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostM1" url="172.16.221.150:3306" user="root"
                   password="1234qwer">
            <readHost host="hostS1" url="172.16.221.152:3306" user="root" password="1234qwer"/>
        </writeHost>
    </dataHost>

**Comment by budingts** [comment]
我也遇到跟你一样的需要，我配置好了，在控制台查询，总是走从库，但是程序查的时候总是走主库，不知道你遇到过你没啊

**Comment by specialGirl** [comment]
@budingts  我的都是正常的，你可以把你的配置文件贴出来看一下或者你可是使用maxscal试一下读写分离

**Comment by ArmorHerO** [comment]
@budingts  我的都是正常的 你可以把你的配置文件贴出来看一下

**Comment by talkw-liu** [comment]
<schema name="mytest" checkSQLschema="true" sqlMaxLimit="10000">
        <table name="t_user" dataNode="dn0,dn1,dn2,dn3" rule="rang-long-uid-rule-customer"/>
</schema>
<dataNode name="dn0" dataHost="localhost1" database="mytest"/>
<dataNode name="dn1" dataHost="localhost1" database="mytest1"/>
<dataNode name="dn2" dataHost="localhost1" database="mytest2"/>
<dataNode name="dn3" dataHost="localhost1" database="mytest3"/>

<dataHost balance="3" maxCon="1000" minCon="10" name="localhost1" writeType="0" switchType="1" slaveThreshold="100" dbType="mysql" dbDriver="native">
        <heartbeat>select 1</heartbeat>
        <writeHost host="hostM1" url="192.168.3.243:3306" password="123456" user="root">
            <readHost host="hostS1" url="192.168.3.243:3306" password="123456" user="root"/>
        </writeHost>
</dataHost>

**如上面配置，我加入了readHost后就报错：**
/mycat/mycat-cluster-1/schema/dataHost error:Exception info:
io.mycat.config.util.ConfigException: SelfCheck### there are some datasource connection failed, pls check!
        at io.mycat.config.ConfigInitializer.testConnection(ConfigInitializer.java:214) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.manager.response.ReloadConfig.reload_all(ReloadConfig.java:108) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.config.loader.zkprocess.zktoxml.listen.SchemaszkToxmlLoader.notiflyProcess(SchemaszkToxmlLoader.java:138) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.config.loader.zkprocess.comm.ZookeeperProcessListen.notifly(ZookeeperProcessListen.java:149) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:191) ~[Mycat-server-1.6.6.1-release.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:310) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:304) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) ~[curator-framework-2.11.0.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) ~[guava-19.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) ~[curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:301) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:269) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:56) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:122) ~[curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749) ~[curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522) ~[curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:257) ~[curator-framework-2.11.0.jar:?]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) ~[zookeeper-3.4.6.jar:3.4.6-1569965]

如果去掉readHost配置就是正常的，试过了通过在243服务器上直连244的数据库是没有问题的
![image](https://user-images.githubusercontent.com/11623379/51171720-93a62b00-18ec-11e9-90b5-16a5c4484016.png)
很奇怪，不知道是怎么回事，在线等！！！

**Comment by talkw-liu** [comment]
@xuejipeng 帮我看下上面的问题，感谢

**Comment by xuejipeng** [comment]
@talkw-liu  这是我当时的配置文件，你可以参考下，我已经很久没搞 mycat 了

```
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
     <schema name="api" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1" />
     <schema name="apitest" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn2" />
     <schema name="mqtt" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn3" />
     <schema name="zoned_1" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn4" />
     <schema name="xuejp" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn5" />
     <dataNode name="dn1" dataHost="test_db" database="api" />
     <dataNode name="dn2" dataHost="test_db" database="apitest" />
     <dataNode name="dn3" dataHost="test_db" database="mqtt" />
     <dataNode name="dn4" dataHost="test_db" database="zoned_1" />
     <dataNode name="dn5" dataHost="test_db" database="xuejp" />
     <dataHost name="test_db" maxCon="1000" minCon="10" balance="1"
         writeType="0" dbType="mysql" dbDriver="native" switchType="2" slaveThreshold="100">
         <heartbeat>show slave status</heartbeat>
         <writeHost host="hostM1" url="172.19.0.4:3306" user="root" password="1t5YlBdTQUlI">
             <readHost host="db-slave1" url="172.19.0.7:3306" user="root" password="1t5YlBdTQUlI" weight="1" />
             <readHost host="db-slave2" url="172.19.0.10:3306" user="root" password="1t5YlBdTQUlI" weight="1" />
             <readHost host="db-slave3" url="172.19.0.6:3306" user="root" password="1t5YlBdTQUlI"  weight="1" />
         </writeHost>
        <writeHost host="hostM2" url="172.19.0.10:3306" user="root" password="1t5YlBdTQUlI" />
     </dataHost>
</mycat:schema>
当主down后 备用的写的主机代替主机写 当主重启后写的主机后并不会切换到主
```

**Comment by talkw-liu** [comment]
> @talkw-liu 这是我当时的配置文件，你可以参考下，我已经很久没搞 mycat 了
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE mycat:schema SYSTEM "schema.dtd">
> <mycat:schema xmlns:mycat="http://io.mycat/">
>      <schema name="api" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1" />
>      <schema name="apitest" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn2" />
>      <schema name="mqtt" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn3" />
>      <schema name="zoned_1" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn4" />
>      <schema name="xuejp" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn5" />
>      <dataNode name="dn1" dataHost="test_db" database="api" />
>      <dataNode name="dn2" dataHost="test_db" database="apitest" />
>      <dataNode name="dn3" dataHost="test_db" database="mqtt" />
>      <dataNode name="dn4" dataHost="test_db" database="zoned_1" />
>      <dataNode name="dn5" dataHost="test_db" database="xuejp" />
>      <dataHost name="test_db" maxCon="1000" minCon="10" balance="1"
>          writeType="0" dbType="mysql" dbDriver="native" switchType="2" slaveThreshold="100">
>          <heartbeat>show slave status</heartbeat>
>          <writeHost host="hostM1" url="172.19.0.4:3306" user="root" password="1t5YlBdTQUlI">
>              <readHost host="db-slave1" url="172.19.0.7:3306" user="root" password="1t5YlBdTQUlI" weight="1" />
>              <readHost host="db-slave2" url="172.19.0.10:3306" user="root" password="1t5YlBdTQUlI" weight="1" />
>              <readHost host="db-slave3" url="172.19.0.6:3306" user="root" password="1t5YlBdTQUlI"  weight="1" />
>          </writeHost>
>         <writeHost host="hostM2" url="172.19.0.10:3306" user="root" password="1t5YlBdTQUlI" />
>      </dataHost>
> </mycat:schema>
> 当主down后 备用的写的主机代替主机写 当主重启后写的主机后并不会切换到主
> ```

知道问题了，是我有个主从库数据库名不一致，所以这里没办法做主从复制，导致mycat这里连接报错，很感谢你的帮助，谢谢！
