### ISSUE TITLE
扩容时提示table不存在，但运行schema时是存在

### ISSUE THREAD

**Issue by AaronSheng** [MyCATApache/Mycat-Server#1476]
Table 'mycatdb.USER' doesn't exist
2017-05-05 15:24:18,222 [ERROR][main] Table 'mycatdb.USER' doesn't exist com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mycatdb.USER' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at com.alibaba.druid.util.JdbcUtils.executeQuery(JdbcUtils.java:665)
	at io.mycat.util.dataMigrator.DataMigratorUtil.executeQuery(DataMigratorUtil.java:214)
	at io.mycat.util.dataMigrator.TableMigrateInfo.setTableStructure(TableMigrateInfo.java:76)
	at io.mycat.util.dataMigrator.DataMigrator.<init>(DataMigrator.java:55)
	at io.mycat.util.dataMigrator.DataMigrator.main(DataMigrator.java:71)
 (io.mycat.util.dataMigrator.DataMigrator:DataMigrator.java:59)

**Comment by AaronSheng** [comment]
使用schema=all扩容失败
使用schema=tb1,tb2,....扩容则成功了
