### ISSUE TITLE
Mycat运行一段时间挂了，后台不断报错

### ISSUE THREAD

**Issue by zhouwuyuan** [MyCATApache/Mycat-Server#1519]
开始会不断报错：
java.lang.NullPointerException
	at io.mycat.net.AbstractConnection.ensureFreeSpaceOfReadBuffer(AbstractConnection.java:387) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:366) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

后面就不断刷：
2017-05-23 05:57:22.027 ERROR [$_NIOREACTOR-1-RW] (io.mycat.net.NIOReactor$RW.register(NIOReactor.java:163)) - register err
java.lang.NullPointerException
	at io.mycat.backend.mysql.BufferUtil.writeUB3(BufferUtil.java:39) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.mysql.HandshakePacket.write(HandshakePacket.java:98) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:441) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by yanjunli** [comment]
方便把配置贴一下吗？

**Comment by zhouwuyuan** [comment]
想要什么配置呢

**Comment by yanjunli** [comment]
server.xml 的配置

**Comment by zhouwuyuan** [comment]
<mycat:server xmlns:mycat="http://io.mycat/">
        <system>
                                <property name="defaultSqlParser">druidparser</property>
                                <property name="mutiNodeLimitType">1</property>
                                <property name="serverPort">8066</property>
                                <property name="managerPort">9066</property>
                                <property name="processors">32</property>
                                <property name="processorExecutor">256</property>
                                <property name="processorBufferPool">204800000</property>
                                <property name="processorBufferChunk">40960</property>
        </system>
        <user name="XXXXX">
                <property name="password">XXXXX</property>
                <property name="schemas">XXXXX</property>
        </user>
        <user name="XXXXX">
                <property name="password">XXXXX</property>
                <property name="schemas">XXXXX</property>
                <property name="readOnly">true</property>
        </user>
</mycat:server>

**Comment by zhouwuyuan** [comment]
![image](https://user-images.githubusercontent.com/29219006/27419783-36829fda-5755-11e7-9584-38daf9804d10.png)

**Comment by yanjunli** [comment]
buferchunk 设置的是不是有点大了？

**Comment by zhouwuyuan** [comment]
我发现这个值和bufferpool怎么设置在后台FREE_BUFFER  | TOTAL_BUFFER  都不会变

**Comment by zhouwuyuan** [comment]
然后我show @@sysparam;  看到processorBufferChunk的值也是4096B

**Comment by yanjunli** [comment]
bufferPoolChunkSize
bufferPoolPageSize

**Comment by zhouwuyuan** [comment]
@yanjunli 过段时间还是会报这个错误

**Comment by ben0x007** [comment]
遇到同样的问题，版本1.6
