### ISSUE TITLE
使用分布式事务访问global表，update/insert操作syntax error, error in :'XA RECOVER',expect IDENTIFIER, actual IDENTIFIER XA

### ISSUE THREAD

**Issue by 1042904326** [MyCATApache/Mycat-Server#1527]
DruidMycatRouteStrategyError com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'XA RECOVER',expect IDENTIFIER, actual IDENTIFIER XA
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:362)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2029)
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:70)
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:77)

**Comment by yanjunli** [comment]
使用xa 事务可以通过以下方式开启。
set autocommit=0/start/begin;
set xa=on;
commit;/rollback;

**Comment by yanjunli** [comment]
@1042904326  这个问题可以关闭了吗？

**Comment by jaryur** [comment]
@yanjunli  我在使用Druid连接池的时候，也遇到这个问题了，上面的答案我好像没看懂，能不能解释下是哪里的问题？

**Comment by yanjunli** [comment]
如果要使用xa事务. 在mycat中只需要执行 set xa=on; 就表示当前事务开启了xa事务。

**Comment by yichengmao** [comment]
你好 为何我按照你的操作设置了 还报错呢
