### ISSUE TITLE
ERROR 1003 (HY000): Reload config failure

### ISSUE THREAD

**Issue by liuflylove666** [MyCATApache/Mycat-Server#153]
Mcat:Mycat-server-1.3.0.2-20150105144205-linux.tar.gz
OS:CentOS release 6.4 (Final)
Mysql:5.5
Java:java version "1.7.0_67"

问题1：ERROR 1003 (HY000): Reload config failure
error log::
02/12 15:50:51.569   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:194)
	at org.opencloudb.net.NIOSocketWR.register(NIOSocketWR.java:27)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:154)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:722)
+++++++++++++++++++++++++++++++++++++++++++++++
问题2：
create table orders (id int not null primary key ,customer_id int not null,sataus int ,note varchar(100) );               //正常执行

insert into orders(id,customer_id) values(1,1);  //插入数据失败
insert into orders(id,customer_id) values(2,2); //插入数据失败

**Comment by liuflylove666** [comment]
ERROR 1003 (HY000): Reload config failure

**Comment by apachemycat** [comment]
此问题有人遇到过，可能是配置文件错误导致的，比如配置WriteHost 与ReadHost相同的IP地址
