### ISSUE TITLE
mycat连接oracle数据库,创表语句不可用的问题

### ISSUE THREAD

**Issue by JacXuan** [MyCATApache/Mycat-Server#1530]
如题.我在使用mycat连接oracle分库分表的时候出现的问题,打开逻辑表会出现field `create table` not found

一下是我的schema

<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/" >

	<schema name="ORACLEDB" checkSQLschema="false" sqlMaxLimit="100">

		<table name="people" primaryKey="_ID" dataNode="dn1" needAddLimit="false"/>

	</schema>

	<dataNode name="dn1" dataHost="oracle1" database="system" />

	 <dataHost name="oracle1" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc"> 
	 	<heartbeat>select 1 from dual</heartbeat> 	
		<writeHost host="hostM1" url="jdbc:oracle:thin:@127.0.0.1:1521:orcl" user="system" 	password="Liu965752" > </writeHost> 
	</dataHost> 
</mycat:schema>

请各位大哥帮帮小弟

**Comment by yanjunli** [comment]
用的是哪个版本？
mycat 后台日志有没有报错？

**Comment by beyondonly** [comment]
我也是遇到这个问题 ，我使用的是sqlserver 2014，请问一下怎么解决
后边报错日志
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultBusiness': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bpmBaseServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.activiti.engine.ActivitiException: couldn't create db schema: create table ACT_GE_PROPERTY ( 
NAME_ varchar(64), 
VALUE_ varchar(300), 
REV_ integer, 
primary key (NAME_) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
