### ISSUE TITLE
Sysbench 测试Mycat 连接丢失问题

### ISSUE THREAD

**Issue by dandan32** [MyCATApache/Mycat-Server#1594]
场景：
在用Sysbench 1.0测试Mycat、Mysql做对比
问题：Sysbench 提示连接丢失

```bash
[xyz@ubuntu sysbench]$ ../../bin/sysbench './oltp_read_only.lua' --mysql_storage_engine=innodb --mysql-db=sbtest --mysql-port=3307 --mysql-host="127.0.0.1" --mysql-user=root --mysql-password=123456  --table_size=1000000 --tables=1 run
sysbench 1.0.8 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!

FATAL: mysql_stmt_execute() returned error 2013 (Lost connection to MySQL server during query) for query 'BEGIN'
FATAL: `thread_run' function failed: ./oltp_common.lua:399: SQL error, errno = 2013, state = 'HY000': Lost connection to MySQL server during query
Error in my_thread_global_end(): 1 threads didn't exit

```

请问如何解决？？？TAT.

**Comment by HashZhang** [comment]
你检查下MyCat后台是不是有数据库连接不上，用户名密码对不对，一般2013返回是这个问题

**Comment by dandan32** [comment]
发现是为啥了。
sysbench关了这两个选项就好了
 --skip_trx=off --db-ps-mode=disable
不知道为啥。。。

**Comment by ZzzCrazyPig** [comment]
从sysbench的报错信息来看，应该是走了mycat预处理，请问测试mycat的版本是多少？

**Comment by ZzzCrazyPig** [comment]
`--db-ps-mode=disable`为取消mysql服务端预处理，如果mycat版本是1.5或者更低版本，并不支持服务端预处理

**Comment by baixiaoyu** [comment]
我也遇到相同的问题，mycat1.6, sysbench1.1
sysbench /usr/local/share/sysbench/oltp_read_only.lua --mysql-user=test --mysql-password=test --mysql-port=8066 --mysql-host=127.0.0.1  --mysql-db=testdb --threads=1 run
sysbench 1.1.0 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!

FATAL: mysql_stmt_execute() returned error 2013 (Lost connection to MySQL server during query) for query 'BEGIN'
FATAL: `thread_run' function failed: /usr/local/share/sysbench/oltp_common.lua:400: SQL error, errno = 2013, state = 'HY000': Lost connection to MySQL server during query
该命令直接运行在mysql上是没有问题的，mycat后端出现数组越界的提示：
 use server prepare, sql: SELECT DISTINCT c FROM sbtest1 WHERE id BETWEEN ? AND ? ORDER BY c
2017-08-07 15:15:58.455  WARN [$_NIOREACTOR-2-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
java.lang.ArrayIndexOutOfBoundsException: 14
        at io.mycat.backend.mysql.MySQLMessage.read(MySQLMessage.java:79) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.mysql.ExecutePacket.read(ExecutePacket.java:117) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:128) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:386) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:99) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]

我用java写了个预处理的测试了下 SELECT DISTINCT c FROM sbtest1 WHERE id BETWEEN ? AND ? ORDER BY c这个语句，发现这个语句执行提示空指针错误。即使不使用预处理的语句，在mycat中直接执行这个语句也是有问题，测试如下：
mysql> select c from sbtest1 where id between 0 and 10700 group by c order by c;
ERROR 1105 (HY000): java.lang.NullPointerException
测试表的全部数据如下，表按k mod分片
mysql> select * from sbtest1;
+-------+-----+---+-----+
| id    | k   | c | pad |
+-------+-----+---+-----+
| 10608 |   4 | d | dd  |
| 10611 |   7 | d | dd  |
| 10614 |  10 | d | dd  |
| 10700 |  11 | d | dd  |
| 10607 |   3 | c | cc  |
| 10610 |   6 | d | dd  |
| 10613 |   9 | d | dd  |
| 10615 | 111 | d | dd  |
+-------+-----+---+-----+
8 rows in set (0.06 sec)

**Comment by ZzzCrazyPig** [comment]
@baixiaoyu 看了你的Mycat版本是1.6-RELEASE？是在哪里下载的？用最新的1.6.5-BETA有试过？

**Comment by baixiaoyu** [comment]
我的release版本是在 http://dl.mycat.io/1.6-RELEASE/这里下载的。我上面说的有些问题，“我用java写了个预处理的测试了下 SELECT DISTINCT c FROM sbtest1 WHERE id BETWEEN ? AND ? ORDER BY c这个语句，发现这个语句执行提示空指针错误”这部分，我用的github1.6的源码运行的，release上没有出现空指针的问题

**Comment by ZzzCrazyPig** [comment]
也就是说用了Mycat 1.6分支最新源码跑你上面说的那个预处理SQL，也是会有问题的？

sql如下:
```sql
SELECT DISTINCT c FROM sbtest1 WHERE id BETWEEN ? AND ? ORDER BY c;
```

**Comment by baixiaoyu** [comment]
![image](https://user-images.githubusercontent.com/12657003/29019400-d6ed6b26-7b90-11e7-811d-c5ddc8601dc3.png)
是的

**Comment by ZzzCrazyPig** [comment]
恩，通过命令行是不走预处理的，不过预处理最终也是走的普通SQL处理，所以都是一样会抛NPE的异常，这个需要验证下是哪里的问题了

**Comment by ZzzCrazyPig** [comment]
@yanjunli 你好，你改的`DataNodeMergeManager.java`里面的`onRowMetaData`方法里面最后用的:

```java
Arrays.sort(mergeColsIndex);
```
当`mergeColsIndex`为null时抛NPE，详细复现请看下上面的，麻烦修复一下吧

**Comment by yanjunli** [comment]
好的

**Comment by yanjunli** [comment]
该问题已经修复.请更新最新源码
