### ISSUE TITLE
WARN [Timer1] (io.mycat.net.NIOProcessor.backendCheck(NIOProcessor.java:207))

### ISSUE THREAD

**Issue by wzlapple** [MyCATApache/Mycat-Server#1599]
mycat 出现这个警告WARN [Timer1] (io.mycat.net.NIOProcessor.backendCheck(NIOProcessor.java:207)) - found backend connection SQL timeout ,close it MySQLConnection
应用端就报这个异常，
Cause: java.lang.reflect.UndeclaredThrowableException
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:368)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at com.sun.proxy.$Proxy20.selectList(Unknown Source)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at com.ys.atds.template.MybatisTemplateForMy.selectList(MybatisTemplateForMy.java:61)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at com.ys.atds.dao.oa.impl.StaticClockDaoImpl.getMaxOrMinCtimeStaticClockByCodes(StaticClockDaoImpl.java:271)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at com.ys.atds.service.oa.impl.StaticClockServiceImpl.getMaxOrMinCtimeStaticClockByCodes(StaticClockServiceImpl.java:350)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at com.ys.atds.service.oa.impl.StaticClockServiceImpl$$FastClassBySpringCGLIB$$c16deea5.invoke(<generated>)
INFO   | jvm 1    | 2017/07/10 06:36:04 | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

哪位大神遇到这样问题请赐教

**Comment by ZzzCrazyPig** [comment]
sql执行超时，默认时间是300s，看mysql后端是否有耗时的SQL跑了5min还没有结束

**Comment by yanjunli** [comment]
found backend connection SQL timeout
