### ISSUE TITLE
1.3.0.2版本查询时报com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLPropertyExpr

### ISSUE THREAD

**Issue by kevingzhz** [MyCATApache/Mycat-Server#160]
表：
CREATE TABLE `app_log` (
  `car_id` int(11) NOT NULL DEFAULT '0',
  `din` varchar(20) DEFAULT NULL,
  `car_time` datetime DEFAULT '2015-01-01 00:00:00',
  `receive_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`car_id`,`car_time`)
) ENGINE=InnoDB DEFAULT CHARSET= utf8mb4
PARTITION BY LIST (TO_DAYS(car_time)) (  
    PARTITION p20150226 VALUES  IN (TO_DAYS('2015-02-26')),  
    PARTITION p20150227 VALUES  IN (TO_DAYS('2015-02-27')),  
    PARTITION p20150228 VALUES  IN (TO_DAYS('2015-02-28')),  
	PARTITION p20150301 VALUES  IN (TO_DAYS('2015-03-01')), 
	PARTITION p20150302 VALUES  IN (TO_DAYS('2015-03-02')), 
	PARTITION p20150303 VALUES  IN (TO_DAYS('2015-03-03')), 
	PARTITION p20150304 VALUES  IN (TO_DAYS('2015-03-04')), 
	PARTITION p20150305 VALUES  IN (TO_DAYS('2015-03-05')), 
	PARTITION p20150306 VALUES  IN (TO_DAYS('2015-03-06')), 
	PARTITION p20150307 VALUES  IN (TO_DAYS('2015-03-07')), 
	PARTITION p20150308 VALUES  IN (TO_DAYS('2015-03-08')), 
	PARTITION p20150309 VALUES  IN (TO_DAYS('2015-03-09')), 
	PARTITION p20150310 VALUES  IN (TO_DAYS('2015-03-10')), 
	PARTITION p20150311 VALUES  IN (TO_DAYS('2015-03-11')), 
	PARTITION p20150312 VALUES  IN (TO_DAYS('2015-03-12')), 
	PARTITION p20150313 VALUES  IN (TO_DAYS('2015-03-13')), 
	PARTITION p20150314 VALUES  IN (TO_DAYS('2015-03-14')),
	PARTITION p20150315 VALUES  IN (TO_DAYS('2015-03-15'))  	
);

mycat分片：org.opencloudb.route.function.PartitionByLong

查询sql:select car_id,car_time from app_log  where  car_time between '2015-03-03 00:00:00' and '2015-03-03 23:59:59' and car_id=879 order by car_time desc

报错：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLPropertyExpr
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1612)

**Comment by apachemycat** [comment]
更新到1.3.0.3版试试，0.2版本存在比较多的SQL解析问题

**Comment by linzhiqiang0514** [comment]
请确认这个问题是否还存在？

**Comment by mycatmerger** [comment]
1.4测试此sql解析正常
