### ISSUE TITLE
心跳检测任务报java.lang.NullPointerException

### ISSUE THREAD

**Issue by kevingzhz** [MyCATApache/Mycat-Server#161]
03-04 15:20:05.070  ERROR [Timer1] (PhysicalDatasource.java:301) -hostM198 heartbeat error.
java.lang.NullPointerException
	at org.opencloudb.heartbeat.MySQLDetector.getPass(MySQLDetector.java:239)
	at org.opencloudb.heartbeat.MySQLDetector.authenticate(MySQLDetector.java:152)
	at org.opencloudb.heartbeat.MySQLDetector.heartbeat(MySQLDetector.java:172)
	at org.opencloudb.heartbeat.MySQLHeartbeat.heartbeat(MySQLHeartbeat.java:137)
	at org.opencloudb.backend.PhysicalDatasource.doHeartbeat(PhysicalDatasource.java:299)
	at org.opencloudb.backend.PhysicalDBPool.doHeartbeat(PhysicalDBPool.java:313)
	at org.opencloudb.MycatServer$6$1.run(MycatServer.java:521)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by apachemycat** [comment]
是Mycat什么版本？可能此版本有缺陷，目前最新稳定版本是1.3.xx系列

**Comment by mycatmerger** [comment]
1.4已经做过改进，请使用最新版
