### ISSUE TITLE
手动停止一个大数据查询语句执行中断，mycat虽然服务保持但用程序去连接mycat就连不上了

### ISSUE THREAD

**Issue by boonyachengdu** [MyCATApache/Mycat-Server#1645]
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,841 [WARN ][BusinessExecutor6] caught exception  java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,841 [WARN ][BusinessExecutor6] caught exception  java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,841 [WARN ][BusinessExecutor6] caught exception  java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,841 [WARN ][BusinessExecutor6] caught exception  java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,841 [WARN ][BusinessExecutor6] caught exception  java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 |  (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler:MultiNodeQueryHandler.java:660) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | 2017-09-12 18:15:20,842 [ERROR][BusinessExecutor6] sql execute error, this Mongo has been closed, java.lang.IllegalStateException: this Mongo has been closed  (io.mycat.backend.jdbc.JDBCConnection:JDBCConnection.java:350) 
INFO   | jvm 1    | 2017/09/12 18:15:20 | Exception in thread "BusinessExecutor6" java.lang.NullPointerException
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.net.AbstractConnection.checkWriteBuffer(AbstractConnection.java:456)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.net.mysql.ErrorPacket.write(ErrorPacket.java:118)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.net.mysql.ErrorPacket.writeToBytes(ErrorPacket.java:89)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:351)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.backend.jdbc.JDBCConnection.access$000(JDBCConnection.java:40)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:914)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2017/09/12 18:15:20 | 	at java.lang.Thread.run(Thread.java:748)

**Comment by boonyachengdu** [comment]
[local_error.txt](https://github.com/MyCATApache/Mycat-Server/files/1301532/local_error.txt)
[local_app.txt](https://github.com/MyCATApache/Mycat-Server/files/1301534/local_app.txt)

**Comment by boonyachengdu** [comment]
https://github.com/MyCATApache/Mycat-Server/issues/1616 已基本上解决此问题
