### ISSUE TITLE
MyCat1.6版本 ServerPrepareHandler预处理BUG

### ISSUE THREAD

**Issue by HUPFC** [MyCATApache/Mycat-Server#1647]
问题复现过程:
       使用PHP pdo prepare预处理方式请求，当连续两次请求同一条sql语句时，抛出异常"Unknown pstmtId when executing."
       源码断点调试发现在ServerPrepareHandler中
       prepare()执行完毕后在close()中pstmtForSql的清理问题

表结构:
CREATE TABLE `test` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `run` int(2) unsigned NOT NULL COMMENT '启动方式',
  PRIMARY KEY (`id`),
  KEY `run` (`run`)
) ENGINE=MyISAM AUTO_INCREMENT=21841 DEFAULT CHARSET=utf8;

SQL语句:
INSERT INTO test (`run` ) VALUES ( '0')

**Comment by zhuam** [comment]
给出错误的log

**Comment by HUPFC** [comment]
MyCat debug日志
`2017-09-14 11:03:40,065 [INFO ][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC]'kuai8_prod' login success  (io.mycat.net.handler.FrontendAuthenticator:FrontendAuthenticator.java:226) 
2017-09-14 11:03:40,066 [DEBUG][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC] SET NAMES utf8  (io.mycat.net.FrontendConnection:FrontendConnection.java:289) 
2017-09-14 11:03:40,066 [DEBUG][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC]SET NAMES utf8  (io.mycat.server.ServerQueryHandler:ServerQueryHandler.java:57) 
2017-09-14 11:03:40,072 [DEBUG][$_NIOREACTOR-19-RW] use server prepare, sql: INSERT INTO test (`run` ) VALUES ( '0')  (io.mycat.server.handler.ServerPrepareHandler:ServerPrepareHandler.java:83) 
2017-09-14 11:03:40,076 [DEBUG][$_NIOREACTOR-19-RW] execute prepare sql: INSERT INTO test (`run` ) VALUES ( '0')  (io.mycat.server.handler.ServerPrepareHandler:ServerPrepareHandler.java:152) 
2017-09-14 11:03:40,076 [DEBUG][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC] INSERT INTO test (`run` ) VALUES ( '0')  (io.mycat.net.FrontendConnection:FrontendConnection.java:289) 
2017-09-14 11:03:40,076 [DEBUG][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC]INSERT INTO test (`run` ) VALUES ( '0')  (io.mycat.server.ServerQueryHandler:ServerQueryHandler.java:57) 
2017-09-14 11:03:40,165 [DEBUG][$_NIOREACTOR-19-RW] ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC]INSERT INTO test (`run` ) VALUES ( '0'), route={
   1 -> STAT_MC_DN_PRI{INSERT INTO test (`run` ) VALUES ( '0')}
} rrs   (io.mycat.server.NonBlockingSession:NonBlockingSession.java:126) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] rrs.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:167) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] node.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:169) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] node.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:178) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] node.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:180) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] rrs.getRunOnSlave() null  (io.mycat.backend.datasource.PhysicalDBNode:PhysicalDBNode.java:96) 
2017-09-14 11:03:40,168 [DEBUG][$_NIOREACTOR-19-RW] rrs.getRunOnSlave() null  (io.mycat.backend.datasource.PhysicalDBNode:PhysicalDBNode.java:127) 
2017-09-14 11:03:40,169 [DEBUG][$_NIOREACTOR-19-RW] con need syn ,total syn cmd 1 commands SET names utf8;schema change:false con:MySQLConnection [id=8, lastTime=1505358220169, user=kuai8_prod, schema=stat_mc, old shema=stat_mc, borrowed=true, fromSlaveDB=false, threadId=1861, charset=utf8, txIsolation=3, autocommit=true, attachment=STAT_MC_DN_PRI{INSERT INTO test (`run` ) VALUES ( '0')}, respHandler=SingleNodeHandler [node=STAT_MC_DN_PRI{INSERT INTO test (`run` ) VALUES ( '0')}, packetId=0], host=183.61.19.92, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=true]  (io.mycat.backend.mysql.nio.MySQLConnection:MySQLConnection.java:451) 
2017-09-14 11:03:40,214 [DEBUG][$_NIOREACTOR-8-RW] release connection MySQLConnection [id=8, lastTime=1505358220168, user=kuai8_prod, schema=stat_mc, old shema=stat_mc, borrowed=true, fromSlaveDB=false, threadId=1861, charset=utf8, txIsolation=3, autocommit=true, attachment=STAT_MC_DN_PRI{INSERT INTO test (`run` ) VALUES ( '0')}, respHandler=SingleNodeHandler [node=STAT_MC_DN_PRI{INSERT INTO test (`run` ) VALUES ( '0')}, packetId=1], host=183.61.19.92, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=true]  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:372) 
2017-09-14 11:03:40,214 [DEBUG][$_NIOREACTOR-8-RW] release channel MySQLConnection [id=8, lastTime=1505358220168, user=kuai8_prod, schema=stat_mc, old shema=stat_mc, borrowed=true, fromSlaveDB=false, threadId=1861, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=183.61.19.92, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:590) 
2017-09-14 11:03:40,215 [DEBUG][$_NIOREACTOR-19-RW] use server prepare, sql: INSERT INTO test (`run` ) VALUES ( '0')  (io.mycat.server.handler.ServerPrepareHandler:ServerPrepareHandler.java:83) 
2017-09-14 11:03:40,216 [DEBUG][$_NIOREACTOR-19-RW] close prepare stmt, stmtId = 1  (io.mycat.server.handler.ServerPrepareHandler:ServerPrepareHandler.java:163) 
2017-09-14 11:03:40,221 [DEBUG][$_NIOREACTOR-19-RW] close prepare stmt, stmtId = 1  (io.mycat.server.handler.ServerPrepareHandler:ServerPrepareHandler.java:163) 
2017-09-14 11:03:40,222 [INFO ][$_NIOREACTOR-19-RW] close connection,reason:quit cmd ,ServerConnection [id=1, schema=STAT_MC, host=192.168.0.170, user=kuai8_prod,txIsolation=3, autocommit=true, schema=STAT_MC]  (io.mycat.net.AbstractConnection:AbstractConnection.java:514) 
Disconnected from the target VM, address: '127.0.0.1:56107', transport: 'socket'`

**Comment by HUPFC** [comment]
PHP 日志

command sql INSERT INTO test (`run` ) VALUES ( '0')
result 21855
command sql INSERT INTO test (`run` ) VALUES ( '0')
Exception Code:HY000
Message :SQLSTATE[HY000]: General error: 1220 Unknown pstmtId when executing.
#0 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/vendor/workerman/mysql/src/Connection.php(1740): PDOStatement->execute()
#1 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/vendor/workerman/mysql/src/Connection.php(1820): Workerman\MySQL\Connection->execute('INSERT INTO tes...', NULL)
#2 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/app/mc/controller/StatNew32.php(52): Workerman\MySQL\Connection->query('INSERT INTO tes...')
#3 [internal function]: app\mc\controller\StatNew32->__construct()
#4 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/thinkphp/library/think/App.php(243): ReflectionClass->newInstanceArgs(Array)
#5 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/thinkphp/library/think/Loader.php(418): think\App::invokeClass('app\\mc\\controll...')
#6 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/thinkphp/library/think/App.php(367): think\Loader::controller('statNew32', 'controller', false, 'Error')
#7 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/thinkphp/library/think/App.php(130): think\App::module(Array, Array, false)
#8 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/thinkphp/start.php(18): think\App::run()
#9 /mnt/hgfs/kuai8/mc/socket.mc.kuai8.com/console/mc/stat-dev.php(17): require('/mnt/hgfs/kuai8...')

**Comment by HUPFC** [comment]
连续执行非相同sql 没有问题 （Values不通即可）
command sql INSERT INTO test (`run` ) VALUES ( '0')
result 21856
command sql INSERT INTO test (`run` ) VALUES ( '1')
result 21857
