### ISSUE TITLE
insert SQL中注释无法解析

### ISSUE THREAD

**Issue by liyongxian** [MyCATApache/Mycat-Server#1671]
navicat连接mycat（使用mycat的读写分离模式），后端连接mysql。通过navicat导出的sql中如下，

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO `test` VALUES ('1', 'aa', '1');
INSERT INTO `test` VALUES ('2', 'aa', '2');
INSERT INTO `test` VALUES ('3', 'aa', '3');
INSERT INTO `test` VALUES ('4', 'aa', '4');
再通过navicat导入该SQL文件时，报错。
INSERT INTO `test` VALUES ('1', 'aa', '1') err:java.lang.StringIndexOutOfBoundsException: String index out of range: -1 java.lang.StringIndexOutOfBoundsException: String index out of range: -1
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at java.lang.String.substring(String.java:1967)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.util.StringUtil.getTableName(StringUtil.java:546)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.route.util.RouterUtil.processERChildTable(RouterUtil.java:1534)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:95)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:36)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.route.RouteService.route(RouteService.java:137)
INFO   | jvm 1    | 2017/10/17 14:33:42 |       at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273).
经分析，StringUtil.getTableName中，mycat对sql中的如下注释无法去掉。
-- ----------------------------
-- Records of test
-- ----------------------------

**Comment by liyongxian** [comment]
mycat  不支持 -- 注释
