### ISSUE TITLE
配置[database="sys_order$1-4"]启动报错

### ISSUE THREAD

**Issue by hhy5861** [MyCATApache/Mycat-Server#1675]
<table name="tbl_order" primaryKey="id" autoIncrement="true" dataNode="multipleOrders_node1$1-4,multipleOrders_node2$5-10,multipleOrders_node3$11-16" rule="sharding-by-murmur"></table>
                
                
        </schema>
        
        <dataNode name="multipleOrders_node1" dataHost="orders1" database="sys_order$1-4" />
        <dataNode name="multipleOrders_node2" dataHost="orders2" database="sys_order$5-10" />
        <dataNode name="multipleOrders_node3" dataHost="orders3" database="sys_order$11-16" />

启动报错信息：
STATUS | wrapper  | 2017/10/20 19:55:52 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/10/20 19:55:52 | Launching a JVM...
INFO   | jvm 1    | 2017/10/20 19:55:52 | OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
INFO   | jvm 1    | 2017/10/20 19:56:03 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2017/10/20 19:56:03 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2017/10/20 19:56:03 |
INFO   | jvm 1    | 2017/10/20 19:56:04 |
INFO   | jvm 1    | 2017/10/20 19:56:04 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2017/10/20 19:56:04 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2017/10/20 19:56:04 | Caused by: io.mycat.config.util.ConfigException: java.lang.NullPointerException
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:126)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:83)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:87)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:76)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.MycatServer.<init>(MycatServer.java:170)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.MycatServer.<clinit>(MycatServer.java:116)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	... 7 more
INFO   | jvm 1    | 2017/10/20 19:56:04 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.getDbType(XMLSchemaLoader.java:458)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:387)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:173)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:122)
INFO   | jvm 1    | 2017/10/20 19:56:04 | 	... 13 more
STATUS | wrapper  | 2017/10/20 19:56:07 | <-- Wrapper Stopped

**Comment by DaiZZZZZ** [comment]
![image](https://user-images.githubusercontent.com/22972651/87624378-3b0e5300-c75a-11ea-85dd-e26f42979b03.png)
