### ISSUE TITLE
mycat server 1.6

### ISSUE THREAD

**Issue by zhengvictor** [MyCATApache/Mycat-Server#1677]
启动报错：
INFO   | jvm 1    | 2017/10/25 17:28:09 | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INFO   | jvm 1    | 2017/10/25 17:28:09 | 2017-10-25 17:28:09,060 [ERROR][WrapperSimpleAppMain] 2017-10-25 17:28:09 startup error java.lang.NumberFormatException: Size must be specified as bytes (b), kibibytes (k), mebibytes (m), gibibytes (g), tebibytes (t), or pebibytes(p). E.g. 50b, 100k, or 250m.
INFO   | jvm 1    | 2017/10/25 17:28:09 | Failed to parse byte string: -375809638B
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAs(JavaUtils.java:223)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAsBytes(JavaUtils.java:234)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.utils.MycatPropertyConf.byteStringAsBytes(MycatPropertyConf.java:92)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.utils.MycatPropertyConf.getSizeAsBytes(MycatPropertyConf.java:50)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.memory.mm.MemoryManager.<init>(MemoryManager.java:30)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.unsafe.memory.mm.ResultMergeMemoryManager.<init>(ResultMergeMemoryManager.java:15)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.memory.MyCatMemory.<init>(MyCatMemory.java:125)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.MycatServer.startup(MycatServer.java:335)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at io.mycat.MycatStartup.main(MycatStartup.java:57)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2017/10/25 17:28:09 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/10/25 17:28:09 |  (io.mycat.MycatStartup:MycatStartup.java:62)
STATUS | wrapper  | 2017/10/25 17:28:11 | <-- Wrapper Stopped

配置参数 就是默认。没改过什么啊。

**Comment by HashZhang** [comment]
磁盘空间可能不足
