### ISSUE TITLE
使用mycat全局序列号 本地时间戳方式 报错

### ISSUE THREAD

**Issue by zhuangshi163** [MyCATApache/Mycat-Server#1724]
求助使用mycat全局序列号 本地时间戳方式 报错
mysql> INSERT INTO brc.`brc_trx_detail` (`LINE_ID`, `TRX_ID`) VALUES (next value for MYCATSEQ_GLOBAL, '6');
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    9
Current database: brc

ERROR 2013 (HY000): Lost connection to MySQL server during query

mycat.log 日志：
2017-12-04 23:51:27.055  WARN [$_NIOREACTOR-2-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
com.alibaba.druid.sql.parser.ParserException: syntax error
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2132) ~[druid-1.0.26.jar:1.0.26]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2022) ~[druid-1.0.26.jar:1.0.26]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:193) ~[druid-1.0.26.jar:1.0.26]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:199) ~[druid-1.0.26.jar:1.0.26]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
        at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:25) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:214) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273) ~[Mycat-server-1.6-RELEASE.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6-RELEASE.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

server.xml文件：
        <system>
        <property name="sequnceHandlerType">2</property>
        </system>

sequence_time_conf.properties 文件：
WORKID=01
DATAACENTERID=01

**Comment by 3legcat** [comment]
next value for MYCATSEQ_GLOBAL 不需要加引号
