### ISSUE TITLE
MyCat解析ORACLE SQL语法报错

### ISSUE THREAD

**Issue by mayinglong** [MyCATApache/Mycat-Server#1729]
MyCat后面是连ORACLE数据库，如果SQL语句中有 START WITH ... CONNECT BY... 这种语法，解析时报错，具体错误如下：

(io.mycat.route.impl.DruidMycatRouteStrategy:DruidMycatRouteStrategy.java:112) 
2017-12-15 09:40:43,128 [WARN ][$_NIOREACTOR-0-RW] ServerConnection [id=8, schema=TESTDB, host=127.0.0.1, user=user,txIsolation=3, autocommit=false, schema=TESTDB]/*!mycat:schema=TESTDB*/SELECT DISTINCT MENUID FROM T_EN_RBAC_ROLEMENU WHERE TENANTID='225062062644002816' AND STS='000' 
    AND ROLEID IN(
    	SELECT AR.ROLEID FROM T_EN_RBAC_ACCOUNTROLE AR,T_EN_RBAC_ROLE RO 
    	WHERE RO.ID=AR.ROLEID AND RO.STS='000' AND
    	((AR.ACCOUNTID = '226219453908516864' AND AR.TYPE='003') 
		OR (AR.ACCOUNTID IN (SELECT T.ID FROM T_EN_BASE_DEPT T START WITH T.ID='225164323751723008' CONNECT BY PRIOR T.PARENTID=T.ID) 
			AND (AR.TYPE='001' OR AR.TYPE='002')))
    ) AND PARENTID = '193522613478227969' err:java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER START java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER START
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:113)
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
	at io.mycat.route.handler.HintSchemaHandler.route(HintSchemaHandler.java:51)
	at io.mycat.route.RouteService.route(RouteService.java:124)
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:280)
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:226)
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:324)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:344)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:500)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:482)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER START

**Comment by mayinglong** [comment]
MyCat版本号为1.6
