### ISSUE TITLE
Mycat 1.6.5连接 Postgresql 10 问题

### ISSUE THREAD

**Issue by wtzyeah** [MyCATApache/Mycat-Server#1743]
无法连接postgresql数据库

mycat ：1.6.5
postgresql：10
jdbc：postgresql-42.1.4.jar

<dataHost name="localhost1" maxCon="1000" minCon="3" balance="0" writeType="0" dbType="postgresql" dbDriver="jdbc" switchType="1">
		<heartbeat>select 1</heartbeat>
		<writeHost host="host1M1" url="jdbc:postgresql://localhost:5432/test" user="postgres" password="roosss">
		</writeHost>
</dataHost>

wrapper.log信息如下：

INFO   | jvm 1    | 2018/01/06 15:23:21 | 一月 06, 2018 3:23:21 下午 org.postgresql.Driver connect
INFO   | jvm 1    | 2018/01/06 15:23:21 | 严重: Connection error: 
INFO   | jvm 1    | 2018/01/06 15:23:21 | org.postgresql.util.PSQLException: 尝试连线已失败。
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.Driver.makeConnection(Driver.java:450)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.Driver.connect(Driver.java:252)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at io.mycat.backend.jdbc.JDBCDatasource.getConnection(JDBCDatasource.java:109)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:100)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at io.mycat.backend.datasource.PhysicalDatasource.doHeartbeat(PhysicalDatasource.java:438)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at io.mycat.backend.datasource.PhysicalDBPool.doHeartbeat(PhysicalDBPool.java:345)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at io.mycat.MycatServer$8$1.run(MycatServer.java:897)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2018/01/06 15:23:21 | Caused by: java.net.SocketException: Connection reset
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.PGStream.receiveChar(PGStream.java:288)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:418)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
INFO   | jvm 1    | 2018/01/06 15:23:21 | 	... 14 more

**Comment by lx088** [comment]
jdk用的是1.8的吗，要么就是postgresql的jar版本

**Comment by wtzyeah** [comment]
@lx088 
jdk用的是：1.8.0_131
postgresql的jar是：postgresql-9.4-1202.jdbc42.jar

**Comment by westsince2001** [comment]
这个是不是还没解决啊？
