### ISSUE TITLE
java.lang.NumberFormatException: 65535

### ISSUE THREAD

**Issue by cloudscode** [MyCATApache/Mycat-Server#1759]
# mycat version 1.6.5-release

# java.lang.NumberFormatException: 65535

```
==> mycat.log <==
2018-01-30 16:09:12.947  WARN [BusinessExecutor3] (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:764)) - caught exception 
java.lang.NumberFormatException: 65535
	at io.mycat.memory.unsafe.utils.BytesTools.getShort(BytesTools.java:301) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.memory.unsafe.utils.BytesTools.getShort(BytesTools.java:242) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.getValue(UnsafeRowGrouper.java:561) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.addRow(UnsafeRowGrouper.java:608) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.sqlengine.mpp.DataNodeMergeManager.run(DataNodeMergeManager.java:459) ~[Mycat-server-1.6.5-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

==> wrapper.log <==
INFO   | jvm 1    | 2018/01/30 16:09:13 | java.lang.NumberFormatException: 65535
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at io.mycat.memory.unsafe.utils.BytesTools.getShort(BytesTools.java:301)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at io.mycat.memory.unsafe.utils.BytesTools.getShort(BytesTools.java:242)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.getValue(UnsafeRowGrouper.java:561)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at io.mycat.sqlengine.mpp.UnsafeRowGrouper.addRow(UnsafeRowGrouper.java:608)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at io.mycat.sqlengine.mpp.DataNodeMergeManager.run(DataNodeMergeManager.java:459)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2018/01/30 16:09:13 | 	at java.lang.Thread.run(Thread.java:745)

```

**Comment by zhengweisk** [comment]
我也遇见了这个问题
