### ISSUE TITLE
单库分表的问题，谢谢

### ISSUE THREAD

**Issue by robertbee** [MyCATApache/Mycat-Server#1768]
http://dl.mycat.io/1.6.5/Mycat-server-1.6.5-release-20180122220033-linux.tar.gz
下载版本后，在suse linux 12 SP2上。

```
<mycat:schema xmlns:mycat="http://io.mycat/">  
    <schema name="iddb" checkSQLschema="false" sqlMaxLimit="100">  
		<table name="single" primaryKey="id" subTables="single$0-4" dataNode="dn0" rule="single" />  
    </schema>  
    <dataNode name="dn0" dataHost="dh-1" database="test0"/>  
    <dataHost name="dh-1" maxCon="500" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">  
        <heartbeat>select 100</heartbeat>  
        <writeHost host="192.168.1.100" url="192.168.1.100:3306" user="root" password="root">  
        </writeHost>  
    </dataHost>  
</mycat:schema>

<mycat:rule xmlns:mycat="http://io.mycat/">
<tableRule name="single"> 
 <rule> 
   <columns>id</columns> 
   <algorithm>single</algorithm> 
 </rule> 
</tableRule> 
</mycat:rule>

<function name="single" class="io.mycat.route.function.PartitionByPrefixPattern"> 
 <property name="patternValue">5</property> 
 <property name="prefixLength">36</property> 
 <property name="mapFile">single-partition-pattern.txt</property> 
</function>
```

single-partition-pattern.txt
0-0=0
1-1=1
2-2=2
3-3=3
4-4=4

修改后启动mycat报rule.xml里的最后一行：</mycat:rule> 
The content of element type "mycat:rule" must match "(tableRule*,function*)"
wrapper.log 日志截取如下：

INFO   | jvm 1    | 2018/03/02 11:58:27 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2018/03/02 11:58:27 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2018/03/02 11:58:27 | Caused by: io.mycat.config.util.ConfigException: org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 14; The content of element type "mycat:rule" must match "(tableRule*,function*)".
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.loader.xml.XMLRuleLoader.load(XMLRuleLoader.java:95)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.loader.xml.XMLRuleLoader.<init>(XMLRuleLoader.java:64)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:74)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:87)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:76)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.MycatServer.<init>(MycatServer.java:170)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.MycatServer.<clinit>(MycatServer.java:116)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       ... 7 more
INFO   | jvm 1    | 2018/03/02 11:58:27 | Caused by: org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 14; The content of element type "mycat:rule" must match "(tableRule*,function*)".
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTDValidator.java:1994)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(XMLDTDValidator.java:879)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.util.ConfigUtil.getDocument(ConfigUtil.java:115)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       at io.mycat.config.loader.xml.XMLRuleLoader.load(XMLRuleLoader.java:86)
INFO   | jvm 1    | 2018/03/02 11:58:27 |       ... 14 more

**Comment by robertbee** [comment]
看了git上的源码，问题已经清楚了，rule.xml里不支持tableRule/function/tableRule/function交叉的方式配置。只能是tableRule/function
