### ISSUE TITLE
1.6 使用 mybatis 执行多条 sql 报错 1.5没问题

### ISSUE THREAD

**Issue by codeyung** [MyCATApache/Mycat-Server#1774]
### 测试环境从1.5升级到1.6
先insert 后 update 就会报错
先update 后 insert都不会报错
请问这是为什么 
WARN [$_NIOREACTOR-0-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:285)) - ServerConnection [id=237909, schema=db-cluster-core-development, host=x.x.x.x, user=dbcoredevu01,txIsolation=3, autocommit=true, schema=db-cluster-core-development]

INSERT INTO Task (`articleId`, `taskStatus`, `taskType`, `lastSubId`, `createTime`) VALUES ('1296', '1', '0', '13', '2016-06-01 16:47:10');
UPDATE  Task set taskStatus = 1 where taskId = 1 

err:java.lang.ClassCastException: com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlUpdateStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement
java.lang.ClassCastException: com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlUpdateStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement
        at io.mycat.route.util.RouterUtil.processERChildTable(RouterUtil.java:1602) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:95) ~[Mycat-server-1.6.5-release.jar:?]

**Comment by JefferyZh** [comment]
这个问题有解决吗？我是1.6.6.1，先insert 再select 也报这个MySql.Data.MySqlClient.MySqlException : com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement

**Comment by JefferyZh** [comment]
``` 
2019-02-19 15:38:37.108  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:296)) - ServerConnection [id=2, schema=*, host=*, user=root,txIsolation=3, autocommit=true, schema=*, executeSql=insert into regionconvserver(server_enable,server_errmsg,server_errtime,server_ip,server_order,server_port,server_regionid,server_remark,server_status,server_trynum,server_type,server_actiontime) values(1,'',NULL,'172.19.0.3',0,'',1,'',1,10,'pc',NULL); select @@identity]insert into regionconvserver(server_enable,server_errmsg,server_errtime,server_ip,server_order,server_port,server_regionid,server_remark,server_status,server_trynum,server_type,server_actiontime) values(1,'',NULL,'172.19.0.3',0,'',1,'',1,10,'pc',NULL); select @@identity err:java.lang.ClassCastException: com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement
java.lang.ClassCastException: com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement
	at io.mycat.route.util.RouterUtil.processERChildTable(RouterUtil.java:1602) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:96) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:36) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:138) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:291) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:237) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:149) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:375) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:395) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:551) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:533) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:201) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.6.1-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by codeyung** [comment]
> 这个问题有解决吗？我用的mycat1.6.6.1，先insert 再select 也报这个MySql.Data.MySqlClient.MySqlException : com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement，但是这个问题只在客户端（.net core 2.1用MySql.Data 8.0.12操作数据库）才会出现，直接把sql在navicat里可以正常执行
> @magicdoom

我都把语句改成InsertOrUpdate了 
还有select有的时候确实会为null 返回对象判断一下 。这个可能是mycat同步的问题 。
我1.5 1.6都有select为null的时候

**Comment by JiaoFu1973** [comment]
> 这个问题有解决吗？我用的mycat1.6.6.1，先insert 再select 也报这个MySql.Data.MySqlClient.MySqlException : com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement，但是这个问题只在客户端（.net core 2.1用MySql.Data 8.0.12操作数据库）才会出现，直接把sql在navicat里可以正常执行
> @magicdoom

这个问题您最好解决了吗

**Comment by codeyung** [comment]
> > 这个问题有解决吗？我用的mycat1.6.6.1，先insert 再select 也报这个MySql.Data.MySqlClient.MySqlException : com.alibaba.druid.sql.ast.statement.SQLSelectStatement cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlInsertStatement，但是这个问题只在客户端（.net core 2.1用MySql.Data 8.0.12操作数据库）才会出现，直接把sql在navicat里可以正常执行
> > @magicdoom
> 
> 这个问题您最好解决了吗

2年了 后面我记得是升级了一个小的release版本就没出现了
