### ISSUE TITLE
DataGrip 连接 Mycat 报错

### ISSUE THREAD

**Issue by ztcaoll222** [MyCATApache/Mycat-Server#1853]
DataGrip 版本: 2018.1.3
Mycat 版本: 1.6.5

DataGrip 的 log:
java.lang.IllegalStateException: Cannot open cursor: the statement was not executed or it has not returned cursor.
  at org.jetbrains.dekaf.jdbc.JdbcIntermediateSeance.openDefaultCursor(JdbcIntermediateSeance.java:132)
  at org.jetbrains.dekaf.jdbc.JdbcIntermediateSimpleSeance.openCursor(JdbcIntermediateSimpleSeance.java:40)
  at org.jetbrains.dekaf.jdbc.JdbcIntermediateSimpleSeance.openCursor(JdbcIntermediateSimpleSeance.java:14)
  at com.intellij.database.remote.jdba.impl.RemoteSeanceImpl.openCursor(RemoteSeanceImpl.java:37)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
  at sun.rmi.transport.Transport$1.run(Transport.java:200)
  at sun.rmi.transport.Transport$1.run(Transport.java:197)
  at java.security.AccessController.doPrivileged(Native Method)
  at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
  at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
  at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
  at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
  at java.security.AccessController.doPrivileged(Native Method)
  at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
  at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
  at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
  at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
  at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
  at com.sun.proxy.$Proxy135.openCursor(Unknown Source)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:179)
  at com.intellij.execution.rmi.RemoteUtil.access$300(RemoteUtil.java:39)
  at com.intellij.execution.rmi.RemoteUtil$RemoteInvocationHandler.invoke(RemoteUtil.java:275)
  at com.sun.proxy.$Proxy136.openCursor(Unknown Source)
  at org.jetbrains.dekaf.intermediate.AdaptIntermediateSeance.openCursor(AdaptIntermediateSeance.java:51)
  at org.jetbrains.dekaf.core.BaseQueryRunner.run(BaseQueryRunner.java:74)
  at com.intellij.database.introspection.MysqlIntrospector.introspectNamespacesInTran(MysqlIntrospector.kt:116)
  at com.intellij.database.introspection.BaseIntrospector$introspectNamespaces$$inlined$inTransactionUnit$1.run(BaseIntrospector.kt:638)
  at org.jetbrains.dekaf.core.BaseSession.inTransaction(BaseSession.java:88)
  at org.jetbrains.dekaf.core.BaseFacade$2.run(BaseFacade.java:93)
  at org.jetbrains.dekaf.core.BaseFacade.inSession(BaseFacade.java:125)
  at org.jetbrains.dekaf.core.BaseFacade.inTransaction(BaseFacade.java:89)
  at com.intellij.database.introspection.BaseIntrospector.introspectNamespaces(BaseIntrospector.kt:646)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.introspectDatabaseList(DatabaseModelLoader.java:450)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$null$2(DatabaseModelLoader.java:301)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.withFacade(DatabaseModelLoader.java:533)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$introspect$3(DatabaseModelLoader.java:294)
  at com.intellij.database.dataSource.DataSourceSyncManager.lambda$null$0(DataSourceSyncManager.java:41)
  at com.intellij.database.dataSource.DatabaseConnectionManager$Executor.perform(DatabaseConnectionManager.java:363)
  at com.intellij.database.dataSource.DatabaseConnectionManager$Executor.lambda$sync$2(DatabaseConnectionManager.java:302)
  at com.intellij.database.dataSource.AsyncUtil.withAsyncFriendly(AsyncUtil.java:161)
  at com.intellij.database.dataSource.DatabaseConnectionManager$Executor.sync(DatabaseConnectionManager.java:298)
  at com.intellij.database.dataSource.DatabaseConnectionManager$Builder.sync(DatabaseConnectionManager.java:112)
  at com.intellij.database.dataSource.DataSourceSyncManager.lambda$static$1(DataSourceSyncManager.java:40)
  at com.intellij.database.dataSource.DataSourceSyncManager$SyncProcessor$1.perform(DataSourceSyncManager.java:268)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.introspect(DatabaseModelLoader.java:291)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$run$0(DatabaseModelLoader.java:271)
  at com.intellij.database.dataSource.LocalDataSource.performBatch(LocalDataSource.java:1192)
  at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.run(DatabaseModelLoader.java:269)
  at com.intellij.database.dataSource.DataSourceSyncManager$SyncProcessor.performSync(DataSourceSyncManager.java:270)
  at com.intellij.database.dataSource.AsyncUtil.lambda$null$6(AsyncUtil.java:58)
  at com.intellij.database.dataSource.AsyncUtil.lambda$underProgress$14(AsyncUtil.java:130)
  at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
  at com.intellij.database.dataSource.AsyncUtil.underProgress(AsyncUtil.java:136)
  at com.intellij.database.dataSource.AsyncUtil.underProgress(AsyncUtil.java:130)
  at com.intellij.database.dataSource.AsyncUtil.lambda$captureIndicator$7(AsyncUtil.java:58)
  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
  at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745) (no stack trace).
Cannot open cursor: the statement was not executed or it has not returned cursor.

Mycat 的 log:
2018-05-21 16:37:48.465  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:514)) - close connection,reason:quit cmd ,ServerConnection [id=6, schema=null, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=null]

btw: Navicat 11.0.10 没问题

**Comment by Evangelione** [comment]
+1 
还没有解决？？

**Comment by davelet** [comment]
+1
btw: Navicat  没问题

**Comment by hrenxiang** [comment]
有什么解决办法吗

**Comment by smallodd** [comment]
+10086 还没解决？

**Comment by smallodd** [comment]
ε=(´ο｀*)))唉 貌似是加上数据库名称就好了

**Comment by xueshuai0922** [comment]
我现在也是这样的问题 坑呀
