### ISSUE TITLE
分库一个节点异常影响其他节点正常使用

### ISSUE THREAD

**Issue by kfwang90** [MyCATApache/Mycat-Server#1860]
- 最近在虚拟机研究mycat+postgresql结合进行数据库分库，配置为1个mycat，2个pg节点。
- 经测试分库功能OK，但是发现一个问题，当我停掉一个pg节点后，再次从mycat执行sql，有很大几率会失败，但偶尔会有成功，把debug日志打开后，发现每次执行sql时都会执行一个SHOW STATUS的语句到每个节点，好像是为了检测节点状态，但是检测到第二个节点的时候就报错了，所以反馈给前端就是失败。不过有意思的是其实我查询的语句并不是要去第二个节点执行，分库规则应该去查第一个节点就行的。
异常信息如下，那位大神遇到过这个问题吗？
2018-05-31 16:43:49,918 [DEBUG][$_NIOREACTOR-3-RW] select read source master for dataHost:db2_host  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:456) 
2018-05-31 16:43:49,929 [WARN ][BusinessExecutor0] set txisolation error: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:823)
	at io.mycat.backend.jdbc.JDBCConnection.syncIsolation(JDBCConnection.java:278)
	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:294)
	at io.mycat.backend.jdbc.JDBCConnection.access$0(JDBCConnection.java:284)
	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:768)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 (io.mycat.backend.jdbc.JDBCConnection:JDBCConnection.java:281)

**Comment by ustcqb** [comment]
mycat也不修复bug，也不出新版本，搞个QQ群还要收费加入，开源的精神都丢了，mycat迟早被淘汰

**Comment by lazio579** [comment]
加入我们 https://github.com/Lede-Inc/cetus
