### ISSUE TITLE
mycat查询表时报错

### ISSUE THREAD

**Issue by jumprn** [MyCATApache/Mycat-Server#1878]
2018-06-13 21:00:33.012  WARN [$_NIOREACTOR-1-RW] (io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:500)) -  find no Route:SELECT st.* FROM performance_schema.events_stages_history_long st WHERE st.nesting_event_id = 0
2018-06-13 21:00:33.012  WARN [$_NIOREACTOR-1-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:285)) - ServerConnection [id=2, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test]SELECT st.* FROM performance_schema.events_stages_history_long st WHERE st.nesting_event_id = 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT st.* FROM performance_schema.events_stages_history_long st WHERE st.nesting_event_id = 0
java.sql.SQLNonTransientException:  find no Route:SELECT st.* FROM performance_schema.events_stages_history_long st WHERE st.nesting_event_id = 0
	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:501) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:350) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.directRoute(DruidMycatRouteStrategy.java:387) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:199) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:138) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:277) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:226) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:324) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:344) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:500) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:482) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.5-release.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by jumprn** [comment]
插入没报错，但是在底层mysql查询不到数据，通过mycat可以查询到，但是几次查询的结果都不完整且都不一样
