### ISSUE TITLE
mysql8.0.11登陆mycat1.6.5报密码错误，但是用户密码配置无问题

### ISSUE THREAD

**Issue by 258357754qq** [MyCATApache/Mycat-Server#1898]
将mycat部署完成之后，处于正常运行的状态下，使用mysql8.0.11客户端版本登陆mycat，经过多次登陆访问，都是无法访问，提示密码错误（Access denied for user 'user', because password is error）。
 mysql -uuser -puser -h127.0.0.1 -P3306 
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (HY000): Access denied for user 'user', because password is error
mysql --version
mysql  Ver 8.0.11 for linux-glibc2.12 on x86_64 (MySQL Community Server - GPL)

后将mysql更换为5.7.20，能够正常访问mycat1.6.5版本
mysql -uuser -puser -h127.0.0.1 -P3306 
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1015
Server version: 5.6.29-mycat-1.6.5-release-20180122220033 MyCat Server (OpenCloundDB)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
mysql  --version
mysql  Ver 14.14 Distrib 5.7.20, for linux-glibc2.12 (x86_64) using  EditLine wrapper
初步验证是由于MYSQL在8.0.4的版本中，将数据库用户的默认认证机制变更为“caching_sha2_password”

**Comment by 258357754qq** [comment]
这是由于mycat1.6.5仅支持mysql_native_password认证，而8.0.11的客户端连接mycat1.6.5使用"caching_sha2_password"机制。

**Comment by SQkaer** [comment]
我将mysql8.0的登入改回了mysql_native_password，还是不成功

**Comment by SQkaer** [comment]
还是报Access denied for user 'user', because password is error

**Comment by chutian52** [comment]
@SQkaer MyCat貌似还不支持，最高5.7

**Comment by chutian52** [comment]
@SQkaer thanks a lot.

**Comment by 1314520huang** [comment]
@SQkaer 
![image](https://user-images.githubusercontent.com/19749400/55055116-09710480-509d-11e9-9caf-f8752aca5b42.png)
![image](https://user-images.githubusercontent.com/19749400/55055169-29a0c380-509d-11e9-935a-0a2898d5b693.png)


![image](https://user-images.githubusercontent.com/19749400/55055154-24dc0f80-509d-11e9-88a9-3db70ecdfeb6.png)
最近也正在学习mycat，然后也是遇到了楼主同样的报错问题，mysql8.0.13已经把mysql.ini的登录方式改为mysql-native-password了。不行，之后在登录手动指明，现在还是无法登录

**Comment by SQkaer** [comment]
@1314520huang 你可以试一试先登入mysql，然后
ALTER USER 'root'@'localhost'
  IDENTIFIED WITH mysql_native_password
  BY 'password';
改成你的password，
然后再试一试用指定--default-auth=mysql_native_password登入

**Comment by 1314520huang** [comment]
@SQkaer 嗯嗯，谢谢啦，不过已经把MySQL将为5.7.22，现在是正常的，8.0的话，要等之后再去处理一下了

**Comment by Pancat007** [comment]
> @1314520huang 你可以试一试先登入mysql，然后
> ALTER USER 'root'@'localhost'
> IDENTIFIED WITH mysql_native_password
> BY 'password';
> 改成你的password，
> 然后再试一试用指定--default-auth=mysql_native_password登入

还是不行，同 @1314520huang 还有其他解决方法吗？

**Comment by COCL666** [comment]
同问，mysql -uroot -p123456 -h127.0.0.1 -P8066 --default-auth=mysql_native_password
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (HY000): Access denied for user 'root', because password is error
用以上方法处理后mycat1.6.5仍报错，mysql1.6.6.1虽然可以进入但是不能执行sql语句，会报连接未建立的错误，求解决。

**Comment by jetli123** [comment]
我的mycat 1.6.5 版本，换了mysql-connector-java-8.0.22.jar 驱动，可以连接MySQL8.0.22 ，但是java 应用程序，使用mysql-connector-java-8.0.22.jar 连不上mycat，请问怎么解决

**Comment by jetli123** [comment]
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
        at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:180)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at com.smartfoxserver.v2.db.SFSDBManager.getConnection(SFSDBManager.java:58)
        at com.smartfoxserver.v2.db.SFSDBManager.executeQuery(SFSDBManager.java:72)
        at com.smartfoxserver.v2.db.SFSDBManager.executeQuery(SFSDBManager.java:62)
        at com.smartfoxserver.v2.db.SFSDBManager.testSQLStatement(SFSDBManager.java:231)
        at com.smartfoxserver.v2.db.SFSDBManager.init(SFSDBManager.java:33)
        at com.im30.ls.utils.SFSMysql.initGlobalDBManager(SFSMysql.java:598)
        at com.im30.ls.utils.SFSMysql.init(SFSMysql.java:48)
        at com.im30.ls.core.ServiceEngine.init(ServiceEngine.java:66)
        at com.im30.ls.core.MainServer.initService(MainServer.java:76)
        at com.im30.ls.core.MainServer.start(MainServer.java:63)
        at com.im30.ls.core.MainServer.main(MainServer.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
        at com.install4j.runtime.launcher.Launcher.main(Unknown Source)

**Comment by ygqygq2** [comment]
相同的命令 8.0 客户端死活不行，一换 5.7 客户端就好使。各种配置过了，没用。
```
mysql -uroot -p123456 -hXXXXXX -P 8066 --default-auth=mysql_native_password
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 5.6.29-mycat-1.6-RELEASE-20161028204710 MyCat Server (OpenCloundDB)
```
