### ISSUE TITLE
出现大量事务回滚，分表数据保存失败

### ISSUE THREAD

**Issue by 437865981** [MyCATApache/Mycat-Server#1951]
Caused by: java.sql.SQLException: Transaction error, need to rollback. errno:1023 stream closed
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)org.springframework.orm.hibernate4.HibernateJdbcJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1003]; could not execute statement; nested exception is is org.hibernate.excepti
on.
ti
on.GenericJDBCExBCException: could not execute statement
        at at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernbernateAccessException(on(SessionFactoryUtils.java:170)
  )
        at at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(Hib(te(HibernateTemplate.java:344)
  )
        at at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNathNativeSession(on(HibernateTemplate.java:309)
  )
        at at org.springframework.orm.hibernate4.HibernateTemplate.save(HibernateTemplate.java:618)
  )
        at at top.hb.common.baseclass.AbstractBaseDAO.save(HibernateTemplate.java:618)
  )
这仅仅是个查询然后保存的逻辑，先从一张表查询统计数据，然后插入另一张表，为什么会频繁的出现这个报错呀。

**Comment by zwyqz** [comment]
mycat报错日志贴下

**Comment by WERNERWAN1** [comment]
运行时异常了，事务要回滚，堵塞了。不知道解决了吗？
