### ISSUE TITLE
紧急求助，mycat创建完最小连接后，出现register err java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by likanghai** [MyCATApache/Mycat-Server#1977]
如题，启动日志如下
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,107 [INFO ][$_NIOREACTOR-1-RW] connected successfuly MySQLConnection [id=9, lastTime=1535221598107, user=root, schema=safecity, old shema=safecity, borrowed=true, fromSlaveDB=false, threadId=210, charset=latin1, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.10.100.134, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.backend.mysql.nio.handler.GetConnectionHandler:GetConnectionHandler.java:67) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,107 [INFO ][$_NIOREACTOR-2-RW] connected successfuly MySQLConnection [id=6, lastTime=1535221598107, user=root, schema=safecity, old shema=safecity, borrowed=true, fromSlaveDB=false, threadId=208, charset=latin1, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.10.100.134, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.backend.mysql.nio.handler.GetConnectionHandler:GetConnectionHandler.java:67) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,107 [INFO ][$_NIOREACTOR-0-RW] connected successfuly MySQLConnection [id=8, lastTime=1535221598107, user=root, schema=safecity, old shema=safecity, borrowed=true, fromSlaveDB=false, threadId=203, charset=latin1, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.10.100.134, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.backend.mysql.nio.handler.GetConnectionHandler:GetConnectionHandler.java:67) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,107 [INFO ][$_NIOREACTOR-2-RW] connected successfuly MySQLConnection [id=10, lastTime=1535221598107, user=root, schema=safecity, old shema=safecity, borrowed=true, fromSlaveDB=false, threadId=211, charset=latin1, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.10.100.134, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]  (io.mycat.backend.mysql.nio.handler.GetConnectionHandler:GetConnectionHandler.java:67) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,139 [INFO ][WrapperSimpleAppMain] init result :finished 10 success 10 target count:10  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:319) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | 2018-08-26 02:26:38,139 [INFO ][WrapperSimpleAppMain] dk index:0 init success  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:265) 
INFO   | jvm 1    | 2018/08/26 02:26:38 | MyCAT Server startup successfully. see logs in logs/mycat.log
INFO   | jvm 1    | 2018/08/26 02:26:39 | 2018-08-26 02:26:39,620 [ERROR][$_NIOREACTOR-3-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2018/08/26 02:26:39 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2018/08/26 02:26:39 | 2018-08-26 02:26:39,683 [ERROR][$_NIOREACTOR-0-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2018/08/26 02:26:39 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2018/08/26 02:26:39 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
服务器是CENTOS7.2的系统，对此问题着实不解，希望有大神来指点一下

**Comment by Fxdemon** [comment]
BUG 
修复因前端连接register失败导致bytebuffer泄露的bug
中间件版本： MyCat-Server-1.6.4-RELEASE
问题描述：https://github.com/MyCATApache/Mycat-Server/issues/1616
