### ISSUE TITLE
err:java.lang.IllegalArgumentException: columnValue:sysdate() Please check if the format satisfied.

### ISSUE THREAD

**Issue by tw1202** [MyCATApache/Mycat-Server#1982]
分表字段created_time 里面用的sysdate  报错了，求指导
java.lang.IllegalArgumentException: columnValue:sysdate() Please check if the format satisfied.
	at io.mycat.route.function.PartitionByMonth.calculate(PartitionByMonth.java:100) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:1368) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1165) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1026) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.directRoute(DruidMycatRouteStrategy.java:412) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:199) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:138) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:277) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:226) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:324) ~[Mycat-server-1.6.5-release.jar:?]

**Comment by nchuxyz** [comment]
您是insert的时候使用了sysdate()函数吗？

**Comment by tw1202** [comment]
@nchuxyz  对的   mycat支持sysdate函数吗？   now支持吗？

**Comment by nchuxyz** [comment]
等下给您加上对now()和sysdate()的支持哈

**Comment by tw1202** [comment]
@nchuxyz  哥  大哥 什么意思啊 等下加上？

**Comment by nchuxyz** [comment]
暂不支持
