### ISSUE TITLE
mycat load data 数据报错

### ISSUE THREAD

**Issue by wuqiu-ai** [MyCATApache/Mycat-Server#2008]
2018-09-20 18:46:45.431  INFO [$_NIOREACTOR-3-RW] (com.dxy.mycat.net.AbstractConnection.write(AbstractConnection.java:450)) - connId:3 queue size:47213
--
2018-09-20 18:46:45.441 DEBUG [$_NIOREACTOR-7-RW] (com.dxy.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:59)) - caught err:
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270) ~[?:1.8.0_181]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461) ~[?:1.8.0_181]
	at com.dxy.mycat.net.NIOSocketWR.write0(NIOSocketWR.java:100) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:43) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.AbstractConnection.write(AbstractConnection.java:466) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.mysql.BinaryPacket.write(BinaryPacket.java:74) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.LoadDataUtil.writeToBackConnection(LoadDataUtil.java:98) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.LoadDataUtil.requestFileDataResponse(LoadDataUtil.java:54) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.requestDataResponse(MultiNodeQueryHandler.java:866) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRequestPacket(MySQLConnectionHandler.java:180) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:102) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:81) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.AbstractConnection.handle(AbstractConnection.java:273) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:331) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:197) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:283) ~[dxy-mycat.jar:?]
	at com.dxy.mycat.net.NIOReactor$RW.run(NIOReactor.java:114) ~[dxy-mycat.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by zhoujianjun** [comment]
你这个异常是在哪个版本出现的？

**Comment by ppj19891020** [comment]
最新版1.6.5版本

**Comment by xmmxjy** [comment]
我也出现了这个问题，有解决吗
