### ISSUE TITLE
not authorized for query

### ISSUE THREAD

**Issue by ighack** [MyCATApache/Mycat-Server#2052]
this is my schema.xml
```
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">

		<!-- global table is auto cloned to all defined data nodes ,so can join
			with any table whose sharding node is in the same data node -->
		<table name="ratings" primaryKey="_id" type="global" dataNode="dn1" />
		
	</schema>
	<!-- <dataNode name="dn1$0-743" dataHost="localhost1" database="db$0-743"
		/> -->
	<dataNode name="dn1" dataHost="mongodbHost" database="joint" />
	
	<!--<dataNode name="dn4" dataHost="sequoiadb1" database="SAMPLE" />
	 <dataNode name="jdbc_dn1" dataHost="jdbchost" database="db1" />
	<dataNode	name="jdbc_dn2" dataHost="jdbchost" database="db2" />
	<dataNode name="jdbc_dn3" 	dataHost="jdbchost" database="db3" /> -->
	<dataHost name="mongodbHost" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="monogdb" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
		<heartbeat></heartbeat>
		<!-- can have multi write hosts -->
		<writeHost host="mongodbHostr" url="mongodb://10.3.87.54:27017/" user="jzt" password="123456">
			<!-- can have multi read hosts -->
			<readHost host="mongodbHostw" url="mongodb://10.3.87.54:27017/" user="jzt" password="123456" />
		</writeHost>
		
		<!-- <writeHost host="hostM2" url="localhost:3316" user="root" password="123456"/> -->
	</dataHost>
	<!--
		<dataHost name="sequoiadb1" maxCon="1000" minCon="1" balance="0" dbType="sequoiadb" dbDriver="jdbc">
		<heartbeat> 		</heartbeat>
		 <writeHost host="hostM1" url="sequoiadb://1426587161.dbaas.sequoialab.net:11920/SAMPLE" user="jifeng" 	password="jifeng"></writeHost>
		 </dataHost>

	  <dataHost name="oracle1" maxCon="1000" minCon="1" balance="0" writeType="0" 	dbType="oracle" dbDriver="jdbc"> <heartbeat>select 1 from dual</heartbeat>
		<connectionInitSql>alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'</connectionInitSql>
		<writeHost host="hostM1" url="jdbc:oracle:thin:@127.0.0.1:1521:nange" user="base" 	password="123456" > </writeHost> </dataHost>

		<dataHost name="jdbchost" maxCon="1000" 	minCon="1" balance="0" writeType="0" dbType="mongodb" dbDriver="jdbc">
		<heartbeat>select 	user()</heartbeat>
		<writeHost host="hostM" url="mongodb://192.168.0.99/test" user="admin" password="123456" ></writeHost> </dataHost>

		<dataHost name="sparksql" maxCon="1000" minCon="1" balance="0" dbType="spark" dbDriver="jdbc">
		<heartbeat> </heartbeat>
		 <writeHost host="hostM1" url="jdbc:hive2://feng01:10000" user="jifeng" 	password="jifeng"></writeHost> </dataHost> -->

	<!-- <dataHost name="jdbchost" maxCon="1000" minCon="10" balance="0" dbType="mysql"
		dbDriver="jdbc"> <heartbeat>select user()</heartbeat> <writeHost host="hostM1"
		url="jdbc:mysql://localhost:3306" user="root" password="123456"> </writeHost>
		</dataHost> -->
</mycat:schema>
```

I get a error
[SQL]select * from ratings

[Err] 1105 - not authorized for query on joint.ratings

in mycat.log

> FROM ratings
LIMIT 100}, headerOutputed=false, modifiedSQLExecuted=false, startTime=1541656768491, lastTime=1541657145115, isSpark=false, processor=io.mycat.net.NIOProcessor@3496bc3a] frontend host:127.0.0.1/5265/root
2018-11-08 14:05:46.089 ERROR [BusinessExecutor7] (io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:343)) - sql execute error, not authorized for query on joint.ratings
com.mongodb.MongoException: not authorized for query on joint.ratings
	at com.mongodb.MongoException.parse(MongoException.java:82) ~[mongo-java-driver-2.11.4.jar:?]
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:292) ~[mongo-java-driver-2.11.4.jar:?]
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273) ~[mongo-java-driver-2.11.4.jar:?]
	at com.mongodb.DBCursor._check(DBCursor.java:368) ~[mongo-java-driver-2.11.4.jar:?]
	at com.mongodb.DBCursor._hasNext(DBCursor.java:459) ~[mongo-java-driver-2.11.4.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:484) ~[mongo-java-driver-2.11.4.jar:?]
	at io.mycat.backend.jdbc.mongodb.MongoResultSet.<init>(MongoResultSet.java:71) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.backend.jdbc.mongodb.MongoStatement.executeQuery(MongoStatement.java:71) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.ouputResultSet(JDBCConnection.java:626) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:318) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.access$000(JDBCConnection.java:33) ~[Mycat-server-1.6.6.1-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:781) ~[Mycat-server-1.6.6.1-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2018-11-08 14:05:46.089  WARN [BusinessExecutor7] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.backConnectionErr(SingleNodeHandler.java:267)) - execute  sql err : errno:1105 not authorized for query on joint.ratings con:JDBCConnection [id=2,autocommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@72bbe908, schema=joint, dbType=MONOGDB, oldSc

**Comment by ighack** [comment]
什么时候mongodb支持用户名和密码
