### ISSUE TITLE
MyCat表名无法使用'$'关键字

### ISSUE THREAD

**Issue by livejava** [MyCATApache/Mycat-Server#2054]
现在有个场景设计mysql数据库时，所有表名带了 '$' 关键字

[例] 创建表 trade$kline ，表名中有 '$' 关键字，使用Mycat分表，配置schema.xml片段

```
<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100"  >
    <table name="trade$order_turnover" primaryKey="id" autoIncrement="true"  subTables="trade$order_turnover$1-10"  dataNode="dn1" rule="mod-long"  >
    </table>
</schema>
```

启动Mycat失败，查看错误日志，报错数字转换异常，给'$'加了\转义符号，还是报这个错误。
```
Caused by: java.lang.NumberFormatException: For input string: "order_turnover"
 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 	at java.lang.Integer.parseInt(Integer.java:580)
 	at java.lang.Integer.parseInt(Integer.java:615)
 	at io.mycat.util.SplitUtil.split(SplitUtil.java:232)
 	at io.mycat.util.SplitUtil.split(SplitUtil.java:263)
 	at io.mycat.util.SplitUtil.split(SplitUtil.java:252)
 	at io.mycat.config.model.TableConfig.<init>(TableConfig.java:98)
 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:387)
 	at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:173)
 	at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:122)
```

**Comment by zwyqz** [comment]
由于mycat的分表使用的table$1-4,使用了关键字 导致的报错

**Comment by livejava** [comment]
因为业务出去设计的时候，所以表名使用了＄符号，程序要改动的地方太多，请问怎么可以优化这个bug

**Comment by zwyqz** [comment]
需要修改吗 需要的话我这两天改下~

**Comment by livejava** [comment]
紧急需要用呢，麻烦您了

**Comment by zwyqz** [comment]
表名在druid解析的时候会因为$解析不正确,最好是应用程序修改 或者看下新改的druid分支能否支持~
![image](https://user-images.githubusercontent.com/4454612/48684833-8a4f5980-ebee-11e8-96d2-3661397be948.png)
修改上面代码即可

**Comment by livejava** [comment]
好的，谢谢，因为程序设计近100张表使用了$关键字，粗略看了下， 程序有上千处需要更改，期待新改的druid分支。
