### ISSUE TITLE
register err java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by mengma1** [MyCATApache/Mycat-Server#2061]
2018-11-18 10:32:30,936 [DEBUG][$_NIOREACTOR-2-RW] caught err: java.io.IOException: Connection reset by peer
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.IOUtil.write(IOUtil.java:51)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOSocketWR.write0(NIOSocketWR.java:98)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:42)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.AbstractConnection.write(AbstractConnection.java:447)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.mysql.HandshakePacket.write(HandshakePacket.java:110)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.FrontendConnection.register(FrontendConnection.java:441)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2018/11/18 10:32:30 |  (io.mycat.net.NIOSocketWR:NIOSocketWR.java:58)
INFO   | jvm 1    | 2018/11/18 10:32:30 | 2018-11-18 10:32:30,936 [ERROR][$_NIOREACTOR-2-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2018/11/18 10:32:30 |       at java.lang.Thread.run(Thread.java:745)

**Comment by zwyqz** [comment]
网络问题？
