### ISSUE TITLE
心跳检测报"Too many connections"

### ISSUE THREAD

**Issue by dengly** [MyCATApache/Mycat-Server#2094]
今天Mycat报了以下错误，看了错误信息和相关代码。原因是因为心跳检测是通过直接创建新的连接来检测的，而创建的时候没有检测是否达到最大连接数。所以就报了这个错误。
```
2018-12-18 20:36:36.188 ERROR io.mycat.backend.jdbc.JDBCHeartbeat - JDBCHeartBeat error
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
      at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
      at com.mysql.jdbc.Util.getInstance(Util.java:372)
      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:958)
      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1037)
      at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2239)
      at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
      at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
      at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
      at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
      at java.sql.DriverManager.getConnection(DriverManager.java:664)
      at java.sql.DriverManager.getConnection(DriverManager.java:247)
      at io.mycat.backend.jdbc.JDBCDatasource.getConnection(JDBCDatasource.java:115)
      at io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:99)
      at io.mycat.backend.datasource.PhysicalDatasource.doHeartbeat(PhysicalDatasource.java:458)
      at io.mycat.backend.datasource.PhysicalDBPool.doHeartbeat(PhysicalDBPool.java:459)
      at io.mycat.MycatServer$8$1.run(MycatServer.java:971)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```

**Comment by Fxdemon** [comment]
应该是JDBC心跳的BUG  已经修改了 你查看一下历史问题
