### ISSUE TITLE
按照mycat _in_action 第一次插入 insert into orders(id,customer_id) values(2,2); 报错

### ISSUE THREAD

**Issue by luotianwen** [MyCATApache/Mycat-Server#211]
04/07 17:40:45.112   WARN [$_NIOREACTOR-2-RW] (ServerConnection.java:170) -ServerConnection [id=7, schema=TESTDB, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=TESTDB]insert into orders(id,customer_id) values(2,2) err:java.sql.SQLNonTransientException: can't find (root) parent sharding node for sql:INSERT INTO orders (id, customer_id)
VALUES (2, 2)
java.sql.SQLNonTransientException: can't find (root) parent sharding node for sql:INSERT INTO orders (id, customer_id)
VALUES (2, 2)
	at org.opencloudb.parser.druid.impl.DruidInsertParser.parserChildTable(DruidInsertParser.java:138)
	at org.opencloudb.parser.druid.impl.DruidInsertParser.statementParse(DruidInsertParser.java:50)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:60)
	at org.opencloudb.route.impl.DruidMysqlRouteStrategy.routeNormalSqlWithAST(DruidMysqlRouteStrategy.java:40)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:52)
	at org.opencloudb.route.RouteService.route(RouteService.java:118)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:162)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:263)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:56)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:370)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:264)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:97)
	at java.lang.Thread.run(Thread.java:722)
04/07 17:40:45.114   WARN [$_NIOREACTOR-2-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:194)
	at org.opencloudb.net.NIOSocketWR.register(NIOSocketWR.java:27)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:154)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:722)

**Comment by yygymmmmsee** [comment]
我按照步骤来做时，到这一步时，也报同样的异常，配置都是默认的

**Comment by songwie** [comment]
测试发现1.3.0.3不存在这个问题

**Comment by waj89757** [comment]
这个原因应该是customer表没有customer_id=2这条记录～

**Comment by yygymmmmsee** [comment]
今天重新执行了以下插入操作，又没问题了，不知道楼主是否也是这样

**Comment by luotianwen** [comment]
嗯 第二次执行 就没问题

**Comment by mycatmerger** [comment]
建议虚机和单核不用使用父子表配置，可以通过配置相同分片规则来解决
