### ISSUE TITLE
4核8g压测cpu到280%多，是正常的么？

### ISSUE THREAD

**Issue by lzg553665176** [MyCATApache/Mycat-Server#2129]
我压测的mycat是4核8g。压测2000RPS读 mycat的cpu高到280%多，都比后端mysql的cpu还高。按道理mycat只是负责转发，不应该那么高！
配置是
{
		"value": "8",
		"name": "processors"
	}, {
		"value": "16",
		"name": "processorExecutor"
	}, 
参数也调了，没多大用！

**Comment by lzg553665176** [comment]
版本是1.6.6 release

**Comment by lzg553665176** [comment]
再补充一下：压测是短连接，长连接达到5000RPS才开始出现TIME_WAIT积压，cpu才100%左右

**Comment by lzg553665176** [comment]
自己再补充吧
"$_NIOREACTOR-4-RW" #35 prio=5 os_prio=0 tid=0x00007faecc8a5000 nid=0x8a2b runnable [0x00007fae29fcc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000803da6b8> (a sun.nio.ch.Util$3)
	- locked <0x00000000803da6a8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000008030d308> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:94)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOREACTOR-3-RW" #34 prio=5 os_prio=0 tid=0x00007faecc88a800 nid=0x8a2a runnable [0x00007fae2a0cd000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000802da910> (a sun.nio.ch.Util$3)
	- locked <0x00000000802da900> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000801ecb50> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:94)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOREACTOR-2-RW" #33 prio=5 os_prio=0 tid=0x00007faecc86f800 nid=0x8a29 runnable [0x00007fae2a1ce000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
