### ISSUE TITLE
mycat 使用连接池连接过程中，通过jdbc执行load data以后，执行类似update语句，出现长时间卡死

### ISSUE THREAD

**Issue by limingbonc** [MyCATApache/Mycat-Server#2159]
程序中需要将文件数据load data进Mysql，之后会有部分更新语句，在执行更新语句的时候，
长时间阻塞卡死，报错如下
 | 2019/03/30 19:32:23 | 2019-03-30 19:32:23,022  DEBUG [com.bonc.ads.sqlengine.SQLJob] con query sql:select user() to con:MySQLConnection [id=112, lastTime=1553945543022, user=clyx_app_mycat, schema=clyx_app_sms_qinghai, old shema=clyx_app_gd_ningxia, borrowed=true, fromSlaveDB=false, threadId=64899441, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.162.156.100, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
INFO   | jvm 1    | 2019/03/30 19:32:23 | 2019-03-30 19:32:23,022  DEBUG [com.bonc.ads.backend.mysql.nio.MySQLConnection] con need syn ,total syn cmd 1 commands schema change:true con:MySQLConnection [id=112, lastTime=1553945543022, user=clyx_app_mycat, schema=clyx_app_sms_qinghai, old shema=clyx_app_gd_ningxia, borrowed=true, fromSlaveDB=false, threadId=64899441, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=clyx_app_sms_qinghai,sql=select user(),  jobHandler=com.bonc.ads.sqlengine.OneRawSQLQueryResultHandler@42b0d33], host=10.162.156.100, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
INFO   | jvm 1    | 2019/03/30 19:32:23 | 2019-03-30 19:32:23,022  DEBUG [com.bonc.ads.sqlengine.SQLJob] con query sql:select user() to con:MySQLConnection [id=81, lastTime=1553945543022, user=clyx_app_sms, schema=clyx_app_sms_qinghai, old shema=clyx_app_sms_qinghai, borrowed=true, fromSlaveDB=false, threadId=64891207, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.162.156.100, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
INFO   | jvm 1    | 2019/03/30 19:32:23 | 2019-03-30 19:32:23,022  DEBUG [com.bonc.ads.backend.datasource.PhysicalDatasource] release channel MySQLConnection [id=112, lastTime=1553945543014, user=clyx_app_mycat, schema=clyx_app_sms_qinghai, old shema=clyx_app_sms_qinghai, borrowed=true, fromSlaveDB=false, threadId=64899441, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.162.156.100, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
INFO   | jvm 1    | 2019/03/30 19:32:23 | 2019-03-30 19:32:23,022  DEBUG [com.bonc.ads.backend.datasource.PhysicalDatasource] release channel MySQLConnection [id=81, lastTime=1553945543014, user=clyx_app_sms, schema=clyx_app_sms_qinghai, old shema=clyx_app_sms_qinghai, borrowed=true, fromSlaveDB=false, threadId=64891207, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.162.156.100, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,694  WARN [NIOProcessor] found backend connection SQL timeout ,close it MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=SingleNodeHandler [node=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, packetId=0], host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true]
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,695  INFO [com.bonc.ads.net.AbstractConnection] close connection,reason:sql timeout ,MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=SingleNodeHandler [node=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, packetId=0], host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true]
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,695  WARN [com.bonc.ads.backend.mysql.nio.handler.SingleNodeHandler] execute  sql err : errno:1023 sql timeout con:MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=SingleNodeHandler [node=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, packetId=1], host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true] frontend host:10.162.16.117/43747/test
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,769  DEBUG [com.bonc.ads.net.FrontendConnection] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=false, schema=ORDERDB20] rollback
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,769  DEBUG [com.bonc.ads.server.ServerQueryHandler] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=false, schema=ORDERDB20]rollback
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,771  ERROR [com.bonc.ads.backend.mysql.nio.handler.RollbackNodeHandler] MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=null, host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true]receive rollback,but fond backend con is closed or quit
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,771  DEBUG [com.bonc.ads.backend.mysql.nio.handler.RollbackNodeHandler] rollback job run for MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=null, host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true]
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,771  DEBUG [com.bonc.ads.net.AbstractConnection] caught err:
INFO   | jvm 1    | 2019/03/30 19:32:28 | java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:479)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.NIOSocketWR.write0(NIOSocketWR.java:98)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:42)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.AbstractConnection.write(AbstractConnection.java:446)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.mysql.CommandPacket.write(CommandPacket.java:122)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.backend.mysql.nio.MySQLConnection.rollback(MySQLConnection.java:548)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.backend.mysql.nio.handler.RollbackNodeHandler.rollback(RollbackNodeHandler.java:84)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.server.NonBlockingSession.rollback(NonBlockingSession.java:257)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.server.ServerConnection.rollback(ServerConnection.java:327)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.server.ServerQueryHandler.query(ServerQueryHandler.java:106)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.FrontendConnection.handle(FrontendConnection.java:460)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.AbstractConnection.onReadData(AbstractConnection.java:320)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.AbstractConnection.asynRead(AbstractConnection.java:272)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at com.bonc.ads.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,772  DEBUG [com.bonc.ads.net.FrontendConnection] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=false, schema=ORDERDB20] SET autocommit=1
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,772  DEBUG [com.bonc.ads.server.ServerQueryHandler] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=false, schema=ORDERDB20]SET autocommit=1
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,772  ERROR [com.bonc.ads.backend.mysql.nio.handler.CommitNodeHandler] MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=com.bonc.ads.backend.mysql.nio.handler.CommitNodeHandler@514e2278, host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=0, modifiedSQLExecuted=true]receive commit,but fond backend con is closed or quit
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,784  DEBUG [com.bonc.ads.net.FrontendConnection] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20] select user()
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,784  DEBUG [com.bonc.ads.server.ServerQueryHandler] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20]select user()
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,785  DEBUG [com.bonc.ads.net.FrontendConnection] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20] SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,785  DEBUG [com.bonc.ads.server.ServerQueryHandler] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20]SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,785  DEBUG [com.bonc.ads.cache.impl.EnchachePool] SQLRouteCache  miss cache ,key:ORDERDB20SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.cache.impl.EnchachePool] SQLRouteCache add cache ,key:ORDERDB20SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193 value:SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193, route={
INFO   | jvm 1    | 2019/03/30 19:32:28 |    1 -> 107-dn-clyx_app_gd_zb{SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193}
INFO   | jvm 1    | 2019/03/30 19:32:28 | }
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.server.NonBlockingSession] ServerConnection [id=115, schema=ORDERDB20, host=10.162.16.117, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20]SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193, route={
INFO   | jvm 1    | 2019/03/30 19:32:28 |    1 -> 107-dn-clyx_app_gd_zb{SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193}
INFO   | jvm 1    | 2019/03/30 19:32:28 | } rrs 
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.backend.mysql.nio.handler.SingleNodeHandler] rrs.getRunOnSlave() null
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.backend.mysql.nio.handler.SingleNodeHandler] node.getRunOnSlave() null
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.server.NonBlockingSession] found connections in session to use MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{UPDATE PLT_ACTIVITY_PROCESS_LOG
INFO   | jvm 1    | 2019/03/30 19:32:28 | SET   BLACK_FILTER_AMOUNT='0'
INFO   | jvm 1    | 2019/03/30 19:32:28 | WHERE ( ACTIVITY_SEQ_ID='181193' and TENANT_ID='uni099' and CHANNEL_ID='1' and ACTIVITY_ID='49902')}, respHandler=com.bonc.ads.backend.mysql.nio.handler.CommitNodeHandler@514e2278, host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=1, modifiedSQLExecuted=true] for 107-dn-clyx_app_gd_zb{SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193}
INFO   | jvm 1    | 2019/03/30 19:32:28 | 2019-03-30 19:32:28,786  DEBUG [com.bonc.ads.backend.mysql.nio.MySQLConnection] con need syn ,total syn cmd 1 commands SET autocommit=1;schema change:false con:MySQLConnection [id=25, lastTime=1553944668254, user=test, schema=clyx_app_gd_zb, old shema=clyx_app_gd_zb, borrowed=true, fromSlaveDB=false, threadId=8, charset=utf8, txIsolation=3, autocommit=false, attachment=107-dn-clyx_app_gd_zb{SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193}, respHandler=SingleNodeHandler [node=107-dn-clyx_app_gd_zb{SELECT MAX(REC_ID) AS MAX,MIN(REC_ID) AS MIN,COUNT(1) AS ROW FROM PLT_ORDER_INFO_TEMP WHERE TENANT_ID = 'uni099'  AND ACTIVITY_SEQ_ID = 181193}, packetId=0], host=10.162.156.107, port=8066, statusSync=com.bonc.ads.backend.mysql.nio.MySQLConnection$StatusSync@266f9168, writeQueue=1, modifiedSQLExecuted=true]
INFO   | jvm 1    | 2019/03/30 19:32:30 | 2019-03-30 19:32:30,000  DEBUG [com.bonc.ads.net.FrontendConnection] ServerConnection [id=5, schema=ORDERDB20, host=10.162.16.119, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20] select * from TENANT_INFO where STATE='1'
INFO   | jvm 1    | 2019/03/30 19:32:30 | 2019-03-30 19:32:30,000  DEBUG [com.bonc.ads.server.ServerQueryHandler] ServerConnection [id=5, schema=ORDERDB20, host=10.162.16.119, user=test,txIsolation=3, autocommit=true, schema=ORDERDB20]select * from TENANT_INFO where STATE='1'
INFO   | jvm 1    | 2019/03/30 19:32:30 | 2019-03-30 19:32:30,000  DEBUG [com.bonc.ads.cache.impl.EnchachePool] SQLRouteCache hit cache ,key:ORDERDB20select * from TENANT_INFO where STATE='1'
INFO   | jvm 1    | 2019/03/30 19:32:30 | 2019-03-30 19:32:30,001  DEBUG [com.bonc.ads.server.NonBlockingSession] ServerConnection [id=5, schema=ORDERDB20, host=10.162.16.119, user=test,txIsolation=3, auto

**Comment by limingbonc** [comment]
按修改了  usingAIO=1,和设置mutiNodeLimitType =0 均无效

**Comment by limingbonc** [comment]
由于线上着急解决问题，就遇到这种路由更新语句，单独调用JDBC不走mycat的连接池方式，暂时性处理了这个问题
