### ISSUE TITLE
在childTable 里面定义了 needAddLimit 报错

### ISSUE THREAD

**Issue by difeijin** [MyCATApache/Mycat-Server#2218]
INFO   | jvm 1    | 2019/06/04 16:03:12 | Caused by: org.xml.sax.SAXParseException; lineNumber: 51; columnNumber: 177; Attribute "needaddLimit" must be declared for element type "childTable".
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1253)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:763)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at io.mycat.config.util.ConfigUtil.getDocument(ConfigUtil.java:115)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:111)
INFO   | jvm 1    | 2019/06/04 16:03:12 |       ... 13 more

**Comment by junwen12221** [comment]
fix
