### ISSUE TITLE
db2不能 使用like  concat(concat('%','a'),'%')  根据limit 10 会报错

### ISSUE THREAD

**Issue by 419861036** [MyCATApache/Mycat-Server#2250]
[id=1, schema=xxxx, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=bp_user_db, executeSql=select * from auth_app where app_name  LIKE  concat(concat('%','a'),'%')  limit 1]select * from auth_app where app_name  LIKE  concat(concat('%','a'),'%')  limit 1 err:
         com.alibaba.druid.sql.parser.ParserException: ERROR. token : CONCAT, pos : 51 
        com.alibaba.druid.sql.parser.ParserException: ERROR. token : CONCAT, pos : 51
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:587)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:120)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:157)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1246)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1274)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1152)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1166)
	at com.alibaba.druid.sql.parser.SQLExprParser.relationalRest(SQLExprParser.java:1428)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:111)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:100)
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:527)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:247)
	at com.alibaba.druid.sql.dialect.db2.parser.DB2SelectParser.query(DB2SelectParser.java:77)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:1874)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:183)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)

**Comment by junwen12221** [comment]
这个比较麻烦了，你看看使用1.66-druid这个分支的mycat源码能否解决这个问题
