### ISSUE TITLE
navcat 12.1.9 连接1.6时 多次点击运行按钮 程序报错 连接不能关闭

### ISSUE THREAD

**Issue by 419861036** [MyCATApache/Mycat-Server#2251]
Exception in thread "BusinessExecutor38" java.lang.NullPointerException
	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:344)
	at io.mycat.backend.jdbc.JDBCConnection.access$0(JDBCConnection.java:285)
	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:781)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by junwen12221** [comment]
用新的版本看看

**Comment by chenziwucodeing** [comment]
哪个版本稳定？
