### ISSUE TITLE
mycat自定义分片规则重启后报错 NoSuchMethodError -- AbstractPartitionAlgorithm.suitableFor

### ISSUE THREAD

**Issue by Sunyelw** [MyCATApache/Mycat-Server#2266]
环境：win10
版本：mycat-3.2.3

我自己写了一个类来实现自己的分片规则,打成jar包放到 `lib`文件下后重启mycat,报错如下:

```
INFO   | wrapper  | 2019/07/31 22:09:36 | Waiting to start...
INFO   | jvm 1    | 2019/07/31 22:09:39 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2019/07/31 22:09:39 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2019/07/31 22:09:39 |
INFO   | wrapper  | 2019/07/31 22:09:41 | Waiting to start...
INFO   | jvm 1    | 2019/07/31 22:09:41 |
INFO   | jvm 1    | 2019/07/31 22:09:41 | WrapperSimpleApp: Encountered an error running main: java.lang.NoSuchMethodError: io.mycat.route.function.AbstractPartitionAlgorithm.suitableFor(Lio/mycat/config/model/TableConfig;)I
INFO   | jvm 1    | 2019/07/31 22:09:41 | java.lang.NoSuchMethodError: io.mycat.route.function.AbstractPartitionAlgorithm.suitableFor(Lio/mycat/config/model/TableConfig;)I
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.checkRuleSuitTable(XMLSchemaLoader.java:563)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.loadTables(XMLSchemaLoader.java:396)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.loadSchemas(XMLSchemaLoader.java:168)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.load(XMLSchemaLoader.java:117)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:78)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.loader.xml.XMLSchemaLoader.<init>(XMLSchemaLoader.java:82)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:76)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.MycatServer.<init>(MycatServer.java:166)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.MycatServer.<clinit>(MycatServer.java:109)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/07/31 22:09:41 |       at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/07/31 22:09:43 | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
STATUS | wrapper  | 2019/07/31 22:09:44 | <-- Wrapper Stopped
ERROR  | wrapper  | 2019/07/31 22:09:45 | The Mycat-server service was launched, but failed to start.
```

下面是我的具体代码与配置:

HyRuleHashHandle.java
```
package io.mycat.route.function;

import io.mycat.config.rule.RuleAlgorithm;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * 创建时间:   2019/7/25 15:42
 */
@EqualsAndHashCode(callSuper = true)
@Data
@Slf4j
public class HyRuleHashHandle extends AbstractPartitionAlgorithm implements RuleAlgorithm {

    private final static String SUB_LENGTH = "sub-length";
    private final static String SUB_LIST = "sub-list";
    private final static String SUB_SUFFIX = "sub-mod";
    private final static String SPLIT = ",";

    // 配置文件名称
    private String mapFile;
    // 分区个数
    private String count;
    // 截取字段长度
    private Integer subLength;
    // 默认节点
    private Integer defaultNode = -1;

    // 分区具体配置
    private List<SubConfig> configs = new ArrayList <>();

    private Map<Object, Integer> app2Partition;

    @Override
    public void init(){
        // 配置文件转换
        doInit();
    }

    // 实际处理
    @Override
    public Integer calculate(String columnValue){

        Integer node = 0;
        int partition;
        String subString = columnValue.substring(0, subLength);
        for (SubConfig sub : configs) {
            if (sub.value.equals(subString)) {
                partition = getPartition(sub, columnValue);
                return node + partition;
            }
            node += sub.size;
        }
        return null;
    }

    /* other functions */

    @Override
    public Integer[] calculateRange(String beginValue, String endValue){
        Integer begin, end;
        begin = calculateStart(beginValue);
        end = calculateEnd(endValue);

        if ((begin == null) || (end == null)) {
            return new Integer[0];
        }

        if (end >= begin) {
            int len = end - begin + 1;
            Integer[] re = new Integer[len];

            for (int i = 0; i < len; i++) {
                re[i] = begin + i;
            }

            return re;
        }
        return null;
    }


    private Integer calculateStart(String columnValue) {
        int nodeIndex = 0;
        for (SubConfig stringRang : this.configs) {
            if (columnValue.substring(0, this.subLength).equals(stringRang.value)) {
                return nodeIndex;
            }

            nodeIndex += stringRang.size;
        }

        if (this.defaultNode >= 0) {
            return this.defaultNode;
        }
        return null;
    }
    private Integer calculateEnd(String columnValue) {
        int nodeIndex = 0;
        for (SubConfig stringRang : this.configs) {
            if (columnValue.substring(0, this.subLength).equals(stringRang.value)) {
                return nodeIndex + stringRang.size - 1;
            }
            nodeIndex += stringRang.size;
        }

        if (this.defaultNode >= 0) {
            return this.defaultNode;
        }
        return null;
    }
    
    @Override
    public int getPartitionNum(){
        SubConfig config = this.configs.get(0);
        return config.size * this.configs.size();
    }

    // 获取正确的分区
    private Integer getPartition(SubConfig subConfig, String columnValue) {
        int lg = (int) Math.abs(((long) columnValue.substring(subLength).hashCode() % 10000L));
        List<Integer> indexList = subConfig.indexList;
        for (int i = 0; i < indexList.size(); i++) {
            if (lg <= indexList.get(i)) {
                return i;
            }
        }
        return defaultNode;
    }

    /**
     * 初始化，读取配置文件
     *
     */
    private void doInit() {
        InputStream ins = null;
        try {
            ins = getClass().getClassLoader().getResourceAsStream(this.mapFile);
            if (ins == null) {
                throw new RuntimeException("can't find class resource file " + this.mapFile);
            }
            Properties po = new Properties();
            po.load(ins);
            // 拿到子字符串前缀长度
            this.subLength = Integer.valueOf(po.getProperty(SUB_LENGTH)); // 4
            String subList = po.getProperty(SUB_LIST);
            String[] subArr = null == subList ? null : subList.split(SPLIT); // 110U 119U 120U
            if (null == subArr) {
                throw new RuntimeException("sub-list is illegal -> ");
            }

            String indexes;
            List<Integer> indexList = new ArrayList <>();
            indexes = po.getProperty(SUB_SUFFIX);
            if (null == indexes) {
                throw new RuntimeException("sub-mod is illegal -> " + SUB_SUFFIX);
            }
            // 存储每个分区所需的范围
            for (String index : indexes.split(SPLIT)) {
                indexList.add(Integer.valueOf(index));
            }
            for (String sub : subArr) {
                this.configs.add(new SubConfig(indexes.length(), sub, indexList));
            }
        } catch (Exception e) {
            log.error("hy_error_hy_file_read_error: {}", e.getMessage(), e);
        } finally {
            try {
                if (null != ins) ins.close();
            } catch (IOException e) {
                log.error("hy_error_close_error: {}", e.getMessage(), e);
            }
        }
    }

    /**
     * 每个分区属性配置
     */
    static class SubConfig{
        // 分区所配节点数
        int size;
        // 分区关键字
        String value;
        // 分区节点分配规则
        List<Integer> indexList;

        SubConfig(int size, String value, List<Integer> indexList) {
            this.value = value;
            this.size = size;
            this.indexList = indexList;
        }
    }

    public static void main(String[] args){

        HyRuleHashHandle hashHandle = new HyRuleHashHandle();

    }
}

```
mycat 相关配置:
rule.xml
```
<tableRule name="rule-hy-name">
	<rule>
		<columns>name</columns>
		<algorithm>sharding-by-name</algorithm>
	</rule>
</tableRule>
<function name="sharding-by-name" class="io.mycat.route.function.HyRuleHashHandle">
	<property name="mapFile">hy.file</property>
</function>
```
schema.xml
```
<schema name="db" checkSQLschema="false" sqlMaxLimit="100">
	<table name="cat" primaryKey="id" dataNode="dn$10-12,dn$13-15,dn$16-18" rule="rule-hy-name" />
</schema>

<dataNode name="dn10" dataHost="localhost1" database="ddcat0" />
<dataNode name="dn11" dataHost="localhost1" database="ddcat1" />
<dataNode name="dn12" dataHost="localhost1" database="ddcat2" />
<dataNode name="dn13" dataHost="localhost1" database="ddcat3" />
<dataNode name="dn14" dataHost="localhost1" database="ddcat4" />
<dataNode name="dn15" dataHost="localhost1" database="ddcat5" />
<dataNode name="dn16" dataHost="localhost1" database="ddcat6" />
<dataNode name="dn17" dataHost="localhost1" database="ddcat7" />
<dataNode name="dn18" dataHost="localhost1" database="ddcat8" />
```
hy.file
```
sub-length=4
sub-list=xxxx,yyyy,zzzz
sub-mod=3333,6666,9999

```

cat table:
```
create table cat(
	id int(11) not null auto_increment comment 'primary key',
	name varchar(255) comment 'sharding column',
	primary key(id)
)Engine=Innodb DEFAULT CHARSET=UTF8 COMMENT='for test mycat';
```

有什么好的建议吗? thx all！

**Comment by junwen12221** [comment]
怀疑与lombok注解有关

**Comment by Sunyelw** [comment]
把lombok的注解依赖全去掉了，也是一样的报错。

**Comment by Sunyelw** [comment]
代码目录结构：
![](https://user-images.githubusercontent.com/31758533/62255420-b1be1d80-b42f-11e9-9d5b-5b110b4ee5db.png)

AbstractPartitionAlgorithm.java
```
package io.mycat.route.function;


import io.mycat.config.TableConfig;
import io.mycat.config.rule.RuleAlgorithm;

import java.io.Serializable;
import java.util.List;

/**
 * 路由分片函数抽象类
 * 为了实现一个默认的支持范围分片的函数 calcualteRange
 * 重写它以实现自己的范围路由规则
 * @author lxy
 *
 */
public abstract class AbstractPartitionAlgorithm implements RuleAlgorithm, Serializable {

	@Override
	public void init() {
	}

	/**
	 * 返回所有被路由到的节点的编号
	 * 返回长度为0的数组表示所有节点都被路由（默认）
	 * 返回null表示没有节点被路由到
	 */
	@Override
	public Integer[] calculateRange(String beginValue, String endValue)  {
		return new Integer[0];
	}
	
	/**
	 * 对于存储数据按顺序存放的字段做范围路由，可以使用这个函数
	 * @param algorithm
	 * @param beginValue
	 * @param endValue
	 * @return
	 */
	public static Integer[] calculateSequenceRange(AbstractPartitionAlgorithm algorithm, String beginValue, String endValue)  {
		Integer begin = 0, end = 0;
		begin = algorithm.calculate(beginValue);
		end = algorithm.calculate(endValue);

		if(begin == null || end == null){
			return new Integer[0];
		}
		
		if (end >= begin) {
			int len = end-begin+1;
			Integer [] re = new Integer[len];
			
			for(int i =0;i<len;i++){
				re[i]=begin+i;
			}
			
			return re;
		}else{
			return new Integer[0];
		}
	}
	
	/**
	 * 
	 * 分片表所跨的节点数与分片算法分区数一致性校验
	 * @param tableConf
	 * @return 
	 * -1 if table datanode size < rule function partition size
	 * 0 if table datanode size == rule function partition size
	 * 1 if table datanode size > rule function partition size
	 */
	public final int suitableFor(TableConfig tableConf) {
		int nPartition = getPartitionNum();
		if(nPartition > 0) { // 对于有限制分区数的规则,进行检查
			int dnSize = tableConf.getDataNodes().size();
			boolean  distTable = tableConf.isDistTable();
			List tables = tableConf.getDistTables();
			if(distTable){
				if(tables.size() < nPartition){
					return  -1;
				} else if(dnSize > nPartition) {
					return 1;
				}
			}else{
				if(dnSize < nPartition) {
					return  -1;
				} else if(dnSize > nPartition) {
					return 1;
				}
			}
		}
		return 0;
	}
	
	/**
	 * 返回分区数, 返回-1表示分区数没有限制
	 * @return
	 */
	public int getPartitionNum() {
		return -1; // 表示没有限制
	}
	
}

```

**Comment by Sunyelw** [comment]
![](https://user-images.githubusercontent.com/31758533/62256007-41fd6200-b432-11e9-9d33-171d9791cb9a.png)

I have resolved my problem....

是文件目录的问题。

自定义规则时一定要严格按照原来的目录结构开发！
自定义规则时一定要严格按照原来的目录结构开发！
自定义规则时一定要严格按照原来的目录结构开发！

嗯，谢谢楼上帮助我的大大。@junwen12221
