### ISSUE TITLE
err:java.lang.NullPointerException

### ISSUE THREAD

**Issue by xxx1204** [MyCATApache/Mycat-Server#2270]
Mycat-server-1.6.6.1-release-20181031195535-linux
mysql5.7.25
centos7.5
执行如下sql报错
UPDATE orgdb.dept
INNER JOIN ( select a.id aid,a.no ano,a.parent_id apid,b.id bid from orgdb.dept a ,orgdb.dept b
where a.parent_id= b.`no`) c ON orgdb.dept.id = c.aid 
SET parent_id= c.bid 

2019-08-09 08:48:34.549  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:296)) - ServerConnection [id=220, schema=orgdb, host=127.0.0.1, user=pec,txIsolation=3, autocommit=true, schema=orgdb, executeSql=UPDATE orgdb.dept
INNER JOIN ( select a.id aid,a.no ano,a.parent_id apid,b.id bid from orgdb.dept a ,orgdb.dept b
where a.parent_id= b.`no`) c ON orgdb.dept.id = c.aid
SET parent_id= c.bid]UPDATE orgdb.dept
INNER JOIN ( select a.id aid,a.no ano,a.parent_id apid,b.id bid from orgdb.dept a ,orgdb.dept b
where a.parent_id= b.`no`) c ON orgdb.dept.id = c.aid
SET parent_id= c.bid err:java.lang.NullPointerException
java.lang.NullPointerException
        at io.mycat.route.parser.druid.impl.DruidUpdateParser.statementParse(DruidUpdateParser.java:33) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:76) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:122) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.RouteService.route(RouteService.java:138) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:291) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:237) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:149) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:375) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:395) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:551) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:533) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:201) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.6.1-release.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by junwen12221** [comment]
应该是不支持这种sql
