### ISSUE TITLE
Mycat-server-1.3.0.3-alpha-20150211194835-win.tar bad insert sql (sharding column:ID not provided,INSERT INTO Sale (version, pid, cdate, creator) VALUES (0, 2, '2015-04-23', 1)

### ISSUE THREAD

**Issue by luotianwen** [MyCATApache/Mycat-Server#229]
<table name="sale" dataNode="dn1"  primaryKey="ID"  rule="auto-sharding-long" />

bad insert sql (sharding column:ID not provided,INSERT INTO Sale (version, pid, cdate, creator)
VALUES (0, 2, '2015-04-23', 1)

**Comment by luotianwen** [comment]
<table name="sale" dataNode="dn1"  primaryKey="ID"  rule="auto-sharding-long" />

**Comment by luotianwen** [comment]
id为自动增长的

**Comment by luotianwen** [comment]
WARN [$_NIOREACTOR-2-RW] (DruidInsertParser.java:171) -bad insert sql (sharding column:ID not provided,INSERT INTO `sale` (`pid`, `cdate`)
VALUES ('3', '2015-04-11 20:58:22')
04/11 21:05:48.947   WARN [$_NIOREACTOR-2-RW] (ServerConnection.java:170) -ServerConnection [id=7, schema=mycat, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=mycat]INSERT INTO `sale` (`pid`, `cdate`) VALUES ('3', '2015-04-11 20:58:22') err:java.sql.SQLNonTransientException: bad insert sql (sharding column:ID not provided,INSERT INTO `sale` (`pid`, `cdate`)
VALUES ('3', '2015-04-11 20:58:22')
java.sql.SQLNonTransientException: bad insert sql (sharding column:ID not provided,INSERT INTO `sale` (`pid`, `cdate`)
VALUES ('3', '2015-04-11 20:58:22')
	at org.opencloudb.parser.druid.impl.DruidInsertParser.parserSingleInsert(DruidInsertParser.java:172)
	at org.opencloudb.parser.druid.impl.DruidInsertParser.statementParse(DruidInsertParser.java:69)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:60)
	at org.opencloudb.route.impl.DruidMysqlRouteStrategy.routeNormalSqlWithAST(DruidMysqlRouteStrategy.java:40)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:52)
	at org.opencloudb.route.RouteService.route(RouteService.java:118)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:162)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:263)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:56)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:370)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:264)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:97)
	at java.lang.Thread.run(Thread.java:722)

**Comment by stonelion** [comment]
分片的列，ID没有插入语句提供。查rule.xml，配置下分片列。
