### ISSUE TITLE
mycat1.6.5版本单库分表不能联查的问题

### ISSUE THREAD

**Issue by 314926481** [MyCATApache/Mycat-Server#2298]
我的schema.xml配置如下，使用范围分片
![image](https://user-images.githubusercontent.com/48713296/64224911-d5cbbd80-cf0b-11e9-87d9-9057bf6b7bcd.png)
使用数据库方式的全局Id
<property name="sequnceHandlerType">1</property>
下面是分了6张表
![image](https://user-images.githubusercontent.com/48713296/64224970-057ac580-cf0c-11e9-97da-1a57084e5141.png)

下面是我查询的SQL语句
SELECT
			cc.id AS custId,
			cc.nickName,
			ca.custName,
			ca.checkPhone,
			ca.idCard,
			cc.mobilePhone,
			cc.isRealName,
			case when cc.password is null or cc.password='' then '0' else '1' end
		    isPassWord
		FROM
			cust_customer cc
		LEFT JOIN cust_customer_check ca ON ca.custId = cc.id
		WHERE cc.id  = '1100111424'

报如下错误：
 1054 - Unknown column 'cc.id' in 'field list'
通过查看mycat的debug日志发现在解析时变成了下面的SQL方式
![image](https://user-images.githubusercontent.com/48713296/64225078-71f5c480-cf0c-11e9-9e96-12315daf1786.png)

如果使用/*!mycat:catlet=demo.catlets.ShareJoin */注解的方式查询会报如下错误：
1064 - java.lang.ClassNotFoundException: demo.catlets.ShareJoin
2019-09-04 12:07:49.464  WARN [$_NIOREACTOR-11-RW] (io.mycat.route.handler.HintCatletHandler.route(HintCatletHandler.java:57)) - catlet error java.lang.ClassNotFoundException: demo.catlets.ShareJoin
2019-09-04 12:07:49.464  WARN [$_NIOREACTOR-11-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:285)) - ServerConnection [id=1, schema=icity1, host=10.200.108.67, user=root,txIsolation=3, autocommit=true, schema=icity1]/*!mycat:catlet=demo.catlets.ShareJoin */SELECT
			cc.id AS custId,
			cc.nickName,
			ca.custName,
			ca.checkPhone,
			ca.idCard,
			cc.mobilePhone,
			cc.isRealName,
			case when cc.password is null or cc.password='' then '0' else '1' end
		    isPassWord
		FROM
			cust_customer cc
		LEFT JOIN cust_customer_check ca ON ca.custId = cc.id
		WHERE cc.id  = '1100111424' err:java.sql.SQLNonTransientException: java.lang.ClassNotFoundException: demo.catlets.ShareJoin
java.sql.SQLNonTransientException: java.lang.ClassNotFoundException: demo.catlets.ShareJoin
	at io.mycat.route.handler.HintCatletHandler.route(HintCatletHandler.java:58) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:124) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:277) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:226) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:324) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:344) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:500) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:482) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.5-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: demo.catlets.ShareJoin
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at io.mycat.config.classloader.DynaClassLoader$MyDynaClassLoader.loadClass(DynaClassLoader.java:141) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.config.classloader.DynaClassLoader.getInstanceofClass(DynaClassLoader.java:45) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.route.handler.HintCatletHandler.route(HintCatletHandler.java:52) ~[Mycat-server-1.6.5-release.jar:?]
	... 15 more

希望能够得到回复，谢谢！

**Comment by zwyqz** [comment]
check设置为全局表

**Comment by 314926481** [comment]
> check设置为全局表

check更换成全局表后也是报一样的错
1054 - Unknown column 'cc.id' in 'field list'
