### ISSUE TITLE
springmvc+mybatis+mycat 事务无法回滚

### ISSUE THREAD

**Issue by swwheihei** [MyCATApache/Mycat-Server#2308]
版本：Mycat 1.6-release，Springmvc 4.3.6，Mybatis 3.2.6，Mysql 5.7
问题：项目使用springmvc+mybatis+mycat+mysql进行多租户管理，在操作数据库时使用@Transactional时，事务无效，无法回滚。相同代码直连mysql时，事务生效。

项目分为controller、service、dao三层，controller层未捕获该异常，@Transactional注解加载service层，代码片段如下：
@Transactional
public void insertDbgl(Dbgl dbgl) {
	dbglMapper.insertDbgl(dbgl);
	String str = null;
	str.toString();
}

依次尝试以下方法，均无效。
1、@Transactional加在类上
2、改为@Transactional(propagation=Propagation.REQUIRED)
3、Mysql autocommit=0

mycat配置文件server.xml中handleDistributedTransactions=0，是这个配置文件的问题吗？
不胜感激。

**Comment by swwheihei** [comment]
是否需要将mycat设置为autocommit=0？

**Comment by swwheihei** [comment]
查看日志，spring也走事务控制并rollback了。
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

**Comment by swwheihei** [comment]
handleDistributedTransactions参数、autocommit各种组合都试了一遍

**Comment by swwheihei** [comment]
springboot 1.5.4 ，mybatis3.3.1纯净项目，事务依旧无效。mysql直连可以，mycat就不行

**Comment by swwheihei** [comment]
问题解决，解决方式：
1、升级最新版mycat 1.6.7.3
2、修改server.xml中参数handleDistributedTransactions = 0，strictTxIsolation=true

**Comment by swwheihei** [comment]
更好的解决方式：
/!mycat:sql方式注解，注解SQL需与实际SQL操作类型一致，是SELECT则都是SELECT，是INSERT则mycat:sql也用INSERT。MYCAT为提高性能，如果是SELECT操作则不会保持session，导致rollbcak操作无效化。

**Comment by wf0206** [comment]
@swwheihei  更好的解决方式：
/!mycat:sql方式注解，注解SQL需与实际SQL操作类型一致，是SELECT则都是SELECT，是INSERT则mycat:sql也用INSERT。MYCAT为提高性能，如果是SELECT操作则不会保持session，导致rollbcak操作无效化。
你这个更好的解决方式是什么意思 没太懂
