### ISSUE TITLE
mysql5.8 sequence db global seq is not unsupported in jdbc driver yet 

### ISSUE THREAD

**Issue by kiddlovemoon** [MyCATApache/Mycat-Server#2319]
2019-09-29 10:55:47,510 [ERROR][SequenceExecutor1] {} java.lang.UnsupportedOperationException: global seq is not unsupported in jdbc driver yet 
	at io.mycat.backend.jdbc.JDBCConnection.query(JDBCConnection.java:727)
	at io.mycat.route.sequence.handler.FetchMySQLSequnceHandler.connectionAcquired(IncrSequenceMySQLHandler.java:222)
	at io.mycat.backend.datasource.PhysicalDatasource.takeCon(PhysicalDatasource.java:490)
	at io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:537)
	at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:140)
	at io.mycat.route.sequence.handler.FetchMySQLSequnceHandler.execute(IncrSequenceMySQLHandler.java:200)
	at io.mycat.route.sequence.handler.SequenceVal.waitFinish(IncrSequenceMySQLHandler.java:378)
	at io.mycat.route.sequence.handler.SequenceVal.waitFinish(IncrSequenceMySQLHandler.java:406)
	at io.mycat.route.sequence.handler.SequenceVal.waitFinish(IncrSequenceMySQLHandler.java:406)
	at io.mycat.route.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:154)
	at io.mycat.route.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:96)
	at io.mycat.route.parser.druid.DruidSequenceHandler.getExecuteSql(DruidSequenceHandler.java:85)
	at io.mycat.route.MyCATSequnceProcessor.executeSeq(MyCATSequnceProcessor.java:51)
	at io.mycat.route.util.RouterUtil$1.run(RouterUtil.java:569)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by junwen12221** [comment]
mysql datasource must be mysql native,or you can add this function by youself

**Comment by junwen12221** [comment]
https://blog.csdn.net/qq_31183071/article/details/102673959
