### ISSUE TITLE
mycat使用JDBC连接postgresql报如下异常

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#232]
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 20 ms ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
请问是啥问题？1.4-dev版本，直接从master check的代码

mysql驱动使用的是 5.1.6

发现是：SHOW COLLATION 这个命令执行时候报错了。

**Comment by zhouwenbin2000** [comment]
换了mysql JDBC驱动，5.1.34，可以了。但是mysql JDBC 5.1.6 不行。对比了下，两个驱动在连接服务器时候，5.1.34，少发了show collation命名。 因此可以正常执行。

**Comment by stonelion** [comment]
关闭掉把。

**Comment by zhouwenbin2000** [comment]
这个需要解决吧。不然其他的版本不支持。

**Comment by mycatmerger** [comment]
建议通过使用新版驱动解决
