### ISSUE TITLE
帮忙看看这个原因 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by rubyvirus** [MyCATApache/Mycat-Server#2341]
Mycat version: 1.6.6.1

wrapper log info:

INFO   | jvm 1    | 2019/10/29 17:28:42 | Exception in thread "Timer0" 
INFO   | jvm 1    | 2019/10/29 17:29:14 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.util.Arrays.copyOf(Arrays.java:3332)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.StringBuilder.append(StringBuilder.java:136)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.server.ServerConnection.toString(ServerConnection.java:414)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.net.AbstractConnection.idleCheck(AbstractConnection.java:537)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.net.NIOProcessor.frontendCheck(NIOProcessor.java:182)
INFO   | jvm 1    | 2019/10/29 17:30:08 | 
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at io.mycat.net.NIOProcessor.checkFrontCons(NIOProcessor.java:156)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at io.mycat.MycatServer$6$2.run(MycatServer.java:876)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:10 | Exception in thread "$_NIOREACTOR-32-RW" Exception in thread "$_NIOREACTOR-46-RW" java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:10 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | Oct 29, 2019 5:27:08 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
INFO   | jvm 1    | 2019/10/29 17:35:26 | SEVERE: Exception processing: 7250 org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapper@65159896
INFO   | jvm 1    | 2019/10/29 17:35:26 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.StringCoding.encode(StringCoding.java:344)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.String.getBytes(String.java:918)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 
INFO   | jvm 1    | 2019/10/29 17:35:26 | Exception in thread "Log4j2-AsyncLoggerConfig-1" java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:27 | Caused by: java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.StringCoding.encode(StringCoding.java:344)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.String.getBytes(String.java:918)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	... 3 more

**Comment by rubyvirus** [comment]
> Mycat version: 1.6.6.1
> 
> wrapper log info:
> 
> INFO | jvm 1 | 2019/10/29 17:28:42 | Exception in thread "Timer0"
> INFO | jvm 1 | 2019/10/29 17:29:14 | java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:29:36 | at java.util.Arrays.copyOf(Arrays.java:3332)
> INFO | jvm 1 | 2019/10/29 17:29:36 | at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
> INFO | jvm 1 | 2019/10/29 17:29:36 | at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
> INFO | jvm 1 | 2019/10/29 17:29:36 | at java.lang.StringBuilder.append(StringBuilder.java:136)
> INFO | jvm 1 | 2019/10/29 17:30:02 | at io.mycat.server.ServerConnection.toString(ServerConnection.java:414)
> INFO | jvm 1 | 2019/10/29 17:30:02 |
> INFO | jvm 1 | 2019/10/29 17:30:02 | at io.mycat.net.AbstractConnection.idleCheck(AbstractConnection.java:537)
> INFO | jvm 1 | 2019/10/29 17:30:02 | at io.mycat.net.NIOProcessor.frontendCheck(NIOProcessor.java:182)
> INFO | jvm 1 | 2019/10/29 17:30:08 |
> INFO | jvm 1 | 2019/10/29 17:30:38 | at io.mycat.net.NIOProcessor.checkFrontCons(NIOProcessor.java:156)
> INFO | jvm 1 | 2019/10/29 17:30:38 | at io.mycat.MycatServer$6$2.run(MycatServer.java:876)
> INFO | jvm 1 | 2019/10/29 17:30:38 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> INFO | jvm 1 | 2019/10/29 17:30:38 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> INFO | jvm 1 | 2019/10/29 17:30:38 | at java.lang.Thread.run(Thread.java:748)
> INFO | jvm 1 | 2019/10/29 17:35:10 | Exception in thread "$_NIOREACTOR-32-RW" Exception in thread "$_NIOREACTOR-46-RW" java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:35:10 | java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:35:26 | Oct 29, 2019 5:27:08 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
> INFO | jvm 1 | 2019/10/29 17:35:26 | SEVERE: Exception processing: 7250 org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapper@65159896
> INFO | jvm 1 | 2019/10/29 17:35:26 | java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.lang.StringCoding.encode(StringCoding.java:344)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.lang.String.getBytes(String.java:918)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at java.lang.Thread.run(Thread.java:748)
> INFO | jvm 1 | 2019/10/29 17:35:26 |
> INFO | jvm 1 | 2019/10/29 17:35:26 | Exception in thread "Log4j2-AsyncLoggerConfig-1" java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:35:26 | at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
> INFO | jvm 1 | 2019/10/29 17:35:26 | at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:148)
> INFO | jvm 1 | 2019/10/29 17:35:27 |
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.lang.Thread.run(Thread.java:748)
> INFO | jvm 1 | 2019/10/29 17:35:27 | Caused by: java.lang.OutOfMemoryError: Java heap space
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.lang.StringCoding.encode(StringCoding.java:344)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at java.lang.String.getBytes(String.java:918)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
> INFO | jvm 1 | 2019/10/29 17:35:27 | at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
> INFO | jvm 1 | 2019/10/29 17:35:27 | ... 3 more

**Comment by zwyqz** [comment]
还有其他报错信息吗

**Comment by rubyvirus** [comment]
> 还有其他报错信息吗

NFO   | jvm 1    | 2019/10/29 17:28:42 | Exception in thread "Timer0" 
INFO   | jvm 1    | 2019/10/29 17:29:14 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.util.Arrays.copyOf(Arrays.java:3332)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
INFO   | jvm 1    | 2019/10/29 17:29:36 | 	at java.lang.StringBuilder.append(StringBuilder.java:136)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.server.ServerConnection.toString(ServerConnection.java:414)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.net.AbstractConnection.idleCheck(AbstractConnection.java:537)
INFO   | jvm 1    | 2019/10/29 17:30:02 | 	at io.mycat.net.NIOProcessor.frontendCheck(NIOProcessor.java:182)
INFO   | jvm 1    | 2019/10/29 17:30:08 | 
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at io.mycat.net.NIOProcessor.checkFrontCons(NIOProcessor.java:156)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at io.mycat.MycatServer$6$2.run(MycatServer.java:876)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:30:38 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:10 | Exception in thread "$_NIOREACTOR-32-RW" Exception in thread "$_NIOREACTOR-46-RW" java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:10 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | Oct 29, 2019 5:27:08 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
INFO   | jvm 1    | 2019/10/29 17:35:26 | SEVERE: Exception processing: 7250 org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapper@65159896
INFO   | jvm 1    | 2019/10/29 17:35:26 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.StringCoding.encode(StringCoding.java:344)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.String.getBytes(String.java:918)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 
INFO   | jvm 1    | 2019/10/29 17:35:26 | Exception in thread "Log4j2-AsyncLoggerConfig-1" java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
INFO   | jvm 1    | 2019/10/29 17:35:26 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/10/29 17:35:27 | Caused by: java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.StringCoding.encode(StringCoding.java:344)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at java.lang.String.getBytes(String.java:918)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.getBytes(AbstractStringLayout.java:121)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:148)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:88)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:103)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:90)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:76)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
INFO   | jvm 1    | 2019/10/29 17:35:27 | 	... 3 more
INFO   | jvm 1    | 2019/10/29 17:35:30 | SELECT * FROM tb
INFO   | jvm 1    | 2019/10/29 17:35:31 | SELECT * FROM tb
INFO   | jvm 1    | 2019/10/29 17:35:31 | SELECT * FROM tb
STATUS | wrapper  | 2019/10/29 17:36:39 | TERM trapped.  Shutting down.
ERROR  | wrapper  | 2019/10/29 17:37:13 | Shutdown failed: Timed out waiting for signal from JVM.
ERROR  | wrapper  | 2019/10/29 17:37:13 | JVM did not exit on request, terminated
INFO   | wrapper  | 2019/10/29 17:37:13 | JVM exited on its own while waiting to kill the application.
STATUS | wrapper  | 2019/10/29 17:37:13 | JVM exited in response to signal SIGKILL (9).
STATUS | wrapper  | 2019/10/29 17:37:13 | <-- Wrapper Stopped
STATUS | wrapper  | 2019/10/29 17:37:39 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2019/10/29 17:37:39 | Launching a JVM...
INFO   | jvm 1    | 2019/10/29 17:37:39 | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
INFO   | jvm 1    | 2019/10/29 17:37:40 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2019/10/29 17:37:40 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2019/10/29 17:37:40 | 
INFO   | jvm 1    | 2019/10/29 17:37:41 | MyCAT Server startup successfully. see logs in logs/mycat.log

**Comment by rubyvirus** [comment]
> 还有其他报错信息吗

溢出前后程序正在执行的SQL基本上都是上百行

请求是这个原因导致的解析时拼接溢出了吗
