### ISSUE TITLE
关于扩展mycat识别mysql COM_SET_OPTION command的提议

### ISSUE THREAD

**Issue by binghx** [MyCATApache/Mycat-Server#2370]
问题描述：
在jdbcurl上配置了rewritebatchedstatements=true但没有配置allowMultiQueries=true时，批量更新抛出异常：
```java
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Unknown command
	at sun.reflect.GeneratedConstructorAccessor125.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.disableMultiQueries(MysqlIO.java:3669)
	at com.mysql.jdbc.PreparedStatement.executePreparedBatchAsMultiStatement(PreparedStatement.java:1447)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1258)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
...
```
问题分析：
mysql-connector-java-5.1.46.jar中PreparedStatement#executeBatchInternal中有如下逻辑：

```java 
         try {
                statementBegins();

                clearWarnings();

                if (!this.batchHasPlainStatements && this.connection.getRewriteBatchedStatements()) {

                    if (canRewriteAsMultiValueInsertAtSqlLevel()) {
                        return executeBatchedInserts(batchTimeout);
                    }

                    if (this.connection.versionMeetsMinimum(4, 1, 0) && !this.batchHasPlainStatements && this.batchedArgs != null
                            && this.batchedArgs.size() > 3 /* cost of option setting rt-wise */) {
                        return executePreparedBatchAsMultiStatement(batchTimeout);
                    }
                }

                return executeBatchSerially(batchTimeout);
            } finally {
                this.statementExecuting.set(false);

                clearBatch();
            }
```
其中，executePreparedBatchAsMultiStatement()会因为启用了rewritebatchedstatements临时启用allowMultiQueries，执行批量sql后，再禁用allowMultiQueries，这时候会发送COM_SET_OPTION command，但mycat不支持这个command。
PreparedStatement#executePreparedBatchAsMultiStatement中临时启用、禁用allowMultiQueries的逻辑：
```java
try {
    if (!multiQueriesEnabled) {
        locallyScopedConn.getIO().enableMultiQueries();
    }

    ...
} finally {
    ...

    if (!multiQueriesEnabled) {
        locallyScopedConn.getIO().disableMultiQueries();
    }

    ...
}
```
enableMultiQueries和disableMultiQueries中发送COM_SET_OPTION command
```java
void enableMultiQueries() throws SQLException {
    Buffer buf = getSharedSendPacket();

    buf.clear();
    buf.writeByte((byte) MysqlDefs.COM_SET_OPTION);
    buf.writeInt(0);
    sendCommand(MysqlDefs.COM_SET_OPTION, null, buf, false, null, 0);
}

void disableMultiQueries() throws SQLException {
    Buffer buf = getSharedSendPacket();

    buf.clear();
    buf.writeByte((byte) MysqlDefs.COM_SET_OPTION);
    buf.writeInt(1);
    sendCommand(MysqlDefs.COM_SET_OPTION, null, buf, false, null, 0);
}
```
而mycat中并不支持这个命令:
FrontendCommandHandler#handle
```java
switch (data[4])
{
...
    default:
        commands.doOther();
        MycatConfig config = MycatServer.getInstance().getConfig();
        if( config.getSystem().getIgnoreUnknownCommand()==1){
            LOGGER.warn("Unknown command:{}",data[4]);
            source.ping();
        }else {
            LOGGER.error("Unknown command:{}",new String(data));
            source.writeErrMessage(ErrorCode.ER_UNKNOWN_COM_ERROR,
                                   "Unknown command");
        }
}
```
提issues的目的：
1.为后来遇到这个问题的同学提供参考,添加allowMultiQueries=true可解决
2.大佬考虑下是不是可以支持COM_SET_OPTION command

**Comment by junwen12221** [comment]
COM_SET_OPTION command会要求mysql返回多结果集，mycat1.6没有相应处理。你说的问题实际上是jdbc客户端的适配问题，版本不同，行为不一样。

**Comment by binghx** [comment]
> COM_SET_OPTION command会要求mysql返回多结果集，mycat1.6没有相应处理。你说的问题实际上是jdbc客户端的适配问题，版本不同，行为不一样。

那直接在url加上allowMultiQueries=true不会返回多结果集吗？mycat是否支持？

**Comment by junwen12221** [comment]
现在mycat源码里面
server.xml
<property name="ignoreUnknownCommand">0</property>

COM_SET_OPTION开启这个属性之后能绕过Unknown command异常，响应mysql报文设置成功（无论COM_SET_OPTION是开启多语句还是关闭多语句），多语句，多查询会导致多结果集，但是具体行为看mysql响应，jdbc发送多个查询语句，mycat只返回一个结果也是可以的。顺带一提的是mycat现在连接后端mysql没有处理多结果集响应。

**Comment by binghx** [comment]
> 现在mycat源码里面
> server.xml
> `<property name="ignoreUnknownCommand">0</property> `
> COM_SET_OPTION开启这个属性之后能绕过Unknown command异常，响应mysql报文设置成功（无论COM_SET_OPTION是开启多语句还是关闭多语句），多语句，多查询会导致多结果集，但是具体行为看mysql响应，jdbc发送多个查询语句，mycat只返回一个结果也是可以的。顺带一提的是mycat现在连接后端mysql没有处理多结果集响应。

如果多语句导致了多结果集，mycat会选择一个返回，还是说会抛出错误，导致回滚。

**Comment by junwen12221** [comment]
如果jdbc上的业务有获取多于一个结果集，就是异常

**Comment by junwen12221** [comment]
你确定一下是调用哪个方法enableMultiQueries和disableMultiQueries，只是关闭的话，那没有问题，如果是开启，可能jdbc后一个操作就是发送多语句

**Comment by binghx** [comment]
> 你确定一下是调用哪个方法enableMultiQueries和disableMultiQueries，只是关闭的话，那没有问题，如果是开启，可能jdbc后一个操作就是发送多语句

如果url上配置了allowMultiQueries=true，这两个方法都不会调到了，但是这表示我可以发送多语句，可能是多结果集。

**Comment by junwen12221** [comment]
你看看jdbc发送的sql里面是不是一次请求使用了;分隔多个sql

**Comment by junwen12221** [comment]
或者mycat是否接收到的是这种sql

**Comment by chachae** [comment]
全干掉就可以
