### ISSUE TITLE
MyCAT1.6版本不支持Json字段

### ISSUE THREAD

**Issue by CutePHP** [MyCATApache/Mycat-Server#2384]
在使用MyCAT的时候，客户端收到一个报错:

```
Packets out of order. Expected 20 received 1. Packet size=65
```

错误日志：

```
2019-12-23 19:08:47.635  WARN [BusinessExecutor13] (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:829)) - io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@56d5b4fa caught exception 
java.lang.IndexOutOfBoundsException: Index: 16, Size: 16
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_221]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_221]
	at io.mycat.net.mysql.BinaryRowDataPacket.write(BinaryRowDataPacket.java:313) ~[classes/:?]
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.outputMergeResult(MultiNodeQueryHandler.java:641) ~[classes/:?]
	at io.mycat.sqlengine.mpp.DataMergeService.run(DataMergeService.java:228) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
2019-12-23 19:08:47.636 DEBUG [BusinessExecutor13] (io.mycat.backend.mysql.nio.handler.MultiNodeHandler.tryErrorFinished(MultiNodeHandler.java:206)) - io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@56d5b4faerror all end ,clear session resource 
2019-12-23 19:08:47.636 DEBUG [BusinessExecutor13] (io.mycat.backend.mysql.nio.handler.MultiNodeHandler.tryErrorFinished(MultiNodeHandler.java:207)) - error all end ,clear session resource 
2019-12-23 19:08:47.636 ERROR [BusinessExecutor13] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=2, schema=gold, host=172.17.12.11, user=root,txIsolation=3, autocommit=true, schema=gold, executeSql=null]java.lang.IndexOutOfBoundsException: Index: 16, Size: 16java.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
```

最终定位到io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.outputMergeResult
发现调用binRowDataPk.read(fieldPackets, row)的时候，使用convert方法转换

在switch的时候发现没有针对Json(fieldType=245)字段进行处理,导致List少了一个元素，出现了数组越界。

希望能加入对Json字段的支持。

**Comment by ouyangzhongmin** [comment]
同样遇到了，你是如何解决的呢
