### ISSUE TITLE
1.4版本批量load data infile 报错。

### ISSUE THREAD

**Issue by 18721230141** [MyCATApache/Mycat-Server#239]
我是通过load data infile 导入数据文件的时候报错的。我的file文件类容为：
1101133834040160	10	1	757	1	0	0
1101133834147413	10	1	277	1	0	0
1101133834255374	10	1	315	0	0	0
1101133834255374	10	2	95	0	0	0
1201133834350565	10	1	549	1	0	0
1101133834562148	10	1	825	1	0	0
具体报错一直为：
04/20 17:41:33.888  DEBUG [$_NIOREACTOR-99-RW] (ServerQueryHandler.java:56) -ServerConnection [id=4, schema=db_casino, host=127.0.0.1, user=wolfplus,txIsolation=3, autocommit=true, schema=db_casino]LOAD DATA LOCAL INFILE '/home/wolfplus/data/tb_achieve_data_20150420.txt' INTO TABLE tb_achieve_data character set 'latin1'(ac_ply_guid,ac_game_id,ac_index,ac_num,ac_status,ac_type,ac_date)
04/20 17:41:44.673  ERROR [$_NIOREACTOR-99-RW] (FrontendConnection.java:282) -load data error
java.lang.NullPointerException
	at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:582)
	at org.opencloudb.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:531)
	at org.opencloudb.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:279)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:447)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Thread.java:745)
04/20 17:41:44.675   INFO [$_NIOREACTOR-99-RW] (AbstractConnection.java:445) -close connection,reason:stream closed ,ServerConnection [id=4, schema=db_casino, host=127.0.0.1, user=wolfplus,txIsolation=3, autocommit=true, schema=db_casino]
04/20 17:41:45.043  DEBUG [$_NIOREACTOR-99-RW] (NIOReactor.java:112) -ServerConnection [id=4, schema=db_casino, host=127.0.0.1, user=wolfplus,txIsolation=3, autocommit=true, schema=db_casino] socket key canceled

**Comment by magicdoom** [comment]
最新代码以及解决了这个问题，请验证通过后关闭

**Comment by ggggggggod** [comment]
我的file内容是：
964509 1426749300 698 89114767 17 152129
964509 1426749300 480 106520088 13 152129
964509 1426749300 2768 492330311 20 152129
964509 1426749300 390 49319705 21 152129
964509 1426749300 252 72952676 18 152129
964509 1426749300 163 40324348 30 152129
964509 1426749300 415 55857747 22 152129
在load data的时候一直报错：
mysql> LOAD DATA INFILE '/tmp/user.txt' IGNORE INTO TABLE table1(domain_id,time,req_num,size,area_id,rollback_id) FIELDS TERMINATED BY '\t';
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: user
ERROR 3009 (HY000): For input string: "09 142674"
使用空格分隔字符 为何把09 142674当成一个字符

**Comment by ggggggggod** [comment]
05/10 23:13:29.373  ERROR [$_NIOREACTOR-12-RW] (FrontendConnection.java:244) -load data error
java.lang.NumberFormatException: For input string: "09 142674"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.math.BigInteger.<init>(BigInteger.java:327)
        at java.math.BigInteger.<init>(BigInteger.java:445)
        at org.opencloudb.route.function.PartitionByMod.calculate(PartitionByMod.java:61)
        at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:758)
        at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:658)
        at org.opencloudb.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:542)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:349)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:382)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:680)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:214)
        at org.opencloudb.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:241)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:112)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

**Comment by 18721230141** [comment]
把字段分隔符换成逗号，然后每个字段都加上引号，再导入试试，我就是这样导入成功的来自我的华为手机-------- 原始邮件 --------主题：Re: [Mycat-Server] 1.4版本批量load data infile 报错。 (#239)发件人：liucyao 收件人：MyCATApache/Mycat-Server 抄送：18721230141 <18721230141@163.com>05/10 23:13:29.373  ERROR $_NIOREACTOR-12-RW -load data error
java.lang.NumberFormatException: For input string: "09 142674"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.math.BigInteger.(BigInteger.java:327)
        at java.math.BigInteger.(BigInteger.java:445)
        at org.opencloudb.route.function.PartitionByMod.calculate(PartitionByMod.java:61)
        at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:758)
        at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:658)
        at org.opencloudb.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:542)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:349)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:382)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:680)
        at org.opencloudb.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:214)
        at org.opencloudb.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:241)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:112)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
你这个FIELDS TERMINATED BY '\t';配置的tab为分割符号，而不是空格；
你可以按照楼上的方法试试，具体参考下文档
