### ISSUE TITLE
Mycat调用节点存储过程时出错

### ISSUE THREAD

**Issue by yuhaoooo** [MyCATApache/Mycat-Server#2394]
存储过程如下所示：
```
CREATE DEFINER=`root`@`%` PROCEDURE `buyBook`(IN `book_num` INT,IN `order_number` varchar(255),IN `order_time` varchar(255),OUT `res` INT)
BEGIN
	#Routine body goes here...
	DECLARE book_id VARCHAR(255);
	DECLARE book_stock INT DEFAULT -1;
	DECLARE book_money FLOAT DEFAULT 0.0;
	START TRANSACTION;
	SELECT bookId INTO book_id from bookpurchase WHERE orderNumber = order_number;
	SELECT bookStock,bookPrice INTO book_stock,book_money FROM book WHERE bookId = book_id and bookdeleted = 0;
	SET book_stock = book_stock - book_num;
	IF book_stock < 0 THEN
		SET res = 0;
		ROLLBACK;
	ELSE
		SET book_money = book_money * book_num;
		UPDATE book SET bookStock = book_stock WHERE bookId = book_id and bookdeleted = 0;
		UPDATE bookpurchase SET num = book_num, `time` = order_time, totalMoney = book_money, paymentType = 1, `status` = 5 WHERE orderNumber = order_number;
		SET res = 1;
		COMMIT;
	END IF;
END
```
该存储过程部署在节点dn1,dn2,dn3中，我使用Navicat中的命令行调用存储过程，如下所示：
```
/*#mycat: sql=select * from bookpurchase where orderNumber = @order_number; */
set @book_num=1,@order_number="20200105150017",@order_time="20210212132113";
Call buyBook(@book_num,@order_number,@order_time,@res); select @res;
```
结果显示为：
```
+------+
| @res |
+------+
|    1 |
+------+
```
但是根据bookpurchase表中的数据，@res的值应该为0。而且我多次执行时@res值在null和1之间波动。
请问是我的使用方法不对嘛？

**Comment by junwen12221** [comment]
开启事务,使后端的session不会释放

**Comment by yuhaoooo** [comment]
使用```set autocommit = 0;```开启事务嘛？这个是需要每次执行都需要开启么？因为我注意到我在命令行键入```set autocommit = 0;```之后，我再```select @@autocommit;```结果还是1。
```
+--------------+
| @@autocommit |
+--------------+
|            1 |
+--------------+
```

**Comment by yuhaoooo** [comment]
还有一个问题，我用Mybatis调用存储过程，具体的Mapper是这么写的。
```
  <select id="buyBook" resultType="java.lang.Integer">
    <![CDATA[
    /*!mycat:sql=SELECT 1 FROM bookpurchase inner join book on book.bookId = bookpurchase.bookId where orderNumber = ${order_number}*/{call `buyBook`(
        #{book_num, mode=IN, jdbcType=INTEGER},
        #{order_number, mode=IN, jdbcType=VARCHAR},
        #{order_time, mode=IN, jdbcType=VARCHAR},
        @res
    )};select @res;
    ]]>
  </select>
```
它可以执行成功，但是总是会报错，如下。
```
org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:80) ~[mybatis-3.5.3.jar:3.5.3]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.sun.proxy.$Proxy62.selectOne(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93) ~[mybatis-3.5.3.jar:3.5.3]
	at com.sun.proxy.$Proxy64.buyBook(Unknown Source) ~[na:na]
	at com.yuhao.bookstore.service.BookpurchaseService.buyBook(BookpurchaseService.java:69) ~[classes/:na]
	at com.yuhao.bookstore.controller.BookPurchaseController.usrByBook(BookPurchaseController.java:145) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
```
我怀疑由三个结果的原因是有三个MySQL站点，但是我认为我的Mapper好像写的没有问题，究竟是什么原因导致这个问题呢？

**Comment by junwen12221** [comment]
不支持多语句，用jdbc连接一次执行一条sql
