### ISSUE TITLE
1.6.7.3版本使用LOAD DATA LOCAL INFILE报空指针

### ISSUE THREAD

**Issue by tangjingtai** [MyCATApache/Mycat-Server#2413]
错误日志：
2020-02-04 22:30:27.944 ERROR [$_NIOREACTOR-6-RW] (io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:323)) - load data error
java.lang.NullPointerException
	at io.mycat.route.util.RouterUtil.routeToDistTableNode(RouterUtil.java:1397) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1352) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1266) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:368) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:401) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:671) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:321) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:546) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:537) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.3-release.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
2020-02-04 22:30:27.944  INFO [$_NIOREACTOR-6-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:stream closed ,ServerConnection [id=4, schema=USERDB, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=USERDB, executeSql=LOAD DATA LOCAL INFILE 'D:\\data\\t_order.txt'  
INTO TABLE `t_order`(`id`, `total_price`)
CHARACTER SET utf8
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\r\n'   ]

报错对应的配置（单库多表）：
<schema name="USERDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="t_order" dataNode="dn1" subTables="t_order_$1-3" primaryKey="id" rule="mod-long" ></table>
	</schema>

使用多库同名表配置不报错：
<schema name="USERDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="t_user" dataNode="dn1,dn2,dn3" rule="mod-long" primaryKey="id"/>		
	</schema>

请问这是什么问题呢，是哪里配置不对吗

**Comment by tangjingtai** [comment]
报错对应的配置（单库多表）：
`<schema name="USERDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="t_order" dataNode="dn1" subTables="t_order_$1-3" primaryKey="id" rule="mod-long" ></table>
	</schema>`

使用多库同名表配置不报错：
<schema name="USERDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="t_user" dataNode="dn1,dn2,dn3" rule="mod-long" primaryKey="id"/>
	</schema>

**Comment by junwen12221** [comment]
public void loadDataInfileEnd(byte packID) {
		if (loadDataInfileHandler != null) {
			try {
				loadDataInfileHandler.end(packID);
			} catch (Exception e) {
				LOGGER.error("load data error", e);
				writeErrMessage(ErrorCode.ERR_HANDLE_DATA, e.getMessage());
			}
		} else {
			writeErrMessage(ErrorCode.ER_UNKNOWN_COM_ERROR, "load data infile end is not  unsupported!");
		}
	}

**Comment by junwen12221** [comment]
(io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:323)) - load data error
java.lang.NullPointerException

**Comment by tangjingtai** [comment]
这个错误是什么原因导致的，更新的版本中解决了吗，怎样可以规避呢。
