### ISSUE TITLE
mycat 1.6是不是对postgresql的支持还有很多问题，怎么配置都不行

### ISSUE THREAD

**Issue by HiFangfangXu** [MyCATApache/Mycat-Server#2432]
mycat 1.6是不是对postgresql的支持还有很多问题，怎么配置都不行

**Comment by longzhihun** [comment]
建议你把报错信息以及配置信息发出来，方便定位问题

**Comment by bomby33** [comment]
schema.xml 
?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
       <schema name="bdd" checkSQLschema="false" sqlMaxLimit="1000" dataNode="mydn3">
        </schema>

        <dataNode name="mydn3" dataHost="myhost3" database="ceshi" />

        <dataHost name="myhost3" maxCon="100" minCon="10" balance="3" writeType="0" dbType="postgres" dbDriver="jdbc">
                <heartbeat>select user</heartbeat>
                <writeHost host="hostM3" url="jdbc:postgresql://192.168.2.36:5432/ceshi" user="postgres" password="123456">
                <readHost host="hostS3" url="jdbc:postgresql://192.168.2.80:5432/ceshi" user="postgres" password="123456"/>
                </writeHost>
        </dataHost>
</mycat:schema>


启动一切正常，用navicat连接才会报

2020-03-26 09:54:22.722 ERROR [$_NIOREACTOR-1-RW] (io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:272)) - load data error
java.lang.NullPointerException
        at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:630) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:270) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:491) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:482) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.register(FrontendConnection.java:466) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:181) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:96) ~[Mycat-server-1.6.5-release.jar:?]


navicat报
![image](https://user-images.githubusercontent.com/26901004/77603116-2f4c1600-6f4a-11ea-9a5a-9195f89fae21.png)

**Comment by CrazyZhou0708** [comment]
我也碰到类似的问题了,请问您是如何解决的,能否交流一下
