### ISSUE TITLE
django中使用mycat做中间件，生成模型之后以model.objects.create()的方式新增并保存模型到数据库的时候出错

### ISSUE THREAD

**Issue by silverstone-chaebol** [MyCATApache/Mycat-Server#2433]

**Comment by junwen12221** [comment]
看mycat日志

**Comment by lijintaotzx** [comment]
可以使用mycat直接作为django的数据库使用吗？
为什么我的项目启动都会报错？，需要修改哪里的配置吗？
==========================================================================================

settings:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_db_server',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '8066',
    }
}
==========================================================================================
django log:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/core/management/base.py", line 442, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    return get_names(cursor)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/mysql/introspection.py", line 55, in get_table_list
    cursor.execute("SHOW FULL TABLES")
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/tzx/.pyenv/versions/tarena/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1184, '')

==========================================================================================

Mycat log:
2020-07-21 10:33:04.642  INFO [$_NIOREACTOR-2-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - ServerConnection [id=11, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=my_db_server, executeSql=null]'root' login success
2020-07-21 10:33:04.644  WARN [$_NIOREACTOR-2-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:207)) - ServerConnection [id=11, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=2, autocommit=true, schema=my_db_server, executeSql=SHOW FULL TABLES]SHOW FULL TABLES, route={
   1 -> dn1,dn2{SHOW FULL TABLES}
}
java.lang.NullPointerException
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:203) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:148) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:314) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:241) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.handler.ShowHandler.handle(ShowHandler.java:60) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:92) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.4-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2020-07-21 10:33:04.645 ERROR [$_NIOREACTOR-2-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=11, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=2, autocommit=true, schema=my_db_server, executeSql=SHOW FULL TABLES]nulljava.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .connectionError263
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .execute209
io.mycat.server.NonBlockingSession .execute148
io.mycat.server.ServerConnection .routeEndExecuteSQL314
io.mycat.server.ServerConnection .execute241
io.mycat.server.handler.ShowHandler .handle60
io.mycat.server.ServerQueryHandler .query92
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76
io.mycat.net.FrontendConnection .rawHandle570
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run748
 write errorMsg:{} error
2020-07-21 10:33:05.202  INFO [$_NIOREACTOR-3-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - ServerConnection [id=12, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=my_db_server, executeSql=null]'root' login success
2020-07-21 10:33:05.204  WARN [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:207)) - ServerConnection [id=12, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=2, autocommit=true, schema=my_db_server, executeSql=SHOW FULL TABLES]SHOW FULL TABLES, route={
   1 -> dn1,dn2{SHOW FULL TABLES}
}
java.lang.NullPointerException
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:203) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:148) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:314) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:241) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.handler.ShowHandler.handle(ShowHandler.java:60) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:92) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.4-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2020-07-21 10:33:05.204 ERROR [$_NIOREACTOR-3-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=12, schema=my_db_server, host=127.0.0.1, user=root,txIsolation=2, autocommit=true, schema=my_db_server, executeSql=SHOW FULL TABLES]nulljava.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .connectionError263
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .execute209
io.mycat.server.NonBlockingSession .execute148
io.mycat.server.ServerConnection .routeEndExecuteSQL314
io.mycat.server.ServerConnection .execute241
io.mycat.server.handler.ShowHandler .handle60
io.mycat.server.ServerQueryHandler .query92
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76
io.mycat.net.FrontendConnection .rawHandle570
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run748
 write errorMsg:{} error

**Comment by BenzMen** [comment]
同问,mycat到底支持不支持django 的orm，烦请回复
