### ISSUE TITLE
无法启动1.6 Server

### ISSUE THREAD

**Issue by Jackjun724** [MyCATApache/Mycat-Server#2452]
```
2020-04-03 16:48:33,074 [ERROR][main] 2020-04-03 16:48:33 startup error java.lang.NumberFormatException: Size must be specified as bytes (b), kibibytes (k), mebibytes (m), gibibytes (g), tebibytes (t), or pebibytes(p). E.g. 50b, 100k, or 250m.
Failed to parse byte string: -375809638B
        at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAs(JavaUtils.java:223)
        at io.mycat.memory.unsafe.utils.JavaUtils.byteStringAsBytes(JavaUtils.java:234)
        at io.mycat.memory.unsafe.utils.MycatPropertyConf.byteStringAsBytes(MycatPropertyConf.java:92)
        at io.mycat.memory.unsafe.utils.MycatPropertyConf.getSizeAsBytes(MycatPropertyConf.java:50)
        at io.mycat.memory.unsafe.memory.mm.MemoryManager.<init>(MemoryManager.java:30)
        at io.mycat.memory.unsafe.memory.mm.ResultMergeMemoryManager.<init>(ResultMergeMemoryManager.java:15)
        at io.mycat.memory.MyCatMemory.<init>(MyCatMemory.java:125)
        at io.mycat.MycatServer.startup(MycatServer.java:335)
        at io.mycat.MycatStartup.main(MycatStartup.java:57)
 (io.mycat.MycatStartup:MycatStartup.java:62) 
```

**Comment by king192** [comment]
单位都列举出来了

**Comment by Jackjun724** [comment]
已解决 把堆外处理的配置关掉就好了
