### ISSUE TITLE
执行join查询的时候一直往日志文件中刷报错的信息，怎么解决

### ISSUE THREAD

**Issue by pang691** [MyCATApache/Mycat-Server#2470]
我的sql:
/!mycat:catlet=io.mycat.catlets.ShareJoin /SELECT s.,t. from student s
left join teacher t on s.id = t.stu_id

说明：student是跨库分表，teacher是单张表（既没有跨库也没有分表）

报错信息如下---这些错误信息一直刷，应该是一个while循环，这个怎么解决呢，谢谢
java.lang.Thread .run745
 write errorMsg:{} error
2020-04-23 15:12:13.162 DEBUG [$_NIOREACTOR-14-RW] (io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)) - ServerConnection [id=1, schema=student1, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=student1, executeSql=SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_TYPE] SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME
2020-04-23 15:12:13.162 DEBUG [$_NIOREACTOR-14-RW] (io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:70)) - ServerConnection [id=1, schema=student1, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=student1, executeSql=SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME]SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME
2020-04-23 15:12:13.162 DEBUG [$_NIOREACTOR-14-RW] (io.mycat.cache.impl.EnchachePool.get(EnchachePool.java:77)) - SQLRouteCache  miss cache ,key:student1SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME
2020-04-23 15:12:13.163  WARN [$_NIOREACTOR-14-RW] (io.mycat.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:1598)) - can't find table define in schema COLUMNS schema:student1
2020-04-23 15:12:13.163  WARN [$_NIOREACTOR-14-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:333)) - ServerConnection [id=1, schema=student1, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=student1, executeSql=SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME]SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME 
err:java.sql.SQLNonTransientException: can't find table define in schema COLUMNS schema:student1
java.sql.SQLNonTransientException: can't find table define in schema COLUMNS schema:student1
	at io.mycat.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:1599) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1292) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:521) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:343) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.directRoute(DruidMycatRouteStrategy.java:390) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:202) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:83) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:139) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:328) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:267) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:107) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:95) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.5-release.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2020-04-23 15:12:13.163 ERROR [$_NIOREACTOR-14-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=1, schema=student1, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=student1, executeSql=SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'student1' ORDER BY TABLE_SCHEMA, TABLE_NAME]can't find table define in schema COLUMNS schema:student1java.lang.Thread .getStackTrace1556
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.server.ServerConnection .routeEndExecuteSQL335
io.mycat.server.ServerConnection .execute267
io.mycat.server.handler.SelectHandler .handle107
io.mycat.server.ServerQueryHandler .query95
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76
io.mycat.net.FrontendConnection .rawHandle570
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113

**Comment by funnyAnt** [comment]
元数据获取报错了，建议不用catlet=io.mycat.catlets.ShareJoin
