### ISSUE TITLE
从TXT中load数据时总卡在24338这行，报java.lang.ArrayIndexOutOfBoundsException: 65535

### ISSUE THREAD

**Issue by xiaomaixu** [MyCATApache/Mycat-Server#2492]
从TXT格式文件中load数据时总卡在24338这行，报java.lang.ArrayIndexOutOfBoundsException: 65535，
这行换了内容还是卡在了这行，而且报错内容一样
再后来尝试把数据拆分几份导入，不卡在这行数据报错了，但是报错内容一样，很着急，谢谢解答！
其中下面是TXT格式文件中的数据：
084|PROV_DETAIL|DIMENSION1|??|sn_84b3151|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b3158|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b3156|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b315e|????????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b315c|??????????|||||
084|PR
报错内容如下：
084|PROV_DETAIL|DIMENSION1|??|sn_84b3151|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b3158|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b3156|??????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b315e|????????????|||||
084|PROV_DETAIL|DIMENSION1|??|sn_84b315c|??????????|||||
084|PR
        at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:339) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:475) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:669) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:321) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:546) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:537) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.3-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.3-release.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535
        at com.univocity.parsers.common.input.DefaultCharAppender.appendUntil(DefaultCharAppender.java:223) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.univocity.parsers.csv.CsvParser.parseQuotedValue(CsvParser.java:268) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:119) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:444) ~[univocity-parsers-2.2.1.jar:2.2.1]
        ... 9 more
2020-06-03 15:44:15.948  INFO [$_NIOREACTOR-14-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:stream closed ,ServerConnection

**Comment by junwen12221** [comment]
看看1671 与1675有没有这个问题

**Comment by junwen12221** [comment]
可以把可以复现的配置和文件发到我邮箱294712221@qq.com

**Comment by xiaomaixu** [comment]
谢谢您，已经发您邮箱了

**Comment by xiaomaixu** [comment]
您好，load数据时mycat日志报错[Timer1] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=host，是什么原因啊，谢谢帮忙解决

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightfish"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 上午9:37
收件人:&nbsp;"MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;;
抄送:&nbsp;"小麦～西电硕士毕业"<1647178091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 从TXT中load数据时总卡在24338这行，报java.lang.ArrayIndexOutOfBoundsException: 65535 (#2492)





 
Closed #2492.

**Comment by xiaomaixu** [comment]
您好，最近我们使用的mycat1.6.7.3总是报心跳错误，什么原因？有没有解决方法？，谢谢
[Timer1] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1 DBHostConfig [hostName=host








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightfish"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 上午9:37
收件人:&nbsp;"MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;;
抄送:&nbsp;"小麦～西电硕士毕业"<1647178091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 从TXT中load数据时总卡在24338这行，报java.lang.ArrayIndexOutOfBoundsException: 65535 (#2492)





 
Closed #2492.
