### ISSUE TITLE
LOADDATA时偶尔会出现ERROR 2013 (HY000) at line 3: Lost connection to MySQL server during query是什么原因？

### ISSUE THREAD

**Issue by xiaomaixu** [MyCATApache/Mycat-Server#2505]
LOADDATA时偶尔会出现ERROR 2013 (HY000) at line 3: Lost connection to MySQL server during query是什么原因？下面是mycat日志报错信息，谢谢帮忙解答
报错：
create connections ,because idle connection not enough ,cur is 7, minCon is 10 for host2
close connection,reason:program err:java.io.IOException: Connection reset by peer 
![image](https://user-images.githubusercontent.com/20907534/84228244-1bf82200-ab19-11ea-8812-2ab23f245674.png)

**Comment by xiaomaixu** [comment]
补充：这个错误是服务器命令行执行load语句时报的错

**Comment by funnyAnt** [comment]
用的最新版本吗？ load data执行时间多长，是不是超时被mycat空闲检查线程kill掉了

**Comment by xiaomaixu** [comment]
您好，load数据时mycat日志报错[Timer1] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=host，是什么原因啊，谢谢帮忙解决


------------------ 原始邮件 ------------------
发件人:&nbsp;"momo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 下午4:48
收件人:&nbsp;"MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;;
抄送:&nbsp;"小麦～西电硕士毕业"<1647178091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] LOADDATA时偶尔会出现ERROR 2013 (HY000) at line 3: Lost connection to MySQL server during query是什么原因？ (#2505)





 
用的最新版本吗？ load data执行时间多长，是不是超时被mycat空闲检查线程kill掉了

**Comment by cheungfeifu** [comment]
> 用的最新版本吗？ load data执行时间多长，是不是超时被mycat空闲检查线程kill掉了

我今天也出现这个问题，因为是分片表 所以load 都加字段了还是报错：RROR 2013 (HY000): Lost connection to MySQL server during query
mysql> 

load sql：
load data local infile '/dir/20210125_bak_20210115_16_nfv_dn.txt' into table table (dr_type,dl_type ,prov_code ,      file_name,       file_date ,      deal_date,       sheet_cnt,       mo_cnt,  eo_cnt,  ao_cnt,  mt_cnt , et_cnt,  at_cnt,  mm_len,  basic_fee ,info_fee,disc_fee,        earliest_t,      latest_t,        act_time );

报错日志：
--
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_201]
        at java.math.BigInteger.<init>(BigInteger.java:470) ~[?:1.8.0_201]
        at java.math.BigInteger.<init>(BigInteger.java:606) ~[?:1.8.0_201]
        at io.mycat.route.function.PartitionByMod.calculate(PartitionByMod.java:59) ~[Mycat-server-1.6.7.1-release.jar:?]
        ... 14 more
2021-01-28 17:15:13.131  INFO [$_NIOREACTOR-4-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:stream closed ,ServerConnection [id=59076883, schema=cbbs_rst4, host=10.252.190.151, user=admin,txIsolation=2, autocommit=true, schema=cbbs_rst4, executeSql=load data local infile '/dir/20210125_bak_20210115_16_nfv_dn.txt' into table table (dr_type,dl_type ,prov_code ,      file_name,       file_date ,      deal_date,       sheet_cnt,       mo_cnt,  eo_cnt,  ao_cnt,  mt_cnt , et_cnt,  at_cnt,  mm_len,  basic_fee ,info_fee,disc_fee,        earliest_t,      latest_t,        act_time )]

**Comment by funnyAnt** [comment]
@cheungfeifu  最长不要超过30分钟，超过被空闲超时干掉后端连接。

**Comment by cheungfeifu** [comment]
没用，我最后直接在节点上load的，load数据应该不会锁吧？另外就是load data报错的try 给的错误信息不明确啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "momo"<notifications@github.com&gt;; 
发送时间: 2021年2月1日(星期一) 上午9:29
收件人: "MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;; 
抄送: "张飞虎"<915401550@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MyCATApache/Mycat-Server] LOADDATA时偶尔会出现ERROR 2013 (HY000) at line 3: Lost connection to MySQL server during query是什么原因？ (#2505)





 
@cheungfeifu  最长不要超过30分钟，超过被空闲超时干掉后端连接。
