### ISSUE TITLE
大批量插入数据报错丢失链接

### ISSUE THREAD

**Issue by DevinLeeQingZu** [MyCATApache/Mycat-Server#2526]
执行400条批量插入时可以正常执行，若超过400条。这mycat会报错丢失链接。
### Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 18 milliseconds ago.  The last packet sent successfully to the server was 22 milliseconds ago.
; SQL []; Communications link failure

The last packet successfully received from the server was 18 milliseconds ago.  The last packet sent successfully to the server was 22 milliseconds ago.; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 18 milliseconds ago.  The last packet sent successfully to the server was 22 milliseconds ago.
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:98)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:399)
	at com.sun.proxy.$Proxy53.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:253)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:52)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy217.insertAll(Unknown Source)
	at hitf.itf.service.impl.ItfImpInterfacesServiceImpl.insertAll(ItfImpInterfacesServiceImpl.java:61)
	at sun.reflect.GeneratedMethodAccessor6289.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at com.hand.hap.core.impl.ServiceExecutionAdvice.invoke(ServiceExecutionAdvice.java:126)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy244.insertAll(Unknown Source)

**Comment by DevinLeeQingZu** [comment]
有哪位大神遇到过并解决这个问题的么？请指教下～

**Comment by funnyAnt** [comment]
有能必现的代码吗，提供下。

**Comment by DevinLeeQingZu** [comment]
换成了1.6.6版本之后没有问题了

**Comment by DevinLeeQingZu** [comment]
> 有能必现的测试代码吗，提供下。

换成了1.6.6版本之后没有问题了
