### ISSUE TITLE
Cannot execute statement in a READ ONLY transaction.java.lang.Thread .getStackTrace1559

### ISSUE THREAD

**Issue by itbright-cn** [MyCATApache/Mycat-Server#2537]
**### **1、问题背景：**
**1.1、业务背景****
我们现在的业务是单体的ssm架构的项目，目前使用的是mycat 1.6.7.4 后面一主一从mysql数据库进行的数据读取。目前遇到的问题是偶现的，mycat端主要报错日志为：Cannot execute statement in a READ ONLY transaction.java.lang.Thread .getStackTrace1559

**1.2、中间件版本：**
spring 4.2.5.RELEASE
mybatis-spring 1.3.1
mysql-connector-java 5.1.38
mybatis 3.4.5

**1.3、tomcat主要异常日志：**
 uncategorized SQLException for SQL []; SQL state [25006]; error code [1792]; Cannot execute statement in a READ ONLY transaction.; nested exception is java.sql.SQLException: Cannot execute statement in a READ ONLY transaction.
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy39.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy47.updateByPrimaryKeySelective(Unknown Source)
	at com.fittime.ecom.hotcamp.dao.merge.impl.ApplyRecordMergeDao.updateApplyRecord(ApplyRecordMergeDao.java:66)
	at com.fittime.ecom.hotcamp.apply.service.HotcampApplyService.update2VByApplyId(HotcampApplyService.java:313)
	at com.fittime.ecom.hotcamp.course.service.HotcampCustomCourseService.onPerfectApplyAndCourseInfo(HotcampCustomCourseService.java:313)
	at com.fittime.ecom.hotcamp.course.service.HotcampCustomCourseService.save(HotcampCustomCourseService.java:246)
	at com.fittime.ecom.hotcamp.course.service.HotcampCustomCourseService$$FastClassBySpringCGLIB$$103dac32.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.fittime.ecom.hotcamp.course.service.HotcampCustomCourseService$$EnhancerBySpringCGLIB$$95c990f.save(<generated>)
	at com.fittime.ecom.hotcamp.course.controller.HotcampCourseController.onPublicForSaveCourse(HotcampCourseController.java:157)
	at com.fittime.ecom.hotcamp.course.controller.HotcampCourseController.saveCourseForSport(HotcampCourseController.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:178)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:444)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:432)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.fittime.ecom.common.filter.XssFilter.doFilter(XssFilter.java:22)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.fittime.ecom.common.filter.InterfaceLoggerFilter.doFilter(InterfaceLoggerFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.fittime.ecom.common.web.filter.CrossDomainFilter.doFilterInternal(CrossDomainFilter.java:22)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Cannot execute statement in a READ ONLY transaction.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at sun.reflect.GeneratedMethodAccessor1351.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 71 more

**1.4、myccat主要异常日志：**

**Comment by itbright-cn** [comment]
关键性报错信息：

2020-06-30 23:16:31.160 DEBUG [$_NIOREACTOR-10-RW] (io.mycat.backend.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:503)) - con need syn ,total syn cmd 1 commands SET autocommit=0;schema change:false con:MySQLConnection@417949910 [id=530, lastTime=1593530191160, user=mycat_rw, schema=eshop, old shema=eshop, borrowed=true, fromSlaveDB=false, threadId=195708, charset=utf8, txIsolation=3, autocommit=true, attachment=eshopDataNode{update TB_APPLY_RECORD




2020-06-30 23:16:31.161 ERROR [$_NIOREACTOR-15-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=40509, schema=eshop, host=172.31.100.181, user=eshop_mycat,txIsolation=3, autocommit=false, schema=eshop, executeSql=update TB_APPLY_RECORD
		 SET STUDENT_ID = 3002044,
			
			
				TERM_ID = 602,
			
			
				SOURCE = 0,
			
			
				NEED_PACKAGE = 0,
			
			
				PACKAGE_ORDER_ID = 1263496,
			
			
				PAY_METHOD = 'other',
			
			
				PAY_AMOUNT = 1798.50,
			
			
				IS_REFUND = 0,
			
			
			
				CAMP_ID = 27562,
			
			
				CREATE_TIME = '2020-05-14 13:55:06',
			
			
				UPDATE_TIME = '2020-06-30 00:00:06.343',
			
			
				WEIXIN_NAME = 'L100990950209',
			
			
				IS_END = 0,
			
			
				DELAY = 0,
			
			
				NAME = '顾杏',
			
			
				MOBILE = '18916350930',
			
			
				LOCATION = '中国大陆',
			
			
				GENDER = 'F',
			
			
				AGE = 27,
			
			
				HEIGHT = 165,
			
			
				WEIGHT = 83.5,
			
			
				WEIXIN_QRCODE = 'https://fop-fitcamp-resource.rjfittime.com/20976854-26eb-4cc9-9ae3-7c994eac5162.png?x-oss-process=image/resize,m_fill,w_1128,h_1353#',
			
			
				DISEASE_HISTORY = '无',
			
			
				SPORT_INJURY_HISTORY = '无',
			
			
				FITNESS_EXPERIENCE = '怀孕前健身，近两周恢复跳舞锻炼',
			
			
				REMARK = '无',
			
			
			
				BABY_MONTH = 21.00,
			
			
				BORN_TYPE = 1,
			
			
				IS_LACTATION = 0,
			
			
				VEGETARIAN_TYPE = 0,
			
			
				APPLY_STATUS = 0,
			
			
			
				SCORE = 0,
			
			
				TARGET = '{"1":{"weight":78.97089576721191,"waistLine":84.96551132202148}}',
			
			
			
			
			
			
			
				is_quit_group = 2,
			
			
				BABY_BIRTHDAY = '2018-09-14 00:00:00',
			
			
				BREASTMILK_RATIO = 1,
			
			
				hot_level = 4,
			
			
				water_level = 1,
			
			
				user_id = 12673458,
			
			
				athletic_ability_level = 'B2' 
		where APPLY_ID = 100006629]MySQLConnection@417949910 [id=530, lastTime=1593530191145, user=mycat_rw, schema=eshop, old shema=eshop, borrowed=true, fromSlaveDB=false, threadId=195708, charset=utf8, txIsolation=3, autocommit=false, attachment=eshopDataNode{update TB_APPLY_RECORD
		 SET STUDENT_ID = 3002044,
			
			
				TERM_ID = 602,
			
			
				SOURCE = 0,
			
			
				NEED_PACKAGE = 0,
			
			
				PACKAGE_ORDER_ID = 1263496,
			
			
				PAY_METHOD = 'other',
			
			
				PAY_AMOUNT = 1798.50,
			
			
				IS_REFUND = 0,
			
			
			
				CAMP_ID = 27562,
			
			
				CREATE_TIME = '2020-05-14 13:55:06',
			
			
				UPDATE_TIME = '2020-06-30 00:00:06.343',
			
			
				WEIXIN_NAME = 'L100990950209',
			
			
				IS_END = 0,
			
			
				DELAY = 0,
			
			
				NAME = '顾杏',
			
			
				MOBILE = '18916350930',
			
			
				LOCATION = '中国大陆',
			
			
				GENDER = 'F',
			
			
				AGE = 27,
			
			
				HEIGHT = 165,
			
			
				WEIGHT = 83.5,
			
			
				WEIXIN_QRCODE = 'https://fop-fitcamp-resource.rjfittime.com/20976854-26eb-4cc9-9ae3-7c994eac5162.png?x-oss-process=image/resize,m_fill,w_1128,h_1353#',
			
			
				DISEASE_HISTORY = '无',
			
			
				SPORT_INJURY_HISTORY = '无',
			
			
				FITNESS_EXPERIENCE = '怀孕前健身，近两周恢复跳舞锻炼',
			
			
				REMARK = '无',
			
			
			
				BABY_MONTH = 21.00,
			
			
				BORN_TYPE = 1,
			
			
				IS_LACTATION = 0,
			
			
				VEGETARIAN_TYPE = 0,
			
			
				APPLY_STATUS = 0,
			
			
			
				SCORE = 0,
			
			
				TARGET = '{"1":{"weight":78.97089576721191,"waistLine":84.96551132202148}}',
			
			
			
			
			
			
			
				is_quit_group = 2,
			
			
				BABY_BIRTHDAY = '2018-09-14 00:00:00',
			
			
				BREASTMILK_RATIO = 1,
			
			
				hot_level = 4,
			
			
				water_level = 1,
			
			
				user_id = 12673458,
			
			
				athletic_ability_level = 'B2' 
		where APPLY_ID = 100006629}, respHandler=SingleNodeHandler [node=eshopDataNode{update TB_APPLY_RECORD
		 SET STUDENT_ID = 3002044,
			
			
				TERM_ID = 602,
			
			
				SOURCE = 0,
			
			
				NEED_PACKAGE = 0,
			
			
				PACKAGE_ORDER_ID = 1263496,
			
			
				PAY_METHOD = 'other',
			
			
				PAY_AMOUNT = 1798.50,
			
			
				IS_REFUND = 0,
			
			
			
				CAMP_ID = 27562,
			
			
				CREATE_TIME = '2020-05-14 13:55:06',
			
			
				UPDATE_TIME = '2020-06-30 00:00:06.343',
			
			
				WEIXIN_NAME = 'L100990950209',
			
			
				IS_END = 0,
			
			
				DELAY = 0,
			
			
				NAME = '顾杏',
			
			
				MOBILE = '18916350930',
			
			
				LOCATION = '中国大陆',
			
			
				GENDER = 'F',
			
			
				AGE = 27,
			
			
				HEIGHT = 165,
			
			
				WEIGHT = 83.5,
			
			
				WEIXIN_QRCODE = 'https://fop-fitcamp-resource.rjfittime.com/20976854-26eb-4cc9-9ae3-7c994eac5162.png?x-oss-process=image/resize,m_fill,w_1128,h_1353#',
			
			
				DISEASE_HISTORY = '无',
			
			
				SPORT_INJURY_HISTORY = '无',
			
			
				FITNESS_EXPERIENCE = '怀孕前健身，近两周恢复跳舞锻炼',
			
			
				REMARK = '无',
			
			
			
				BABY_MONTH = 21.00,
			
			
				BORN_TYPE = 1,
			
			
				IS_LACTATION = 0,
			
			
				VEGETARIAN_TYPE = 0,
			
			
				APPLY_STATUS = 0,
			
			
			
				SCORE = 0,
			
			
				TARGET = '{"1":{"weight":78.97089576721191,"waistLine":84.96551132202148}}',
			
			
			
			
			
			
			
				is_quit_group = 2,
			
			
				BABY_BIRTHDAY = '2018-09-14 00:00:00',
			
			
				BREASTMILK_RATIO = 1,
			
			
				hot_level = 4,
			
			
				water_level = 1,
			
			
				user_id = 12673458,
			
			
				athletic_ability_level = 'B2' 
		where APPLY_ID = 100006629}, packetId=1], host=172.31.100.106, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@c1f5dd7, writeQueue=0, modifiedSQLExecuted=true]
Cannot execute statement in a READ ONLY transaction.java.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .backConnectionErr311
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .errorResponse272
io.mycat.backend.mysql.nio.MySQLConnectionHandler .handleErrorPacket168
io.mycat.backend.mysql.nio.MySQLConnectionHandler .handleData97
io.mycat.net.handler.BackendAsyncHandler .offerData36
io.mycat.backend.mysql.nio.MySQLConnectionHandler .handle79
io.mycat.net.AbstractConnection .handle269
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run748
 write errorMsg:{} error




2020-06-30 23:16:31.162 DEBUG [$_NIOREACTOR-15-RW] (io.mycat.server.NonBlockingSession.releaseConnection(NonBlockingSession.java:386)) - release connection MySQLConnection@417949910 [id=530, lastTime=1593530191145, user=mycat_rw, schema=eshop, old shema=eshop, borrowed=true, fromSlaveDB=false, threadId=195708, charset=utf8, txIsolation=3, autocommit=false, attachment=eshopDataNode{update TB_APPLY_RECORD
		 SET STUDENT_ID = 3002044,
			
			
				TERM_ID = 602,
			
			
				SOURCE = 0,
			
			
				NEED_PACKAGE = 0,
			
			
				PACKAGE_ORDER_ID = 1263496,
			
			
				PAY_METHOD = 'other',
			
			
				PAY_AMOUNT = 1798.50,
			
			
				IS_REFUND = 0,
			
			
			
				CAMP_ID = 27562,
			
			
				CREATE_TIME = '2020-05-14 13:55:06',
			
			
				UPDATE_TIME = '2020-06-30 00:00:06.343',
			
			
				WEIXIN_NAME = 'L100990950209',
			
			
				IS_END = 0,
			
			
				DELAY = 0,
			
			
				NAME = '顾杏',
			
			
				MOBILE = '18916350930',
			
			
				LOCATION = '中国大陆',
			
			
				GENDER = 'F',
			
			
				AGE = 27,
			
			
				HEIGHT = 165,
			
			
				WEIGHT = 83.5,
			
			
				WEIXIN_QRCODE = 'https://fop-fitcamp-resource.rjfittime.com/20976854-26eb-4cc9-9ae3-7c994eac5162.png?x-oss-process=image/resize,m_fill,w_1128,h_1353#',
			
			
				DISEASE_HISTORY = '无',
			
			
				SPORT_INJURY_HISTORY = '无',
			
			
				FITNESS_EXPERIENCE = '怀孕前健身，近两周恢复跳舞锻炼',
			
			
				REMARK = '无',
			
			
			
				BABY_MONTH = 21.00,
			
			
				BORN_TYPE = 1,
			
			
				IS_LACTATION = 0,
			
			
				VEGETARIAN_TYPE = 0,
			
			
				APPLY_STATUS = 0,
			
			
			
				SCORE = 0,
			
			
				TARGET = '{"1":{"weight":78.97089576721191,"waistLine":84.96551132202148}}',
			
			
			
			
			
			
			
				is_quit_group = 2,
			
			
				BABY_BIRTHDAY = '2018-09-14 00:00:00',
			
			
				BREASTMILK_RATIO = 1,
			
			
				hot_level = 4,
			
			
				water_level = 1,
			
			
				user_id = 12673458,
			
			
				athletic_ability_level = 'B2' 
		where APPLY_ID = 100006629}, respHandler=io.mycat.backend.mysql.nio.handler.RollbackNodeHandler@1b8a3f1a, host=172.31.100.106, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@c1f5dd7, writeQueue=0, modifiedSQLExecuted=true]
2020-06-30 23:16:31.162 DEBUG [$_NIOREACTOR-15-RW] (io.mycat.backend.mysql.nio.handler.RollbackReleaseHandler.okResponse(RollbackReleaseHandler.java:59)) - autocomit is false,but no commit or rollback ,so mycat rollbacked backend conn MySQLConnection@417949910 [id=530, lastTime=1593530191145, user=mycat_rw, schema=eshop, old shema=eshop, borrowed=true, fromSlaveDB=false, threadId=195708, charset=utf8, txIsolation=3, autocommit=false, attachment=null, respHandler=io.mycat.backend.mysql.nio.handler.RollbackReleaseHandler@2e53b378, host=172.31.100.106, port=3306, statusSync=io.mycat.backend.mysql.nio.MySQLConnection$StatusSync@c1f5dd7, writeQueue=0, modifiedSQLExecuted=true]

**Comment by junwen12221** [comment]
1675版本解决了readonly了

**Comment by itbright-cn** [comment]
@junwen12221 junwen12221  现在1.6.7.5 是不是只有test版本啊？

**Comment by itbright-cn** [comment]
@junwen12221  还有一个问题请教下，1.6.7下面的小版本比较多，1.6.7.1，1.6.7.3，1.6.7.4，1.6.7.5，这些每个版本的变更列表（change list ）在哪里可以找到？谢谢！

**Comment by itbright-cn** [comment]
> @junwen12221 junwen12221 现在1.6.7.5 是不是只有test版本啊？

我已经找到了1.6.7.5的release 版本了，谢谢。这个版本我再试下。

**Comment by itbright-cn** [comment]
> > @junwen12221 junwen12221 现在1.6.7.5 是不是只有test版本啊？
> 
> 我已经找到了1.6.7.5的release 版本了，谢谢。这个版本我再试下。
http://dl.mycat.org.cn/1.6.7.5/2020-4-10/

**Comment by gotodoit** [comment]
使用的5.6.29-mycat-1.6.7.6-release-20201104174609版本，还是存在这个问题，求解决，是否有配置可以修改？

**Comment by junwen12221** [comment]
@funnyAnt

**Comment by junwen12221** [comment]
@gotodoit 你找一下日志中出现的readonly的sql,贴一下

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/1.6.7.6/20201120140934
