### ISSUE TITLE
mycat集群配置，init_zk_data.sh执行报错

### ISSUE THREAD

**Issue by reckless-huang** [MyCATApache/Mycat-Server#2552]
hello
我使用zookeeper和mycat构建集群，但是在执行init_zk_data.sh导入配置到zookeeper中时报错，错误结果如下，zookeeper版本3.6.1 mycat版本 1.6.7.5 jdk 1.8.0_251
[root@rabbit-node1 zookeeper-3.6.1]# init_zk_data.sh 
o2020-07-13 09:40:01 INFO JAVA_CMD=/usr/local/jdk1.8.0_251/bin/java
o2020-07-13 09:40:01 INFO Start to initialize /mycat of ZooKeeper
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:41)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:257)
	at io.mycat.util.ZKUtils.createConnection(ZKUtils.java:62)
	at io.mycat.util.ZKUtils.<clinit>(ZKUtils.java:35)
	at io.mycat.config.loader.zkprocess.xmltozk.XmltoZkMain.buildConnection(XmltoZkMain.java:86)
	at io.mycat.config.loader.zkprocess.xmltozk.XmltoZkMain.main(XmltoZkMain.java:39)
o2020-07-13 09:40:01 ERROR Something wrong happened, please refer logs above
希望得到各位的帮助，顺便我们的qq群满了，进不去

**Comment by 457775987** [comment]
应该是版本问题吧zookeeper，你是自己用源码编译的吗？

**Comment by tonyfud** [comment]
我也遇到同样的问题。 zookeeper-3.4.14   Mycat-server-1675-release   .

**Comment by tonyfud** [comment]
tcpdump 也没发现  init_zk_data 时有连接过 zk ，没连接 zk 前就炸了 没抓到包。

**Comment by tonyfud** [comment]
用 git master 分支上的代码 自己构建后， 运行 init_zk_data 可以成功导入数据到 zookeeper 了。 可是启动的时候又遇到别的问题。 


2020-09-10 15:51:42.332 ERROR [Curator-PathChildrenCache-1] (org.apache.curator.framework.recipes.cache.PathChildrenCache.handleException(PathChildrenCache.java:584)) -
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /mycat/mycat-cluster-1/bindata
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:103) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1426) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291) ~[curator-client-4.0.1.jar:?]
        at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:230) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:224) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~[curator-client-4.0.1.jar:?]
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~[curator-client-4.0.1.jar:?]
        at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:221) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:206) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:35) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.createContainers(CuratorFrameworkImpl.java:247) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.EnsureContainers.internalEnsure(EnsureContainers.java:69) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.EnsureContainers.ensure(EnsureContainers.java:53) ~[curator-framework-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.ensurePath(PathChildrenCache.java:589) ~[curator-recipes-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:488) [curator-recipes-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35) ~[curator-recipes-4.0.1.jar:4.0.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:786) [curator-recipes-4.0.1.jar:4.0.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by reckless-huang** [comment]
> 用 git master 分支上的代码 自己构建后， 运行 init_zk_data 可以成功导入数据到 zookeeper 了。 可是启动的时候又遇到别的问题。
> 
> 2020-09-10 15:51:42.332 ERROR [Curator-PathChildrenCache-1] (org.apache.curator.framework.recipes.cache.PathChildrenCache.handleException(PathChildrenCache.java:584)) -
> org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /mycat/mycat-cluster-1/bindata
> at org.apache.zookeeper.KeeperException.create(KeeperException.java:103) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
> at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
> at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1426) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
> at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291) ~[curator-client-4.0.1.jar:?]
> at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:230) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:224) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~[curator-client-4.0.1.jar:?]
> at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~[curator-client-4.0.1.jar:?]
> at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:221) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:206) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:35) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.imps.CuratorFrameworkImpl.createContainers(CuratorFrameworkImpl.java:247) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.EnsureContainers.internalEnsure(EnsureContainers.java:69) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.EnsureContainers.ensure(EnsureContainers.java:53) ~[curator-framework-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.recipes.cache.PathChildrenCache.ensurePath(PathChildrenCache.java:589) ~[curator-recipes-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:488) [curator-recipes-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35) ~[curator-recipes-4.0.1.jar:4.0.1]
> at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:786) [curator-recipes-4.0.1.jar:4.0.1]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

我用1.6.7.1的mycat和3.5.8的zk 没有出现问题，可以尝试下我这个组合

**Comment by tonyfud** [comment]
我现在换回 1.6.7.4 了。 问题好了。 手贱用了最新版。
