### ISSUE TITLE
 TODO:insert into .... select .... not supported!

### ISSUE THREAD

**Issue by ethanxzw** [MyCATApache/Mycat-Server#2565]
now we face a issue about insert into sql as below. so any plan for achieving this function on mycat?
Mycat version: Mycat-server-1.6.6.1

java.sql.SQLNonTransientException: TODO:insert into .... select .... not supported!
        at io.mycat.route.parser.druid.impl.DruidInsertParser.parserBatchInsert(DruidInsertParser.java:311) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.parser.druid.impl.DruidInsertParser.statementParse(DruidInsertParser.java:82) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:76) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:122) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.route.RouteService.route(RouteService.java:138) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:291) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:237) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:149) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:375) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:395) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:551) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:533) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:201) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.6.1-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.6.1-release.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by funnyAnt** [comment]
属于约束语句，不支持的。请改写。
