### ISSUE TITLE
mycat  CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by zk123456** [MyCATApache/Mycat-Server#2586]
`Caused by: com.mysql.cj.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:223)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1443)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:952)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822)`

mysql驱动5.1.34
mycat1.6版本

**Comment by junwen12221** [comment]
可以尝试换个客户端

**Comment by zk123456** [comment]
@junwen12221  驱动的版本换了几个,都不行,之前用的8.0.12,后来降级的

**Comment by funnyAnt** [comment]
@zk123456  mycat后端的mysql版本是多少？ 应用报错的时候，Mycat的相关报错提供下。

**Comment by zk123456** [comment]
@funnyAnt  5.7.20  mycat已经升级了  新的1.6的mycat可以适应高版本的mysql驱动,已解决了
