### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: Unknown command

### ISSUE THREAD

**Issue by mawenbin666** [MyCATApache/Mycat-Server#2612]
1. mycat版本：
```
BuildTime  2020-02-09 14:22:52
GitVersion   738757c133cad7a06a690cb35196e00b37db2eab
MavenVersion 1.6.7.1-release
```
2.程序抛出的错误为：
```
2020-10-11 16:16:50 WARN - [xxl-job, admin JobScheduleHelper#scheduleThread]c.z.h.p.ProxyConnection : HikariCP - Connection com.mysql.cj.jdbc.ConnectionImpl@744a5b95 marked as broken because of SQLSTATE(08S01), ErrorCode(1047)
java.sql.SQLNonTransientConnectionException: Unknown command
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2056)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:393)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:160)
        at java.lang.Thread.run(Thread.java:745)
2020-10-11 16:16:50 ERROR - [xxl-job, admin JobScheduleHelper#scheduleThread]c.x.j.a.c.t.JobScheduleHelper : Unknown command
java.sql.SQLNonTransientConnectionException: Unknown command
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2056)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:393)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:160)
        at java.lang.Thread.run(Thread.java:745)
```
3.在mycat上对应的日志为：
```
2020-10-11 16:02:14.885  INFO [$_NIOREACTOR-2-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - ServerConnection [id=3800, schema=xxl_job, host=192.168.48.1, user=dml_xxl_job,txIsolation=3, autocommit=true, schema=xxl_job, executeSql=null]'dml_xxl_job' login success
2020-10-11 16:16:50.012  INFO [$_NIOREACTOR-2-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:stream closed ,ServerConnection [id=3800, schema=xxl_job, host=192.168.48.1, user=dml_xxl_job,txIsolation=3, autocommit=false, schema=xxl_job, executeSql=commit]
```
请问，遇到这种问题该怎么解决呢。

**Comment by funnyAnt** [comment]
- 1、这个问题必现吗
- 2、请打开下mycat的日志级别为debug，看下mycat收到的SQL语句

**Comment by junwen12221** [comment]
这个问题可以用新版本,
`<property name="ignoreUnknownCommand">0</property>`

<!-- 0遇上没有实现的报文(Unknown command:),就会报错、1为忽略该报文，返回ok报文。
