### ISSUE TITLE
mycat1.65版本 连接mysql8做高可用的时候切换不过去

### ISSUE THREAD

**Issue by namehuanxin** [MyCATApache/Mycat-Server#2617]
2020-10-22 17:42:05.090 ERROR [Timer0] (io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:114)) - JDBCHeartBeat error
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_251]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_251]
	at io.mycat.backend.jdbc.JDBCDatasource.getConnection(JDBCDatasource.java:109) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:100) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.backend.datasource.PhysicalDatasource.doHeartbeat(PhysicalDatasource.java:440) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.backend.datasource.PhysicalDBPool.doHeartbeat(PhysicalDBPool.java:345) ~[Mycat-server-1.6.5-release.jar:?]
	at io.mycat.MycatServer$8$1.run(MycatServer.java:897) ~[Mycat-server-1.6.5-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	... 13 more
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_251]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_251]
	at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_251]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.19.jar:8.0.19]

配置文件：
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
</schema>
	<dataNode name="dn1" dataHost="db1" database="dream" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1">
			<heartbeat>select user()</heartbeat>
		<writeHost host="host1" url="jdbc:mysql://192.168.1.57:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host2" url="jdbc:mysql://192.168.1.61:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
		<writeHost host="host3" url="jdbc:mysql://192.168.1.58:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host4" url="jdbc:mysql://192.168.1.68:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
	</dataHost>
</mycat:schema>

问题描述：
正常情况是这样
mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           4 |
+-------------+
1 row in set (0.01 sec)

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           3 |
+-------------+
1 row in set (0.00 sec)

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           1 |
+-------------+
1 row in set (0.01 sec)

mysql> begin ;select @@server_id; commit;
Query OK, 0 rows affected (0.00 sec)

+-------------+
| @@server_id |
+-------------+
|           2 |
+-------------+
1 row in set (0.01 sec)

关掉主的那台server_id=2那台，后会切换不过去，而且1还在读，不会成为主的，做写入操作会报错

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           1 |
+-------------+
1 row in set (0.01 sec)

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           3 |
+-------------+
1 row in set (0.00 sec)

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           1 |
+-------------+
1 row in set (0.01 sec)

mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           3 |
+-------------+
1 row in set (0.01 sec)

mysql> begin ;select @@server_id; commit;
Query OK, 0 rows affected (0.00 sec)

ERROR: 
No operations allowed after connection closed.
ERROR 1003 (HY000): Transaction error, need to rollback.
mysql> begin ;select @@server_id; commit;
Query OK, 0 rows affected (0.00 sec)

ERROR 1003 (HY000): Transaction error, need to rollback. errno:0 No operations allowed after connection closed.
ERROR 1003 (HY000): Transaction error, need to rollback.
mysql>

**Comment by namehuanxin** [comment]
配置文件

<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
</schema>
	<dataNode name="dn1" dataHost="db1" database="dream" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1">
			<heartbeat>select user()</heartbeat>
		<writeHost host="host1" url="jdbc:mysql://192.168.1.57:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host2" url="jdbc:mysql://192.168.1.61:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
		<writeHost host="host3" url="jdbc:mysql://192.168.1.58:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host4" url="jdbc:mysql://192.168.1.68:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
	</dataHost>
</mycat:schema>

**Comment by namehuanxin** [comment]
<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
</schema>
	<dataNode name="dn1" dataHost="db1" database="dream" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1">
			<heartbeat>select user()</heartbeat>
		<writeHost host="host1" url="jdbc:mysql://192.168.1.57:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host2" url="jdbc:mysql://192.168.1.61:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
		<writeHost host="host3" url="jdbc:mysql://192.168.1.58:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host4" url="jdbc:mysql://192.168.1.68:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
	</dataHost>
</mycat:schema>

**Comment by namehuanxin** [comment]
![Uploading image.png…]()

**Comment by namehuanxin** [comment]
</schema>
	<dataNode name="dn1" dataHost="db1" database="dream" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1">
			<heartbeat>select user()</heartbeat>
		<writeHost host="host1" url="jdbc:mysql://192.168.1.57:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host2" url="jdbc:mysql://192.168.1.61:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
		<writeHost host="host3" url="jdbc:mysql://192.168.1.58:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host4" url="jdbc:mysql://192.168.1.68:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
	</dataHost>

**Comment by namehuanxin** [comment]
</schema>
	<dataNode name="dn1" dataHost="db1" database="dream" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1">
			<heartbeat>select user()</heartbeat>
		<writeHost host="host1" url="jdbc:mysql://192.168.1.57:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host2" url="jdbc:mysql://192.168.1.61:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
		<writeHost host="host3" url="jdbc:mysql://192.168.1.58:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1"
				   password="DreamSoft_123">
			<readHost host="host4" url="jdbc:mysql://192.168.1.68:3306?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;serverTimezone=UTC" user="mycat1" password="DreamSoft_123" />
		</writeHost>
	</dataHost>
