### ISSUE TITLE
字符编码bug

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#262]
mysql 5.6 
服务器字符编码是：
mysql> show variables like '%char%';
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| character_set_client     | utf8                          |
| character_set_connection | utf8                          |
| character_set_database   | utf8mb4                       |
| character_set_filesystem | binary                        |
| character_set_results    | utf8                          |
| character_set_server     | utf8mb4                       |
| character_set_system     | utf8                          |
| character_sets_dir       | /home/q/mysql/share/charsets/ |
+--------------------------+-------------------------------+
8 rows in set (0.29 sec)

在使用mysql native方式时，查询表总是包字符编码错误

java.lang.RuntimeException: java.io.UnsupportedEncodingException: maccecias
	at org.opencloudb.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:278) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:457) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mysql.nio.MySQLConnection.execute(MySQLConnection.java:393) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mysql.nio.handler.SingleNodeHandler._execute(SingleNodeHandler.java:145) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:118) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:129) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:216) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:73) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96) [mycat-server-1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.io.UnsupportedEncodingException: maccecias
	at java.lang.StringCoding.encode(StringCoding.java:341) ~[na:1.7.0_45]
	at java.lang.String.getBytes(String.java:916) ~[na:1.7.0_45]
	at org.opencloudb.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:276) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	... 18 common frames omitted

经过查看CharsetUtil中maccecias中对应的index是45. 然后分析报文。经过dba同学调试帮忙，发现45对应的字符编码是utf8mb4，而不是CharsetUtil中的maccecias.   刚好也跟我的服务器字符设计对应。

**Comment by runfriends** [comment]
https://github.com/alibaba/cobar/issues/26 

看来这是个陈年老bug了



runfriends@126.com
 
发件人： zhouwenbin2000
发送时间： 2015-04-30 16:07
收件人： MyCATApache/Mycat-Server
主题： [Mycat-Server] 字符编码bug (#262)
mysql 5.6 
服务器字符编码是：
mysql> show variables like '%char%';
+--------------------------+-------------------------------+
| Variable_name | Value |
+--------------------------+-------------------------------+
| character_set_client | utf8 |
| character_set_connection | utf8 |
| character_set_database | utf8mb4 |
| character_set_filesystem | binary |
| character_set_results | utf8 |
| character_set_server | utf8mb4 |
| character_set_system | utf8 |
| character_sets_dir | /home/q/mysql/share/charsets/ |
+--------------------------+-------------------------------+
8 rows in set (0.29 sec)
在使用mysql native方式时，查询表总是包字符编码错误
java.lang.RuntimeException: java.io.UnsupportedEncodingException: maccecias
at org.opencloudb.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:278) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:457) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.mysql.nio.MySQLConnection.execute(MySQLConnection.java:393) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.mysql.nio.handler.SingleNodeHandler._execute(SingleNodeHandler.java:145) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:118) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:129) ~[mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:216) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:73) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267) [mycat-server-1.4-SNAPSHOT.jar:na]
at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96) [mycat-server-1.4-SNAPSHOT.jar:na]
at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.io.UnsupportedEncodingException: maccecias
at java.lang.StringCoding.encode(StringCoding.java:341) ~[na:1.7.0_45]
at java.lang.String.getBytes(String.java:916) ~[na:1.7.0_45]
at org.opencloudb.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:276) ~[mycat-server-1.4-SNAPSHOT.jar:na]
... 18 common frames omitted
经过查看CharsetUtil中maccecias中对应的index是45. 然后分析报文。经过dba同学调试帮忙，发现45对应的字符编码是utf8mb4，而不是CharsetUtil中的maccecias. 刚好也跟我的服务器字符设计对应。

**Comment by zhouwenbin2000** [comment]
各个版本的字符集编码的index不一样？

**Comment by linzhiqiang0514** [comment]
请验证这个问题是否以修复？

**Comment by zhouwenbin2000** [comment]
已经修复了

**Comment by ywooer** [comment]
@linzhiqiang0514 这个问题在Mycat-server-1.3.0.3-release-20150527095523-linux.tar.gz版本复现了……
