### ISSUE TITLE
java.lang.NumberFormatException: Value out of range. Value:"65535" Radix:10

### ISSUE THREAD

**Issue by zhengweisk** [MyCATApache/Mycat-Server#2622]
2020-10-27 06:00:26.828  WARN [$_NIOREACTOR-1-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:118)) - caught err:
java.lang.NumberFormatException: Value out of range. Value:"65535" Radix:10
	at java.lang.Short.parseShort(Short.java:120) ~[?:1.8.0_265]
	at java.lang.Short.parseShort(Short.java:144) ~[?:1.8.0_265]
	at io.mycat.util.ByteUtil.getShort(ByteUtil.java:158) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.mysql.BinaryRowDataPacket.convert(BinaryRowDataPacket.java:163) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.mysql.BinaryRowDataPacket.read(BinaryRowDataPacket.java:97) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:515) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:232) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:137) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:82) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:269) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.5-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by funnyAnt** [comment]
@zhengweisk  提供下mysql数据库里面数据的值，初步看是prepare语句结果集转换的时候超出了short范围。

**Comment by junwen12221** [comment]
收到的数据是无符号short,但是被作为有符号short处理超出范围报错

**Comment by funnyAnt** [comment]
@zhengweisk 已经解决。
