### ISSUE TITLE
Mycat-server-1.6.7.6-release启动后数据无法插入

### ISSUE THREAD

**Issue by luolt** [MyCATApache/Mycat-Server#2638]
2020-11-04 16:32:18.740  WARN [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.MySQLConnectionHandler.setResponseHandler(MySQLConnectionHandler.java:166)) - try to reset resultStatus. last responseHandler:io.mycat.backend.mysql.nio.handler.PrepareRequestHandler@1165b4fa, resultStatus = 3
2020-11-04 16:32:18.743 ERROR [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleErrorPacket(MySQLConnectionHandler.java:222)) - receive ErrorPacket but no handler
2020-11-04 16:32:18.745  WARN [$_NIOREACTOR-5-RW] (io.mycat.backend.mysql.nio.MySQLConnectionHandler.closeNoHandler(MySQLConnectionHandler.java:272))- no handler bind in this con io.mycat.backend.mysql.nio.MySQLConnectionHandler@41953738 client:MySQLConnection@1892869212 [id=5, lastTime=1604478738724, user=program_common, schema=vxy_log_db1, old shema=vxy_log_db1, borrowed=false, fromSlaveDB=false, threadId=6657, charset=utf8, txIsolation=3, autocommit=true, txReadonly=false, attachment=null, respHandler=null, host=192.168.1.3, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2020-11-04 16:32:18.866 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.nio.handler.PrepareRequestHandler.parseTables(PrepareRequestHandler.java:132)) - can not get column count
java.lang.IllegalArgumentException: not support visitor type : com.alibaba.druid.sql.visitor.SchemaStatVisitor
 at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlUpdateStatement.accept0(MySqlUpdateStatement.java:75) ~[druid-1.0.26.jar:1.0.26]
 at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.26.jar:1.0.26]
 at io.mycat.backend.mysql.nio.handler.PrepareRequestHandler.parseTables(PrepareRequestHandler.java:129) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.backend.mysql.nio.handler.PrepareRequestHandler.execute(PrepareRequestHandler.java:64) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:121) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.FrontendConnection.stmtPrepare(FrontendConnection.java:442) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:92) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
 at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
2020-11-04 16:32:18.869  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler$1.callback(ServerPrepareHandler.java:112)) - Get prepare meta data error: can't find route node

**Comment by funnyAnt** [comment]
@luolt  提供下
   schema.xml表配置信息，
  rule.xml里面的分片规则，
  prepare测试相关语句的代码片段
