### ISSUE TITLE
1.6.7.6版本连接卡死和select 1影响后续查询结果

### ISSUE THREAD

**Issue by outman-dd** [MyCATApache/Mycat-Server#2648]
1.show create table语句不在本库执行，第一次有返回，第二次卡死，executeSqlQueue没有释放
2.开启select 1 心跳时，执行查询不正确。aa_id为1588837346550218752数据库中存在的数据

mysql> use AAA;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select 1;
+------+
| 1    |
+------+
| 1    |
+------+
1 row in set (0.00 sec)

mysql> select * from aa  WHERE aa_id = 1588837346550218752;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

mysql>

**Comment by funnyAnt** [comment]
@outman-dd show create table语句不在本库执行,是什么意思？ 举个例子

**Comment by funnyAnt** [comment]
@junwen12221  请审查，如果没问题请重新打包放到官网。这2个问题是我之前增加功能引入。#2542 #2590

**Comment by junwen12221** [comment]
/var/www/dlcache/1.6.7.6/20201112144313

**Comment by outman-dd** [comment]
@junwen12221 最新版本http://dl.mycat.org.cn/1.6.7.6/20201112144313/ 查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死

(io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:925)) - io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@3bc6b875 caught exception 
java.lang.NullPointerException: null
        at io.mycat.sqlengine.mpp.DataMergeService.run(DataMergeService.java:244) [Mycat-server-1.6.7.6-release.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]


java.lang.NullPointerException: null
        at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.connectionError(MultiNodeQueryHandler.java:338) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.execute(MultiNodeQueryHandler.java:244) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:169) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:360) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:275) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:123) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:95) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:397) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:417) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]

**Comment by junwen12221** [comment]
@outman-dd 
http://dl.mycat.org.cn/1.6.7.6/20201113201359/

测试一下,但是mycat出现连接异常可以换成jdbc连接方式,流控减少这个情况

**Comment by funnyAnt** [comment]
@outman-dd   `查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死` 这个问题我来排查下

**Comment by outman-dd** [comment]
> @outman-dd ` `查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死` `，这个问题我来排查下

连接数不够用时候，抓包看了下，一次请求回了两个数据包，一个是ERR Packet(NullpointerException)，另一个是表字段的描述，两个回包顺序不确定

**Comment by outman-dd** [comment]
> @outman-dd
> http://dl.mycat.org.cn/1.6.7.6/20201113201359/
> 
> 测试一下,但是mycat出现连接异常可以换成jdbc连接方式,流控减少这个情况

这个版本，查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死的情况还存在

**Comment by outman-dd** [comment]
> > @outman-dd ` `查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死` `，这个问题我来排查下
> 
> 连接数不够用时候，抓包看了下，一次请求回了两个数据包，一个是ERR Packet(NullpointerException)，另一个是表字段的描述，两个回包顺序不确定

@funnyAnt 表字段描述先回，连接必卡死

**Comment by funnyAnt** [comment]
@outman-dd  确认后本周内修复

**Comment by funnyAnt** [comment]
####  查询已存在数据，路由到多个分片，后端连接不够用时候，会出现客户端连接卡死， 原因
   conn为null时，为判断处理，导致直接到RWReactor异常处理模块。

#### 修复说明
  增加判断conn是否为null  @outman-dd

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/1.6.7.6/20201124193646/
