### ISSUE TITLE
mycat报错 Invalid DataSource:0

### ISSUE THREAD

**Issue by zhoufeilongjava** [MyCATApache/Mycat-Server#2654]
dataNode 配置 
``<dataNode name="test_$25001-28000" dataHost="test" database="test_$25001-28000" />``

实例该实例中的database只有test_25001到test_27213，修改配置为
`<dataNode name="test_$25001-27800" dataHost="test" database="test_$25001-27800" />`
则可以正常访问。

**Comment by zhoufeilongjava** [comment]
2020-11-12 20:43:50.537  INFO [$_NIOREACTOR-17-RW] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:419)) - init result :finished 2 success 0 target count:2
2020-11-12 20:43:50.537 ERROR [$_NIOREACTOR-17-RW] (io.mycat.backend.datasource.PhysicalDBPool.init(PhysicalDBPool.java:379)) - #!MyCat#emc_user_v49 init failure
2020-11-12 20:43:50.538  WARN [$_NIOREACTOR-17-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:207)) - ServerConnection [id=1, schema=emc_user, host=220.184.236.193, user=r
oot,txIsolation=3, autocommit=true, schema=emc_user, executeSql=/*!mycat:dataNode=emc_user_26211 */select db_id, id,number, shop_id, total_price, client_id, free, sale, pos_payment, mask_code, ctime, utime from do
cument_list where number=1001823 and `type`=1 and dtime=0]select db_id, id,number, shop_id, total_price, client_id, free, sale, pos_payment, mask_code, ctime, utime from document_list where number=1001823 and `typ
e`=1 and dtime=0, route={
   1 -> emc_user_26211{select db_id, id,number, shop_id, total_price, client_id, free, sale, pos_payment, mask_code, ctime, utime from document_list where number=1001823 and `type`=1 and dtime=0}
}
java.lang.IllegalArgumentException: Invalid DataSource:0
	at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:146) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:203) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:148) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:314) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:241) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:95) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.4-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
2020-11-12 20:43:50.539 ERROR [$_NIOREACTOR-17-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=1, schema=emc_user, host=220.184.236.193, user=root,txIsolat
ion=3, autocommit=true, schema=emc_user, executeSql=/*!mycat:dataNode=emc_user_26211 */select db_id, id,number, shop_id, total_price, client_id, free, sale, pos_payment, mask_code, ctime, utime from document_list
where number=1001823 and `type`=1 and dtime=0]Invalid DataSource:0java.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .connectionError263
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .execute209
io.mycat.server.NonBlockingSession .execute148
io.mycat.server.ServerConnection .routeEndExecuteSQL314
io.mycat.server.ServerConnection .execute241
io.mycat.server.handler.SelectHandler .handle105
io.mycat.server.ServerQueryHandler .query95
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76

**Comment by junwen12221** [comment]
检查一下是否有心跳错误的异常

**Comment by zhoufeilongjava** [comment]
2020-11-13 09:33:31.116  WARN [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:91)) - can't connect to mysql server ,errmsg:Unknown database 'emc_user_27800' MySQLConnection@1057444296 [id=4574, lastTime=1605231211100, user=mycat, schema=emc_user_27800, old shema=emc_user_27800, borrowed=false, fromSlaveDB=false, threadId=2027186, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=rm-bp1p2ymbno7lqhhhy.mysql.rds.aliyuncs.com, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2020-11-13 09:33:31.116  INFO [$_NIOREACTOR-0-RW] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2020-11-13 09:33:31.116  WARN [$_NIOREACTOR-0-RW] (io.mycat.backend.heartbeat.MySQLDetector.onResult(MySQLDetector.java:208)) - heart beat error: hostM1/emc_user_v49 retry=10 tmo=30000
2020-11-13 09:33:31.116 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=rm-bp1p2ymbno7lqhhhy.mysql.rds.aliyuncs.com:3306]

**Comment by zwyqz** [comment]
应该配置为test_$25001-27213 没有的节点就不要配置了

**Comment by zhoufeilongjava** [comment]
我们的业务场景，库是动态增加的，该实例的库最终会创建到28000，这里是否有可以关闭检查的设置项。

**Comment by zwyqz** [comment]
你们可以一次性把28000个库都建好
