### ISSUE TITLE
[BUG]默认配置randomDataNode，导致单表找不到的问题

### ISSUE THREAD

**Issue by RankRao** [MyCATApache/Mycat-Server#2679]
版本：Mycat-server-1.6.7.6-release

报错信息：2020-12-11 10:00:19.265  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.handler.SetHandler.handle(SetHandler.java:194)) - ServerConnection [id=1, schema=TESTDB, host=192.168.145.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB, executeSql=SET PROFILING = 1]SET PROFILING = 1 is not recoginized and ignored
2020-12-11 10:00:19.288  WARN [$_NIOREACTOR-0-RW] (io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1259)) - can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
2020-12-11 10:00:19.288  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:341)) - ServerConnection [id=1, schema=TESTDB, host=192.168.145.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB, executeSql=select afid,coin,birthday from user_test as a]select afid,coin,birthday from user_test as a err:java.sql.SQLNonTransientException: can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
java.sql.SQLNonTransientException: can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1260) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:574) ~[Mycat-server-1.6.7.6-release.jar:?]

查询sql：select afid,coin,birthday from user_test;

user_test为dn1节点的单表，未进行分区或者分表，也未加入到schema的<table>配置中。

schema默认配置：

```xml
<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100" randomDataNode="dn1">
```

RouterUtil.java多表路由

```java
	public static RouteResultset tryRouteForTables(SchemaConfig schema, DruidShardingParseInfo ctx,
			RouteCalculateUnit routeUnit, RouteResultset rrs, boolean isSelect, LayerCachePool cachePool)
			throws SQLNonTransientException {

		List<String> tables = ctx.getTables();

         // ###设想的是走到这个过程
		if(schema.isNoSharding()||(tables.size() >= 1&&isNoSharding(schema,tables.get(0)))) {
			return routeToSingleNode(rrs, schema.getDataNode(), ctx.getSql());
		}
		
		.....
				for(String tableName : tables) {

			TableConfig tableConfig = schema.getTables().get(tableName.toUpperCase());

			if(tableConfig == null) {
				//add 如果表读取不到则先将表名从别名中读取转化后再读取
				String alias = ctx.getTableAliasMap().get(tableName);
				if(!StringUtil.isEmpty(alias)){
					tableConfig = schema.getTables().get(alias.toUpperCase());
				}
                  // ###实际的是走到这个过程
				if(tableConfig == null){
					String msg = "can't find table define in schema "+ tableName + 
							" alias：" + alias + ", schema:" + schema.getName();
					LOGGER.warn(msg);
					throw new SQLNonTransientException(msg);
				}

			}
			
			......
						}
		}
```

修改schema默认配置：

```xml
<schema name="TESTDB" checkSQLschema="true" dataNode="dn1" randomDataNode="dn1">
```

问题解决。

当前版本，randomDataNode随机节点不能完全代替dataNode功能。

**Comment by RankRao** [comment]
版本：Mycat-server-1.6.7.6-release

报错信息：2020-12-11 10:00:19.265  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.handler.SetHandler.handle(SetHandler.java:194)) - ServerConnection [id=1, schema=TESTDB, host=192.168.145.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB, executeSql=SET PROFILING = 1]SET PROFILING = 1 is not recoginized and ignored
2020-12-11 10:00:19.288  WARN [$_NIOREACTOR-0-RW] (io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1259)) - can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
2020-12-11 10:00:19.288  WARN [$_NIOREACTOR-0-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:341)) - ServerConnection [id=1, schema=TESTDB, host=192.168.145.1, user=root,txIsolation=3, autocommit=true, schema=TESTDB, executeSql=select afid,coin,birthday from user_test as a]select afid,coin,birthday from user_test as a err:java.sql.SQLNonTransientException: can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
java.sql.SQLNonTransientException: can't find table define in schema USER_TEST alias：user_test, schema:TESTDB
	at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1260) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:574) ~[Mycat-server-1.6.7.6-release.jar:?]

查询sql：select afid,coin,birthday from user_test;

user_test为dn1节点的单表，未进行分区或者分表，也未加入到schema的<table>配置中。

schema默认配置：

```xml
<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100" randomDataNode="dn1">
```

RouterUtil.java多表路由

```java
	public static RouteResultset tryRouteForTables(SchemaConfig schema, DruidShardingParseInfo ctx,
			RouteCalculateUnit routeUnit, RouteResultset rrs, boolean isSelect, LayerCachePool cachePool)
			throws SQLNonTransientException {

		List<String> tables = ctx.getTables();

         // ###设想的是走到这个过程
		if(schema.isNoSharding()||(tables.size() >= 1&&isNoSharding(schema,tables.get(0)))) {
			return routeToSingleNode(rrs, schema.getDataNode(), ctx.getSql());
		}
		
		.....
				for(String tableName : tables) {

			TableConfig tableConfig = schema.getTables().get(tableName.toUpperCase());

			if(tableConfig == null) {
				//add 如果表读取不到则先将表名从别名中读取转化后再读取
				String alias = ctx.getTableAliasMap().get(tableName);
				if(!StringUtil.isEmpty(alias)){
					tableConfig = schema.getTables().get(alias.toUpperCase());
				}
                  // ###实际的是走到这个过程
				if(tableConfig == null){
					String msg = "can't find table define in schema "+ tableName + 
							" alias：" + alias + ", schema:" + schema.getName();
					LOGGER.warn(msg);
					throw new SQLNonTransientException(msg);
				}

			}
			
			......
						}
		}

	/**
	 * 增加判断支持未配置分片的表走默认的dataNode
	 * @param schemaConfig
	 * @param tableName
	 * @return
	 */
	public static boolean isNoSharding(SchemaConfig schemaConfig, String tableName) {
		// Table名字被转化为大写的，存储在schema
		tableName = tableName.toUpperCase();
		if (schemaConfig.isNoSharding()) {
			return true;
		}
         // ###默认配置导致getDataNode()获取到空值
		if (schemaConfig.getDataNode() != null && !schemaConfig.getTables().containsKey(tableName)) {
			return true;
		}

		return false;
	}
```

修改schema默认配置：

```xml
<schema name="TESTDB" checkSQLschema="true" dataNode="dn1" randomDataNode="dn1">
```

问题解决。

当前版本，randomDataNode随机节点不能完全代替dataNode功能。

**Comment by junwen12221** [comment]
randomDataNode与dataNode是两个独立的功能,默认是不需要配置randomDataNode
