### ISSUE TITLE
当JDBC连接的不是mysql数据库时，delete语句报异常

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#269]
[2015-05-04 21:06:04 ERROR org.opencloudb.route.impl.DruidMycatRouteStrategy:52] [$_NIOREACTOR-3-RW] DruidMycatRouteStrategyError
com.alibaba.druid.sql.parser.ParserException: ERROR. token : DELETE, pos : 6
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:545) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:118) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:457) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceQueryTableExpr(SQLSelectParser.java:361) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:349) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:272) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:152) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:167) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1655) ~[druid-1.0.12.jar:1.0.12]
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:49) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:58) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.route.RouteService.route(RouteService.java:118) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:204) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:120) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96) [mycat-server-1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
[2015-05-04 21:06:04  WARN org.opencloudb.server.ServerConnection:209] [$_NIOREACTOR-3-RW] ServerConnection [id=1, schema=des_trade, host=0:0:0:0:0:0:0:1, user=root,txIsolation=3, autocommit=true, schema=des_trade]delete from order_ext where id=5 err:java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: ERROR. token : DELETE, pos : 6
java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: ERROR. token : DELETE, pos : 6
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:53) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:58) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.route.RouteService.route(RouteService.java:118) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:204) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:120) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267) [mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96) [mycat-server-1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: com.alibaba.druid.sql.parser.ParserException: ERROR. token : DELETE, pos : 6
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:545) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:118) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:457) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceQueryTableExpr(SQLSelectParser.java:361) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:349) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:272) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:152) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:167) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1655) ~[druid-1.0.12.jar:1.0.12]
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:49) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	... 14 common frames omitted

**Comment by magicdoom** [comment]
已经提交了修正代码，请测试

**Comment by zhouwenbin2000** [comment]
已经验证。
