### ISSUE TITLE
1.6.7.6版本ConcurrentModificationException异常

### ISSUE THREAD

**Issue by outman-dd** [MyCATApache/Mycat-Server#2702]
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_162]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_162]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_162]
        at io.mycat.cache.DefaultLayedCachePool.getAllCacheStatic(DefaultLayedCachePool.java:149) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.cache.DefaultLayedCachePool.getCacheStatic(DefaultLayedCachePool.java:124) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.route.parser.druid.impl.DruidUpdateParser.statementParse(DruidUpdateParser.java:82) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:76) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST0(DruidMycatRouteStrategy.java:156) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:100) ~[Mycat-server-1.6.7.6-release.jar:?]
        at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:83) ~[Mycat-server-1.6.7.6-release.jar:?]

并发情况下，某一个update语句下出现ConcurrentModificationException

**Comment by funnyAnt** [comment]
@outman-dd 问题待确认
