### ISSUE TITLE
Mycat 1.6 Release 当Insert的数据量大的时候，会写入失败

### ISSUE THREAD

**Issue by YouZhengChuan** [MyCATApache/Mycat-Server#2716]
我搭建了一个mycat服务，用来测试对grafana服务的mysql后端做代理，grafana 的mysql配置切换到mycat后，能成功启动，读取数据正常，但是编辑dashboard后无法保存。

我测试了下同样的操作，和直接连接mysql对比，通过mysqlbinlog观察，发现是grafana每次更新会将dashboard的文本内容全量写入，内容字节数很大，直接写入mysql正常，但是通过mycat写入则失败。

mycat 报错日志：

```

jvm 1    | 2021-01-12 16:17:28,081 [WARN ][$_NIOREACTOR-0-RW] caught err: java.lang.IllegalArgumentException: Illegal group reference
jvm 1    | 	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
jvm 1    | 	at java.util.regex.Matcher.replaceFirst(Matcher.java:1004)
jvm 1    | 	at java.lang.String.replaceFirst(String.java:2178)
jvm 1    | 	at io.mycat.server.handler.ServerPrepareHandler.prepareStmtBindValue(ServerPrepareHandler.java:222)
jvm 1    | 	at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:135)
jvm 1    | 	at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:386)
jvm 1    | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:99)
jvm 1    | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
jvm 1    | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
jvm 1    | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
jvm 1    | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
jvm 1    | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
jvm 1    | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:107)
jvm 1    | 2021-01-12 16:17:28,081 [INFO ][$_NIOREACTOR-0-RW] close connection,reason:program err:java.lang.IllegalArgumentException: Illegal group reference ,ServerConnection [id=1, schema=grafana7, host=10.24.0.114, user=grafana-dev,txIsolation=3, autocommit=false, schema=grafana7]  (io.mycat.net.AbstractConnection:AbstractConnection.java:508)
```

引起mycat异常的操作语句如下，因为语句特别长，无法复制，只能截图：

![image](https://user-images.githubusercontent.com/3882312/104289488-28e85400-54f4-11eb-89ce-d208a1b9f7b2.png)

**Comment by YouZhengChuan** [comment]
最新版本 `Mycat-server-1.6.7.5-release-20200422133810-linux` 已经没有这个问题了，我认为可以关闭这个issue了。
