### ISSUE TITLE
ERROR 1003 (HY000): Reload config failure

### ISSUE THREAD

**Issue by root2000xyz** [MyCATApache/Mycat-Server#274]
MySQL [(none)]> reload @@config;
ERROR 1003 (HY000): Reload config failure

查看mycat.log里的日志
05/06 10:35:38.132   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:35:44.132   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=220, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:35:44.133   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:35:50.134   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=221, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:35:50.134   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:35:56.135   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=222, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:35:56.136   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:36:02.136   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=223, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:36:02.137   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:36:08.139   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=224, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:36:08.139   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
05/06 10:36:14.139   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:386) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=225, schema=null, host=172.16.110.166, user=null,txIsolation=3, autocommit=true, schema=null]
05/06 10:36:14.140   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)

每次调整配置都需要./mycat stop 然后start
STATUS | wrapper  | 2015/05/06 10:14:25 | TERM trapped.  Shutting down.
STATUS | wrapper  | 2015/05/06 10:14:26 | <-- Wrapper Stopped
STATUS | wrapper  | 2015/05/06 10:14:29 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/05/06 10:14:29 | Launching a JVM...
INFO   | jvm 1    | 2015/05/06 10:14:30 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2015/05/06 10:14:30 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2015/05/06 10:14:30 | 
INFO   | jvm 1    | 2015/05/06 10:14:30 | log4j 2015-05-06 10:14:30 [./conf/log4j.xml] load completed.
INFO   | jvm 1    | 2015/05/06 10:14:31 | MyCAT Server startup successfully. see logs in logs/mycat.log

**Comment by mycatmerger** [comment]
reload 1.5会进行彻底改进
