### ISSUE TITLE
java.lang.NullPointerException  io.mycat.route.parser.druid.impl.DruidUpdateParser.statementParse

### ISSUE THREAD

**Issue by goudai** [MyCATApache/Mycat-Server#2759]
**1、bug描述** 
 简单清晰描述下bug现象.
mycat运行一段时候后抛出如下空指针，片键是order_id
2021-03-20 18:18:13.408  WARN [$_NIOREACTOR-6-RW] (io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:281)) - ServerConnection [id=1014, schema=pay_cashier_center_shard, host=0.0.0.0, user=usvr_uploadsql,txIsolation=3, autocommit=true, schema=pay_cashier_center_shard]update t_refund set status =1 where order_id = 'xxxx' err:java.lang.NullPointerException
java.lang.NullPointerException
	at io.mycat.route.parser.druid.impl.DruidUpdateParser.statementParse(DruidUpdateParser.java:39) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:64) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.route.RouteService.route(RouteService.java:133) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:276) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:318) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:338) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:488) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:470) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:322) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:274) ~[Mycat-server-1.6-RELEASE.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6-RELEASE.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
**2、版本号(非常重要)**
 v 1.6-release

**Comment by funnyAnt** [comment]
单独执行下 `update t_refund set status =1 where order_id = 'xxxx' ` 看是否报错。

对应的代码，是获取表名的地方报错。

**Comment by goudai** [comment]
单独执行不爆粗。是偶尔来一下。

**Comment by funnyAnt** [comment]
@goudai  http://dl.mycat.org.cn/1.6.7.6/20210303094759/ 里面下载最新的1.6.76版本试下
