### ISSUE TITLE
进行Insert数据时mycat崩溃，错误日志如下

### ISSUE THREAD

**Issue by root2000xyz** [MyCATApache/Mycat-Server#276]
05/06 15:01:47.895   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)
执行的语句：
insert into yx_orders(id,ordercode,orderType,orderstatus,createt_ime) VALUE(226,UUID(),'test','1',NOW());
 insert into yx_detials(id,orderid,createby,startby,createt_ime) values(6,226,'dd',1,now());
是否与配置有关？

**Comment by magicdoom** [comment]
是insert into VALUES；  不是VALUE；   少了个S

**Comment by root2000xyz** [comment]
thank you!
