### ISSUE TITLE
dataNode为PG时无法连接Mycat

### ISSUE THREAD

**Issue by hanxu00920** [MyCATApache/Mycat-Server#2762]
**1、bug描述** 
当dn为pg数据库时，无法登录数据库，报错信息：”ERROR: missing FROM-clause entry for table "session"“

**2、版本号(非常重要)**
 v 1.6.7.6-release

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="postgres" checkSQLschema="true" sqlMaxLimit="100">
		<table name="tb_order" primaryKey="order_no" dataNode="pg1,pg2" rule="order_rule"></table>
		
		
		<table name="tb_order_info" primaryKey="order_id" autoIncrement="true" dataNode="pg1,pg2" rule="order_info_rule"></table>
	</schema>

	<dataNode name="pg1" dataHost="hx-pg-1" database="postgres" />
	<dataNode name="pg2" dataHost="hx-pg-2" database="postgres" />

	<dataHost name="hx-pg-1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="postgresql" dbDriver="jdbc">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM1" url="jdbc:postgresql://192.168.187.3:5432/postgres" user="postgres"
				   password="x">
		</writeHost>
	</dataHost>

	<dataHost name="hx-pg-2" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="postgresql" dbDriver="jdbc">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM2" url="jdbc:postgresql://192.168.187.4:5432/postgres" user="postgres"
				   password="x">
		</writeHost>
	</dataHost>
</mycat:schema>
  rule.xml (涉及到的路由函数)
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mycat:rule SYSTEM "rule.dtd">
<mycat:rule xmlns:mycat="http://io.mycat/">
	<tableRule name="order_rule">
		<rule>
			<columns>order_no</columns>
			<algorithm>order_func</algorithm>
		</rule>
	</tableRule>

	<tableRule name="order_info_rule">
		<rule>
			<columns>order_no</columns>
			<algorithm>order_info_func</algorithm>
		</rule>
	</tableRule>

	<function name="order_func" class="io.mycat.route.function.PartitionByLong">
		<property name="partitionCount">2</property>
		<property name="partitionLength">512</property>
	</function>

	<function name="order_info_func" class="io.mycat.route.function.PartitionByFileMap">
		<property name="mapFile">partition-hash-int.txt</property>
		<property name="type">0</property>
		<property name="defaultNode">0</property>
	</function>
</mycat:rule>
  server.xml(可选)

**4、操作步骤**
1.启动Mycat服务
2.通过DBeaver数据库工具，以mysql jdbc方式连接mycat
3.或是通过mysql -u -d -P -p登录数据库

**5、期望结果**

**6、实际结果**

**7、额外信息**
异常日志：
2021-03-24 17:34:50,056 [DEBUG][$_MyCatServer] ServerConnection [id=1, schema=null, host=127.0.0.1, user=null,txIsolation=3, autocommit=true, schema=null, executeSql=null] localPort:51745 port8066  (io.mycat.net.FrontendConnection:FrontendConnection.java:119) 
2021-03-24 17:34:50,070 [INFO ][$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=null]'postgres' login success  (io.mycat.net.handler.FrontendAuthenticator:FrontendAuthenticator.java:241) 
2021-03-24 17:34:50,071 [DEBUG][$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=null] /* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout  (io.mycat.net.FrontendConnection:FrontendConnection.java:358) 
2021-03-24 17:34:50,071 [DEBUG][$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout]/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout  (io.mycat.server.ServerQueryHandler:ServerQueryHandler.java:70) 
2021-03-24 17:34:50,116 [DEBUG][$_NIOREACTOR-1-RW] SQLRouteCache  miss cache ,key:postgres/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout  (io.mycat.cache.impl.EnchachePool:EnchachePool.java:77) 
2021-03-24 17:34:50,132 [DEBUG][$_NIOREACTOR-1-RW] add queue,executeSqlQueue size 1  (io.mycat.server.ServerConnection:ServerConnection.java:362) 
2021-03-24 17:34:50,133 [DEBUG][$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=null]/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout, route={
   1 -> pg2{/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
} rrs   (io.mycat.server.NonBlockingSession:NonBlockingSession.java:128) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] rrs.getRunOnSlave() default  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:187) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] node.getRunOnSlave()  default   (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:189) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] node.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:199) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] node.getRunOnSlave() null  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:201) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] rrs.getRunOnSlave()  default   (io.mycat.backend.datasource.PhysicalDBNode:PhysicalDBNode.java:102) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] rrs.getRunOnSlave()  default   (io.mycat.backend.datasource.PhysicalDBNode:PhysicalDBNode.java:133) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] select read source hostM2 for dataHost:hx-pg-2  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:556) 
2021-03-24 17:34:50,135 [DEBUG][$_NIOREACTOR-1-RW] bindConnection Connection@733575006 [id=11] for node=pg2, sql=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:471) 
2021-03-24 17:34:50,146 [ERROR][BusinessExecutor20] sql execute error, ERROR: missing FROM-clause entry for table "session"
  位置：97 org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "session"
  位置：97
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
	at io.mycat.backend.jdbc.JDBCConnection.ouputResultSet(JDBCConnection.java:706)
	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:371)
	at io.mycat.backend.jdbc.JDBCConnection.access$0(JDBCConnection.java:329)
	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:862)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 (io.mycat.backend.jdbc.JDBCConnection:JDBCConnection.java:384) 
2021-03-24 17:34:50,151 [WARN ][BusinessExecutor20] execute  sql err : errno:0 ERROR: missing FROM-clause entry for table "session"
  位置：97 con:JDBCConnection [id=11,autocommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@58a9760d, schema=postgres, dbType=POSTGRESQL, oldSchema=postgres, packetId=1, txIsolation=0, running=false, borrowed=true, host=192.168.187.4, port=5432, con=org.postgresql.jdbc.PgConnection@96d287c, respHandler=SingleNodeHandler [node=pg2{/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}, packetId=1], attachement=pg2{/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}, headerOutputed=false, modifiedSQLExecuted=false, startTime=1616578471192, lastTime=1616578490135, isSpark=false, processor=io.mycat.net.NIOProcessor@7aac721] frontend host:127.0.0.1/51745/postgres  (io.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:287) 
2021-03-24 17:34:50,151 [DEBUG][BusinessExecutor20] releaseConnection Connection@733575006 [id=11] for node=pg2, sql=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:412) 
2021-03-24 17:34:50,151 [DEBUG][BusinessExecutor20] release channel JDBCConnection [id=11,autocommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@58a9760d, schema=postgres, dbType=POSTGRESQL, oldSchema=postgres, packetId=1, txIsolation=0, running=false, borrowed=true, host=192.168.187.4, port=5432, con=org.postgresql.jdbc.PgConnection@96d287c, respHandler=null, attachement=null, headerOutputed=false, modifiedSQLExecuted=false, startTime=1616578471192, lastTime=1616578490135, isSpark=false, processor=io.mycat.net.NIOProcessor@7aac721]  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:633) 
2021-03-24 17:34:50,152 [ERROR][BusinessExecutor20] ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=null]ERROR: missing FROM-clause entry for table "session"
  位置：97java.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack245
io.mycat.net.FrontendConnection .writeErrMessage231
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .backConnectionErr314
io.mycat.backend.mysql.nio.handler.SingleNodeHandler .errorResponse275
io.mycat.backend.jdbc.JDBCConnection .executeSQL385
io.mycat.backend.jdbc.JDBCConnection .access$0329
io.mycat.backend.jdbc.JDBCConnection$1 .run862
java.util.concurrent.ThreadPoolExecutor .runWorker1149
java.util.concurrent.ThreadPoolExecutor$Worker .run624
java.lang.Thread .run748
 write errorMsg:{} error  (io.mycat.net.FrontendConnection:FrontendConnection.java:231) 
2021-03-24 17:34:50,153 [DEBUG][BusinessExecutor20] on event sql end  (io.mycat.backend.mysql.listener.DefaultSqlExecuteStageListener:DefaultSqlExecuteStageListener.java:68) 
2021-03-24 17:34:50,153 [DEBUG][BusinessExecutor20] poll queue,executeSqlQueue size 0  (io.mycat.server.ServerConnection:ServerConnection.java:537) 
2021-03-24 17:34:50,154 [INFO ][$_NIOREACTOR-1-RW] close connection,reason:stream closed ,ServerConnection [id=1, schema=postgres, host=127.0.0.1, user=postgres,txIsolation=3, autocommit=true, schema=postgres, executeSql=null]  (io.mycat.net.AbstractConnection:AbstractConnection.java:531)

**Comment by funnyAnt** [comment]
问题待确认

**Comment by renweiXu** [comment]
> 问题待确认

大佬 确认好了吗 这个问题
