### ISSUE TITLE
使用 mycat 后 laravel migrate 执行失败

### ISSUE THREAD

**Issue by specialnote** [MyCATApache/Mycat-Server#2777]
**1、bug描述** 
 laravel 连接 mycat, 执行 migrate refresh 时候失败

**2、版本号(非常重要)**
 v 1.6.*.*

**4、操作失败截图**
![图片](https://user-images.githubusercontent.com/13742920/116341719-fb5db700-a813-11eb-89c4-acb5f5197567.png)

**5、相关日志**

2021-04-28 11:23:23.317  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - Mycat does not support the allowMultiQueries value to be true, maybe occur some error.Client connection is[io.mycat.net.handler.FrontendAuthenticator@72c04ae5]
2021-04-28 11:23:23.317  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:241)) - ServerConnection [id=32, schema=laravel, host=192.168.96.4, user=root,txIsolation=3, autocommit=true, schema=laravel, executeSql=null]'root' login success
2021-04-28 11:23:23.318  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:297
2021-04-28 11:23:23.318  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.318  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:297
2021-04-28 11:23:23.318  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:297
2021-04-28 11:23:23.318  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:298
2021-04-28 11:23:23.319  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.319  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:298
2021-04-28 11:23:23.320  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:298
2021-04-28 11:23:23.320 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:99)) - can not get column count
java.lang.Exception: unsupport * in select items:SELECT *
FROM information_schema.tables
WHERE table_schema = ?
	AND table_name = ?
	AND table_type = 'BASE TABLE'
	at io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:87) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.backend.mysql.PreparedStatement.<init>(PreparedStatement.java:72) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:106) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtPrepare(FrontendConnection.java:442) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:92) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.322  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:299
2021-04-28 11:23:23.322  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.322  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:299
2021-04-28 11:23:23.330  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:299
2021-04-28 11:23:23.332  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:300
2021-04-28 11:23:23.332  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.332  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:300
2021-04-28 11:23:23.334  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:300
2021-04-28 11:23:23.335 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:99)) - can not get column count
java.lang.Exception: unsupport * in select items:SELECT *
FROM information_schema.tables
WHERE table_schema = ?
	AND table_name = ?
	AND table_type = 'BASE TABLE'
	at io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:87) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.backend.mysql.PreparedStatement.<init>(PreparedStatement.java:72) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:106) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtPrepare(FrontendConnection.java:442) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:92) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.335  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:301
2021-04-28 11:23:23.335  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.335  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:301
2021-04-28 11:23:23.337  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:301
2021-04-28 11:23:23.337  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:302
2021-04-28 11:23:23.337  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.337  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:302
2021-04-28 11:23:23.339  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:302
2021-04-28 11:23:23.340  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:303
2021-04-28 11:23:23.340  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.340  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:303
2021-04-28 11:23:23.343  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:303
2021-04-28 11:23:23.343 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:99)) - can not get column count
com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:243) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:590) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseTableOptionCharsetOrCollate(MySqlCreateTableParser.java:722) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:215) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:342) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:194) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
	at io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:80) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.backend.mysql.PreparedStatement.<init>(PreparedStatement.java:72) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:106) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtPrepare(FrontendConnection.java:442) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:92) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.344  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:304
2021-04-28 11:23:23.344  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.344  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:304
2021-04-28 11:23:23.345  WARN [$_NIOREACTOR-0-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:118)) - caught err:
com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:243) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:590) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseTableOptionCharsetOrCollate(MySqlCreateTableParser.java:722) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:215) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:342) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:194) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
	at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:23) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:267) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:169) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:397) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:180) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:466) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:104) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.348  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:531)) - close connection,reason:program err:com.alibaba.druid.sql.parser.ParserException: syntax error ,ServerConnection [id=32, schema=laravel, host=192.168.96.4, user=root,txIsolation=3, autocommit=true, schema=laravel, executeSql=create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci']
2021-04-28 11:23:23.348  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - Mycat does not support the allowMultiQueries value to be true, maybe occur some error.Client connection is[io.mycat.net.handler.FrontendAuthenticator@2b81b8db]
2021-04-28 11:23:23.348  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:241)) - ServerConnection [id=33, schema=laravel, host=192.168.96.4, user=root,txIsolation=3, autocommit=true, schema=laravel, executeSql=null]'root' login success
2021-04-28 11:23:23.349  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:305
2021-04-28 11:23:23.349  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.349  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:305
2021-04-28 11:23:23.349  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:305
2021-04-28 11:23:23.349  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:306
2021-04-28 11:23:23.350  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.350  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:306
2021-04-28 11:23:23.351  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.close(ServerPrepareHandler.java:188)) - preparestatement  close id:306
2021-04-28 11:23:23.351 ERROR [$_NIOREACTOR-0-RW] (io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:99)) - can not get column count
com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:243) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:590) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseTableOptionCharsetOrCollate(MySqlCreateTableParser.java:722) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:215) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:342) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:194) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
	at io.mycat.backend.mysql.PreparedStatement.constructColumns(PreparedStatement.java:80) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.backend.mysql.PreparedStatement.<init>(PreparedStatement.java:72) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:106) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtPrepare(FrontendConnection.java:442) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:92) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.352  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.prepare(ServerPrepareHandler.java:109)) - preparestatement  parepare id:307
2021-04-28 11:23:23.352  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.response.PreparedStmtResponse.response(PreparedStmtResponse.java:47)) - prepared metadata comes from self-construction and is incomplete
2021-04-28 11:23:23.352  INFO [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:158)) - preparestatement  execute id:307
2021-04-28 11:23:23.353  WARN [$_NIOREACTOR-0-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:118)) - caught err:
com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:243) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:590) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseTableOptionCharsetOrCollate(MySqlCreateTableParser.java:722) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:215) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:342) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:194) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065) ~[druid-1.0.26.jar:1.0.26]
	at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:23) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:267) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:169) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:397) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:180) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:466) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:104) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:591) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2021-04-28 11:23:23.357  INFO [$_NIOREACTOR-0-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:531)) - close connection,reason:program err:com.alibaba.druid.sql.parser.ParserException: syntax error ,ServerConnection [id=33, schema=laravel, host=192.168.96.4, user=root,txIsolation=3, autocommit=true, schema=laravel, executeSql=create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci']

**Comment by funnyAnt** [comment]
@specialnote  这个迁移工具平时用的少，问题已经记录，抽时间看看。
