### ISSUE TITLE
执行select语句，没有加任何条件，导致mycat-server出现异常，客户端无反应，卡死

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#278]
[2015-05-07 15:42:34  WARN org.opencloudb.mpp.DataMergeService:296] [BusinessExecutor31] data Merge error:
java.lang.ArrayIndexOutOfBoundsException: 255
	at org.opencloudb.mysql.MySQLMessage.readLength(MySQLMessage.java:137) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mysql.MySQLMessage.readBytesWithLength(MySQLMessage.java:201) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.net.mysql.RowDataPacket.read(RowDataPacket.java:84) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mpp.DataMergeService.handleRowData(DataMergeService.java:253) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mpp.DataMergeService.access$2(DataMergeService.java:251) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at org.opencloudb.mpp.DataMergeService$2.run(DataMergeService.java:282) ~[mycat-server-1.4-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by magicdoom** [comment]
master的代码里DataMergeService这块我已经做过异常处理，会返回错误包，客户端会自动断开连接

**Comment by zhouwenbin2000** [comment]
出现这个异常的时候，客户端就会卡死。

**Comment by magicdoom** [comment]
你是mysql的客户端还是jdbc的客户端，我自己模拟抛了个异常，mysql命令行是会自动断开连接的

**Comment by magicdoom** [comment]
应该是跨了线程了，所以异常没catch到

**Comment by zhouwenbin2000** [comment]
select * from "order" limit 2;    dn0 是postgresql, dn1是mysql。

这个问题，跟了下是mysql native合并代码的时候，读取长度的时候position超出了data的长度

**Comment by zhouwenbin2000** [comment]
这个问题经过跟踪，发现是由于两个数据库中列数不一致导致的， postgresql 40列，mysql 39列，然后合并的时候，fieldcount=40， 然后接mysql的包，导致超出异常。 

改进思路： 判断合并的fieldcount是否一致，如果不一致，就给出错误信息。
