### ISSUE TITLE
mycat load 设置character set 'utf8mb4'，报错load data error java.nio.charset.UnsupportedCharsetException: utf8mb4

### ISSUE THREAD

**Issue by andrewzhuxu** [MyCATApache/Mycat-Server#2795]
**1、bug描述** 
 简单清晰描述下bug现象.

数据文件中存在emoji表情符号，在做load时碰到此问题。
目前已将mysql db的字符集全部改为了utf8mb4
mycat的server.xml中也修改了charset=utf8mb4
也重启过mycat。

但在执行mycat load语句时，设置character set 'utf8mb4'，报错不支持utf8mb4。详细报错如下

2021-05-24 18:01:49.346 ERROR [$_NIOREACTOR-14-RW] (io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:320)) - load data error
java.nio.charset.UnsupportedCharsetException: utf8mb4
	at java.nio.charset.Charset.forName(Charset.java:531) ~[?:1.8.0_91]
	at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:640) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:318) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:561) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.4-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.4-release.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2021-05-24 18:01:49.346 ERROR [$_NIOREACTOR-14-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=7, schema=teach_bigdata, host=192.168.201.7, user=user_teach,txIsolation=3, autocommit=true, schema=teach_bigdata, executeSql=		LOAD DATA Local INFILE '/data/server/dev_treasury/export/trot/export_dm_trot_student_practice_stat/../../../export/trot/export_dm_trot_student_practice_stat/temp/dm_trot_student_practice_stat_month/3/000000_0aa' INTO TABLE trot_student_practice_stat_month
		character set 'utf8mb4' 
                FIELDS TERMINATED BY ''  lines terminated by '\n' (
      date_period,period_type,
      user_id,user_name,icon,
      mobile_number,
      study_duration,practice_duration,
      que_times,right_que_times,
      wrong_que_times,right_rate,
      level_stat_string
   )]utf8mb4java.lang.Thread .getStackTrace1552
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.net.FrontendConnection .loadDataInfileEnd321
io.mycat.net.FrontendConnection .rawHandle561
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run745
 write errorMsg:{} error

**2、版本号(非常重要)**
 v 1.6.7.4-release

**3、相关表的配置信息**
  schema.xml (mysql的连接驱动是native方式)
  rule.xml (涉及到的路由函数)
  server.xml
已设置字符集为utf8mb4
<property name="charset">utf8mb4</property>

**index_to_charset.properties**配置文件中，也包含utf8mb4
223=utf8
224=utf8mb4

**4、操作步骤**
LOAD DATA Local INFILE '/data/server/dev_treasury/export/trot/export_dm_trot_student_practice_stat/../../../export/trot/export_dm_trot_student_practice_stat/temp/dm_trot_student_practice_stat_month/3/000000_0aa' INTO TABLE trot_student_practice_stat_month
		character set 'utf8mb4' 
                FIELDS TERMINATED BY ''  lines terminated by '\n' (
      date_period,period_type,
      user_id,user_name,icon,
      mobile_number,
      study_duration,practice_duration,
      que_times,right_que_times,
      wrong_que_times,right_rate,
      level_stat_string
   );

mycat报错	
ERROR 2013 (HY000) at line 2: Lost connection to MySQL server during query

查看mycat.log后，看到bug描述中的错误信息。

**7、额外信息**
mysql版本 v5.7.16

mysql> \s
--------------
mysql  Ver 14.14 Distrib 5.7.14, for Linux (x86_64) using  EditLine wrapper

Connection id:		295179
Current database:	trot
Current user:		user_teach@192.168.201.14
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.14-log Source distribution
Protocol version:	10
Connection:		192.168.201.14 via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		3307
Uptime:			497 days 5 hours 37 min 29 sec

**Comment by funnyAnt** [comment]
请试试最新的1676有没有这个问题。 问题待确认，近1周内解决。

**Comment by andrewzhuxu** [comment]
部署1676最新版本测试，仍存在此问题。使用的schema.xml，rule.xml，server.xml配置文件是同一份。

版本信息：
BuildTime  2021-03-03 01:47:57
GitVersion   0a3a93327217f33ab63f0b8ea07891db62069baa
MavenVersion 1.6.7.6-release
GitUrl https://github.com/MyCATApache/Mycat-Server.git
MyCatSite http://www.mycat.org.cn

报错信息：
2021-06-02 12:04:08.527  INFO [$_NIOREACTOR-13-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - Mycat does not support the allowMultiQueries value to be true, maybe occur some error.Client connection is[io.mycat.net.handler.FrontendAuthenticator@673de8ca]
2021-06-02 12:04:08.527  INFO [$_NIOREACTOR-13-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:241)) - ServerConnection [id=2, schema=teach_bigdata, host=192.168.201.7, user=user_teach,txIsolation=3, autocommit=true, schema=teach_bigdata, executeSql=null]'user_teach' login success
2021-06-02 12:04:08.584 ERROR [$_NIOREACTOR-13-RW] (io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:341)) - load data error
java.nio.charset.UnsupportedCharsetException: utf8mb4
	at java.nio.charset.Charset.forName(Charset.java:531) ~[?:1.8.0_91]
	at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:604) ~[Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:339) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:582) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:573) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:338) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:290) [Mycat-server-1.6.7.6-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.7.6-release.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2021-06-02 12:04:08.591 ERROR [$_NIOREACTOR-13-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:231)) - ServerConnection [id=2, schema=teach_bigdata, host=192.168.201.7, user=user_teach,txIsolation=3, autocommit=true, schema=teach_bigdata, executeSql=null]utf8mb4java.lang.Thread .getStackTrace1552
io.mycat.net.FrontendConnection .getStack245
io.mycat.net.FrontendConnection .writeErrMessage231
io.mycat.net.FrontendConnection .loadDataInfileEnd342
io.mycat.net.FrontendConnection .rawHandle582
io.mycat.net.FrontendConnection .handle573
io.mycat.net.AbstractConnection .onReadData338
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead290
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run745
 write errorMsg:{} error
2021-06-02 12:04:08.593  INFO [$_NIOREACTOR-13-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:531)) - close connection,reason:stream closed ,ServerConnection [id=2, schema=teach_bigdata, host=192.168.201.7, user=user_teach,txIsolation=3, autocommit=true, schema=teach_bigdata, executeSql=null]
