### ISSUE TITLE
subTabs模式下，进行load data infile操作会报错。

### ISSUE THREAD

**Issue by dualven** [MyCATApache/Mycat-Server#2804]
**1、bug描述** 
 简单清晰描述下bug现象.
建立简单的测试环境 ： 分表365 合适subTables模式
      <schema name="cndata" checkSQLschema="false"  dataNode="cndata0" >
                <table name="dw_reportimsi" primaryKey="id"  dataNode="cndata0" subTables="dw_reportimsi_$1-365" rule="pdas-dateRule"  />
        </schema>

mysql -uroot -p123456 -P8067 -h127.0.0.1 cndata -e "set character_set_server=utf8 ;set character_set_database=utf8;load data infile '/usr/local/mycat/logs/$1' into table dw_reportimsi (device_name,equip_id,imsi,imei,time,source_tac,cell_no,mcc,mnc,equip_longitude,equip_latitude,belong,address,rssi,phone_num) ;  
**2、版本号(非常重要)**
 v 1.6.7.5   6-15更新到最新

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
  rule.xml (涉及到的路由函数)
  server.xml(可选)

**4、操作步骤**
1.  先导出数据 
   mysql -uroot -p123456 -P8067 -h127.0.0.1 pdas -N -e "SELECT device_name,equip_id,imsi,imei,time,source_tac,cell_no,mcc,mnc,equip_longitude,equip_latitude,belong,address,IFNULL(rssi,'1'),IFNULL(phone_num,'159')  from dw_reportimsi where time between '$current'  and '$currentEnd' limit 10" >> ./data3336/$3
2.  再想导入数据
mysql -uroot -p123456 -P8067 -h127.0.0.1 cndata -e "set character_set_server=utf8 ;set character_set_database=utf8;load data infile '/usr/local/mycat/logs/$1' into table dw_reportimsi (device_name,equip_id,imsi,imei,time,source_tac,cell_no,mcc,mnc,equip_longitude,equip_latitude,belong,address,rssi,phone_num) ;  
3
3.  ...

**5、期望结果**
无报错插入

**6、实际结果**
2021-06-15 08:12:29.044 ERROR [$_NIOREACTOR-38-RW] (io.mycat.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:292)) - load data error
java.lang.NullPointerException
        at io.mycat.route.util.RouterUtil.routeToDistTableNode(RouterUtil.java:1413) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1368) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1282) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:368) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:401) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:731) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:227) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:290) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:138) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.5-test.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.5-test.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2021-06-15 08:12:29.044 ERROR [$_NIOREACTOR-38-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=48, schema=cndata, host=172.17.0.1, user=root,txIsolation=3, autocommit=true, schema=cndata, executeSql=load data infile '/usr/local/mycat/logs/8.txt' into table dw_reportimsi (device_name,equip_id,imsi,imei,time,source_tac,cell_no,mcc,mnc,equip_longitude,equip_latitude,belong,address,rssi,phone_num)]nulljava.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.net.FrontendConnection .loadDataInfileStart293
io.mycat.server.ServerQueryHandler .query138
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76
io.mycat.net.FrontendConnection .rawHandle570
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run748
 write errorMsg:{} error

**7、额外信息**

**Comment by dualven** [comment]
我的意思是，在subtables模式下，使用load data infile 会报错；
如果使用datanode模式，如
 <table name="dw_reportimsi" primaryKey="id" dataNode="cn$1-365" rule="pdas-dateRule"  />
则不会报错。
所以应该很好复现。 敬待回复 ，谢谢

**Comment by junwen12221** [comment]
导入文件里面是不是有一些没有表名的sql

**Comment by junwen12221** [comment]
把这些sql去掉看看

**Comment by dualven** [comment]
矿山医院门口    00:34:cb:04:7c:ca       460110524522433         2020-07-02 10:00:00     23050   0       460     11      104.71024       28.45550                矿山医院门口
矿山医院门口    00:34:cb:04:7c:ca       460110514678978         2020-07-02 10:00:00     23050   0       460     11      104.71024       28.45550                矿山医院门口

导入文件只有这样的数据。 是通过 mysql -u root -p   ........ -e "select * from dw**" > 8.txt 出来 的

**Comment by junwen12221** [comment]
1675 http://dl.mycat.org.cn/1.6.7.5/2021-6-16/

**Comment by dualven** [comment]
验证了一下，还是不行。
<schema name="cndata" checkSQLschema="false"  dataNode="cndata0" >
                <table name="dw_reportimsi" dataNode="cndata0" subTables="dw_reportimsi_$1-365" rule="pdas-dateRule"  />
        </schema>
我在cndata 里有dw_reportimsi_1 ~ 365
我如果没有建立dw_reportimsi 这个物理表，它会报找不到表dw_reportimsi；如果建立后，不会报错，把数据都插入到dw_reportimsi了。而没有按路由分到dw_reportimsi_1~365 .
感谢回复。 请帮忙 再看看，谢谢。

**Comment by junwen12221** [comment]
那应该是不支持
