### ISSUE TITLE
查询字段包含 sum(`show`) as `show`，就会链接丢失

### ISSUE THREAD

**Issue by chen-jiang-hui** [MyCATApache/Mycat-Server#2816]
<img width="641" alt="图片" src="https://user-images.githubusercontent.com/32922951/126602841-343cd141-b2e0-4b44-a2ea-2f722d6fe355.png">

**Comment by junwen12221** [comment]
估计是某个语法不支持,贴出日志

**Comment by chen-jiang-hui** [comment]
2021-07-23 09:00:31.166&nbsp; WARN [$_NIOREACTOR-3-RW] (io.mycat.server.handler.SetHandler.handle(SetHandler.java:194)) - ServerConnection [id=9, schema=test_mycat, host=192.168.62.225, user=user,txIsolation=3, autocommit=true, schema=test_mycat, executeSql=SET PROFILING = 1]SET PROFILING = 1 is not recoginized and ignored
2021-07-23 09:00:31.261&nbsp; WARN [BusinessExecutor3] (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:828)) - ***@***.*** caught exception
java.lang.NullPointerException: null
	at io.mycat.sqlengine.mpp.RowDataPacketGrouper.<init&gt;(RowDataPacketGrouper.java:68) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.sqlengine.mpp.DataMergeService.onRowMetaData(DataMergeService.java:144) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.fieldEofResponse(MultiNodeQueryHandler.java:815) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.ouputResultSet(JDBCConnection.java:734) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.executeSQL(JDBCConnection.java:365) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection.access$000(JDBCConnection.java:48) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.backend.jdbc.JDBCConnection$1.run(JDBCConnection.java:855) [Mycat-server-1.6.7.5-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2021-07-23 09:00:32.812 ERROR [BusinessExecutor5] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=9, schema=test_mycat, host=192.168.62.225, user=user,txIsolation=3, autocommit=true, schema=test_mycat, executeSql=SELECT
	DATE_FORMAT(`date`, "%Y-%m") as date,
	SUM( req ) AS req,
	SUM( `show` ) AS `show`,
	SUM( click ) AS click,
	SUM( video_not_complete ) AS video_not_complete,
	SUM( video_error ) AS video_error
FROM
	`stat_ad_sdk`
WHERE
	`date` &gt;= '2021-02-01'
	AND `date` <= '2021-02-25'


group by date]java.lang.NullPointerExceptionjava.lang.Thread .getStackTrace1552
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.backend.mysql.nio.handler.MultiNodeHandler .tryErrorFinished218
io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler .rowEofResponse424
io.mycat.backend.jdbc.JDBCConnection .ouputResultSet774
io.mycat.backend.jdbc.JDBCConnection .executeSQL365
io.mycat.backend.jdbc.JDBCConnection .access$00048
io.mycat.backend.jdbc.JDBCConnection$1 .run855
java.util.concurrent.ThreadPoolExecutor .runWorker1142
java.util.concurrent.ThreadPoolExecutor$Worker .run617
java.lang.Thread .run745
&nbsp;write errorMsg:{} error
2021-07-23 09:00:32.818&nbsp; INFO [$_NIOREACTOR-3-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:stream closed ,ServerConnection [id=9, schema=test_mycat, host=192.168.62.225, user=user,txIsolation=3, autocommit=true, schema=test_mycat, executeSql=SELECT
	DATE_FORMAT(`date`, "%Y-%m") as date,
	SUM( req ) AS req,
	SUM( `show` ) AS `show`,
	SUM( click ) AS click,
	SUM( video_not_complete ) AS video_not_complete,
	SUM( video_error ) AS video_error
FROM
	`stat_ad_sdk`
WHERE
	`date` &gt;= '2021-02-01'
	AND `date` <= '2021-02-25'


group by date]
2021-07-23 09:00:32.983&nbsp; INFO [$_NIOREACTOR-4-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:226)) - ServerConnection [id=10, schema=null, host=192.168.62.225, user=user,txIsolation=3, autocommit=true, schema=null, executeSql=null]'user' login success





只有这个了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 查询字段包含 sum(`show`) as `show`，就会链接丢失 (#2816)





 
估计是某个语法不支持,贴出日志

**Comment by junwen12221** [comment]
估计是show是关键字导致的,改变show这个字段名可能可以避免这个问题

**Comment by chen-jiang-hui** [comment]
查询指定表又不会出现异常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 查询字段包含 sum(`show`) as `show`，就会链接丢失 (#2816)





 
估计是show是关键字导致的,改变show这个字段名可能可以避免这个问题

**Comment by junwen12221** [comment]
sum(show) as show0 看看行不行

**Comment by junwen12221** [comment]
`sum(`show`) as show0 看看行不行`

**Comment by chen-jiang-hui** [comment]
用 sum（sum(`show`) + 0 ） as `show` 就没问题


这样子&nbsp;sum(show) as show0 还是不行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 查询字段包含 sum(`show`) as `show`，就会链接丢失 (#2816)





 
sum(show) as show0 看看行不行
