### ISSUE TITLE
mycat 1.6.7.4 支持 json 查询吗？

### ISSUE THREAD

**Issue by Macintosh-c** [MyCATApache/Mycat-Server#2842]
**1、bug描述** 
 使用的mycat版本为Mycat-server-1.6.7.4-release.jar，报错信息如下：
2021-09-02 07:51:14.396  WARN [$_NIOREACTOR-1-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:118)) - caught err:
java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_151]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_151]
        at io.mycat.net.mysql.BinaryRowDataPacket.write(BinaryRowDataPacket.java:309) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:523) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:208) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:269) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) ~[Mycat-server-1.6.7.4-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) ~[Mycat-server-1.6.7.4-release.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

我们发现，代码查询的返回字段中包含一个json字段，去掉该字段返回，则查询返回正常。但通过mysql clent端直连mycat 查询该包含json字段的sql，返回正常。不解

**Comment by junwen12221** [comment]
jdbc等客户端关闭服务器预处理属性
