### ISSUE TITLE
load csv文件导入mycat分库分表时报错

### ISSUE THREAD

**Issue by benevolence-doctor** [MyCATApache/Mycat-Server#2848]
**1、bug描述** 
 mycat进行load file时候报错
2021-09-13 11:15:21.298 ERROR [$_NIOREACTOR-2-RW] (io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:323)) - load dat
a error
java.lang.IllegalArgumentException: columnValue:未满16周岁不骑摩托车和电动车出行。\n      4.不闯红灯、跨越道路隔离护栏或在铁路上逗留 Please e
liminate any quote and non number within it.
        at io.mycat.route.function.PartitionByMod.calculate(PartitionByMod.java:62) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:1537) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1334) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:1193) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:365) ~[Mycat-server-1.6.5-rele
ase.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:398) ~[Mycat-server-1.6.5-releas
e.jar:?]
        at io.mycat.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:668) ~[Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:321) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:542) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:533) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:201) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279) [Mycat-server-1.6.5-release.jar:?]
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113) [Mycat-server-1.6.5-release.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NumberFormatException: For input string: "未满1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_181]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_181]
        at java.math.BigInteger.<init>(BigInteger.java:470) ~[?:1.8.0_181]
        at java.math.BigInteger.<init>(BigInteger.java:606) ~[?:1.8.0_181]
        at io.mycat.route.function.PartitionByMod.calculate(PartitionByMod.java:59) ~[Mycat-server-1.6.5-release.jar:?]
        ... 14 more
**2、版本号(非常重要)**
 v 1.6.5

**3、相关表的配置信息**
  schema.xml (mysql的连接驱动是native方式)
  rule.xml (涉及到的路由函数)
  server.xml(可选)
![image](https://user-images.githubusercontent.com/13461419/133020748-b5835d8f-9934-4829-92b2-3c868824f948.png)
![image](https://user-images.githubusercontent.com/13461419/133020877-74451e51-e5a3-4f13-ae47-672570613c2b.png)

**4、操作步骤**
1.  将数据从mysql中导成csv文件
2.  将数据从csv文件导入mycat
3.  导入规则：LOAD DATA LOCAL INFILE '/home/m.csv' INTO TABLE moment FIELDS TERMINATED BY ';' OPTIONALLY enclosed by '"' LINES TERMINATED BY "\n" (id, type, sub_type, content, resource, third_id, school_id, class_id, student_id, status, is_transcode, shield_uid, shield_roleid, notice_confirm, del_flag, uid, role_id, primary_identity, from_role_id, created_at, updated_at, old_id, check_role_id, like_num, comment_num);

**5、期望结果**
导入成功

**6、实际结果**
1. mycat中moment表做了分库分表，通过mycat 进行load csv文件报错
2. 将csv文件直接导入mysql没问题，导入mycat报错

**7、额外信息**

**Comment by benevolence-doctor** [comment]
![image](https://user-images.githubusercontent.com/13461419/133021243-df9e1cff-ab9c-422c-8417-7e39784cde19.png)
csv文件的内容如上

**Comment by benevolence-doctor** [comment]
@junwen12221 帮忙看下 谢谢

**Comment by junwen12221** [comment]
这个问题可以用最新版,仅用作导入服务器试一下

**Comment by benevolence-doctor** [comment]
最新版是哪个版本

**Comment by benevolence-doctor** [comment]
@junwen12221  用1.6.7.6 直接报错
![image](https://user-images.githubusercontent.com/13461419/133050834-db670c39-fc1b-40a6-b5d1-598968a4b0f2.png)

**Comment by benevolence-doctor** [comment]
@junwen12221  用1.6.7.6版本进行测试还是报错
![image](https://user-images.githubusercontent.com/13461419/133052724-237eacc4-b68d-4166-8260-9530162344bf.png)

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/1.6.7.3/20210913163959/ 试一下这个,如果不行就实用客户端,多线程逐条导入数据或者实用第三方导入工具
https://www.yuque.com/ccazhw/ml3nkf/hq03qo

或者检查这个loaddata临时生成的导入sql脚本,检查生成格式错误,手动导入

**Comment by benevolence-doctor** [comment]
@junwen12221 用1.6.7.3和1.6.7.6版本都不行，是不是你们处理的时候没有参考mysql的机制

**Comment by benevolence-doctor** [comment]
我的脚本需要配合canal使用，所以没法用第三方导入工具

**Comment by junwen12221** [comment]
loaddata有安全问题,最好是使用程序导入

**Comment by junwen12221** [comment]
mycat会先按分片分组生成loadata数据,保存在本地,你找到这个文件,手动导入也行
