### ISSUE TITLE
Mycat-server-1.6.7.6-release-20211221142218不能批量更新

### ISSUE THREAD

**Issue by Ascendtiantian** [MyCATApache/Mycat-Server#2888]
**1、bug描述** 
不能进行批量update操作，通过mycat连接mysql数据mybatis中使用foreach进行批量update报错

       at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: java.sql.SQLSyntaxErrorException: Multi statements is not supported,use single statement instead

![image](https://user-images.githubusercontent.com/24872136/147341761-b258ff6b-e3ea-429b-816b-85ea4acd3a8d.png)

**2、版本号(非常重要)**
 v 1.6.*.*
Mycat-server-1.6.7.6-release-20211221142218-linux.tar.gz

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
jdbc方式
  rule.xml (涉及到的路由函数)
默认
  server.xml(可选)

**4、操作步骤**
1.  '...'
2.  '....'
3.  ...

**5、期望结果**

**6、实际结果**
A clear and concise description of what  actually happened.

**7、额外信息**

**Comment by junwen12221** [comment]
不支持多语句

**Comment by wjsmc** [comment]
难缠的bug
