### ISSUE TITLE
1.4 LOAD DATA INFILE出错

### ISSUE THREAD

**Issue by ggggggggod** [MyCATApache/Mycat-Server#289]
我的file内容是：
964509 1426749300 698 89114767 17 152129
964509 1426749300 480 106520088 13 152129
964509 1426749300 2768 492330311 20 152129
964509 1426749300 390 49319705 21 152129
964509 1426749300 252 72952676 18 152129
964509 1426749300 163 40324348 30 152129
964509 1426749300 415 55857747 22 152129
在load data的时候一直报错：
mysql> LOAD DATA INFILE '/tmp/user.txt' IGNORE INTO TABLE table1(a,b,c,d,e,f) FIELDS TERMINATED BY '\t';
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id: 1
Current database: user
ERROR 3009 (HY000): For input string: "09 142674"
使用空格分隔字符 为何把09 142674当成一个字符

05/10 23:13:29.373 ERROR $_NIOREACTOR-12-RW -load data error
java.lang.NumberFormatException: For input string: "09 142674"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:492)
at java.math.BigInteger.(BigInteger.java:327)
at java.math.BigInteger.(BigInteger.java:445)
at org.opencloudb.route.function.PartitionByMod.calculate(PartitionByMod.java:61)
at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:758)
at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:658)
at org.opencloudb.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:542)
at org.opencloudb.server.handler.ServerLoadDataInfileHandler.tryDirectRoute(ServerLoadDataInfileHandler.java:349)
at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:382)
at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:680)
at org.opencloudb.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:214)
at org.opencloudb.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:241)
at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:112)
at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
at java.lang.Thread.run(Thread.java:745)

**Comment by ggggggggod** [comment]
Mycat-server-1.4-dev-20150510094532-linux.tar.gz

**Comment by magicdoom** [comment]
你这个FIELDS TERMINATED BY '\t';配置的tab为分割符号，而不是空格；

**Comment by magicdoom** [comment]
如果字段内容里包含了分割符换行符等特殊符号的话，建议用引号扩起来，注意sql里参数要配正确，具体参考文档

**Comment by ggggggggod** [comment]
空格我也试了不行,默认不加FIELDS TERMINATED的就是空格， 另外换成逗号 也是一样

**Comment by magicdoom** [comment]
默认不加是  \t   不是空格；

**Comment by ggggggggod** [comment]
之前这个表load的第一个字段是分片字段，我把表换成global不做分片测试了下 文本可以load，
在文本为逗号分隔的情况下：
964509,1426749300,698,89114767,17,152129
load data infile '/tmp/xxx.txt' ignore into table test character set 'utf8' (a,b,c,d,e,f) fields terminated by ',' lines terminated by '\n'; 能够成功load，但是只有第一个字段插入，原因是逗号没分隔开
>show warnings;
| Warning | 1265 | Data truncated for column 'a' at row 11 |
| Warning | 1261 | Row 11 doesn't contain data for all columns  |
| Warning | 1261 | Row 11 doesn't contain data for all columns  |

但是我去掉字段(a,b,c,d,e,f)
load data infile '/tmp/xxx.txt' ignore into table test character set 'utf8' fields terminated by ',' lines terminated by '\n'; 就能够成功load全部数据。

1.4在load这块还是有些问题，load语句在mysql本地测过 都能成功运行

**Comment by magicdoom** [comment]
列名必须放最后，另外参数的顺序必须跟官方文档里的顺序一致
