### ISSUE TITLE
不断报Connection reset by peer错误

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-Server#2894]
**1、bug描述** 
不断的出现java.io.IOException: Connection reset by peer错误
详细如下
2022-01-11 16:22:52.996  WARN [$_NIOREACTOR-11-RW] (io.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:64)) - caught err:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_262]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_262]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_262]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[?:1.8.0_262]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468) ~[?:1.8.0_262]
	at io.mycat.net.NIOSocketWR.write0(NIOSocketWR.java:119) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:48) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.write(AbstractConnection.java:459) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.mysql.HandshakeV10Packet.write(HandshakeV10Packet.java:118) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:520) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:181) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:96) [Mycat-server-1.6.7.5-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**2、版本号(非常重要)**
BuildTime  2020-04-22 05:38:08
GitVersion   6049ef44368d3594ff0c7b118de2ddd4031ee856
MavenVersion 1.6.7.5-release

后端是pxc 5.7.35

**3、相关表的配置信息**
  schema.xml  native方式 
  server.xml
	<property name="nonePasswordLogin">0</property>
	<property name="ignoreUnknownCommand">0</property>
	<property name="useHandshakeV10">1</property>
    <property name="removeGraveAccent">1</property>
	<property name="useSqlStat">1</property>
	<property name="useGlobleTableCheck">0</property>
	<property name="sqlExecuteTimeout">300</property>
	<property name="sequenceHandlerType">1</property>
	<property name="sequenceHanlderClass">io.mycat.route.sequence.handler.HttpIncrSequenceHandler</property>
        <property name="fakeMySQLVersion">5.7.35</property>
	<property name="processorBufferChunk">40960</property> 
	<property name="processors">4</property> 
	<property name="processorExecutor">32</property> 
		<property name="processorBufferPoolType">0</property>
			<property name="serverPort">8066</property> <property name="managerPort">9066</property> 
			<property name="idleTimeout">3000000</property> <property name="bindIp">0.0.0.0</property>
			<property name="dataNodeIdleCheckPeriod">900000</property>
			<property name="frontWriteQueueSize">4096</property> <property name="processors">32</property>

**4、操作步骤**
tail -f /u01/mycat/logs/mycat.log
2022-01-11 16:27:58.669  WARN [$_NIOREACTOR-6-RW] (io.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:64)) - caught err:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_262]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_262]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_262]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[?:1.8.0_262]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468) ~[?:1.8.0_262]
	at io.mycat.net.NIOSocketWR.write0(NIOSocketWR.java:119) ~[Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:48) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.AbstractConnection.write(AbstractConnection.java:459) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.mysql.HandshakeV10Packet.write(HandshakeV10Packet.java:118) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:520) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:181) [Mycat-server-1.6.7.5-release.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:96) [Mycat-server-1.6.7.5-release.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**5、期望结果**
解决这种报错
 
**6、额外信息**
mysql> show global variables like '%timeout%';
+-------------------------------------+----------+
| Variable_name                       | Value    |
+-------------------------------------+----------+
| connect_timeout                     | 10       |
| delayed_insert_timeout              | 300      |
| have_statement_timeout              | YES      |
| innodb_flush_log_at_timeout         | 1        |
| innodb_lock_wait_timeout            | 10       |
| innodb_print_lock_wait_timeout_info | OFF      |
| innodb_rollback_on_timeout          | ON       |
| interactive_timeout                 | 28800    |
| lock_wait_timeout                   | 31536000 |
| net_read_timeout                    | 30       |
| net_write_timeout                   | 60       |
| rpl_stop_slave_timeout              | 31536000 |
| slave_net_timeout                   | 60       |
| thread_pool_idle_timeout            | 60       |
| wait_timeout                        | 86400    |
| wsrep_RSU_commit_timeout            | 5000     |
+-------------------------------------+----------+
16 rows in set (0.00 sec)

**Comment by junwen12221** [comment]
是偶然的还是一直报这个错误

**Comment by cusele** [comment]
> 是偶然的还是一直报这个错误

一直报

**Comment by yingyangxu** [comment]
日志
2022-01-28 08:23:14.824  WARN [BusinessExecutor7] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.backConnectionErr(SingleNodeHandler.java:250)) - execute  sql err : errno:17002 IO Error: Connection reset by peer con:JDBCConnection [id=20,autocommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@66a7ef60, schema=nontax_unified, dbType=ORACLE, oldSchema=nontax_unified, packetId=-76, txIsolation=0, running=false, borrowed=true, host=null, port=-1, con=oracle.jdbc.driver.T4CConnection@34e2c463, respHandler=SingleNodeHandler [node=dn_t0{SELECT  id,subregion,from_region_code,tenant_code,region_code,create_time,update_time,create_user  FROM sys_tenant_region 
 WHERE (from_region_code = '320722')}, packetId=1], attachement=dn_t0{SELECT  id,subregion,from_region_code,tenant_code,region_code,create_time,update_time,create_user  FROM sys_tenant_region 
 WHERE (from_region_code = '320722')}, headerOutputed=false, modifiedSQLExecuted=false, startTime=1643165518419, lastTime=1643329394823, isSpark=false, processor=io.mycat.net.NIOProcessor@65ea3876] frontend host:35.18.35.223/45732/root
 
 **2、版本号(非常重要)**
 1.6.5
 
 **3、相关表的配置信息**
schema.xml jdbc方式

<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
    <schema name="t0" checkSQLschema="true" dataNode = "dn_t0"></schema>
    <schema name="t1" checkSQLschema="true" dataNode = "dn_t1"></schema>
    <schema name="t2" checkSQLschema="true" dataNode = "dn_t2"></schema>
    <schema name="t3" checkSQLschema="true" dataNode = "dn_t3"></schema>
    <schema name="nontax_unified" checkSQLschema="true">
      <table name="sys_tenant_region" dataNode="dn_t0"/>
    </schema>
    
    <dataNode name="dn_t0" dataHost="dh_t0" database="nontax_unified_000000" ></dataNode>
    <dataNode name="dn_t1" dataHost="dh_t1" database="nontax_unified" ></dataNode>
    <dataNode name="dn_t2" dataHost="dh_t2" database="nontax_unified_320100" ></dataNode>
    <dataNode name="dn_t3" dataHost="dh_t3" database="nontax_unified_320000" ></dataNode>
    
    <dataHost name="dh_t0" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <writeHost host="whg" url="jdbc:oracle:thin:@192.168.0.101:1521/orcl" user="nontax_unified_000000" password="orcl"/>
    </dataHost>
    <dataHost name="dh_t1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <writeHost host="wh0" url="jdbc:oracle:thin:@192.168.0.101:1521/orcl" user="nontax_unified" password="orcl"/>
    </dataHost>
    <dataHost name="dh_t2" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <writeHost host="wh1" url="jdbc:oracle:thin:@192.168.0.101:1521/orcl" user="nontax_unified_320100" password="orcl"/>
    </dataHost>

    <dataHost name="dh_t3" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <writeHost host="wh1" url="jdbc:oracle:thin:@192.168.0.101:1521/orcl" user="nontax_unified_320000" password="orcl"/>
    </dataHost>

</mycat:schema>

 重启后解决，但是不知道什么原因引起的，希望给些建议

**Comment by liuhangz1** [comment]
也出现这个问题，不过把对应的DataHost  的maxCon 改小以后没有报错了

**Comment by zwyqz** [comment]
jdbc链接中加上autoReconnect属性试试；
