### ISSUE TITLE
在并发情况下出现以下异常

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#300]
[2015-05-18 16:10:27  WARN org.opencloudb.server.ServerConnection:209] [$_NIOREACTOR-11-RW] ServerConnection [id=1143, schema=dbtest, host=localhost, user=root,txIsolation=3, autocommit=true, schema=dbtest]select id from test where uid = 1111 and ( unused>0 or refund>0 or (update_time>'2015-05-04 00:00:07.375' and (state<=2 or quantity=used or refunded>0))) and source_id=1 order by update_time desc limit 20;      err:java.util.ConcurrentModificationException

java.util.ConcurrentModificationException: null

        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[na:1.7.0_45]

        at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[na:1.7.0_45]

        at org.opencloudb.parser.druid.MycatSchemaStatVisitor.splitConditions(MycatSchemaStatVisitor.java:280) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.parser.druid.impl.DefaultDruidParser.visitorParse(DefaultDruidParser.java:101) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:61) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:61) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:57) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.route.RouteService.route(RouteService.java:118) ~[mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:201) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:73) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267) [mycat-server-1.4-SNAPSHOT.jar:na]

        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96) [mycat-server-1.4-SNAPSHOT.jar:na]

        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by abirdman** [comment]
该问题已经解决，表面上是并发导致，实际上是单线程内递归操作非线程安全list导致。请拉master上最新代码测试。

**Comment by mycatmerger** [comment]
已经修复
