### ISSUE TITLE
java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by root2000xyz** [MyCATApache/Mycat-Server#305]
05/19 20:04:55.838   WARN [$_NIOREACTOR-3-RW] (NIOReactor.java:157) -register error 
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:252)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:358)
	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:155)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
	at java.lang.Thread.run(Thread.java:745)

mycat.log中这种错误一般什么原因？

**Comment by linzhiqiang0514** [comment]
最好给出具体详细一点点的内容，另外验证一下，是否还有现在的问题。

**Comment by stonelion** [comment]
Mycat在要读取数据的时候。你把连接关闭了。

**Comment by mycatmerger** [comment]
这种一般是由于数据库连接关闭引起的，先关闭。如果新版还存在此问题，请提供更详细的内容
