### ISSUE TITLE
1.4beta数据合并报异常

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#345]
[2015-06-12 15:41:01  WARN org.opencloudb.mpp.DataMergeService:297] [BusinessExecutor1] data Merge error:
java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.7.0_45]
        at org.opencloudb.mysql.MySQLMessage.readBytesWithLength(MySQLMessage.java:211) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.net.mysql.RowDataPacket.read(RowDataPacket.java:84) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService.handleRowData(DataMergeService.java:253) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService.access$200(DataMergeService.java:57) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService$2.run(DataMergeService.java:282) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
[2015-06-12 15:41:01  WARN org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler:458] [BusinessExecutor1] caught exception 
java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.7.0_45]
        at org.opencloudb.mysql.MySQLMessage.readBytesWithLength(MySQLMessage.java:211) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.net.mysql.RowDataPacket.read(RowDataPacket.java:84) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService.handleRowData(DataMergeService.java:253) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService.access$200(DataMergeService.java:57) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at org.opencloudb.mpp.DataMergeService$2.run(DataMergeService.java:282) ~[mycat-server-0.0.2-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

case是： 第一个分片是jdbc访问，第二个分片是mysql native访问。 第二个分片没数据，第一个分片有数据的情况下，报出来的。 两个分片都有数据的话时没有问题

**Comment by mycatmerger** [comment]
表结构不一致引起，先关闭
