### ISSUE TITLE
mycat压缩协议问题

### ISSUE THREAD

**Issue by haonan108** [MyCATApache/Mycat-Server#403]
通过jdbc方式启用压缩协议连接mycat会报以下错误

07/22 23:13:10.157  DEBUG [$_NIOREACTOR-0-RW] (NIOReactor.java:101) -caught err:
java.nio.BufferOverflowException
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:357)
	at java.nio.ByteBuffer.put(ByteBuffer.java:832)
	at org.opencloudb.util.CompressUtil.compressMysqlPacket(CompressUtil.java:67)
	at org.opencloudb.util.CompressUtil.compressMysqlPacket(CompressUtil.java:30)
	at org.opencloudb.net.AbstractConnection.writeNotSend(AbstractConnection.java:362)
	at org.opencloudb.net.AbstractConnection.writeToBuffer(AbstractConnection.java:425)
	at org.opencloudb.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:272)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134)
	at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:252)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:306)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Thread.java:745)
07/22 23:13:10.163   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:446) -close connection,reason:program err:java.nio.BufferOverflowException ,MySQLConnection [id=6, lastTime=1437631990105, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=64, charset=utf8, txIsolation=3, autocommit=true, attachment=dn3{SHOW VARIABLES}, respHandler=SingleNodeHandler [node=dn3{SHOW VARIABLES}, packetId=-123], host=192.168.228.128, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@bf7a35, writeQueue=0, modifiedSQLExecuted=false]

**Comment by haonan108** [comment]
通过客户端连接是正常的

**Comment by magicdoom** [comment]
可以试试设置XX:MaxDirectMemorySize的大小大一点 看看

**Comment by haonan108** [comment]
发现把processorBufferChunk设置成20480后不报这个错了，观察了下jdbc连接mycat时会默认发送show variables;这个结果有400多行，打开压缩协议执行这个sql会报异常，关闭后执行正常，压缩协议这应该还是有问题吧

**Comment by mycatmerger** [comment]
另外检查下你的jdbc的版本是多少？

**Comment by haonan108** [comment]
jdbc版本是5.1.15

**Comment by magicdoom** [comment]
你可以换高点的版本试试，比如5.1.35，早期版本会多发些命令

**Comment by cavonchen** [comment]
1.6.5还是有这个问题，压缩这块还没做好啊

**Comment by wangjingfei** [comment]
> 1.6.5还是有这个问题，压缩这块还没做好啊

@cavonchen 你有解决这个问题吗？调整参数？
