### ISSUE TITLE
MyCat配置主从表且主从表都配置全局序列号递增时执行插入从表报错且阻塞客户端

### ISSUE THREAD

**Issue by rayoo** [MyCATApache/Mycat-Server#416]
MyCat配置主从表且主从表都配置全局序列号递增时执行插入从表报错且导致客户端线程一直阻塞,报错信息如下:
oad catelet class:demo.catlets.BatchInsertSequence to run sql insert into xxx(a,b,c,status)

          values(101,108,'1wegwege',1)
     , 
          values(101,109,'remasdsaark',1)
07/30 17:51:38.110 ERROR $_NIOREACTOR-3-RW -BatchInsertSequence.route(......)
com.alibaba.druid.sql.parser.ParserException: syntax error, expect ')'
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2009)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:1957)
at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:153)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:160)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1658)
at demo.catlets.BatchInsertSequence.route(BatchInsertSequence.java:82)
at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:52)

**Comment by songwie** [comment]
明显sql写错了
insert into xxx(a,b,c,status)

      values(101,108,'1wegwege',1)
     ,  (101,109,'remasdsaark',1)
