### ISSUE TITLE
1.4RC版本，使用大批量INSERT语句插入数据时丢失与MYSQL的连接

### ISSUE THREAD

**Issue by 441853335** [MyCATApache/Mycat-Server#419]
使用source语句大批量INSERT语句，格式如：insert into table1(col1,col2,...) values(v1,v2,...)(v3,v4,...)...  
在values数量很小的情况下没有问题，但是在values数量很大的时候（十万百万级，文件大约数百M）就会丢失连接，还有就是在MYSQL单机中加载文件一切正常。
怀疑是JVM内存与MYCAT缓存的问题。
已经尝试过调大 MaxPermSize，MaxDirectMemorySize，processorBufferChunk，processorBufferPool，maxPacketSize等参数，MYSQL相关的参数max_allowed_packet，max_heap_table_size，tmp_table_size也做过调整，均无效果。

日志如下：

	(273302, 19247, 'Add', NULL, 'c:\\documents and settings\\autoer\\application data\\xda7a\\jlxf.exe'),
 err:java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ')'
java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ')'
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:53)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:57)
	at org.opencloudb.route.RouteService.route(RouteService.java:118)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:201)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:120)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:306)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Thread.java:722)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ')'
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2009)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:1957)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:153)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:160)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1658)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:49)
	... 14 more

从日志来看是语法错误，初步判断是由于整个INSERT语句未读取完整导致。
虽然可以使用替代方案来完成大批量数据插入，但是还是想知道这个问题有没有解决的方法。

**Comment by mycatmerger** [comment]
估计跟sql过长了，druid解析出的错；建议分批拆开或者使用load data

**Comment by 441853335** [comment]
的确是sql过长了，druid解析不了过长的语句吗？ 虽然可以使用替代方法，但是这个问题有没有解决办法

**Comment by magicdoom** [comment]
分批吧
