### ISSUE TITLE
mycat +LVS+ keepalived时运行异常的问题

### ISSUE THREAD

**Issue by caizeyin** [MyCATApache/Mycat-Server#423]
mycat的schema配置内容如下：
<dataHost name="localhost1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
                <heartbeat>show slave status</heartbeat>
                
                
                <writeHost host="hostMaster" url="192.168.0.10:3306" user="mha_repl" password="repl_123456">
                        
                        <readHost host="hostSlave1" url="192.168.0.12:3306" user="mha_repl" password="repl_123456" />
                        <readHost host="hostSlave2" url="192.168.0.13:3306" user="mha_repl" password="repl_123456" />
                        <readHost host="hostSlave3" url="192.168.0.14:3306" user="mha_repl" password="repl_123456" />
                        <readHost host="hostSlave3" url="192.168.0.15:3306" user="mha_repl" password="repl_123456" />
                </writeHost>
        </dataHost>

keepalived 配置正如：
[root@CentOS-005 mycat]# cat /etc/keepalived/keepalived.conf
! Configuration File for keepalived

global_defs {
   notification_email {
   289696491@qq.com
   }
   notification_email_from keepalived@localhost
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
   router_id LVS_DEVEL
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.0.9
    }
}

virtual_server 192.168.0.9 8066 {
    delay_loop 3
    lb_algo lc #rr
    lb_kind DR #NAT
    #nat_mask 255.255.255.0
    #persistence_timeout 50
    protocol TCP

    real_server 192.168.0.15 8066 {
        weight 3
        TCP_CHECK {
            connect_port 8066
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }

    real_server 192.168.0.14 8066 {
        weight 1
        TCP_CHECK {
            connect_port 8066
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }
}
异常信息如下：
08/07 17:18:58.983   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:446) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=47, schema=null, host=192.168.0.15, user=null,txIsolation=3, autocommit=true, schema=null]
08/07 17:18:58.984   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:142) -register error
java.nio.channels.ClosedChannelException
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
        at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:414)
        at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:140)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
        at java.lang.Thread.run(Thread.java:745)
08/07 17:19:01.984   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:446) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=48, schema=null, host=192.168.0.15, user=null,txIsolation=3, autocommit=true, schema=null]
08/07 17:19:01.984   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:142) -register error
java.nio.channels.ClosedChannelException
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
        at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:414)
        at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:140)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
        at java.lang.Thread.run(Thread.java:745)
08/07 17:19:04.984   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:446) -close connection,reason:err:java.io.IOException: Connection reset by peer ,ServerConnection [id=49, schema=null, host=192.168.0.15, user=null,txIsolation=3, autocommit=true, schema=null]
08/07 17:19:04.985   WARN [$_NIOREACTOR-0-RW] (NIOReactor.java:142) -register error
java.nio.channels.ClosedChannelException
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:185)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
        at org.opencloudb.net.FrontendConnection.register(FrontendConnection.java:414)
        at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:140)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
        at java.lang.Thread.run(Thread.java:745)
希望帮忙解决下。

**Comment by caizeyin** [comment]
由于先前发有XML文件格式在HTML页面显示不出来，我这里重新发下
mycat的schema配置内容如下：

**Comment by songwie** [comment]
这个确实有错误，但是不影响使用，只是刷错误日志，暂时先忽略吧，后面正式发布 1.4时候会修复。
