### ISSUE TITLE
mycat1.4，C/S 都开启使用压缩，该异常明显 errno:1023 program err:java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by zhuam** [MyCATApache/Mycat-Server#514]
MyCAT Server startup successfully. see logs in logs/mycat.log
10-21 13:29:12.640   WARN [$_NIOREACTOR-2-RW] (BufferPool.java:175) -allocate buffer size large than default chunksize:4096 he want 8192

java.nio.BufferOverflowException
	at java.nio.DirectByteBuffer.put(Unknown Source)
	at java.nio.ByteBuffer.put(Unknown Source)
	at org.opencloudb.util.CompressUtil.compressMysqlPacket(CompressUtil.java:67)
	at org.opencloudb.util.CompressUtil.compressMysqlPacket(CompressUtil.java:30)
	at org.opencloudb.net.AbstractConnection.writeNotSend(AbstractConnection.java:363)
	at org.opencloudb.net.AbstractConnection.writeToBuffer(AbstractConnection.java:426)
	at org.opencloudb.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:285)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134)
	at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:253)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Unknown Source)

10-21 13:29:13.921   WARN [$_NIOREACTOR-2-RW] (SingleNodeHandler.java:187) -execute  sql err : errno:1023 program err:java.nio.BufferOverflowException con:MySQLConnection [id=26, lastTime=1445405348578, schema=flight, old shema=flight, borrowed=true, fromSlaveDB=true, threadId=54897, charset=utf8, txIsolation=3, autocommit=true, attachment=dataNode2{SHOW STATUS}, respHandler=SingleNodeHandler [node=dataNode2{SHOW STATUS}, packetId=-85], host=192.168.5.11, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@5dcdf1, writeQueue=0, modifiedSQLExecuted=false]

**Comment by zhuam** [comment]
客户端通过 navicat 执行 很简单的SQL： SELECT * from dynamic limit 10， BUFFER就出问题了

收到
[Err] 2013 - Lost connection to MySQL server during query

**Comment by zhuam** [comment]
https://github.com/MyCATApache/Mycat-Server/issues/403

把processorBufferChunk设置成20480后不报这个错了

**Comment by zhuam** [comment]
结合 https://github.com/MyCATApache/Mycat-Server/issues/303 ，再看一下代码，明了

**Comment by zhuam** [comment]
测试

开启压缩
MYSQL直连 与 MYCAT连，不论怎么调优性能相差 5-10倍，返回的结果集数据越大，越明显

不开启压缩
MYSQL直连 与 MYCAT连 ，单条SQL返回的耗时，相差不大

注：官方的MYSQL压缩与不压缩之间的性能消耗相差不大
