### ISSUE TITLE
通过reload @@config方式重新加载配置报空指针错误

### ISSUE THREAD

**Issue by ywooer** [MyCATApache/Mycat-Server#526]
Mycat version: 5.5.8-mycat-1.4-release-20151019230038
修改schema.xml的dataNode标签的name属性，然后通过管理端口连接Mycat执行reload @@config，然后通过8066端口连接Mycat执行sql命令抛出ERROR 3009 (HY000): java.lang.NullPointerException，查看logs/mycat.log日志发现的异常信息如下：
10/29 18:21:48.131   WARN [$_NIOREACTOR-18-RW](NonBlockingSession.java:131) -ServerConnection [id=3, schema=boluofan, host=192.168.0.200, user=mytest,txIsolation=3, autocommit=true, schema=boluofan]show tables, route={
   1 -> defaultD{show tables}
}
java.lang.NullPointerException
        at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:124)
        at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:129)
        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:216)
        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
        at org.opencloudb.server.response.ShowTables.response(ShowTables.java:50)
        at org.opencloudb.server.handler.ShowHandler.handle(ShowHandler.java:51)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:70)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:319)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:456)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:434)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
验证下最新版本是否解决

**Comment by magicdoom** [comment]
1.6.5已经支持不丢事务reload
