### ISSUE TITLE
ERROR 1064 (HY000): String index out of range: -1

### ISSUE THREAD

**Issue by zhuam** [MyCATApache/Mycat-Server#539]
mysql> /*!mycat:sql=SELECT * FROM company*/insert into company(_id,name) values(
27,"test");
No connection. Trying to reconnect...
Connection id:    1
Current database: TESTDB1

ERROR 1064 (HY000): String index out of range: -1

//异常信息

11-02 13:25:39.281   WARN [$_NIOREACTOR-2-RW] (ServerConnection.java:202) -ServerConnection [id=1, schema=TESTDB1, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=TESTDB1]/*!mycat:sql=SELECT * FROM company*/insert into company(_id,name) values(27,"test") err:java.lang.StringIndexOutOfBoundsException: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.opencloudb.util.StringUtil.getTableName(StringUtil.java:531)
	at org.opencloudb.route.util.RouterUtil.processERChildTable(RouterUtil.java:1124)
	at org.opencloudb.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:71)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:26)
	at org.opencloudb.route.handler.HintSQLHandler.route(HintSQLHandler.java:31)
	at org.opencloudb.route.RouteService.route(RouteService.java:107)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:197)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:150)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:120)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:436)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Unknown Source)

**Comment by magicdoom** [comment]
验证下最新版是否解决
