### ISSUE TITLE
mybatis连接mycat１.４　出错

### ISSUE THREAD

**Issue by lcq251** [MyCATApache/Mycat-Server#587]
Connection con = DriverManager.getConnection(url);
            Statement stmt = con.createStatement();
            // String query ="show VARIABLES like '%max_allowed_packet%'";
            String query=  "select * from COMPANY where ID=1";
            ResultSet rs=stmt.executeQuery(query);

出错信息如下：
Tue Dec 01 16:30:07 CST 2015 WARN: Invalid value 'null' for server variable named 'auto_increment_increment', falling back to sane default of '1'.
com.mysql.jdbc.PacketTooBigException: Packet for query is too large (43 > -1). You can change this value on the server by setting the max_allowed_packet' variable.
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:570)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:415)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3032)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2280)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
	at TestMybatis.testJdbc(TestMybatis.java:75)
	at TestMybatis.main(TestMybatis.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by magicdoom** [comment]
应该是jdbc驱动问题，最新1.4.1已结支持5.1.37驱动 ，你可以试试

**Comment by runfriends** [comment]
jdbc驱动问题
