### ISSUE TITLE
mycat2.0出现charsetName为空；默认情况charsetName和mycat.xml里面的节点system的charset有关联？

### ISSUE THREAD

**Issue by low901028** [MyCATApache/Mycat-Server#703]
一、异常信息
java.lang.NullPointerException: charsetName
	at java.lang.String.<init>(String.java:412) ~[?:1.8.0_25]
	at io.mycat.server.packet.MySQLMessage.readString(MySQLMessage.java:230) ~[classes/:?]
	at io.mycat.server.MySQLFrontConnection.query(MySQLFrontConnection.java:233) ~[classes/:?]
	at io.mycat.server.MySQLFrontConnectionHandler.doHandleBusinessMsg(MySQLFrontConnectionHandler.java:215) ~[classes/:?]
	at io.mycat.server.MySQLFrontConnectionHandler.handle(MySQLFrontConnectionHandler.java:42) [classes/:?]
	at io.mycat.server.MySQLFrontConnectionHandler.handle(MySQLFrontConnectionHandler.java:1) [classes/:?]
	at io.mycat.net.Connection.handle(Connection.java:185) [classes/:?]
	at io.mycat.net.Connection.onReadData(Connection.java:234) [classes/:?]
	at io.mycat.net.Connection.asynRead(Connection.java:656) [classes/:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:75) [classes/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
2016-01-05 19:11:48.297 DEBUG [Timer1] (io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:108)) - JDBCHeartBeat con query sql: select 1
2016-01-05 19:11:58.298 DEBUG [Timer0] (io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:108)) - JDBCHeartBeat con query sql: select 1
2016-01-05 19:12:08.298 DEBUG [Timer1] (io.mycat.backend.jdbc.JDBCHeartbeat.heartbeat(JDBCHeartbeat.java:108)) - JDBCHeartBeat con query sql: select 1
2016-01-05 19:12:10.987  INFO [$_NIOREACTOR-2-RW] (io.mycat.server.MySQLFrontConnectionHandler.success(MySQLFrontConnectionHandler.java:175)) - Connection [host=127.0.0.1,  port=55081, id=12, state=connecting, direction=in, startupTime=1451992330975, lastReadTime=1451992330975, lastWriteTime=1451992330975]'sa' login success
2016-01-05 19:12:10.988  WARN [$_NIOREACTOR-2-RW] (io.mycat.server.MySQLFrontConnectionHandler.handle(MySQLFrontConnectionHandler.java:44)) - caught err 
java.lang.NullPointerException: charsetName
二、mycat.xml配置内容
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mycat:server>
<mycat>
    <server-config>
		<system>
			<property name="sequnceHandlerType">2</property>
			<property name="serverPort">8066</property>
			<property name="managerPort">9066</property>
			<property name="charset">utf8</property>
		</system>
		<user name="sa">
			<property name="password">admin123456</property>
			<property name="schemas">BaseCardDB</property>
		</user>
    </server-config>
    
    <schema-config>
		<schema name="BaseCardDB" checkSQLschema="false" sqlMaxLimit="100">
			<table name="Users" dataNode="dn1" type="global"/>		
		</schema>

		<dataNode name="dn1" dataHost="localhost1" database="BaseCardDB" />

		<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
			writeType="0" dbType="sqlserver" dbDriver="jdbc" switchType="0"  slaveThreshold="100">
			<heartbeat>select 1</heartbeat>
			
			<writeHost host="hostM1" url="jdbc:sqlserver://127.0.0.1:1433;DatabaseName=BaseCardDB" user="sa" password="admin123456">
				
			</writeHost>
		</dataHost>
    </schema-config>
    
    
    
    
     
    
    
    
</mycat>
三、客户端用c#  后端数据库为sqlserver

**Comment by digdeep126** [comment]
你配置的是 jdbc:sqlserver 协议，怎么异常显示你走了mysql协议呢？正常应该走JDBC协议。有更多信息吗？可以修改log4j2.xml中的log级别，输出更多调试信息看看。

**Comment by digdeep126** [comment]
你错误走了mysql协议，但是因为你配置的是jdbc:sqlserver，所以系统的mysql协议相关的charset信息没有初始化，也无法初始化(2.0需要从mysqld获取)，所以报空指针。关键是你走错了协议。

**Comment by digdeep126** [comment]
该问题原因已经找到：仅仅发生在纯sql server，或者oracle的等其他非mysql数据库的情况下，如果至少配置了一台mysql都不会出现该问题。问题也已经被fix掉了。

**Comment by low901028** [comment]
问题已解决 ； mycat默认需要提供一个mysql用于获取charset；在mycat中配置一个mysql即可

**Comment by digdeep126** [comment]
已经不需要默认的有一个msyql了，该问题已经fix掉了。
