### ISSUE TITLE
《MyCat_In_Action_中文版.doc》中示例，报错can't find (root) parent sharding node for sql:INSERT INTO orders (id, customer_id)

### ISSUE THREAD

**Issue by victorydsk** [MyCATApache/Mycat-Server#73]
根据《MyCat_In_Action_中文版.doc》中的步骤在windows下面测试的时候，报标题所示错误，请各位帮忙分析下原因，具体环境如下：

windows7，64位
JDK1.7
MySQL5.0.45，Community Edition

具体错误信息如下：
2/31 14:15:53.700   WARN [$_NIOREACTOR-0-RW] (ServerConnection.java:170) -ServerConnection [id=1, schema=TESTDB, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=TESTDB]insert into orders(id,customer_id) values(2,2) err:java.sql.SQLNonTransientException: can't find (root) parent sharding node for sql:INSERT INTO orders (id, customer_id)
VALUES (2, 2)
java.sql.SQLNonTransientException: can't find (root) parent sharding node for sql:INSERT INTO orders (id, customer_id)
VALUES (2, 2)
	at org.opencloudb.parser.druid.impl.DruidInsertParser.parserChildTable(DruidInsertParser.java:138)
	at org.opencloudb.parser.druid.impl.DruidInsertParser.statementParse(DruidInsertParser.java:50)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:60)
	at org.opencloudb.route.impl.DruidMysqlRouteStrategy.routeNormalSqlWithAST(DruidMysqlRouteStrategy.java:35)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:46)
	at org.opencloudb.route.RouteService.route(RouteService.java:112)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:162)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:263)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:56)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:370)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:264)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:97)
	at java.lang.Thread.run(Thread.java:722)

**Comment by apachemycat** [comment]
若上述SQL执行超过10秒后才报错，可能原因是CPU为单核心导致默认只有一个线程出现无法回调导致超时，设置server.xml 里面的参数如下：
<mycat:server xmlns:mycat="http://org.opencloudb/">
	<system>
	<property name="processors">4</property> 
	<property name="processorExecutor">4</property> 
	</system>

**Comment by bluoy** [comment]
遇到与楼主同样的问题。
mycat：cpu: i3  4核心，os: ubuntu 14.04 64bit， jdk 1.7.0_02, 使用mysql协议连接mysql服务器。
mysql：cpu: i3  4核心，os: xp sp3, 单机双mysql实例配置

故障现象：
只要是对child table进行insert操作，就会机率性卡死，5分钟后返回，log中抛同样的异常。

初步跟踪了代码（版本与master同步）：
SystemConfig中缺省已经有避免单核心的逻辑，所以可以排除单线程这个原因。
FetchStoreNodeOfChildTableHandler中的execute()函数，5分钟阀值在此处定义，卡死是因为dataNode始终为null,所以一直在循环等待直到超时。dataNode为空，是因为MySQLConnection中的handleData()函数没有进入handleRowPacket()触发上述Handler的rowResponse()，其实出错时连handleData()都没触发。
使用wireshark监听网络通信，mysql应答是正常的。
也就是说，mycat接受到了正常应答包，但没有触发handleData()函数。难道时NIOReactor的问题？

**Comment by bluoy** [comment]
设置usingAIO=1后问题解决，难道是NIO部分后引入的bug?

**Comment by victorydsk** [comment]
请问一下楼上的，这个usingAIO是在什么地方配置的？

**Comment by bluoy** [comment]
在server.xml中的<system>部分追加:
<property name="usingAIO">1</property>

On 2015年01月08日 20:41, victorydsk wrote:
>
> 请问一下楼上的，这个usingAIO是在什么地方配置的？
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MyCATApache/Mycat-Server/issues/73#issuecomment-69174154>.
>

---------------------------------------------------------------------------------------------------
Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s) 
is intended only for the use of the intended recipient and may be confidential and/or privileged of 
Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is 
not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying 
is strictly prohibited, and may be unlawful.If you have received this communication in error,please 
immediately notify the sender by return e-mail, and delete the original message and all copies from 
your system. Thank you. 
---------------------------------------------------------------------------------------------------

**Comment by victorydsk** [comment]
OK，感谢bluoy

**Comment by linzhiqiang0514** [comment]
NIO是否有人研究一下是什么问题导致的？

**Comment by shihao138096** [comment]
对于“基于E-R关系分片策略”部分的内容，使用虚拟机的话，需要将VM->Settings->Processors中的处理器数修改为>2，然后，将server.xml中的如下两行的注释去掉
<property name="processors">2</property>
<property name="processorExecutor">32</property>

最后，重启mycat就ok了。
