### ISSUE TITLE
Mycat-server-1.5-GA-20160225120029-linux.tar.gz 中demo.catlets.BatchInsertSequence报空指针

### ISSUE THREAD

**Issue by digdeep126** [MyCATApache/Mycat-Server#761]
server.xml:  
      <system>
        <property name="defaultSqlParser">druidparser</property>
        <property name="sequnceHandlerType">1</property>
        </system>
        <user name="root">
                <property name="password">digdeep</property>
                <property name="schemas">TESTDB</property>
        </user>

        <user name="read_user">
                <property name="password">test</property>
                <property name="schemas">TESTDB</property>
                <property name="readOnly">true</property>
        </user>

 schema.xml

        <schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">
                <table name="travelrecord" dataNode="dn1,dn2,dn3" rule="auto-sharding-long" />
                <table name="company" primaryKey="ID" type="global" dataNode="dn1,dn2,dn3" />
                <table name="goods" primaryKey="ID" type="global" dataNode="dn1,dn2" />
                <table name="hotnews" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="mod-long" />
        </schema>

        <dataNode name="dn1" dataHost="localhost1" database="db1" />
        <dataNode name="dn2" dataHost="localhost1" database="db2" />
        <dataNode name="dn3" dataHost="localhost1" database="db3" />

        <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
                writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="localhost:3306" user="root" password="digdeep">
                </writeHost>
        </dataHost>

登录：
[root@localhost ~]# mysql -uroot -p -P 8066 -h 192.168.1.200
然后执行：
`(root@192.168.1.200)[TESTDB]mysql>/*!mycat:catlet=demo.catlets.BatchInsertSequence*/insert into hotnews (title) values('test5'),('test77777');`
被卡住，然后日志文件报错：
`03/01 11:16:22.745  DEBUG [$_NIOREACTOR-0-RW] (ServerQueryHandler.java:56) -ServerConnection [id=1, schema=TESTDB, host=192.168.1.200, user=root,txIsolation=3, autocommit=true, schema=TESTDB]/*!mycat:catlet=demo.catlets.BatchInsertSequence*/insert into hotnews (title) values('test5'),('test77777')
03/01 11:16:22.756  DEBUG [$_NIOREACTOR-0-RW] (HintCatletHandler.java:46) -load catelet class:demo.catlets.BatchInsertSequence to run sql insert into hotnews (title) values('test5'),('test77777')
03/01 11:16:22.761  DEBUG [$_NIOREACTOR-0-RW] (IncrSequenceMySQLHandler.java:130) -get next segement of sequence from db for sequnce:HOTNEWS curVal 0
03/01 11:16:22.762  DEBUG [$_NIOREACTOR-0-RW] (IncrSequenceMySQLHandler.java:168) -execute in datanode dn1 for fetch sequnce sql SELECT mycat_seq_nextval('HOTNEWS')
03/01 11:16:27.189  DEBUG [Timer1] (SQLJob.java:85) -con query sql:select user() to con:MySQLConnection [id=11, lastTime=1456802187189, user=root, schema=db1, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=246, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
03/01 11:16:27.190  DEBUG [Timer1] (SQLJob.java:85) -con query sql:select user() to con:MySQLConnection [id=4, lastTime=1456802187190, user=root, schema=db1, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=243, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
03/01 11:16:32.858  ERROR [$_NIOREACTOR-0-RW] (BatchInsertSequence.java:123) -BatchInsertSequence.route(......)
java.lang.RuntimeException: can't fetch sequnce in db,sequnce :HOTNEWS detail:null
        at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:142)
        at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:111)
        at demo.catlets.BatchInsertSequence.route(BatchInsertSequence.java:113)
        at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:52)
        at org.opencloudb.route.RouteService.route(RouteService.java:115)
        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:722)
03/01 11:16:32.867  ERROR [$_NIOREACTOR-0-RW] (BatchInsertSequence.java:135) -BatchInsertSequence.getRoute(String sql)
java.lang.NullPointerException
        at org.opencloudb.route.util.RouterUtil.processWithMycatSeq(RouterUtil.java:440)
        at org.opencloudb.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:89)
        at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:29)
        at demo.catlets.BatchInsertSequence.getRoute(BatchInsertSequence.java:133)
        at demo.catlets.BatchInsertSequence.processSQL(BatchInsertSequence.java:52)
        at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:53)
        at org.opencloudb.route.RouteService.route(RouteService.java:115)
        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
`
Mycat-server-1.5-GA-20160225120029-win.tar.gz 没有该问题，发现 win 版 和 linux 不一致......

**Comment by digdeep126** [comment]
也就是 Mycat-server-1.5-GA-20160225120029-linux.tar.gz 的 BatchInsertSequence 需要先执行：
insert into hotnews(id,title) values(next value for MYCATSEQ_HOTNEWS, 'ttt');
然后在执行：
/*!mycat:catlet=demo.catlets.BatchInsertSequence*/insert into hotnews (title) values('test5'),('test77777');
才不会报错。如果没有执行前者，直接执行后者，会包空指针。
Mycat-server-1.5-GA-20160225120029-win.tar.gz 没有该问题。

**Comment by magicdoom** [comment]
研究下看看是不是源码问题  还是打包问题

**Comment by magicdoom** [comment]
1.6已经支持批量语句不加注解执行
