### ISSUE TITLE
mycat在ubuntu14下运行出现错误：com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION

### ISSUE THREAD

**Issue by yiqiuheng** [MyCATApache/Mycat-Server#771]
系统：ubuntu14
mysql版本：5.6
mycat版本：1.6
在navicat测试sql语句：
explain create table employee (id int not null primary key,name varchar(100),sharding_id int not null);
执行结果成功，并且在按照schema配置在dn1和dn2上执行。
查看执行信息，结果如下：
==============================================================================
[SQL] explain create table employee (id int not null primary key,name varchar(100),sharding_id int not null);
受影响的行: 0
时间: 0.004s
**[Err] 1064 - com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION**
==============================================================================
查看mycat.log，log报错如下：
===============================================================================
03/04 13:24:20.916   WARN [$_NIOREACTOR-0-RW] (ServerConnection.java:232) -ServerConnection [id=3, schema=TESTDB, host=192.168.3.107, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SELECT STATE AS `Status`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ err:java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
        at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:54)
        at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
        at org.opencloudb.route.RouteService.route(RouteService.java:129)
        at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
        at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
        at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:102)
        at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
        at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
        at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
        at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
        at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1471)
        at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:693)
        at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:555)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:119)
        at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:789)
        at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:690)
        at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
        at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectItem(SQLSelectParser.java:298)
        at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:275)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:127)
        at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:196)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1658)
        at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:50)
        ... 15 more
=============================================================================

上面的报错，及sql语句都不知道哪里来的，应该是源码中的。

我在redhat6中，执行上面的语句，没有任何错误，配置文件和环境一下，只是系统换成了ubuntu。
网上没有类似错误信息，希望可以帮忙check一下。

**Comment by yiqiuheng** [comment]
@wenerme @zhuam @ifrenzyc @runfriends @magicdoom

**Comment by magicdoom** [comment]
应该是navicat自动发的语句

**Comment by digdeep126** [comment]
那应该是 navicat 的bug 吧，`SUM(DURATION)/*100` 这里明显多了 一个 ‘*’ 号。正确的语句应该是：
`mysql> SELECT STATE AS Status, ROUND(SUM(DURATION),7) AS Duration, CONCAT(ROUND(SUM(DURATION)/100,3),'%') AS Percentage
    -> FROM INFORMATION_SCHEMA.PROFILING
    -> WHERE QUERY_ID='GROUP BY STATE ORDER BY SEQ';
+--------+----------+------------+
| Status | Duration | Percentage |
+--------+----------+------------+
| NULL   |     NULL | NULL       |
+--------+----------+------------+
1 row in set (0.05 sec)`

**Comment by digdeep126** [comment]
可以试着将 navicat 的 该功能关闭。

**Comment by Oloong** [comment]
同一个NAVICAT 1.4版本的就不会返回这个错误，不知1.5的版本为什么会把这个错误返回给客户端。应该是客户端的兼容问题，有可能是NAVICAT取的SESSION变量值，在MYCAT中无效，不能正确传递参数。
CONCAT(ROUND(SUM(DURATION)/？*100,3), '%') 少了个被除数值和QUERY_ID=？值，没能获取到变量值导致！

**Comment by magicdoom** [comment]
后续会修复   这个只影响navicat  不影响实际应用   已经有类似isses
