### ISSUE TITLE
reload @@config成功，但是进入mycat，showtables报错：ERROR 3009 (HY000):  java.lang.NullpointerException

### ISSUE THREAD

**Issue by chenjing7232** [MyCATApache/Mycat-Server#775]
1、在mycat新配置逻辑库后，动态加载mycat，动态加载成功；
2、连接mycat,，连接成功；
3、show databases，可以成功显示逻辑库名；
4、再进入逻辑库，执行show tables语句，报错：ERROR 3009 (HY000):  java.lang.NullpointerException
###请不要怀疑我配置文件配错了
5、重启mycat服务
6、执行1-4，进入逻辑库，执行show tables，可以正常执行，无报错！

============
上述步骤4里show tables报错部分，mycat的debug日志如下：
03/07 13:43:42.539   INFO [$_NIOREACTOR-1-RW] (FrontendAuthenticator.java:193) -ServerConnection [id=84836, schema=null, host=10.7.13.37, user=broadcast,txIsolation=3, autocommit=true, schema=null]'broadcast' login success
03/07 13:43:54.211   WARN [$_NIOREACTOR-1-RW] (NonBlockingSession.java:130) -ServerConnection [id=84836, schema=broadcast, host=10.7.13.37, user=broadcast,txIsolation=3, autocommit=true, schema=broadcast]show tables, route={
   1 -> broadcast_dn1{show tables}
}
java.lang.NullPointerException
    at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:159)
    at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:128)
    at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:239)
    at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
    at org.opencloudb.server.response.ShowTables.response(ShowTables.java:56)
    at org.opencloudb.server.handler.ShowHandler.handle(ShowHandler.java:48)
    at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:73)
    at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
    at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
    at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
    at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
    at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
    at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
    at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
    at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
    at java.lang.Thread.run(Thread.java:744)
03/07 13:43:54.212   WARN [$_NIOREACTOR-1-RW] (NonBlockingSession.java:130) -ServerConnection [id=84836, schema=broadcast, host=10.7.13.37, user=broadcast,txIsolation=3, autocommit=true, schema=broadcast]show warnings, route={
   1 -> broadcast_dn1{show warnings}
}
java.lang.NullPointerException
    at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:159)
    at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:128)
    at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:239)
    at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
    at org.opencloudb.server.handler.ShowHandler.handle(ShowHandler.java:60)
    at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:73)
    at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
    at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
    at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
    at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
    at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
    at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
    at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
    at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
    at java.lang.Thread.run(Thread.java:744)
03/07 13:43:55.355   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:458) -close connection,reason:quit cmd ,ServerConnection [id=84836, schema=broadcast, host=10.7.13.37, user=broadcast,txIsolation=3, autocommit=true, schema=broadcast]
03/07 13:44:04.221   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:458) -close connection,reason:quit cmd ,ServerConnection [id=84693, schema=subpub, host=10.7.13.11, user=admin,txIsolation=3, autocommit=true, schema=subpub]
03/07 13:44:04.256   INFO [$_NIOREACTOR-0-RW] (FrontendAuthenticator.java:193) -ServerConnection [id=84841, schema=subpub, host=10.7.13.11, user=admin,txIsolation=3, autocommit=true, schema=subpub]'admin' login success
03/07 13:44:06.590   INFO [$_NIOREACTOR-1-RW] (FrontendAuthenticator.java:193) -ServerConnection [id=84842, schema=linecenter, host=10.7.14.209, user=linecenter,txIsolation=3, autocommit=true, schema=linecenter]'linecenter' login success
03/07 13:44:08.291   WARN [$_NIOREACTOR-1-RW] (SingleNodeHandler.java:229) -execute  sql err : errno:1048 Column 'inputMan' cannot be null con:MySQLConnection [id=266, lastTime=1457329448282, user=coupon, schema=coupon, old shema=coupon, borrowed=true, fromSlaveDB=false, threadId=649849, charset=utf8, txIsolation=3, autocommit=false, attachment=coupon_dn1{insert into CouponsDetail (couponDetailId, couponId, couponCode,

================
另外：
1、上述操作是在公司公用测试环境进行的，也就是reload过程，有大量外部连接进来；
我在个人测试环境执行reload @config，不会出现上述一系列报错
2、上述问题有偶发性，99%会出现上述错误

**Comment by stevenlii** [comment]
reload 确实有bug, 我在线上reload了一下，刚开始我也是心大，结果一下子所有DB连接全部被断开了，结果监控报警马上就来了，我一看，只好赶紧重启了一下mycat，结果一重启，所有业务都需要重启了！！！。。。。

后来开了次会，哔掉了MyCat................

**Comment by fireflyhoo** [comment]
出现问题的版本是什么?

**Comment by lesstraveller** [comment]
我也遇到同样的问题，没有找到解决办法
