### ISSUE TITLE
java.nio.Buffer.position 抛异常

### ISSUE THREAD

**Issue by yxb0926** [MyCATApache/Mycat-Server#827]
版本为1.4。 上线之后，发现buffer.position经常抛异常，应该是越界了。能否解决下。

2016-04-20 02:37:27.049  WARN [$_NIOREACTOR-2-RW] (AbstractConnection.java:386) - write err:
java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:96)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.opencloudb.net.NIOSocketWR.write0(NIOSocketWR.java:98)
        at org.opencloudb.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:42)
        at org.opencloudb.net.AbstractConnection.write(AbstractConnection.java:384)
        at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler.fieldEofResponse(MultiNodeQueryHandler.java:457)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:191)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:117)
        at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
        at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:257)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

2016-04-20 08:35:12.130  WARN [$_NIOREACTOR-30-RW] (MultiNodeQueryHandler.java:472) - caught exception
java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:377)
        at org.opencloudb.net.AbstractConnection.writeToBuffer(AbstractConnection.java:418)
        at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler.fieldEofResponse(MultiNodeQueryHandler.java:452)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:191)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:117)
        at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
        at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
        at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:257)
        at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
        at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
        at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
        at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
        at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
检查是否不同分片的  表结构不一致的情况

**Comment by yxb0926** [comment]
只有一个分片，没有分库。我调大了MaxDirectMemorySize报错减少了。 怀疑是DirectBuffer那块的问题。

**Comment by magicdoom** [comment]
你这个明显是多个分片在出来返回列时报的错   MultiNodeQueryHandler.fieldEofResponse

**Comment by yxb0926** [comment]
好的，多谢， 我看看。
