### ISSUE TITLE
1.5release版中，心跳超时的判断是不是有bug？

### ISSUE THREAD

**Issue by Sy9876** [MyCATApache/Mycat-Server#856]
MySQLDetector.java中，isHeartbeatTimeout()中使用的变量heartbeatTimeout是不是没有设置？（没找到调用setter的地方，debug调试时也是0。是不是应该在构造器中，使用heartbeat对象里的超时时间来设置？）

在我的测试环境中，偶尔有发生心跳TIMEOUT的情况，而且只要一发生，就会去做自动切换（switchSourceIfNeed），不像心跳错误时，到maxRetryCount才会切换。

org\opencloudb\heartbeat\MySQLDetector.java：
```java
public class MySQLDetector implements
		SQLQueryResultListener<SQLQueryResult<Map<String, String>>> {
	private MySQLHeartbeat heartbeat;
	private long heartbeatTimeout;

	public long getHeartbeatTimeout() {
		return heartbeatTimeout;
	}

	public void setHeartbeatTimeout(long heartbeatTimeout) {
		this.heartbeatTimeout = heartbeatTimeout;
	}

	public boolean isHeartbeatTimeout() {
		return TimeUtil.currentTimeMillis() > Math.max(lastSendQryTime,
				lasstReveivedQryTime) + heartbeatTimeout;
	}
```

org\opencloudb\heartbeat\DBHeartbeat.java:
```java
public abstract class DBHeartbeat {
	public static final int OK_STATUS = 1;
	public static final int ERROR_STATUS = -1;
	public static final int TIMEOUT_STATUS = -2;
	public static final int INIT_STATUS = 0;
	private static final long DEFAULT_HEARTBEAT_TIMEOUT = 30 * 1000L;
	private static final int DEFAULT_HEARTBEAT_RETRY = 10;
	// heartbeat config
	protected long heartbeatTimeout = DEFAULT_HEARTBEAT_TIMEOUT; // 心跳超时时间
	protected int heartbeatRetry = DEFAULT_HEARTBEAT_RETRY; // 检查连接发生异常到切换，重试次数
```

**Comment by HashZhang** [comment]
这个目前的心跳机制还不会发生bug，因为不是主动心跳。。

**Comment by Sy9876** [comment]
今天又发生了一次心跳TIMEOUT后自动切换。
根据dnindex.properties，得知自动切换发生在16:19:21。
```
#update
#Wed May 11 16:19:21 CST 2016
dh1=1
```

我监控到的heartbeat状态(每隔5秒执行一下show @@heartbeat; )如下：

```

2016/05/11 16:19:01
NAME    TYPE    HOST    PORT    RS_CODE RETRY   STATUS  TIMEOUT EXECUTE_TIME    LAST_ACTIVE_TIME    STOP
dh1M1   mysql   xx.xxx.xx.52    3306    1   0   idle    0   0,0,0   2016-05-11 16:18:51 false
dh1M2   mysql   xx.xxx.xx.53    3306    1   0   idle    0   0,0,0   2016-05-11 16:18:51 false

2016/05/11 16:19:06
NAME    TYPE    HOST    PORT    RS_CODE RETRY   STATUS  TIMEOUT EXECUTE_TIME    LAST_ACTIVE_TIME    STOP
dh1M1   mysql   xx.xxx.xx.52    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:01 false
dh1M2   mysql   xx.xxx.xx.53    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:01 false

2016/05/11 16:19:11
mycat没有响应

2016/05/11 16:19:16
NAME    TYPE    HOST    PORT    RS_CODE RETRY   STATUS  TIMEOUT EXECUTE_TIME    LAST_ACTIVE_TIME    STOP
dh1M1   mysql   xx.xxx.xx.52    3306    1   0   checking    0   0,0,0   2016-05-11 16:19:01 false
dh1M2   mysql   xx.xxx.xx.53    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:11 false

2016/05/11 16:19:21
NAME    TYPE    HOST    PORT    RS_CODE RETRY   STATUS  TIMEOUT EXECUTE_TIME    LAST_ACTIVE_TIME    STOP
dh1M1   mysql   xx.xxx.xx.52    3306    1   0   checking    0   0,0,0   2016-05-11 16:19:01 false
dh1M2   mysql   xx.xxx.xx.53    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:11 false

2016/05/11 16:19:26
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

2016/05/11 16:19:31
NAME    TYPE    HOST    PORT    RS_CODE RETRY   STATUS  TIMEOUT EXECUTE_TIME    LAST_ACTIVE_TIME    STOP
dh1M1   mysql   xx.xxx.xx.52    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:21 false
dh1M2   mysql   xx.xxx.xx.53    3306    1   0   idle    0   0,0,0   2016-05-11 16:19:21 false
```

可以从LAST_ACTIVE_TIME看出，每隔10秒心跳一次，
16:19:01成功后，16:19:21再次成功，本应该在16:19:11执行的那次心跳没有返回，
而16:19:21再次执行时，直接认为是心跳超时，进而切换。
这中间只间隔了20秒，并没有达到DEFAULT_HEARTBEAT_TIMEOUT的30秒。

**Comment by Sy9876** [comment]
补充一下，wrapper.log里报下面的错了。
```
INFO   | jvm 1    | 2016/05/11 16:18:47 | Exception in thread "$_NIOREACTOR-1-RW" java.lang.OutOfMemoryError: Direct buffer memory
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at java.nio.Bits.reserveMemory(Bits.java:658)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.buffer.BufferPool.createDirectBuffer(BufferPool.java:168)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.buffer.BufferPool.allocate(BufferPool.java:101)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.AbstractConnection.allocate(AbstractConnection.java:232)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.AbstractConnection.writeToBuffer(AbstractConnection.java:427)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:272)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:257)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
INFO   | jvm 1    | 2016/05/11 16:18:47 |   at java.lang.Thread.run(Thread.java:722)
```

**Comment by 2899722744** [comment]
oom故障了，所以切了。。。
最好查一下为何oom。

**Comment by magicdoom** [comment]
堆外内存设置的不够用了

**Comment by Sy9876** [comment]
oom估计是因为MaxDirectMemorySize配小了（好像配成64M了）
后来已经改为 -XX:MaxDirectMemorySize=2G 了。但是还会有switch发生，
并且switch时没有oom发生。

**Comment by magicdoom** [comment]
你配置的是哪种切换方式

**Comment by Sy9876** [comment]
switchType="2"
`<dataHost name="dh1" maxCon="1000" minCon="10" balance="0"
        writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="dh1M1" url="mysql1:3306" user="user" password="password" />
        <writeHost host="dh1M2" url="mysql1:3306" user="user" password="password" />
</dataHost>`

**Comment by Sy9876** [comment]
switchType="2"

<dataHost name="dh1" maxCon="1000" minCon="10" balance="0"
        writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="dh1M1" url="mysql1:3306" user="user" password="password" />
        <writeHost host="dh1M2" url="mysql1:3306" user="user" password="password" />
</dataHost>

**Comment by Sy9876** [comment]
switchType="2"

```
<dataHost name="dh1" maxCon="1000" minCon="10" balance="0"
        writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="dh1M1" url="mysql1:3306" user="user" password="password" />
        <writeHost host="dh1M2" url="mysql1:3306" user="user" password="password" />
</dataHost>
```

**Comment by Sy9876** [comment]
后来又发生过由于"$_NIOREACTOR-xx-RW" OOM导致切换的事情。
发生OOM是由于应用程序里从数据库select百万条数据导致的，这个没问题，是应用程序没控制好。

但我认为这不应该影响心跳检测，数据库还是正常工作的，不应该发生切换。
另外，"$_NIOREACTOR-xx-RW"由于OOM死掉后，即使切换也不能正常工作了吧？

**Comment by 2899722744** [comment]
OOM后，Java应用算是“植物人”应用了。
这个时候，可以使用mysql客户端应该是连不上Mycat了。
切走后，切不回来。。

**Comment by Sy9876** [comment]
mycat默认会启动多个"$_NIOREACTOR-xx-RW"，好像是和CPU核心数一样的。
比如8核CPU就启动8个"$_NIOREACTOR-xx-RW"线程。

不清楚是怎么调度的，根据现象来看，只要8个线程不全都OOM死掉，还是有机会成功连接mycat的。

我认为现在mycat不够完善的地方是，
由于"$_NIOREACTOR-xx-RW"发生OOM，导致心跳测试失败，进而发生切换。其实mysql完全没有故障。

是不是能够把心跳测试和执行SQL的组件分开？不要因为执行SQL导致OOM影响心跳测试。
