### ISSUE TITLE
when update/delete a child table, throws a NullPointerException.

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#86]
java.lang.NullPointerException
	at org.opencloudb.route.util.RouterUtil.ruleCalculate(RouterUtil.java:411)
	at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:703)
	at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:577)
	at org.opencloudb.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:466)
	at org.opencloudb.route.impl.DruidMysqlRouteStrategy.routeNormalSqlWithAST(DruidMysqlRouteStrategy.java:48)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:46)
	at org.opencloudb.route.RouteService.route(RouteService.java:112)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:165)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:154)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:250)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:56)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:357)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:276)
	at org.opencloudb.net.AIOReadHandler.completed(AIOSocketWR.java:141)
	at org.opencloudb.net.AIOReadHandler.completed(AIOSocketWR.java:1)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)

**Comment by bluoy** [comment]
测试语句：  delete from customer_addr where id=2;
目前路由算法缺少根据子表的joinkey，parentkey去检索父表，再根据父表的sharding_id定位datanode的逻辑。

**Comment by wdw1206** [comment]
已修改，请使用1.4dev版验证

**Comment by bluoy** [comment]
动作正常了。

希望追加利用父表主键到节点的缓存的逻辑，实用性可能更好些。
另外，目前路由算法中主要使用了子表的parentKey, joinkey相关的逻辑好像没用了。

**Comment by apachemycat** [comment]
父表主键到节点的缓存的逻辑，这个貌似有的，show @@cache   在Mycat  9066管理端口看看

**Comment by bluoy** [comment]
指的是#86问题的修正：
1. 目前没有利用主键缓存机制。
2. 残留的joinkey相关的代码没有清理掉。

**Comment by wdw1206** [comment]
@bluoy :还有空指针吗？需要改成什么样？就是要增加主键缓存吗？父子表我是不推荐使用，因为这个目前好像会导致卡死，即使不卡死，根据主键去数据库查询一遍也是性能不好，而且数据量大时，要缓存全部占用的内存太恐怖了，不缓存全部，命中率也低。我们公司要么joinkey对应的父表字段就是分片字段，要么不配置父子表，直接让两个表用同样的分片规则来代替。

**Comment by bluoy** [comment]
现在动作是正确的了。

我们既有的业务表关联比较多，对master表进行拆分时，如果把其他的关联业务表定义为child table, 保证了单点内的join, 感觉很是方便。

不过你说的有道理，性能和稳定性更重要。
