### ISSUE TITLE
最近测试MyCat时发现的几个问题

### ISSUE THREAD

**Issue by shin74** [MyCATApache/Mycat-Server#87]
测试环境：

硬件：CPU E7500, 内存 4G
软件：WIN7 64位系统，JDK1.7.0_72 64位，MySQL Community 5.6.22.0单实例

测试使用的表按照《MyCat_In_Action_中文版》中快速上手部分使用的SQL进行创建，schema.xml使用默认设置，没有进行修改。

测试出现的问题：

一、普通表，以hotnews表为例

向hotnews表插入5条数据，其ID为1、2、3、4、5

1.1 查询SQL：SELECT * from hotnews where id > 1;
结果：只查到了ID为4的数据

同样，以id>1为条件执行update和delete时也只影响ID为4的数据。

1.2 查询SQL：select * from hotnews where id between 1 and 3;
结果：
java.lang.ClassCastException: com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLPropertyExpr
	at org.opencloudb.parser.druid.MycatSchemaStatVisitor.getColumn(MycatSchemaStatVisitor.java:111)
	at org.opencloudb.parser.druid.MycatSchemaStatVisitor.visit(MycatSchemaStatVisitor.java:23)
	at com.alibaba.druid.sql.ast.expr.SQLBetweenExpr.accept0(SQLBetweenExpr.java:48)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62)
        ...

二、子表，以orders表为例

2.1 使用Insert语句向orders表中插入数据有一定概率5分钟后报ERROR 1064<HY000> can't find <root> parent sharding node for sql，这个已经有人反映过了。

2.2 以customer_id以外的列作为条件进行update delete或者select时会报错，比如执行SQL：select * from orders where id = 1;
结果：
java.lang.NullPointerException
	at org.opencloudb.route.util.RouterUtil.ruleCalculate(RouterUtil.java:411)
	at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:703)
	at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:577)
        ...

2.3 以customer_id为条件进行update delete或者select时会报错，比如执行SQL：update orders set note = "abc" where customer_id = 1;
结果：
java.lang.IllegalArgumentException: can't find datanode for sharding column:SHARDING_ID val:1
	at org.opencloudb.route.util.RouterUtil.ruleCalculate(RouterUtil.java:415)
	at org.opencloudb.route.util.RouterUtil.findRouteWithcConditionsForTables(RouterUtil.java:703)
	at org.opencloudb.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:577)

**Comment by wdw1206** [comment]
1.2 查询SQL：select * from hotnews where id between 1 and 3;
结果：
java.lang.ClassCastException: com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLPropertyExpr
at org.opencloudb.parser.druid.MycatSchemaStatVisitor.getColumn(MycatSchemaStatVisitor.java:111)
at org.opencloudb.parser.druid.MycatSchemaStatVisitor.visit(MycatSchemaStatVisitor.java:23)
at com.alibaba.druid.sql.ast.expr.SQLBetweenExpr.accept0(SQLBetweenExpr.java:48)
at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)

这个问题已解决
at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62)

**Comment by wdw1206** [comment]
这几个已经全部修复，请验证，如果有漏掉的赶紧指出来

**Comment by shin74** [comment]
经过测试，除了2.1，其它问题都已经修复，2.1的问题依然存在。

**Comment by wdw1206** [comment]
对于这个问题“有一定概率5分钟后报ERROR 1064 can't find parent sharding node for sql”
应该是线程被耗死，没有可处理的线程了导致死锁，然后5分钟超时后才有可用线程来处理。
出现这个问题的场景都是与父子表有关。

关于父子表的建议：
父子表的使用（即ER分片）不建议ER分片时候，子表对应的主表字段不是分片字段的情况。
mycat leader说以后会彻底改为异步方式，从数据库获取结果，但性能无法跟 主表关联字段为分片字段相比。

我们公司使用mycat时，我是不建议用父子表的，因为两点：
1、子表对应的主表字段不是分片字段的情况，性能很差，要去数据库反查来确定分片。
2、子表对应的主表字段是分片字段的情况，实际上不指定父子表关系，直接给两个表配置相同分片规则，两个表分片字段名不同的话，只需要在rule.xml中多配置一条规则即可。

**Comment by apachemycat** [comment]
ER关联分片，若子表关联的父表的字段非分片字段，则需要到后端数据库查询定位父表所在分片，比较耗时，目前还是同步的实现方式，大量并发插入不同父表记录对应的子表记录时候，可能会出现线程池消耗殆尽的Bug，不建议这种关联配置。
