### ISSUE TITLE
1.5 版本 字段使用别名报空指针异常

### ISSUE THREAD

**Issue by lihanxie** [MyCATApache/Mycat-Server#877]
执行这条语句不报错：
select COUNT(1) as test from COS_LOGISTIC_ORDER O
JOIN COS_LOGISTIC_ORDER_TYPES T

执行这条语句报错：
SELECT COUNT(1) AS `test` FROM COS_LOGISTIC_ORDER O
JOIN COS_LOGISTIC_ORDER_TYPES T

一些框架会自动在别名上加上  ` 字符。  如果在mysql上执行是没问题的  但是通过mycat就会报NullPointerException

Error Code : 1105
java.lang.NullPointerException

Execution Time : 00:00:00:000
Transfer Time  : 00:00:00:000
Total Time     : 00:00:00:000

**Comment by lihanxie** [comment]
刚刚测试 只有 count(1) max(x) 等聚合函数都会报这个错误

**Comment by HashZhang** [comment]
日志给一下

**Comment by lihanxie** [comment]
05/11 17:03:16.374   INFO [$_NIOREACTOR-3-RW] (FrontendAuthenticator.java:193) -ServerConnection [id=1, schema=null, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=null]'test' login success
05/11 17:03:53.815   WARN [BusinessExecutor0] (MultiNodeQueryHandler.java:477) -caught exception 
java.lang.NullPointerException
	at org.opencloudb.mpp.RowDataPacketGrouper.aggregateRow(RowDataPacketGrouper.java:157)
	at org.opencloudb.mpp.RowDataPacketGrouper.addRow(RowDataPacketGrouper.java:140)
	at org.opencloudb.mpp.DataMergeService.run(DataMergeService.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
MySQL [base]> select count(1) as `aaa` from test;
+-----+
| aaa |
+-----+
|  11 |
+-----+
1 row in set (0.00 sec)
刚测试了几种情况都正常

**Comment by magicdoom** [comment]
你把你的join去掉测试下看看
