### ISSUE TITLE
DirectBufferPool有问题。

### ISSUE THREAD

**Issue by HashZhang** [MyCATApache/Mycat-Server#889]
在请求比较多时，会发生如下异常，然后MyCat拒绝连接：
```
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:236)
	at io.mycat.buffer.ByteBufferPage.allocatChunk(ByteBufferPage.java:57)
	at io.mycat.buffer.DirectByteBufferPool.allocateBuffer(DirectByteBufferPool.java:90)
	at io.mycat.buffer.DirectByteBufferPool.allocate(DirectByteBufferPool.java:65)
	at io.mycat.net.AbstractConnection.allocate(AbstractConnection.java:241)
	at io.mycat.net.mysql.CommandPacket.write(CommandPacket.java:117)
	at io.mycat.backend.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:280)
	at io.mycat.backend.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:425)
	at io.mycat.backend.mysql.nio.MySQLConnection.execute(MySQLConnection.java:392)
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler._execute(MultiNodeQueryHandler.java:173)
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.connectionAcquired(MultiNodeQueryHandler.java:184)
	at io.mycat.backend.datasource.PhysicalDatasource.takeCon(PhysicalDatasource.java:343)
	at io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:377)
	at io.mycat.backend.datasource.PhysicalDBPool.getRWBanlanceCon(PhysicalDBPool.java:456)
	at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:120)
	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.execute(MultiNodeQueryHandler.java:156)
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:143)
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:248)
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:184)
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:102)
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:78)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:302)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:322)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:446)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:428)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:272)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
	at java.lang.Thread.run(Thread.java:745)
 (io.mycat.server.NonBlockingSession:NonBlockingSession.java:145) 
2016-05-16 15:15:22,510 [WARN ][$_NIOREACTOR-3-RW] caught err: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:236)
	at io.mycat.buffer.ByteBufferPage.allocatChunk(ByteBufferPage.java:57)
	at io.mycat.buffer.DirectByteBufferPool.allocateBuffer(DirectByteBufferPool.java:90)
	at io.mycat.buffer.DirectByteBufferPool.allocate(DirectByteBufferPool.java:65)
	at io.mycat.net.AbstractConnection.allocate(AbstractConnection.java:241)
	at io.mycat.net.mysql.ErrorPacket.write(ErrorPacket.java:135)
	at io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:207)
	at io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:199)
	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:146)
	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:248)
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:184)
	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:102)
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:78)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:302)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:322)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:446)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:428)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:272)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
	at java.lang.Thread.run(Thread.java:745)
 (io.mycat.net.NIOReactor$RW:NIOReactor.java:107) 
```

**Comment by HashZhang** [comment]
@zagnix 请查看下

**Comment by HashZhang** [comment]
是最新的1.6代码，几乎是必出现的异常。一个select *操作，不断尝试，就会报。

**Comment by magicdoom** [comment]
你也可以跟踪下看看

**Comment by HashZhang** [comment]
已定位问题：
将ByteBufferPage的allocatChunk函数中的
```
buf.position(offStart);
buf.limit(offEnd);
```
换一个顺序即可。
即：
```
buf.limit(offEnd);
buf.position(offStart);
```
**测试：**
Bug说明：在高并发时或结果及过大，MyCat报buffer异常，同时链接失效
测试语句select * from hotnews;
并发：100，循环次数：100
单次返回结果集大小：10W

修改前：
 
![9](https://cloud.githubusercontent.com/assets/15627489/15309307/6a506a8c-1c18-11e6-82f2-97c2bcfaac9f.png)



后台报错：
2016-05-17 09:47:49,795 [WARN ][$_MyCatServer] $_MyCatServer java.lang.IllegalArgumentException
         at java.nio.Buffer.position(Buffer.java:236)
         at io.mycat.buffer.ByteBufferPage.allocatChunk(ByteBufferPage.java:61)
         at io.mycat.buffer.DirectByteBufferPool.allocateBuffer(DirectByteBufferPool.java:90)
         at io.mycat.buffer.DirectByteBufferPool.allocate(DirectByteBufferPool.java:65)
         at io.mycat.net.AbstractConnection.setProcessor(AbstractConnection.java:212)
         at io.mycat.net.FrontendConnection.setProcessor(FrontendConnection.java:129)
         at io.mycat.net.NIOAcceptor.accept(NIOAcceptor.java:116)
         at io.mycat.net.NIOAcceptor.run(NIOAcceptor.java:92)
(io.mycat.net.NIOAcceptor:NIOAcceptor.java:122)
JVM DirectMemory利用率 0.1%（总共4G）

修改后：
![10](https://cloud.githubusercontent.com/assets/15627489/15309314/7b1b6718-1c18-11e6-8cf1-aa796ceee1a0.png)

后台无报错
JVM DirectMemory利用率 10%（总共4G）

**Comment by HashZhang** [comment]
已在我的最近pull request提交修改
[回滚schema.xml,增加解析函数列兼容性 #891](https://github.com/MyCATApache/Mycat-Server/pull/891)

**Comment by magicdoom** [comment]
ok

**Comment by huangyiminghappy** [comment]
2017-03-01 18:35:42.803  WARN [$_NIOREACTOR-2-RW] (io.mycat.net.NIOReactor$RW.run(NIOReactor.java:107)) - caught err:
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:236) ~[?:1.7.0_79]
	at io.mycat.buffer.ByteBufferPage.allocatChunk(ByteBufferPage.java:60) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.buffer.DirectByteBufferPool.allocateBuffer(DirectByteBufferPool.java:181) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.buffer.DirectByteBufferPool.allocate(DirectByteBufferPool.java:87) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.allocate(AbstractConnection.java:243) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.allocBuffer(SingleNodeHandler.java:366) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.handler.SingleNodeHandler.fieldEofResponse(SingleNodeHandler.java:388) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:192) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:118) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.backend.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.handle(AbstractConnection.java:265) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:323) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:275) ~[Mycat-server-1.6.5-DEV.jar:?]
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102) ~[Mycat-server-1.6.5-DEV.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
我是下载的最新1.6代码，做压测的时候发现还是有这个问题呀
