### ISSUE TITLE
1.5版本load data infile 报错

### ISSUE THREAD

**Issue by 694551594** [MyCATApache/Mycat-Server#914]
导入的数据有6G多，报错如下：

>`05/24 18:19:07.506  ERROR [$_NIOREACTOR-3-RW] (FrontendConnection.java:242) -load data error
com.univocity.parsers.common.TextParsingException: Error processing input: java.lang.ArrayIndexOutOfBoundsException - 512
Hint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Column reordering enabled=true
	Empty value=null
	Header extraction enabled=false
	Headers=null
	Ignore leading whitespaces=true
	Ignore trailing whitespaces=true
	Input buffer size=1048576
	Input reading on separate thread=true
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Null value=null
	Number of records to read=all
	Parse unescaped quotes=true
	Row processor=none
	Selected fields=none
	Skip empty lines=trueFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=\t
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character=quote escape
		Quote escape escape character=\0, line=0, char=2929. Content parsed: [null]
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:239)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:354)
	at org.opencloudb.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:696)
	at org.opencloudb.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:218)
	at org.opencloudb.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:240)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:116)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 512
	at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:247)
	at com.univocity.parsers.csv.CsvParser.parseField(CsvParser.java:181)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:75)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:326)
	... 13 more`

**Comment by HashZhang** [comment]
你的列有512列以上么？

**Comment by 694551594** [comment]
@HashZhang 木有。像这样的：LOAD DATA INFILE '....x.txt' INTO TABLE esp_5 CHARACTER SET 'UTF-8' ( ID, ESPATH, creator, credate, editname, eidtdate, orgId, ctrlusing, destroystat us, isinstore, bussystemid, ID_BUSI_MODEL, C12, C13, C14, C15, C16, C17, C18, C1 9, C20, C21, C22, C23, C24, C25, C26, C27, C28, C29, C30, C31, C32, C33, C35, C37, C36, C34, C38, C39, relation, resourcebusimodelid, boxid, ESPATH1, ESPATH2, C9535, C9536, C1416, C1417, D OCUMENTFLAG, TREENODEID, DELETEOR, CLASSNAME, BOXVAL, C1407, C1408, C1409, C1410 );

**Comment by 694551594** [comment]
可能找到原因了。。可能是数据内容里面存在分隔符，导致程序误以为是列的分隔符，所以会超过512，我再用其他的分隔符试试。

**Comment by magicdoom** [comment]
还可以用escape   如果是load data into file导出的 则数据以及转义好      其他的可以自己转义下   然后数据项每个用引号之类包括起来    基本上就不会有什么问题
