### ISSUE TITLE
使用catlet批量导入-mycat1.5

### ISSUE THREAD

**Issue by minlingchao1** [MyCATApache/Mycat-Server#958]
使用/*!mycat:catlet=demo.catlets.BatchInsertSequence */INSERT INTO批量导入数据，运行十几分钟后
报异常
06/17 00:13:45.066  ERROR [$_NIOREACTOR-2-RW] (BatchInsertSequence.java:123) -BatchInsertSequence.route(......)
java.lang.RuntimeException: can't fetch sequnce in db,sequnce :SMS_RECORD detail:null
	at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:142)
	at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.getNextValidSeqVal(IncrSequenceMySQLHandler.java:124)
	at org.opencloudb.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:113)
	at demo.catlets.BatchInsertSequence.route(BatchInsertSequence.java:113)
	at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:53)
	at org.opencloudb.route.RouteService.route(RouteService.java:119)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:745)
06/17 00:13:45.074  ERROR [$_NIOREACTOR-2-RW] (BatchInsertSequence.java:135) -BatchInsertSequence.getRoute(String sql)
java.lang.NullPointerException
	at org.opencloudb.route.util.RouterUtil.processWithMycatSeq(RouterUtil.java:440)
	at org.opencloudb.route.impl.AbstractRouteStrategy.beforeRouteProcess(AbstractRouteStrategy.java:89)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:29)
	at demo.catlets.BatchInsertSequence.getRoute(BatchInsertSequence.java:133)
	at demo.catlets.BatchInsertSequence.processSQL(BatchInsertSequence.java:52)
	at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:54)
	at org.opencloudb.route.RouteService.route(RouteService.java:119)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:745)
06/17 00:13:45.075  ERROR [$_NIOREACTOR-2-RW] (BatchInsertSequence.java:65) -BatchInsertSequence.processSQL(String sql, EngineCtx ctx)
java.lang.NullPointerException
	at demo.catlets.BatchInsertSequence.processSQL(BatchInsertSequence.java:53)
	at org.opencloudb.route.handler.HintCatletHandler.route(HintCatletHandler.java:54)
	at org.opencloudb.route.RouteService.route(RouteService.java:119)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:125)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:745)

并且有生成的错误日志 hs_err_pid27557.log 

 There is insufficient memory for the Java Runtime Environment to continue.
 Native memory allocation (malloc) failed to allocate 537919488 bytes for committing reserved memory.
 Possible reasons:
   The system is out of physical RAM or swap space
   In 32 bit mode, the process size limit was hit
 Possible solutions:
   Reduce memory load on the system
   Increase physical memory or swap space
   Check if swap backing store is full
   Use 64 bit Java on a 64 bit OS
   Decrease Java heap size (-Xmx/-Xms)
   Decrease number of Java threads
   Decrease Java thread stack sizes (-Xss)
   Set larger code cache with -XX:ReservedCodeCacheSize=
 This output file may be truncated or incomplete.

  Out of Memory Error (os_linux.cpp:2756), pid=27557, tid=140565501953792

 JRE version: Java(TM) SE Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 compressed oops)
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

请问该如何进行配置

**Comment by magicdoom** [comment]
明显是你的jvm分配内存分配失败了    从这方面去查问题

**Comment by magicdoom** [comment]
先关闭   如果不是内存问题再打开
