### ISSUE TITLE
Select时报错find no Route

### ISSUE THREAD

**Issue by songxz** [MyCATApache/Mycat-Server#963]
我用的1.5版本，insert没有问题，但是执行select * from user where id = 1的时候会报如下错误：

> java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `test`.`user` WHERE 0=1

我找到一个配置文件router.xml，但是不知道具体作用，网上也搜不到说明

如果有遇到过相同情况的请指点一下

**Comment by zzcclp** [comment]
我也遇到了这个问题，错误如下：
06/23 11:10:15.352   WARN [$_NIOREACTOR-31-RW] (DruidSelectParser.java:393) - find no Route:SELECT * FROM `hdt_sys6`.`transport_statistics_5min` LIMIT 0
06/23 11:10:15.352   WARN [$_NIOREACTOR-31-RW] (ServerConnection.java:232) -ServerConnection [id=750403, schema=hdt_sys, host=36.251.248.162, user=root,txIsolation=3, autocommit=true, schema=hdt_sys]SELECT * FROM `hdt_sys6`.`transport_statistics_5min` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `hdt_sys6`.`transport_statistics_5min` LIMIT 0
java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `hdt_sys6`.`transport_statistics_5min` LIMIT 0
	at org.opencloudb.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:394)
	at org.opencloudb.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:257)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:66)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:64)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
	at org.opencloudb.route.RouteService.route(RouteService.java:133)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:745)

**Comment by magicdoom** [comment]
请提供下具体配置     如果未分片表即没有做配置 又没有配置默认节点  则会出现这种

**Comment by 446541492** [comment]
我也遇到这个问题，但是是在用navcat连接执行sql时报错的，用java正常

**Comment by zhaoxiaojie0415** [comment]
这个应该是第三方软件的问题吧

**Comment by zzcclp** [comment]
是的，后来发现是使用navicat的问题，额外执行了一些sql

**Comment by xiangwan** [comment]
@zzcclp 你好执行的什么sql 我也需要这个问题了

**Comment by zzcclp** [comment]
就是一些查询语句而已，直接mysql命令连接没问题，navicat的问题啊

**Comment by TrillStones** [comment]
我看到客户端执行时默认增加数据库名称，所以才会执行失败。
