### ISSUE TITLE
1.2.2.1  java.nio.BufferOverflowException 

### ISSUE THREAD

**Issue by Hisen158** [MyCATApache/Mycat-Server#98]
Exception in thread "AIOExecutor2" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:513)
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:291)
	at org.opencloudb.mysql.BufferUtil.writeUB3(BufferUtil.java:39)
	at org.opencloudb.net.mysql.CommandPacket.write(CommandPacket.java:115)
	at org.opencloudb.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:288)
	at org.opencloudb.mysql.nio.MySQLConnection$StatusSync.execute(MySQLConnection.java:449)
	at org.opencloudb.mysql.nio.MySQLConnection.doExecute(MySQLConnection.java:546)
	at org.opencloudb.mysql.nio.MySQLConnection.execute(MySQLConnection.java:526)
	at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler._execute(MultiNodeQueryHandler.java:144)
	at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler.access$6(MultiNodeQueryHandler.java:137)
	at org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler$2.run(MultiNodeQueryHandler.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

产生原因：
我自己写的定时器循环读取（select update） mycat中的数据时，会出现中断，mycat log报上面的异常，mycat 是在本地开发环境eclipse中启动，如果换成服务器上启动mycat，没出现过这种情况，这个会是什么问题产生的？
结果：这样会导致当前查询阻塞，需要重启tomcat服务器解决，但是不影响其他业务查询mycat，如系统登录等等。

**Comment by apachemycat** [comment]
Mycat是什么版本，广泛测评下来，除非Windows系统，否则不建议 AIO模式，性能低于NIO很多。

**Comment by Hisen158** [comment]
如何切换AIO 或者 NIO。 Mycat 1.3-dev 版

**Comment by apachemycat** [comment]
1.3-Dev是开发测试版，有反馈的确有此Bug，建议升级到1.3.0.2正式版。
